plugins {
    id 'java'
    id 'org.springframework.boot' version '3.1.2'
    id 'io.spring.dependency-management' version '1.1.2'
    id 'org.graalvm.buildtools.native' version '0.9.23'
    id 'jacoco'
}
group = 'com.asrevo.cvhome'

java {
    sourceCompatibility = '17'
}

repositories {
    mavenCentral()
}

tasks.named('test') {
    useJUnitPlatform()
}

springBoot {
    buildInfo()
}

bootBuildImage {
    builder = "paketobuildpacks/builder:tiny"
    imageName = "ghcr.io/ashraf-revo/${project.name}:${project.version.replaceAll("\'", "")}"
    docker {
        publishRegistry {
            url = "https://ghcr.io"
            username = "ashraf-revo"
            password = System.getenv("GHCR_TOKEN")
        }
    }
}

ext {
    set('springCloudVersion', "2022.0.4")
}
dependencies {
    implementation 'org.springframework.boot:spring-boot-starter-webflux'
    implementation 'org.springframework.boot:spring-boot-starter-validation'
    implementation 'org.springframework.boot:spring-boot-starter-actuator'
    implementation 'org.springframework.boot:spring-boot-starter-data-jdbc'
    runtimeOnly 'org.postgresql:postgresql'

    implementation 'org.springdoc:springdoc-openapi-starter-webflux-ui:2.2.0'

    implementation 'org.shredzone.acme4j:acme4j-client:2.15'
    implementation 'org.shredzone.acme4j:acme4j-utils:2.15'
    implementation 'commons-codec:commons-codec:1.15'

    developmentOnly 'org.springframework.boot:spring-boot-docker-compose'
    compileOnly 'org.projectlombok:lombok'
    annotationProcessor 'org.projectlombok:lombok'
    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    testImplementation 'org.springframework.boot:spring-boot-testcontainers'
    testImplementation 'io.projectreactor:reactor-test'
    testImplementation 'org.testcontainers:junit-jupiter'
    testImplementation 'org.testcontainers:postgresql'
}

dependencyManagement {
    imports {
        mavenBom "org.springframework.cloud:spring-cloud-dependencies:${springCloudVersion}"
    }
}

test {
    finalizedBy jacocoTestReport // report is always generated after tests run
}
jacocoTestReport {
    dependsOn test // tests are required to run before generating the report
}