plugins {
    id 'java'
    id 'org.springframework.boot' version '3.1.1'
    id 'io.spring.dependency-management' version '1.1.0'
//    id 'org.graalvm.buildtools.native' version '0.9.23'
}
group = 'com.asrevo.cvhome'

java {
    sourceCompatibility = '17'
}

repositories {
    mavenCentral()
}

tasks.named('test') {
    useJUnitPlatform()
}

bootBuildImage {
    builder = "paketobuildpacks/builder:tiny"
    imageName = "ghcr.io/ashraf-revo/${project.name}:${project.version.replaceAll("\'", "")}"
    docker {
        publishRegistry {
            url = "https://ghcr.io"
            username = "ashraf-revo"
            password = System.getenv("GHCR_TOKEN")
        }
    }
}

ext {
    set('springCloudVersion', "2022.0.3")
}
dependencies {
    implementation 'org.springframework.boot:spring-boot-starter-webflux'
    implementation 'org.springframework.boot:spring-boot-starter-actuator'
    implementation 'org.springframework.boot:spring-boot-starter-actuator'
    implementation 'io.opentelemetry.instrumentation:opentelemetry-spring-boot-starter:1.26.0-alpha'
    implementation 'io.micrometer:micrometer-tracing-bridge-otel'
    implementation 'io.micrometer:micrometer-registry-otlp'
    implementation 'io.opentelemetry:opentelemetry-exporter-otlp'
    implementation 'software.amazon.awssdk:s3:2.20.93'
    implementation 'software.amazon.awssdk:dynamodb:2.20.93'

    implementation 'org.shredzone.acme4j:acme4j-client:2.15'
    implementation 'org.shredzone.acme4j:acme4j-utils:2.15'
    implementation 'commons-codec:commons-codec:1.15'

    compileOnly 'org.projectlombok:lombok'
    annotationProcessor 'org.projectlombok:lombok'
    testImplementation 'org.springframework.boot:spring-boot-starter-test'
}

dependencyManagement {
    imports {
        mavenBom "org.springframework.cloud:spring-cloud-dependencies:${springCloudVersion}"
    }
    imports {
        mavenBom "io.opentelemetry:opentelemetry-bom:1.27.0"
    }
}
