### order a domain certificate
POST http://localhost:8082/api/acm/order
Content-Type: application/json

{
  "domain": "wl.asrevo.com",
  "reference": "32"
}

### validate a domain challenge
POST http://localhost:8082/api/acm/validate
Content-Type: application/json

{
  "location": "https://acme-v02.api.letsencrypt.org/acme/order/593265476/201156275356"
}

### generate a domain challenge
POST http://localhost:8082/api/acm/generate
Content-Type: application/json

{
  "location": "https://acme-v02.api.letsencrypt.org/acme/order/593265476/201156275356"
}

### downoad a domain crt file
POST http://localhost:8082/api/acm/domain-certificate-file?fileType=CRT
Content-Type: application/json

{
  "domain": "wl.asrevo.com"
}

### downoad a domain key file
POST http://localhost:8082/api/acm/domain-certificate-file?fileType=KEY
Content-Type: application/json

{
  "domain": "wl.asrevo.com"
}


### downoad a domain csr file
POST http://localhost:8082/api/acm/domain-certificate-file?fileType=CSR
Content-Type: application/json

{
  "domain": "wl.asrevo.com"
}
