### order a domain certificate
POST http://localhost:8082/api/v1/acm/order
Content-Type: application/json

{
  "domain": "gateway.com",
  "reference": "45"
}

### validate a domain challenge
POST http://localhost:8082/api/v1/acm/validate
Content-Type: application/json

{
  "location": "https://acme-v02.api.letsencrypt.org/acme/order/593265476/201332016326"
}

### generate a domain challenge
POST http://localhost:8082/api/v1/acm/generate
Content-Type: application/json

{
  "location": "https://acme-v02.api.letsencrypt.org/acme/order/593265476/201332016326"
}

### downoad a domain crt file
POST http://localhost:8082/api/v1/acm/domain-certificate-file?domain=gateway.com&fileType=CRT


### downoad a domain key file
POST http://localhost:8082/api/v1/acm/domain-certificate-file?domain=gateway.com&fileType=KEY


### downoad a domain csr file
POST http://localhost:8082/api/v1/acm/domain-certificate-file?domain=gateway.com&fileType=CSR
