// GENERATED by scripts/theme-routes.mjs — do not edit. The route logic lives in src/shell/routes.
import '@/app/theme-css/furniture.css';
import theme from '@store-front/theme-furniture';
import {storefrontLayout} from '@/shell/routes/layout';

export {generateMetadata} from '@/shell/routes/layout';
export default storefrontLayout(theme);
