plugins {
	alias(libs.plugins.java.library.conventions)
	alias(libs.plugins.spring.javaformat)
}

dependencies {
	api project(':store-core:manager:manager-commons')
	compileOnly libs.spring.data.commons
	compileOnly libs.spring.data.relational
	compileOnly libs.jackson.annotations
	compileOnly libs.lombok
	annotationProcessor libs.lombok
}
