plugins {
    id 'com.asrevo.java-library-conventions'
}

dependencies {
    implementation 'org.springframework.cloud:spring-cloud-starter-loadbalancer:4.1.3'
    implementation 'software.amazon.awssdk:servicediscovery:2.21.25'
    compileOnly 'org.projectlombok:lombok:1.18.32'
    annotationProcessor 'org.projectlombok:lombok:1.18.32'
}
