// GENERATED by libs/types/scripts/build-color-schemas.mjs (THEME_DEFAULTS.basic) — edit the seed there, then
// `npm run gen:colors` in libs/types. Same rules as the merchant presets (see that file's header).
import type {ColorSchema} from '@store-front/types';

/**
 * The Catalogue Page: white stock, black ink, cobalt title fields and tabs; catalogue-grey wash; print-red price flash. (light)
 *
 * The theme's own palette — what renders when the merchant's colour theme is `DEFAULT` or unset. Wired as
 * `tokens.defaultColors` in `./index.ts`; any fixed preset the merchant picks replaces it whole.
 */
export const DEFAULT_COLORS: ColorSchema = {
    primary: "#1860BC",
    secondary: "#DEDEDE",
    accent: "#B7191C",
    background: "#FFFFFF",
    foreground: "#181818",
    error: "#B7191C",
    warning: "#EE9E10",
    success: "#007533",
    info: "#0065A1",
    neutral: "#ABABAB",
    border: "#DEDEDE",
    ring: "#1860BC",
    outline: "#3E6499",
    hoverPrimary: "#004CA1",
    focusPrimary: "#003C83",
    hoverSecondary: "#C7C7C7",
    focusSecondary: "#B4B4B4",
    hoverAccent: "#99000D",
    focusAccent: "#7D0008",
    hoverError: "#99000D",
    focusError: "#7D0008",
    hoverWarning: "#D38A00",
    focusWarning: "#BA7900",
    hoverSuccess: "#005E28",
    focusSuccess: "#004B1E",
    hoverInfo: "#005182",
    focusInfo: "#004069",
    hoverNeutral: "#959595",
    focusNeutral: "#838383",
};
