com:
  asrevo:
    cvhome:
      fargate:
        namespace: "cvhome.lcl"
spring:
  security:
    oauth2:
      client:
        registration:
          microservice:
            provider: keycloak
            client-id: microservice-app
            client-secret: r1nuVn4HefusLGwHIeRxbdOzdTZLEMvQ
            authorization-grant-type: password
          keycloak:
            client-id: web-app
            client-authentication-method: client_secret_basic
            authorization-grant-type: authorization_code
            scope: openid, profile, email
            redirect-uri: "{baseUrl}/login/oauth2/code/keycloak"
            provider: keycloak
            client-secret: hLwOF59NEOdMzYYrfxUbQEGVK1uTczj7
        provider:
          keycloak:
            jwk-set-uri: http://auth.${spring.cloud.ecs.discovery.namespace}:9999/realms/cvhome/protocol/openid-connect/certs
            authorization-uri: https://auth.${com.asrevo.cvhome.ssl.default-domain}:${server.port}/realms/cvhome/protocol/openid-connect/auth
            token-uri: http://auth.${spring.cloud.ecs.discovery.namespace}:9999/realms/cvhome/protocol/openid-connect/token
  cloud:
    loadbalancer:
      eager-load:
        clients:
          - "gateway"
          - "store"
          - "store-ui"
    ecs:
      discovery:
        namespace: "cvhome.lcl"
        namespace-id: "ns-je7qri6wn7fbsrpn"
        enabled: true
        default-port: 8080
        service-ports:
          "store": 8083
          "store-ui": 4300
    gateway:
      discovery:
        locator:
          enabled: true
      default-filters:
        - TokenRelay
        - PreserveHostHeader
        - AddResponseHeader=X-Frame-Options, SAMEORIGIN
      routes:
        - id: mapped-store
          uri: lb://store
          predicates:
            - Path=/store/**
            - FHost={sub}.{domain}.{x}
            - Header=Map-Host-As-Request-Param, true
          filters:
            - StripPrefix=1
            - MapHostAsRequestParam=userId
        - id: store
          uri: lb://store
          predicates:
            - Path=/store/**
          filters:
            - StripPrefix=1
        - id: store-ui
          uri: lb://store-ui
          predicates:
            - FHost={sub}.{domain}.{x} , {domain}.{x}
