spring:
  security:
    oauth2:
      client:
        registration:
          microservice:
            provider: keycloak
            client-id: microservice-app
            client-secret: r1nuVn4HefusLGwHIeRxbdOzdTZLEMvQ
            authorization-grant-type: password
          keycloak:
            client-id: web-app
            client-authentication-method: client_secret_basic
            authorization-grant-type: authorization_code
            scope: openid, profile, email
            redirect-uri: "{baseUrl}/login/oauth2/code/keycloak"
            provider: keycloak
            client-secret: hLwOF59NEOdMzYYrfxUbQEGVK1uTczj7
        provider:
          keycloak:
            jwk-set-uri: ${com.asrevo.cvhome.services.auth.schema}://${com.asrevo.cvhome.services.auth.domain}:${com.asrevo.cvhome.services.auth.port}/realms/cvhome/protocol/openid-connect/certs
            authorization-uri: ${com.asrevo.cvhome.services.coreGateway.schema}://${com.asrevo.cvhome.services.auth.domain}:${com.asrevo.cvhome.services.coreGateway.port}/realms/cvhome/protocol/openid-connect/auth
            token-uri: ${com.asrevo.cvhome.services.auth.schema}://${com.asrevo.cvhome.services.auth.domain}:${com.asrevo.cvhome.services.auth.port}/realms/cvhome/protocol/openid-connect/token
  cloud:
    local:
      discovery:
        enabled: true
        services:
          store:
            - url: "http://localhost:8083"
              metadata:
                service-name: store
                instance: store-1
          store-ui:
            - url: "http://localhost:4300"
              metadata:
                service-name: store-ui
                instance: store-ui-1
          domain-certificate-manager:
            - url: "http://localhost:8082"
              metadata:
                service-name: domain-certificate-manager
                instance: domain-certificate-manager-1
    gateway:
      discovery:
        locator:
          enabled: true
      default-filters:
        - TokenRelay
        - PreserveHostHeader
        - AddResponseHeader=X-Frame-Options, SAMEORIGIN
      routes:
        - id: mapped-store
          order: -1
          uri: lb://store
          predicates:
            - Path=/store/**
            - FHost={domain}.{x},{sub}.{domain}.{x}
            - Header=Map-Host-As-Request-Param,true
          filters:
            - StripPrefix=1
            - MapHostAsRequestParam=storeId
        - id: store
          order: -1
          uri: lb://store
          predicates:
            - Path=/store/**
          filters:
            - StripPrefix=1
        - id: store-ui
          order: -1
          uri: lb://store-ui
          predicates:
            - FHost={domain}.{x},{sub}.{domain}.{x}
