spring:
  datasource:
    url: jdbc:postgresql://${spring.datasource.host}:${spring.datasource.port}/${spring.datasource.database}
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${com.asrevo.cvhome.services.auth.schema}://${com.asrevo.cvhome.services.auth.domain}:${com.asrevo.cvhome.services.auth.port}/realms/cvhome/protocol/openid-connect/certs
  cloud:
    loadbalancer:
      eager-load:
        clients:
          - "store-core-gateway"
          - "store"
          - "store-ui"
          - "wallet"
    ecs:
      discovery:
        namespace: "store-core.cvhome.lcl"
        namespace-id: "ns-aacm3spcnftheq3b"
        enabled: true
        default-port: 8080
        service-ports:
          "store-core-gateway": 8088
          "store": 8086
          "store-ui": 4300
          "wallet": 8087