// GENERATED by scripts/theme-routes.mjs — do not edit. The route logic lives in src/shell/routes.
import theme from '@store-front/theme-glasses';
import {blogPostPage} from '@/shell/routes/blog-post';

export {generateMetadata} from '@/shell/routes/blog-post';
export default blogPostPage(theme);
