-- Pages beyond the six the store shipped with.
--
-- Demo content for the test store 65f023632bc46470c104b75f (USA Electronics Hub), in every language the store sells in.
-- Generated seed: ids are negative on purpose — content, media and menu ids all come from sequences that
-- only grow upward, so a seed row below zero can never collide with one the running service creates.

-- page: warranty (PUBLISHED)
INSERT INTO content.content (content_id, date_created, date_modified, updt_id, code, content_type, sort_order, visible, store_merchant_id, status, publish_at, unpublish_at, version, created_by, updated_by, parent_id, noindex, canonical_url, og_media_id, show_in_footer, placement, starts_at, ends_at, policy_type, meta)
VALUES (-30001, now(), now(), 'seed', 'warranty', 'PAGE', 10, true, '65f023632bc46470c104b75f', 'PUBLISHED', null, null, 1, 'seed', 'seed', null, false, null, null, true, null, null, null, null, null)
on conflict (content_id) do nothing;
INSERT INTO content.content_description (description_id, date_created, date_modified, updt_id, description, name, title, meta_description, meta_keywords, meta_title, sef_url, language_code, content_id, state, excerpt, alt_text, cta_label, subtitle)
VALUES (-300001, now(), now(), 'seed', '<h2>Two years, in writing</h2><p>Every product sold here carries a two-year warranty, one year longer than most manufacturers offer in the US. The extra year is ours, honoured at our own bench in Long Island City.</p><h3>What is covered</h3><ul><li>Manufacturing defects and component failure under normal use</li><li>Battery capacity falling below 80% within the first year</li><li>Dead pixels above the manufacturer''s own threshold</li></ul><h3>What is not</h3><ul><li>Liquid damage and physical impact</li><li>Devices opened by a third-party repairer</li><li>Consumables: ear tips, cables, screen films</li></ul><h3>How a repair goes</h3><p>Start a claim from your account, drop the device at the store or use the prepaid label. Median turnaround is six business days; if it runs past fourteen we ship a replacement.</p>', 'Warranty & repairs', 'Warranty & repairs', 'Two-year coverage on every product, an in-house repair bench, and what the warranty does not cover.', 'warranty, repairs, coverage', 'Warranty & repairs | USA Electronics Hub', 'warranty', 'en', -30001, 'TRANSLATED', null, null, null, null)
on conflict (description_id) do nothing;
INSERT INTO content.content_description (description_id, date_created, date_modified, updt_id, description, name, title, meta_description, meta_keywords, meta_title, sef_url, language_code, content_id, state, excerpt, alt_text, cta_label, subtitle)
VALUES (-300002, now(), now(), 'seed', '<h2>Deux ans, par écrit</h2><p>Chaque produit vendu ici est garanti deux ans, soit un an de plus que la plupart des constructeurs aux États-Unis. Cette année supplémentaire est la nôtre, assurée dans notre atelier de Long Island City.</p><h3>Ce qui est couvert</h3><ul><li>Défauts de fabrication et pannes de composants en usage normal</li><li>Capacité de batterie tombant sous 80 % la première année</li><li>Pixels morts au-delà du seuil du constructeur</li></ul><h3>Ce qui ne l''est pas</h3><ul><li>Dégâts des liquides et chocs</li><li>Appareils ouverts par un réparateur tiers</li><li>Consommables : embouts, câbles, films d''écran</li></ul><h3>Le déroulé d''une réparation</h3><p>Ouvrez un dossier depuis votre compte, déposez l''appareil en boutique ou utilisez l''étiquette prépayée. Le délai médian est de six jours ouvrés ; au-delà de quatorze, nous expédions un remplacement.</p>', 'Garantie et réparations', 'Garantie et réparations', 'Deux ans de garantie sur chaque produit, un atelier interne, et ce que la garantie ne couvre pas.', 'garantie, réparation, couverture', 'Garantie et réparations | USA Electronics Hub', 'garantie', 'fr', -30001, 'TRANSLATED', null, null, null, null)
on conflict (description_id) do nothing;

-- page: buying-guides (PUBLISHED)
INSERT INTO content.content (content_id, date_created, date_modified, updt_id, code, content_type, sort_order, visible, store_merchant_id, status, publish_at, unpublish_at, version, created_by, updated_by, parent_id, noindex, canonical_url, og_media_id, show_in_footer, placement, starts_at, ends_at, policy_type, meta)
VALUES (-30002, now(), now(), 'seed', 'buying-guides', 'PAGE', 11, true, '65f023632bc46470c104b75f', 'PUBLISHED', null, null, 1, 'seed', 'seed', null, false, null, null, false, null, null, null, null, null)
on conflict (content_id) do nothing;
INSERT INTO content.content_description (description_id, date_created, date_modified, updt_id, description, name, title, meta_description, meta_keywords, meta_title, sef_url, language_code, content_id, state, excerpt, alt_text, cta_label, subtitle)
VALUES (-300003, now(), now(), 'seed', '<h2>Nothing ships untested</h2><p>We carry about four hundred products, out of roughly three thousand we are offered each year. The difference is a week on the bench.</p><h3>What we measure</h3><ul><li><strong>Laptops:</strong> sustained load temperature over 30 minutes, fan noise at 50 cm, panel colour coverage</li><li><strong>Headphones:</strong> frequency response against a compensated target, active-cancellation depth at 100 Hz</li><li><strong>Televisions:</strong> peak and sustained brightness, input latency in game mode</li><li><strong>Phones:</strong> screen brightness under 10,000 lux, charge cycle to 80%</li></ul><h3>What gets turned away</h3><p>Anything that throttles below its advertised sustained performance, anything whose battery is glued past the point of repair, and anything whose manufacturer will not commit to four years of security updates.</p>', 'How we choose what we sell', 'How we choose what we sell', 'The bench tests every product passes before it reaches the catalogue, and the ones we turn away.', 'testing, curation, buying guide', 'How we choose what we sell | USA Electronics Hub', 'how-we-choose', 'en', -30002, 'TRANSLATED', null, null, null, null)
on conflict (description_id) do nothing;
INSERT INTO content.content_description (description_id, date_created, date_modified, updt_id, description, name, title, meta_description, meta_keywords, meta_title, sef_url, language_code, content_id, state, excerpt, alt_text, cta_label, subtitle)
VALUES (-300004, now(), now(), 'seed', '<h2>Rien n''entre sans passer au banc</h2><p>Nous référençons environ quatre cents produits sur les trois mille qu''on nous propose chaque année. L''écart, c''est une semaine de banc d''essai.</p><h3>Ce que nous mesurons</h3><ul><li><strong>Ordinateurs portables :</strong> température en charge continue sur 30 minutes, bruit de ventilation à 50 cm, couverture colorimétrique de la dalle</li><li><strong>Casques :</strong> réponse en fréquence face à une cible compensée, profondeur de réduction active à 100 Hz</li><li><strong>Téléviseurs :</strong> luminance de crête et soutenue, latence d''affichage en mode jeu</li><li><strong>Téléphones :</strong> luminosité sous 10 000 lux, cycle de charge jusqu''à 80 %</li></ul><h3>Ce que nous refusons</h3><p>Tout ce qui bride en dessous de la performance annoncée, tout ce dont la batterie est collée au point d''être irréparable, et tout constructeur refusant de s''engager sur quatre ans de mises à jour de sécurité.</p>', 'Comment nous choisissons ce que nous vendons', 'Comment nous choisissons ce que nous vendons', 'Les tests que chaque produit traverse avant d''entrer au catalogue, et ceux que nous refusons.', 'tests, sélection, guide d''achat', 'Comment nous choisissons | USA Electronics Hub', 'comment-nous-choisissons', 'fr', -30002, 'TRANSLATED', null, null, null, null)
on conflict (description_id) do nothing;

-- page: trade-in-program (PUBLISHED)
INSERT INTO content.content (content_id, date_created, date_modified, updt_id, code, content_type, sort_order, visible, store_merchant_id, status, publish_at, unpublish_at, version, created_by, updated_by, parent_id, noindex, canonical_url, og_media_id, show_in_footer, placement, starts_at, ends_at, policy_type, meta)
VALUES (-30003, now(), now(), 'seed', 'trade-in-program', 'PAGE', 12, true, '65f023632bc46470c104b75f', 'PUBLISHED', null, null, 1, 'seed', 'seed', null, false, null, null, true, null, null, null, null, null)
on conflict (content_id) do nothing;
INSERT INTO content.content_description (description_id, date_created, date_modified, updt_id, description, name, title, meta_description, meta_keywords, meta_title, sef_url, language_code, content_id, state, excerpt, alt_text, cta_label, subtitle)
VALUES (-300005, now(), now(), 'seed', '<h2>Send it in, get credit</h2><ol><li>Get a quote online — model, storage, condition</li><li>We mail a padded box with a prepaid label</li><li>Credit lands within three business days of the device arriving</li></ol><h2>What happens to it</h2><p>Roughly six devices in ten are refurbished and resold with our own one-year warranty. The rest go to a certified R2v3 recycler in New Jersey; nothing is shipped overseas for disposal.</p><h2>Before you send</h2><ul><li>Sign out of the manufacturer''s account — a locked device is worth nothing to anyone</li><li>Back up, then erase</li><li>Leave the charger; we do not need it and it lowers nothing</li></ul>', 'Trade-in programme', 'Trade-in programme', 'Send in an old device, get store credit within three business days, and see where it ends up.', 'trade-in, recycling, credit', 'Trade-in programme | USA Electronics Hub', 'trade-in', 'en', -30003, 'TRANSLATED', null, null, null, null)
on conflict (description_id) do nothing;
INSERT INTO content.content_description (description_id, date_created, date_modified, updt_id, description, name, title, meta_description, meta_keywords, meta_title, sef_url, language_code, content_id, state, excerpt, alt_text, cta_label, subtitle)
VALUES (-300006, now(), now(), 'seed', '<h2>Envoyez, recevez un avoir</h2><ol><li>Obtenez une estimation en ligne — modèle, stockage, état</li><li>Nous envoyons un carton matelassé avec étiquette prépayée</li><li>L''avoir est crédité sous trois jours ouvrés après réception</li></ol><h2>Ce que devient l''appareil</h2><p>Six appareils sur dix environ sont reconditionnés et revendus avec notre garantie d''un an. Les autres partent chez un recycleur certifié R2v3 dans le New Jersey ; rien n''est expédié à l''étranger pour destruction.</p><h2>Avant l''envoi</h2><ul><li>Déconnectez le compte constructeur — un appareil verrouillé ne vaut rien</li><li>Sauvegardez, puis effacez</li><li>Gardez le chargeur : il ne change rien à l''estimation</li></ul>', 'Programme de reprise', 'Programme de reprise', 'Envoyez un ancien appareil, recevez un avoir sous trois jours ouvrés, et sachez ce qu''il devient.', 'reprise, recyclage, avoir', 'Programme de reprise | USA Electronics Hub', 'reprise', 'fr', -30003, 'TRANSLATED', null, null, null, null)
on conflict (description_id) do nothing;

-- page: store-hours (PUBLISHED)
INSERT INTO content.content (content_id, date_created, date_modified, updt_id, code, content_type, sort_order, visible, store_merchant_id, status, publish_at, unpublish_at, version, created_by, updated_by, parent_id, noindex, canonical_url, og_media_id, show_in_footer, placement, starts_at, ends_at, policy_type, meta)
VALUES (-30004, now(), now(), 'seed', 'store-hours', 'PAGE', 13, true, '65f023632bc46470c104b75f', 'PUBLISHED', null, null, 1, 'seed', 'seed', (select content_id from content.content where store_merchant_id = '65f023632bc46470c104b75f' and code = 'location'), false, null, null, false, null, null, null, null, null)
on conflict (content_id) do nothing;
INSERT INTO content.content_description (description_id, date_created, date_modified, updt_id, description, name, title, meta_description, meta_keywords, meta_title, sef_url, language_code, content_id, state, excerpt, alt_text, cta_label, subtitle)
VALUES (-300007, now(), now(), 'seed', '<h2>456 Tech Avenue, New York</h2><p>This page sits under “Location”, which also makes it the breadcrumb check: it should read Home › Location › Store hours & directions.</p><ul><li><strong>Monday–Friday</strong> 10am–8pm</li><li><strong>Saturday</strong> 10am–7pm</li><li><strong>Sunday</strong> 12pm–6pm</li></ul><h3>Getting here</h3><p>Two minutes from the 28th Street station on the 1 and the R. Metered parking on the avenue; the garage on 27th validates for two hours with any purchase.</p><h3>Repair desk</h3><p>At the back of the store, no appointment before 11am, appointments only after.</p>', 'Store hours & directions', 'Store hours & directions', 'Opening hours, subway directions and the repair-bench desk at 456 Tech Avenue.', 'hours, directions, store', 'Store hours & directions | USA Electronics Hub', 'store-hours', 'en', -30004, 'TRANSLATED', null, null, null, null)
on conflict (description_id) do nothing;
INSERT INTO content.content_description (description_id, date_created, date_modified, updt_id, description, name, title, meta_description, meta_keywords, meta_title, sef_url, language_code, content_id, state, excerpt, alt_text, cta_label, subtitle)
VALUES (-300008, now(), now(), 'seed', '<h2>456 Tech Avenue, New York</h2><p>Cette page est rattachée à « Notre emplacement », ce qui en fait le contrôle du fil d''Ariane : Accueil › Notre emplacement › Horaires et accès.</p><ul><li><strong>Lundi–vendredi</strong> 10h–20h</li><li><strong>Samedi</strong> 10h–19h</li><li><strong>Dimanche</strong> 12h–18h</li></ul><h3>Y venir</h3><p>À deux minutes de la station 28th Street, lignes 1 et R. Stationnement payant sur l''avenue ; le parking de la 27e offre deux heures pour tout achat.</p><h3>Comptoir de réparation</h3><p>Au fond de la boutique : sans rendez-vous avant 11h, sur rendez-vous ensuite.</p>', 'Horaires et accès', 'Horaires et accès', 'Horaires d''ouverture, accès en métro et comptoir de réparation au 456 Tech Avenue.', 'horaires, accès, boutique', 'Horaires et accès | USA Electronics Hub', 'horaires-et-acces', 'fr', -30004, 'TRANSLATED', null, null, null, null)
on conflict (description_id) do nothing;

-- page: gift-cards (PUBLISHED)
INSERT INTO content.content (content_id, date_created, date_modified, updt_id, code, content_type, sort_order, visible, store_merchant_id, status, publish_at, unpublish_at, version, created_by, updated_by, parent_id, noindex, canonical_url, og_media_id, show_in_footer, placement, starts_at, ends_at, policy_type, meta)
VALUES (-30005, now(), now(), 'seed', 'gift-cards', 'PAGE', 14, true, '65f023632bc46470c104b75f', 'PUBLISHED', null, null, 1, 'seed', 'seed', null, false, 'https://org1-store2.asrevo.com/content/gift-cards', -390002, true, null, null, null, null, null)
on conflict (content_id) do nothing;
INSERT INTO content.content_description (description_id, date_created, date_modified, updt_id, description, name, title, meta_description, meta_keywords, meta_title, sef_url, language_code, content_id, state, excerpt, alt_text, cta_label, subtitle)
VALUES (-300009, now(), now(), 'seed', '<h2>No expiry, no fees</h2><p>Cards run from $25 to $1,000, digital and delivered in minutes, or printed on a matte card and posted free.</p><p>They never expire, carry no maintenance fee, and any remaining balance stays on the card — which is not true of most retail cards, and is the reason this page exists.</p><p>The page also carries a canonical URL and an Open Graph image, which makes it the check on the storefront''s SEO rendering.</p>', 'Gift cards', 'Gift cards', 'Digital and physical gift cards from $25 to $1,000, with no expiry and no fees.', 'gift card, voucher', 'Gift cards | USA Electronics Hub', 'gift-cards', 'en', -30005, 'TRANSLATED', null, null, null, null)
on conflict (description_id) do nothing;
INSERT INTO content.content_description (description_id, date_created, date_modified, updt_id, description, name, title, meta_description, meta_keywords, meta_title, sef_url, language_code, content_id, state, excerpt, alt_text, cta_label, subtitle)
VALUES (-300010, now(), now(), 'seed', '<h2>Sans expiration, sans frais</h2><p>Les cartes vont de 25 à 1 000 $, en version numérique livrée en quelques minutes ou imprimée sur carte mate et postée gratuitement.</p><p>Elles n''expirent jamais, ne portent aucun frais de gestion, et le solde restant est conservé — ce qui n''est pas le cas de la plupart des cartes du commerce, et justifie cette page.</p><p>Elle porte aussi une URL canonique et une image Open Graph, ce qui en fait le contrôle du rendu SEO.</p>', 'Cartes cadeaux', 'Cartes cadeaux', 'Cartes cadeaux numériques et physiques de 25 à 1 000 $, sans expiration ni frais.', 'carte cadeau, bon d''achat', 'Cartes cadeaux | USA Electronics Hub', 'cartes-cadeaux', 'fr', -30005, 'TRANSLATED', null, null, null, null)
on conflict (description_id) do nothing;

-- page: accessibility (PUBLISHED)
INSERT INTO content.content (content_id, date_created, date_modified, updt_id, code, content_type, sort_order, visible, store_merchant_id, status, publish_at, unpublish_at, version, created_by, updated_by, parent_id, noindex, canonical_url, og_media_id, show_in_footer, placement, starts_at, ends_at, policy_type, meta)
VALUES (-30006, now(), now(), 'seed', 'accessibility', 'PAGE', 15, true, '65f023632bc46470c104b75f', 'PUBLISHED', null, null, 1, 'seed', 'seed', null, true, null, null, false, null, null, null, null, null)
on conflict (content_id) do nothing;
INSERT INTO content.content_description (description_id, date_created, date_modified, updt_id, description, name, title, meta_description, meta_keywords, meta_title, sef_url, language_code, content_id, state, excerpt, alt_text, cta_label, subtitle)
VALUES (-300011, now(), now(), 'seed', '<h2>Where we stand</h2><p>This page is flagged <code>noindex</code>: it should render in the storefront but stay out of the sitemap. That is the check on the SEO flag.</p><ul><li>Target: WCAG 2.2 level AA across the storefront</li><li>Known gap: the comparison table is not yet reachable by keyboard alone</li><li>Report a barrier: <a href="mailto:access@usaelectronics.com">access@usaelectronics.com</a></li></ul>', 'Accessibility statement', 'Accessibility statement', 'Our WCAG conformance status — a page deliberately kept out of the index.', 'accessibility, wcag', 'Accessibility statement | USA Electronics Hub', 'accessibility', 'en', -30006, 'TRANSLATED', null, null, null, null)
on conflict (description_id) do nothing;
INSERT INTO content.content_description (description_id, date_created, date_modified, updt_id, description, name, title, meta_description, meta_keywords, meta_title, sef_url, language_code, content_id, state, excerpt, alt_text, cta_label, subtitle)
VALUES (-300012, now(), now(), 'seed', '<h2>Où nous en sommes</h2><p>Cette page est marquée <code>noindex</code> : elle doit s''afficher dans la boutique mais disparaître du sitemap. C''est le contrôle du drapeau.</p><ul><li>Objectif : WCAG 2.2 niveau AA sur l''ensemble de la boutique</li><li>Écart connu : le tableau comparatif n''est pas encore atteignable au clavier seul</li><li>Signaler un obstacle : <a href="mailto:access@usaelectronics.com">access@usaelectronics.com</a></li></ul>', 'Déclaration d''accessibilité', 'Déclaration d''accessibilité', 'Notre niveau de conformité WCAG — page volontairement exclue de l''indexation.', 'accessibilité, wcag', 'Déclaration d''accessibilité | USA Electronics Hub', 'accessibilite', 'fr', -30006, 'TRANSLATED', null, null, null, null)
on conflict (description_id) do nothing;

-- page: black-friday (SCHEDULED)
INSERT INTO content.content (content_id, date_created, date_modified, updt_id, code, content_type, sort_order, visible, store_merchant_id, status, publish_at, unpublish_at, version, created_by, updated_by, parent_id, noindex, canonical_url, og_media_id, show_in_footer, placement, starts_at, ends_at, policy_type, meta)
VALUES (-30007, now(), now(), 'seed', 'black-friday', 'PAGE', 16, true, '65f023632bc46470c104b75f', 'SCHEDULED', now() + interval '21 days', null, 1, 'seed', 'seed', null, false, null, null, false, null, null, null, null, null)
on conflict (content_id) do nothing;
INSERT INTO content.content_description (description_id, date_created, date_modified, updt_id, description, name, title, meta_description, meta_keywords, meta_title, sef_url, language_code, content_id, state, excerpt, alt_text, cta_label, subtitle)
VALUES (-300013, now(), now(), 'seed', '<h2>Black Friday</h2><p>This page is <strong>SCHEDULED</strong> to publish in three weeks. It should be visible in the console and 404 in the storefront.</p>', 'Black Friday (scheduled)', 'Black Friday (scheduled)', 'A scheduled page: it must not appear in the storefront before its publish date.', 'black friday, sale', 'Black Friday | USA Electronics Hub', 'black-friday', 'en', -30007, 'TRANSLATED', null, null, null, null)
on conflict (description_id) do nothing;
INSERT INTO content.content_description (description_id, date_created, date_modified, updt_id, description, name, title, meta_description, meta_keywords, meta_title, sef_url, language_code, content_id, state, excerpt, alt_text, cta_label, subtitle)
VALUES (-300014, now(), now(), 'seed', '<h2>Black Friday</h2><p>Cette page est en statut <strong>SCHEDULED</strong>, publication dans trois semaines. Visible dans la console, 404 côté boutique.</p>', 'Black Friday (programmée)', 'Black Friday (programmée)', 'Page programmée : elle ne doit pas apparaître avant sa date de publication.', 'black friday, promotion', 'Black Friday | USA Electronics Hub', 'black-friday-fr', 'fr', -30007, 'TRANSLATED', null, null, null, null)
on conflict (description_id) do nothing;

-- page: spec-sheets-2024 (ARCHIVED)
INSERT INTO content.content (content_id, date_created, date_modified, updt_id, code, content_type, sort_order, visible, store_merchant_id, status, publish_at, unpublish_at, version, created_by, updated_by, parent_id, noindex, canonical_url, og_media_id, show_in_footer, placement, starts_at, ends_at, policy_type, meta)
VALUES (-30008, now(), now(), 'seed', 'spec-sheets-2024', 'PAGE', 17, false, '65f023632bc46470c104b75f', 'ARCHIVED', null, null, 1, 'seed', 'seed', null, false, null, null, false, null, null, null, null, null)
on conflict (content_id) do nothing;
INSERT INTO content.content_description (description_id, date_created, date_modified, updt_id, description, name, title, meta_description, meta_keywords, meta_title, sef_url, language_code, content_id, state, excerpt, alt_text, cta_label, subtitle)
VALUES (-300015, now(), now(), 'seed', '<h2>Spec sheets 2024</h2><p>Archived, replaced by the 2026 sheets. Must stay invisible in the storefront.</p>', 'Spec sheets 2024 (archived)', 'Spec sheets 2024 (archived)', null, null, null, 'spec-sheets-2024', 'en', -30008, 'TRANSLATED', null, null, null, null)
on conflict (description_id) do nothing;
INSERT INTO content.content_description (description_id, date_created, date_modified, updt_id, description, name, title, meta_description, meta_keywords, meta_title, sef_url, language_code, content_id, state, excerpt, alt_text, cta_label, subtitle)
VALUES (-300016, now(), now(), 'seed', '<h2>Fiches techniques 2024</h2><p>Archivé, remplacé par les fiches 2026. Doit rester invisible côté boutique.</p>', 'Fiches techniques 2024 (archivé)', 'Fiches techniques 2024 (archivé)', null, null, null, 'fiches-techniques-2024', 'fr', -30008, 'TRANSLATED', null, null, null, null)
on conflict (description_id) do nothing;

-- page: student-discount (DRAFT)
INSERT INTO content.content (content_id, date_created, date_modified, updt_id, code, content_type, sort_order, visible, store_merchant_id, status, publish_at, unpublish_at, version, created_by, updated_by, parent_id, noindex, canonical_url, og_media_id, show_in_footer, placement, starts_at, ends_at, policy_type, meta)
VALUES (-30009, now(), now(), 'seed', 'student-discount', 'PAGE', 18, true, '65f023632bc46470c104b75f', 'DRAFT', null, null, 1, 'seed', 'seed', null, false, null, null, false, null, null, null, null, null)
on conflict (content_id) do nothing;
INSERT INTO content.content_description (description_id, date_created, date_modified, updt_id, description, name, title, meta_description, meta_keywords, meta_title, sef_url, language_code, content_id, state, excerpt, alt_text, cta_label, subtitle)
VALUES (-300017, now(), now(), 'seed', '<h2>Student discount</h2><p>A draft still being written. Invisible in the storefront, editable in the console.</p>', 'Student discount (draft)', 'Student discount (draft)', null, null, null, 'student-discount', 'en', -30009, 'DRAFT', null, null, null, null)
on conflict (description_id) do nothing;
INSERT INTO content.content_description (description_id, date_created, date_modified, updt_id, description, name, title, meta_description, meta_keywords, meta_title, sef_url, language_code, content_id, state, excerpt, alt_text, cta_label, subtitle)
VALUES (-300018, now(), now(), 'seed', '<h2>Réduction étudiante</h2><p>Brouillon en cours. Invisible côté boutique, éditable dans la console.</p>', 'Réduction étudiante (brouillon)', 'Réduction étudiante (brouillon)', null, null, null, 'reduction-etudiante', 'fr', -30009, 'DRAFT', null, null, null, null)
on conflict (description_id) do nothing;

-- pages the store already had, promoted into the footer
UPDATE content.content SET show_in_footer = true
 WHERE store_merchant_id = '65f023632bc46470c104b75f' AND content_type = 'PAGE' AND code IN ('about-us', 'contact-us', 'location');
