-- Legal policies, each with a live version.
--
-- Demo content for the test store 65f023632bc46470c104b75f (USA Electronics Hub), in every language the store sells in.
-- Generated seed: ids are negative on purpose — content, media and menu ids all come from sequences that
-- only grow upward, so a seed row below zero can never collide with one the running service creates.

-- policy: PRIVACY
INSERT INTO content.content (content_id, date_created, date_modified, updt_id, code, content_type, sort_order, visible, store_merchant_id, status, publish_at, unpublish_at, version, created_by, updated_by, parent_id, noindex, canonical_url, og_media_id, show_in_footer, placement, starts_at, ends_at, policy_type, meta)
VALUES (-30010, now(), now(), 'seed', 'privacy-policy', 'POLICY', 100, true, '65f023632bc46470c104b75f', 'PUBLISHED', null, null, 1, 'seed', 'seed', null, false, null, null, false, null, null, null, 'PRIVACY', '{"jurisdiction": null, "requiresAcceptance": false, "notifyCustomers": false, "displayAt": {"footer": true, "checkout": false, "signup": false}}')
on conflict (content_id) do nothing;
INSERT INTO content.content_description (description_id, date_created, date_modified, updt_id, description, name, title, meta_description, meta_keywords, meta_title, sef_url, language_code, content_id, state, excerpt, alt_text, cta_label, subtitle)
VALUES (-300019, now(), now(), 'seed', '<h2>Privacy policy</h2><p>USA Electronics Hub, 456 Tech Avenue, New York, NY 10001, decides how your data is used.</p><h3>What we collect</h3><ul><li>Account and delivery details</li><li>Order, repair and trade-in history</li><li>Device serial numbers, which is how a warranty claim is verified</li></ul><h3>How long we keep it</h3><p>Order records are kept seven years for tax purposes; account data three years after your last activity; repair records for the life of the warranty plus one year.</p><h3>Your choices</h3><p>California residents may request access, deletion and opt-out of sale under the CCPA — we do not sell personal information. Write to <a href="mailto:privacy@usaelectronics.com">privacy@usaelectronics.com</a>.</p>', 'Privacy policy', 'Privacy policy', null, null, null, null, 'en', -30010, 'TRANSLATED', null, null, null, null)
on conflict (description_id) do nothing;
INSERT INTO content.content_description (description_id, date_created, date_modified, updt_id, description, name, title, meta_description, meta_keywords, meta_title, sef_url, language_code, content_id, state, excerpt, alt_text, cta_label, subtitle)
VALUES (-300020, now(), now(), 'seed', '<h2>Politique de confidentialité</h2><p>USA Electronics Hub, 456 Tech Avenue, New York, NY 10001, décide de l''usage fait de vos données.</p><h3>Données collectées</h3><ul><li>Compte et coordonnées de livraison</li><li>Historique de commandes, réparations et reprises</li><li>Numéros de série des appareils, base de la vérification de garantie</li></ul><h3>Conservation</h3><p>Les commandes sont conservées sept ans à des fins fiscales, les données de compte trois ans après la dernière activité, les dossiers de réparation pendant la durée de garantie plus un an.</p><h3>Vos choix</h3><p>Les résidents de Californie disposent d''un droit d''accès, de suppression et d''opposition à la vente au titre du CCPA — nous ne vendons aucune donnée personnelle. Écrivez à <a href="mailto:privacy@usaelectronics.com">privacy@usaelectronics.com</a>.</p>', 'Politique de confidentialité', 'Politique de confidentialité', null, null, null, null, 'fr', -30010, 'TRANSLATED', null, null, null, null)
on conflict (description_id) do nothing;
INSERT INTO content.policy_version (id, store_merchant_id, content_id, version, status, effective_from, note, translations, published_at, published_by)
VALUES (-3001, '65f023632bc46470c104b75f', -30010, 1, 'LIVE', now() - interval '30 days', null, '[{"language": "en", "title": "Privacy policy", "body": "<h2>Privacy policy</h2><p>USA Electronics Hub, 456 Tech Avenue, New York, NY 10001, decides how your data is used.</p><h3>What we collect</h3><ul><li>Account and delivery details</li><li>Order, repair and trade-in history</li><li>Device serial numbers, which is how a warranty claim is verified</li></ul><h3>How long we keep it</h3><p>Order records are kept seven years for tax purposes; account data three years after your last activity; repair records for the life of the warranty plus one year.</p><h3>Your choices</h3><p>California residents may request access, deletion and opt-out of sale under the CCPA — we do not sell personal information. Write to <a href=\"mailto:privacy@usaelectronics.com\">privacy@usaelectronics.com</a>.</p>", "state": "TRANSLATED"}, {"language": "fr", "title": "Politique de confidentialité", "body": "<h2>Politique de confidentialité</h2><p>USA Electronics Hub, 456 Tech Avenue, New York, NY 10001, décide de l''usage fait de vos données.</p><h3>Données collectées</h3><ul><li>Compte et coordonnées de livraison</li><li>Historique de commandes, réparations et reprises</li><li>Numéros de série des appareils, base de la vérification de garantie</li></ul><h3>Conservation</h3><p>Les commandes sont conservées sept ans à des fins fiscales, les données de compte trois ans après la dernière activité, les dossiers de réparation pendant la durée de garantie plus un an.</p><h3>Vos choix</h3><p>Les résidents de Californie disposent d''un droit d''accès, de suppression et d''opposition à la vente au titre du CCPA — nous ne vendons aucune donnée personnelle. Écrivez à <a href=\"mailto:privacy@usaelectronics.com\">privacy@usaelectronics.com</a>.</p>", "state": "TRANSLATED"}]', now(), 'seed')
on conflict (id) do nothing;

-- policy: RETURNS
INSERT INTO content.content (content_id, date_created, date_modified, updt_id, code, content_type, sort_order, visible, store_merchant_id, status, publish_at, unpublish_at, version, created_by, updated_by, parent_id, noindex, canonical_url, og_media_id, show_in_footer, placement, starts_at, ends_at, policy_type, meta)
VALUES (-30011, now(), now(), 'seed', 'return-policy', 'POLICY', 101, true, '65f023632bc46470c104b75f', 'PUBLISHED', null, null, 1, 'seed', 'seed', null, false, null, null, false, null, null, null, 'RETURNS', '{"jurisdiction": null, "requiresAcceptance": false, "notifyCustomers": false, "displayAt": {"footer": true, "checkout": false, "signup": false}}')
on conflict (content_id) do nothing;
INSERT INTO content.content_description (description_id, date_created, date_modified, updt_id, description, name, title, meta_description, meta_keywords, meta_title, sef_url, language_code, content_id, state, excerpt, alt_text, cta_label, subtitle)
VALUES (-300021, now(), now(), 'seed', '<h2>Return policy</h2><p>Forty-five days on anything unopened, thirty days on anything opened, counted from delivery.</p><h3>Conditions</h3><ul><li>All original accessories and packaging</li><li>Device signed out of its manufacturer account</li><li>Return shipping is free; we do not charge restocking fees</li></ul><h3>Refunds</h3><p>Issued within three business days of the item reaching our warehouse, to the original payment method.</p><p><em>Version 2 — the unopened window went from thirty to forty-five days, and the restocking fee is gone.</em></p>', 'Return policy', 'Return policy', null, null, null, null, 'en', -30011, 'TRANSLATED', null, null, null, null)
on conflict (description_id) do nothing;
INSERT INTO content.content_description (description_id, date_created, date_modified, updt_id, description, name, title, meta_description, meta_keywords, meta_title, sef_url, language_code, content_id, state, excerpt, alt_text, cta_label, subtitle)
VALUES (-300022, now(), now(), 'seed', '<h2>Politique de retour</h2><p>Quarante-cinq jours sur tout produit non ouvert, trente jours sur un produit ouvert, à compter de la livraison.</p><h3>Conditions</h3><ul><li>Tous les accessoires et l''emballage d''origine</li><li>Appareil déconnecté du compte constructeur</li><li>Retour gratuit ; aucun frais de remise en stock</li></ul><h3>Remboursement</h3><p>Sous trois jours ouvrés après réception à l''entrepôt, sur le moyen de paiement d''origine.</p><p><em>Version 2 — la fenêtre non ouverte passe de trente à quarante-cinq jours, et les frais de remise en stock disparaissent.</em></p>', 'Politique de retour', 'Politique de retour', null, null, null, null, 'fr', -30011, 'TRANSLATED', null, null, null, null)
on conflict (description_id) do nothing;
INSERT INTO content.policy_version (id, store_merchant_id, content_id, version, status, effective_from, note, translations, published_at, published_by)
VALUES (-3002, '65f023632bc46470c104b75f', -30011, 1, 'ARCHIVED', now() - interval '400 days', 'Initial version', '[{"language": "en", "title": "Return policy", "body": "<h2>Return policy</h2><p>Thirty days unopened, fourteen days opened, with a 10% restocking fee on opened items.</p><p><em>Version 1 — archived.</em></p>", "state": "TRANSLATED"}, {"language": "fr", "title": "Politique de retour", "body": "<h2>Politique de retour</h2><p>Trente jours non ouvert, quatorze jours ouvert, avec 10 % de frais de remise en stock.</p><p><em>Version 1 — archivée.</em></p>", "state": "TRANSLATED"}]', now(), 'seed')
on conflict (id) do nothing;
INSERT INTO content.policy_version (id, store_merchant_id, content_id, version, status, effective_from, note, translations, published_at, published_by)
VALUES (-3003, '65f023632bc46470c104b75f', -30011, 2, 'LIVE', now() - interval '30 days', 'Second version', '[{"language": "en", "title": "Return policy", "body": "<h2>Return policy</h2><p>Forty-five days on anything unopened, thirty days on anything opened, counted from delivery.</p><h3>Conditions</h3><ul><li>All original accessories and packaging</li><li>Device signed out of its manufacturer account</li><li>Return shipping is free; we do not charge restocking fees</li></ul><h3>Refunds</h3><p>Issued within three business days of the item reaching our warehouse, to the original payment method.</p><p><em>Version 2 — the unopened window went from thirty to forty-five days, and the restocking fee is gone.</em></p>", "state": "TRANSLATED"}, {"language": "fr", "title": "Politique de retour", "body": "<h2>Politique de retour</h2><p>Quarante-cinq jours sur tout produit non ouvert, trente jours sur un produit ouvert, à compter de la livraison.</p><h3>Conditions</h3><ul><li>Tous les accessoires et l''emballage d''origine</li><li>Appareil déconnecté du compte constructeur</li><li>Retour gratuit ; aucun frais de remise en stock</li></ul><h3>Remboursement</h3><p>Sous trois jours ouvrés après réception à l''entrepôt, sur le moyen de paiement d''origine.</p><p><em>Version 2 — la fenêtre non ouverte passe de trente à quarante-cinq jours, et les frais de remise en stock disparaissent.</em></p>", "state": "TRANSLATED"}]', now(), 'seed')
on conflict (id) do nothing;

-- policy: SHIPPING
INSERT INTO content.content (content_id, date_created, date_modified, updt_id, code, content_type, sort_order, visible, store_merchant_id, status, publish_at, unpublish_at, version, created_by, updated_by, parent_id, noindex, canonical_url, og_media_id, show_in_footer, placement, starts_at, ends_at, policy_type, meta)
VALUES (-30012, now(), now(), 'seed', 'shipping-policy', 'POLICY', 102, true, '65f023632bc46470c104b75f', 'PUBLISHED', null, null, 1, 'seed', 'seed', null, false, null, null, false, null, null, null, 'SHIPPING', '{"jurisdiction": null, "requiresAcceptance": false, "notifyCustomers": false, "displayAt": {"footer": true, "checkout": false, "signup": false}}')
on conflict (content_id) do nothing;
INSERT INTO content.content_description (description_id, date_created, date_modified, updt_id, description, name, title, meta_description, meta_keywords, meta_title, sef_url, language_code, content_id, state, excerpt, alt_text, cta_label, subtitle)
VALUES (-300023, now(), now(), 'seed', '<h2>Shipping policy</h2><p>Orders confirmed before 3pm Eastern ship the same business day from our Secaucus warehouse.</p><table><tr><th>Service</th><th>Time</th><th>Cost</th></tr><tr><td>Standard (contiguous US)</td><td>3–5 business days</td><td>Free over $75</td></tr><tr><td>Two-day</td><td>2 business days</td><td>$14.99</td></tr><tr><td>Overnight</td><td>Next business day</td><td>$29.99</td></tr><tr><td>Alaska, Hawaii, PR</td><td>5–8 business days</td><td>$24.99</td></tr></table><p>Anything over $500 ships with signature required. We do not deliver to freight forwarders.</p>', 'Shipping policy', 'Shipping policy', null, null, null, null, 'en', -30012, 'TRANSLATED', null, null, null, null)
on conflict (description_id) do nothing;
INSERT INTO content.content_description (description_id, date_created, date_modified, updt_id, description, name, title, meta_description, meta_keywords, meta_title, sef_url, language_code, content_id, state, excerpt, alt_text, cta_label, subtitle)
VALUES (-300024, now(), now(), 'seed', '<h2>Conditions de livraison</h2><p>Les commandes confirmées avant 15h heure de l''Est partent le jour même de notre entrepôt de Secaucus.</p><table><tr><th>Service</th><th>Délai</th><th>Tarif</th></tr><tr><td>Standard (États contigus)</td><td>3–5 jours ouvrés</td><td>Offert dès 75 $</td></tr><tr><td>Deux jours</td><td>2 jours ouvrés</td><td>14,99 $</td></tr><tr><td>Lendemain</td><td>Jour ouvré suivant</td><td>29,99 $</td></tr><tr><td>Alaska, Hawaï, Porto Rico</td><td>5–8 jours ouvrés</td><td>24,99 $</td></tr></table><p>Toute commande au-delà de 500 $ exige une signature. Nous ne livrons pas les transitaires.</p>', 'Conditions de livraison', 'Conditions de livraison', null, null, null, null, 'fr', -30012, 'TRANSLATED', null, null, null, null)
on conflict (description_id) do nothing;
INSERT INTO content.policy_version (id, store_merchant_id, content_id, version, status, effective_from, note, translations, published_at, published_by)
VALUES (-3004, '65f023632bc46470c104b75f', -30012, 1, 'LIVE', now() - interval '30 days', null, '[{"language": "en", "title": "Shipping policy", "body": "<h2>Shipping policy</h2><p>Orders confirmed before 3pm Eastern ship the same business day from our Secaucus warehouse.</p><table><tr><th>Service</th><th>Time</th><th>Cost</th></tr><tr><td>Standard (contiguous US)</td><td>3–5 business days</td><td>Free over $75</td></tr><tr><td>Two-day</td><td>2 business days</td><td>$14.99</td></tr><tr><td>Overnight</td><td>Next business day</td><td>$29.99</td></tr><tr><td>Alaska, Hawaii, PR</td><td>5–8 business days</td><td>$24.99</td></tr></table><p>Anything over $500 ships with signature required. We do not deliver to freight forwarders.</p>", "state": "TRANSLATED"}, {"language": "fr", "title": "Conditions de livraison", "body": "<h2>Conditions de livraison</h2><p>Les commandes confirmées avant 15h heure de l''Est partent le jour même de notre entrepôt de Secaucus.</p><table><tr><th>Service</th><th>Délai</th><th>Tarif</th></tr><tr><td>Standard (États contigus)</td><td>3–5 jours ouvrés</td><td>Offert dès 75 $</td></tr><tr><td>Deux jours</td><td>2 jours ouvrés</td><td>14,99 $</td></tr><tr><td>Lendemain</td><td>Jour ouvré suivant</td><td>29,99 $</td></tr><tr><td>Alaska, Hawaï, Porto Rico</td><td>5–8 jours ouvrés</td><td>24,99 $</td></tr></table><p>Toute commande au-delà de 500 $ exige une signature. Nous ne livrons pas les transitaires.</p>", "state": "TRANSLATED"}]', now(), 'seed')
on conflict (id) do nothing;

-- policy: COOKIES
INSERT INTO content.content (content_id, date_created, date_modified, updt_id, code, content_type, sort_order, visible, store_merchant_id, status, publish_at, unpublish_at, version, created_by, updated_by, parent_id, noindex, canonical_url, og_media_id, show_in_footer, placement, starts_at, ends_at, policy_type, meta)
VALUES (-30013, now(), now(), 'seed', 'cookie-policy', 'POLICY', 103, true, '65f023632bc46470c104b75f', 'PUBLISHED', null, null, 1, 'seed', 'seed', null, false, null, null, false, null, null, null, 'COOKIES', '{"jurisdiction": null, "requiresAcceptance": false, "notifyCustomers": false, "displayAt": {"footer": true, "checkout": false, "signup": false}}')
on conflict (content_id) do nothing;
INSERT INTO content.content_description (description_id, date_created, date_modified, updt_id, description, name, title, meta_description, meta_keywords, meta_title, sef_url, language_code, content_id, state, excerpt, alt_text, cta_label, subtitle)
VALUES (-300025, now(), now(), 'seed', '<h2>Cookies</h2><p>Three families of cookies, one of which you cannot turn off because the cart depends on it.</p><ul><li><strong>Essential</strong> — cart, session, fraud prevention. Always on.</li><li><strong>Analytics</strong> — aggregate traffic measurement, 13 months.</li><li><strong>Advertising</strong> — retargeting, 90 days, off by default.</li></ul><p>Your choice is stored for six months and can be changed from the “Cookie preferences” link in the footer at any time.</p>', 'Cookie policy', 'Cookie policy', null, null, null, null, 'en', -30013, 'TRANSLATED', null, null, null, null)
on conflict (description_id) do nothing;
INSERT INTO content.content_description (description_id, date_created, date_modified, updt_id, description, name, title, meta_description, meta_keywords, meta_title, sef_url, language_code, content_id, state, excerpt, alt_text, cta_label, subtitle)
VALUES (-300026, now(), now(), 'seed', '<h2>Cookies</h2><p>Trois familles de cookies, dont une que vous ne pouvez pas désactiver, le panier en dépendant.</p><ul><li><strong>Essentiels</strong> — panier, session, prévention de la fraude. Toujours actifs.</li><li><strong>Mesure</strong> — trafic agrégé, 13 mois.</li><li><strong>Publicité</strong> — reciblage, 90 jours, désactivé par défaut.</li></ul><p>Votre choix est conservé six mois et modifiable à tout moment depuis « Préférences cookies » en pied de page.</p>', 'Politique relative aux cookies', 'Politique relative aux cookies', null, null, null, null, 'fr', -30013, 'TRANSLATED', null, null, null, null)
on conflict (description_id) do nothing;
INSERT INTO content.policy_version (id, store_merchant_id, content_id, version, status, effective_from, note, translations, published_at, published_by)
VALUES (-3005, '65f023632bc46470c104b75f', -30013, 1, 'LIVE', now() - interval '30 days', null, '[{"language": "en", "title": "Cookie policy", "body": "<h2>Cookies</h2><p>Three families of cookies, one of which you cannot turn off because the cart depends on it.</p><ul><li><strong>Essential</strong> — cart, session, fraud prevention. Always on.</li><li><strong>Analytics</strong> — aggregate traffic measurement, 13 months.</li><li><strong>Advertising</strong> — retargeting, 90 days, off by default.</li></ul><p>Your choice is stored for six months and can be changed from the “Cookie preferences” link in the footer at any time.</p>", "state": "TRANSLATED"}, {"language": "fr", "title": "Politique relative aux cookies", "body": "<h2>Cookies</h2><p>Trois familles de cookies, dont une que vous ne pouvez pas désactiver, le panier en dépendant.</p><ul><li><strong>Essentiels</strong> — panier, session, prévention de la fraude. Toujours actifs.</li><li><strong>Mesure</strong> — trafic agrégé, 13 mois.</li><li><strong>Publicité</strong> — reciblage, 90 jours, désactivé par défaut.</li></ul><p>Votre choix est conservé six mois et modifiable à tout moment depuis « Préférences cookies » en pied de page.</p>", "state": "TRANSLATED"}]', now(), 'seed')
on conflict (id) do nothing;

