-- Blog categories and posts.
--
-- Demo content for the test store 65f023632bc46470c104b75f (USA Electronics Hub), in every language the store sells in.
-- Generated seed: ids are negative on purpose — content, media and menu ids all come from sequences that
-- only grow upward, so a seed row below zero can never collide with one the running service creates.

INSERT INTO content.post_category (id, store_merchant_id, slug, position, names)
VALUES (-351, '65f023632bc46470c104b75f', 'reviews', 0, '{"en": "Reviews", "fr": "Tests"}')
on conflict (store_merchant_id, slug) do nothing;
INSERT INTO content.post_category (id, store_merchant_id, slug, position, names)
VALUES (-352, '65f023632bc46470c104b75f', 'how-to', 1, '{"en": "How-to", "fr": "Tutoriels"}')
on conflict (store_merchant_id, slug) do nothing;
INSERT INTO content.post_category (id, store_merchant_id, slug, position, names)
VALUES (-353, '65f023632bc46470c104b75f', 'workshop', 2, '{"en": "From the bench", "fr": "Au banc d''essai"}')
on conflict (store_merchant_id, slug) do nothing;

-- post: laptop-thermals-what-reviews-miss (PUBLISHED)
INSERT INTO content.content (content_id, date_created, date_modified, updt_id, code, content_type, sort_order, visible, store_merchant_id, status, publish_at, unpublish_at, version, created_by, updated_by, parent_id, noindex, canonical_url, og_media_id, show_in_footer, placement, starts_at, ends_at, policy_type, meta)
VALUES (-30026, now(), now(), 'seed', 'laptop-thermals-what-reviews-miss', 'POST', 0, true, '65f023632bc46470c104b75f', 'PUBLISHED', now() - interval '2 days', null, 1, 'seed', 'seed', null, false, null, null, false, null, null, null, null, '{"heroMediaId": -390003, "categoryIds": [-353, -351], "tags": ["laptops", "thermals", "benchmarks"], "authorName": "Priya Raman", "featured": true}')
on conflict (content_id) do nothing;
INSERT INTO content.content_description (description_id, date_created, date_modified, updt_id, description, name, title, meta_description, meta_keywords, meta_title, sef_url, language_code, content_id, state, excerpt, alt_text, cta_label, subtitle)
VALUES (-300051, now(), now(), 'seed', '<p>Every thin laptop is fast for thirty seconds. The interesting question is what it does in minute twelve.</p><h2>Why peak scores mislead</h2><p>Manufacturers size the cooling for a short burst, because that is what a benchmark measures. Under a thirty-minute sustained load, the same machine can settle 40% below its headline number — and that is the number you get while rendering, compiling or exporting.</p><h2>How we test</h2><ul><li>Thirty minutes of combined CPU and GPU load in a 22°C room</li><li>Fan noise recorded at 50 cm, A-weighted</li><li>Keyboard-deck surface temperature at three points</li></ul><h2>What we look for</h2><p>A machine that settles honestly at 70% of peak and stays quiet beats one that spikes to 100% and then collapses to 45% with the fans at 48 dB. The second looks better in a chart and is worse to own.</p><h2>The chassis that surprised us</h2><p>Two of the three quietest machines this year are the heaviest in their class. Cooling takes volume; there is no way around the physics.</p>', 'Laptop thermals: what most reviews miss', 'Laptop thermals: what most reviews miss', 'Why sustained load matters more than peak scores, and how we measure it before a laptop reaches the catalogue.', 'laptops, thermals, benchmarks', 'Laptop thermals: what most reviews miss | The Bench', 'laptop-thermals-what-reviews-miss', 'en', -30026, 'TRANSLATED', 'A thirty-second benchmark flatters every laptop. Thirty minutes separates them.', null, null, null)
on conflict (description_id) do nothing;
INSERT INTO content.content_description (description_id, date_created, date_modified, updt_id, description, name, title, meta_description, meta_keywords, meta_title, sef_url, language_code, content_id, state, excerpt, alt_text, cta_label, subtitle)
VALUES (-300052, now(), now(), 'seed', '<p>Tout portable fin est rapide pendant trente secondes. La question intéressante, c''est la douzième minute.</p><h2>Pourquoi les scores de crête trompent</h2><p>Les constructeurs dimensionnent le refroidissement pour une salve courte, puisque c''est ce que mesure un benchmark. Sur trente minutes de charge continue, la même machine peut se stabiliser 40 % sous son chiffre d''annonce — et c''est ce chiffre-là que vous obtenez en rendu, en compilation ou à l''export.</p><h2>Notre protocole</h2><ul><li>Trente minutes de charge combinée CPU et GPU dans une pièce à 22 °C</li><li>Bruit de ventilation relevé à 50 cm, pondéré A</li><li>Température de surface du clavier en trois points</li></ul><h2>Ce que nous cherchons</h2><p>Une machine qui se stabilise honnêtement à 70 % de sa crête en restant silencieuse vaut mieux qu''une autre qui monte à 100 % puis s''effondre à 45 % avec les ventilateurs à 48 dB. La seconde paraît meilleure sur un graphique et se vit moins bien.</p><h2>Le châssis qui nous a surpris</h2><p>Deux des trois machines les plus silencieuses de l''année sont les plus lourdes de leur catégorie. Refroidir demande du volume ; la physique ne se contourne pas.</p>', 'Thermique des portables : ce que les tests oublient', 'Thermique des portables : ce que les tests oublient', 'Pourquoi la charge soutenue compte plus que le score de crête, et comment nous la mesurons.', 'laptops, thermals, benchmarks', 'Thermique des portables | Au banc d''essai', 'thermique-des-portables', 'fr', -30026, 'TRANSLATED', 'Trente secondes de benchmark flattent n''importe quel portable. Trente minutes les départagent.', null, null, null)
on conflict (description_id) do nothing;
INSERT INTO content.media_usage (id, asset_id, owner_kind, owner_ref, owner_title, content_id, content_type, field)
VALUES (-3001, -390003, 'CONTENT', '-30026', 'Laptop thermals: what most reviews miss', -30026, 'POST', 'hero')
on conflict (id) do nothing;

-- post: anc-headphones-measured (PUBLISHED)
INSERT INTO content.content (content_id, date_created, date_modified, updt_id, code, content_type, sort_order, visible, store_merchant_id, status, publish_at, unpublish_at, version, created_by, updated_by, parent_id, noindex, canonical_url, og_media_id, show_in_footer, placement, starts_at, ends_at, policy_type, meta)
VALUES (-30027, now(), now(), 'seed', 'anc-headphones-measured', 'POST', 1, true, '65f023632bc46470c104b75f', 'PUBLISHED', now() - interval '8 days', null, 1, 'seed', 'seed', null, false, null, null, false, null, null, null, null, '{"heroMediaId": -390004, "categoryIds": [-351], "tags": ["headphones", "anc", "audio"], "authorName": "Daniel Okafor", "featured": false}')
on conflict (content_id) do nothing;
INSERT INTO content.content_description (description_id, date_created, date_modified, updt_id, description, name, title, meta_description, meta_keywords, meta_title, sef_url, language_code, content_id, state, excerpt, alt_text, cta_label, subtitle)
VALUES (-300053, now(), now(), 'seed', '<h2>Cancellation is a low-frequency trick</h2><p>Active cancellation works well below about 1 kHz and poorly above it. That is why a plane cabin goes quiet and a nearby conversation does not.</p><h2>The number that matters</h2><p>Attenuation at 100 Hz, in decibels, on a measurement head. The best sets on our bench reach 28–32 dB there; a mid-range set manages 18–20; the difference is the entire experience on a long flight.</p><h2>What the box does not say</h2><ul><li>Cancellation depth usually costs battery, sometimes 30% of it</li><li>Strong cancellation can produce a pressure sensation some people cannot tolerate</li><li>Wind noise handling varies far more between models than cancellation depth does</li></ul><h2>Try before you commit</h2><p>Pressure sensitivity is individual and no measurement predicts it. Our thirty-day window on opened headphones exists precisely for this.</p>', 'Noise cancelling, measured rather than described', 'Noise cancelling, measured rather than described', 'How active cancellation is measured, why low frequencies matter most, and what marketing figures leave out.', 'headphones, anc, audio', 'Noise cancelling, measured | The Bench', 'anc-headphones-measured', 'en', -30027, 'TRANSLATED', 'Every set claims to cancel noise. Only the 100 Hz figure tells you whether it cancels the noise you have.', null, null, null)
on conflict (description_id) do nothing;
INSERT INTO content.content_description (description_id, date_created, date_modified, updt_id, description, name, title, meta_description, meta_keywords, meta_title, sef_url, language_code, content_id, state, excerpt, alt_text, cta_label, subtitle)
VALUES (-300054, now(), now(), 'seed', '<h2>La réduction est une affaire de graves</h2><p>La réduction active fonctionne bien en dessous de 1 kHz et mal au-dessus. D''où une cabine d''avion qui se tait et une conversation voisine qui persiste.</p><h2>Le chiffre qui compte</h2><p>L''atténuation à 100 Hz, en décibels, sur tête de mesure. Les meilleurs casques de notre banc atteignent 28 à 32 dB ; un modèle milieu de gamme plafonne à 18–20 ; l''écart, c''est toute l''expérience d''un vol long-courrier.</p><h2>Ce que la boîte ne dit pas</h2><ul><li>La profondeur de réduction coûte de l''autonomie, parfois 30 %</li><li>Une réduction forte crée une sensation de pression que certains ne supportent pas</li><li>La tenue au vent varie bien plus entre modèles que la profondeur de réduction</li></ul><h2>Essayez avant de vous engager</h2><p>La sensibilité à la pression est individuelle et aucune mesure ne la prédit. Nos trente jours sur casque ouvert existent exactement pour cela.</p>', 'La réduction de bruit, mesurée plutôt que décrite', 'La réduction de bruit, mesurée plutôt que décrite', 'Comment se mesure la réduction active, pourquoi les basses fréquences priment, et ce que les fiches omettent.', 'headphones, anc, audio', 'La réduction de bruit, mesurée | Au banc d''essai', 'reduction-de-bruit-mesuree', 'fr', -30027, 'TRANSLATED', 'Tous les casques prétendent réduire le bruit. Seul le chiffre à 100 Hz dit s''ils réduisent le vôtre.', null, null, null)
on conflict (description_id) do nothing;
INSERT INTO content.media_usage (id, asset_id, owner_kind, owner_ref, owner_title, content_id, content_type, field)
VALUES (-3002, -390004, 'CONTENT', '-30027', 'Noise cancelling, measured rather than described', -30027, 'POST', 'hero')
on conflict (id) do nothing;

-- post: make-your-battery-last (PUBLISHED)
INSERT INTO content.content (content_id, date_created, date_modified, updt_id, code, content_type, sort_order, visible, store_merchant_id, status, publish_at, unpublish_at, version, created_by, updated_by, parent_id, noindex, canonical_url, og_media_id, show_in_footer, placement, starts_at, ends_at, policy_type, meta)
VALUES (-30028, now(), now(), 'seed', 'make-your-battery-last', 'POST', 2, true, '65f023632bc46470c104b75f', 'PUBLISHED', now() - interval '16 days', null, 1, 'seed', 'seed', null, false, null, null, false, null, null, null, null, '{"heroMediaId": -390005, "categoryIds": [-352], "tags": ["battery", "maintenance", "phones"], "authorName": "Priya Raman", "featured": false}')
on conflict (content_id) do nothing;
INSERT INTO content.content_description (description_id, date_created, date_modified, updt_id, description, name, title, meta_description, meta_keywords, meta_title, sef_url, language_code, content_id, state, excerpt, alt_text, cta_label, subtitle)
VALUES (-300055, now(), now(), 'seed', '<h2>Three things matter</h2><ol><li><strong>Heat.</strong> A cell held at 35°C degrades roughly twice as fast as one at 25°C. Charging in a hot car is the single worst habit.</li><li><strong>Time at 100%.</strong> Sitting fully charged for hours stresses the cell. Overnight charging is fine if the device caps at 80% until morning — most now do.</li><li><strong>Deep discharge.</strong> Regularly running to 0% costs more cycles than any charging speed does.</li></ol><h2>Things that do not matter</h2><ul><li>Using a fast charger — the device controls the rate, not the brick</li><li>Charging to 100% occasionally, when you need the range</li><li>Third-party cables, provided they are certified</li></ul><h2>The honest expectation</h2><p>A phone battery loses about 20% of its capacity in two years of normal use. That is chemistry, not a defect, and no habit prevents it entirely.</p>', 'Make a lithium battery last', 'Make a lithium battery last', 'What actually degrades lithium cells, what does not, and the three habits that make a measurable difference.', 'battery, maintenance, phones', 'Make a lithium battery last | How-to', 'make-your-battery-last', 'en', -30028, 'TRANSLATED', 'Heat kills batteries faster than charging does. Almost everything else you have read is noise.', null, null, null)
on conflict (description_id) do nothing;
INSERT INTO content.content_description (description_id, date_created, date_modified, updt_id, description, name, title, meta_description, meta_keywords, meta_title, sef_url, language_code, content_id, state, excerpt, alt_text, cta_label, subtitle)
VALUES (-300056, now(), now(), 'seed', '<h2>Trois facteurs comptent</h2><ol><li><strong>La chaleur.</strong> Une cellule maintenue à 35 °C vieillit environ deux fois plus vite qu''à 25 °C. Charger dans une voiture au soleil est la pire habitude.</li><li><strong>Le temps passé à 100 %.</strong> Rester chargé à bloc pendant des heures fatigue la cellule. Charger la nuit ne pose pas de problème si l''appareil plafonne à 80 % jusqu''au matin, ce que la plupart font désormais.</li><li><strong>La décharge profonde.</strong> Descendre régulièrement à 0 % coûte plus de cycles que n''importe quelle vitesse de charge.</li></ol><h2>Ce qui ne compte pas</h2><ul><li>Utiliser un chargeur rapide — c''est l''appareil qui pilote le débit, pas le bloc</li><li>Charger à 100 % occasionnellement, quand vous avez besoin d''autonomie</li><li>Les câbles tiers, s''ils sont certifiés</li></ul><h2>L''attente honnête</h2><p>Une batterie de téléphone perd environ 20 % de sa capacité en deux ans d''usage normal. C''est de la chimie, pas un défaut, et aucune habitude ne l''empêche totalement.</p>', 'Faire durer une batterie lithium', 'Faire durer une batterie lithium', 'Ce qui dégrade réellement les cellules lithium, ce qui ne les dégrade pas, et les trois habitudes utiles.', 'battery, maintenance, phones', 'Faire durer une batterie lithium | Tutoriels', 'faire-durer-une-batterie', 'fr', -30028, 'TRANSLATED', 'La chaleur tue les batteries plus vite que la charge. Presque tout le reste est du bruit.', null, null, null)
on conflict (description_id) do nothing;
INSERT INTO content.media_usage (id, asset_id, owner_kind, owner_ref, owner_title, content_id, content_type, field)
VALUES (-3003, -390005, 'CONTENT', '-30028', 'Make a lithium battery last', -30028, 'POST', 'hero')
on conflict (id) do nothing;

-- post: tv-settings-out-of-the-box (PUBLISHED)
INSERT INTO content.content (content_id, date_created, date_modified, updt_id, code, content_type, sort_order, visible, store_merchant_id, status, publish_at, unpublish_at, version, created_by, updated_by, parent_id, noindex, canonical_url, og_media_id, show_in_footer, placement, starts_at, ends_at, policy_type, meta)
VALUES (-30029, now(), now(), 'seed', 'tv-settings-out-of-the-box', 'POST', 3, true, '65f023632bc46470c104b75f', 'PUBLISHED', now() - interval '25 days', null, 1, 'seed', 'seed', null, false, null, null, false, null, null, null, null, '{"heroMediaId": -390006, "categoryIds": [-352, -351], "tags": ["tv", "calibration", "picture"], "authorName": "Daniel Okafor", "featured": false}')
on conflict (content_id) do nothing;
INSERT INTO content.content_description (description_id, date_created, date_modified, updt_id, description, name, title, meta_description, meta_keywords, meta_title, sef_url, language_code, content_id, state, excerpt, alt_text, cta_label, subtitle)
VALUES (-300057, now(), now(), 'seed', '<h2>1. Turn off motion smoothing</h2><p>It interpolates frames the director never shot. Film looks like video, and the effect has a name for a reason.</p><h2>2. Switch out of Vivid</h2><p>Vivid — or Dynamic — is calibrated to survive fluorescent store lighting. Filmmaker, Cinema or Movie mode is far closer to the reference the content was graded against.</p><h2>3. Take sharpness to zero</h2><p>The sharpness control does not add detail; it adds a white halo around edges. Zero is neutral.</p><h2>4. Leave local dimming on high</h2><p>Contrary to forum advice, on modern panels high local dimming improves black level far more than it introduces blooming.</p><h2>5. Enable game mode for consoles</h2><p>It bypasses the processing that costs 60–100 ms of input lag. Nothing else on this list is as noticeable.</p>', 'The five TV settings to change on day one', 'The five TV settings to change on day one', 'Motion smoothing, picture mode, sharpness, local dimming and game mode — what to change and why.', 'tv, calibration, picture', 'Five TV settings to change on day one | How-to', 'tv-settings-out-of-the-box', 'en', -30029, 'TRANSLATED', 'Showroom mode exists to win a lit store. In a living room it is simply wrong.', null, null, null)
on conflict (description_id) do nothing;
INSERT INTO content.content_description (description_id, date_created, date_modified, updt_id, description, name, title, meta_description, meta_keywords, meta_title, sef_url, language_code, content_id, state, excerpt, alt_text, cta_label, subtitle)
VALUES (-300058, now(), now(), 'seed', '<h2>1. Désactiver la fluidification</h2><p>Elle interpole des images que le réalisateur n''a jamais tournées. Le film prend une allure de vidéo, et l''effet porte un nom pour de bonnes raisons.</p><h2>2. Quitter le mode Vif</h2><p>Vif — ou Dynamique — est calibré pour survivre aux néons d''un magasin. Les modes Filmmaker, Cinéma ou Film sont bien plus proches de la référence d''étalonnage.</p><h2>3. Mettre la netteté à zéro</h2><p>Le réglage de netteté n''ajoute pas de détail : il ajoute un halo blanc autour des contours. Zéro est neutre.</p><h2>4. Laisser la gradation locale au maximum</h2><p>Contrairement aux conseils de forum, sur les dalles récentes une gradation locale élevée améliore bien plus le niveau de noir qu''elle n''introduit de halo.</p><h2>5. Activer le mode jeu pour les consoles</h2><p>Il contourne les traitements qui coûtent 60 à 100 ms de latence. Rien d''autre dans cette liste ne se remarque autant.</p>', 'Les cinq réglages TV à changer le premier jour', 'Les cinq réglages TV à changer le premier jour', 'Fluidification, mode image, netteté, gradation locale et mode jeu : quoi changer et pourquoi.', 'tv, calibration, picture', 'Cinq réglages TV à changer | Tutoriels', 'cinq-reglages-tv', 'fr', -30029, 'TRANSLATED', 'Le mode magasin existe pour gagner un rayon éclairé. Dans un salon, il est simplement faux.', null, null, null)
on conflict (description_id) do nothing;
INSERT INTO content.media_usage (id, asset_id, owner_kind, owner_ref, owner_title, content_id, content_type, field)
VALUES (-3004, -390006, 'CONTENT', '-30029', 'The five TV settings to change on day one', -30029, 'POST', 'hero')
on conflict (id) do nothing;

-- post: refurbished-what-we-replace (PUBLISHED)
INSERT INTO content.content (content_id, date_created, date_modified, updt_id, code, content_type, sort_order, visible, store_merchant_id, status, publish_at, unpublish_at, version, created_by, updated_by, parent_id, noindex, canonical_url, og_media_id, show_in_footer, placement, starts_at, ends_at, policy_type, meta)
VALUES (-30030, now(), now(), 'seed', 'refurbished-what-we-replace', 'POST', 4, true, '65f023632bc46470c104b75f', 'PUBLISHED', now() - interval '38 days', null, 1, 'seed', 'seed', null, false, null, null, false, null, null, null, null, '{"heroMediaId": -390007, "categoryIds": [-353], "tags": ["refurbished", "repair", "trade-in"], "authorName": "Marcus Hale", "featured": false}')
on conflict (content_id) do nothing;
INSERT INTO content.content_description (description_id, date_created, date_modified, updt_id, description, name, title, meta_description, meta_keywords, meta_title, sef_url, language_code, content_id, state, excerpt, alt_text, cta_label, subtitle)
VALUES (-300059, now(), now(), 'seed', '<h2>Always replaced</h2><ul><li>The battery, if capacity is under 90% — not 80%, which is the industry line</li><li>Ear tips, thermal paste, and any adhesive seal opened during service</li><li>Cracked glass, even cosmetic hairlines on a screen</li></ul><h2>Tested and kept</h2><p>Panels, keyboards, ports and speakers are measured against the same bench spec as new stock. A port that passes ten thousand insertion cycles is a port that stays.</p><h2>When we scrap</h2><p>Any board with liquid-damage indicators triggered, any chassis with structural deformation, and any device whose manufacturer has stopped issuing security updates. The first two are safety; the third is honesty.</p><h2>What you get</h2><p>Our own one-year warranty, the full bench report, and a device that failed nothing rather than one that failed nothing visible.</p>', 'Refurbished: what we replace before reselling', 'Refurbished: what we replace before reselling', 'The parts we always change on a trade-in, the ones we test and keep, and when a device is scrapped.', 'refurbished, repair, trade-in', 'Refurbished: what we replace | The Bench', 'refurbished-what-we-replace', 'en', -30030, 'TRANSLATED', 'Six devices in ten come back to life. The other four never leave the bench.', null, null, null)
on conflict (description_id) do nothing;
INSERT INTO content.content_description (description_id, date_created, date_modified, updt_id, description, name, title, meta_description, meta_keywords, meta_title, sef_url, language_code, content_id, state, excerpt, alt_text, cta_label, subtitle)
VALUES (-300060, now(), now(), 'seed', '<h2>Systématiquement remplacé</h2><ul><li>La batterie si la capacité est sous 90 % — pas 80 %, la norme du secteur</li><li>Embouts, pâte thermique et tout joint adhésif ouvert pendant l''intervention</li><li>Verre fêlé, même une micro-fissure cosmétique sur un écran</li></ul><h2>Testé et conservé</h2><p>Dalles, claviers, connecteurs et haut-parleurs sont mesurés selon le même protocole que le neuf. Un connecteur qui tient dix mille cycles d''insertion reste en place.</p><h2>Quand nous mettons au rebut</h2><p>Toute carte dont les témoins de liquide sont déclenchés, tout châssis déformé structurellement, et tout appareil dont le constructeur a cessé les mises à jour de sécurité. Les deux premiers relèvent de la sécurité ; le troisième, de l''honnêteté.</p><h2>Ce que vous recevez</h2><p>Notre garantie d''un an, le rapport de banc complet, et un appareil qui n''a rien raté — pas un appareil qui n''a rien raté de visible.</p>', 'Reconditionné : ce que nous remplaçons avant de revendre', 'Reconditionné : ce que nous remplaçons avant de revendre', 'Les pièces systématiquement changées sur une reprise, celles que nous testons et gardons, et les cas de mise au rebut.', 'refurbished, repair, trade-in', 'Reconditionné : ce que nous remplaçons | Au banc d''essai', 'reconditionne-ce-que-nous-remplacons', 'fr', -30030, 'TRANSLATED', 'Six appareils sur dix repartent. Les quatre autres ne quittent jamais le banc.', null, null, null)
on conflict (description_id) do nothing;
INSERT INTO content.media_usage (id, asset_id, owner_kind, owner_ref, owner_title, content_id, content_type, field)
VALUES (-3005, -390007, 'CONTENT', '-30030', 'Refurbished: what we replace before reselling', -30030, 'POST', 'hero')
on conflict (id) do nothing;

-- post: usb-c-cables-are-not-equal (PUBLISHED)
INSERT INTO content.content (content_id, date_created, date_modified, updt_id, code, content_type, sort_order, visible, store_merchant_id, status, publish_at, unpublish_at, version, created_by, updated_by, parent_id, noindex, canonical_url, og_media_id, show_in_footer, placement, starts_at, ends_at, policy_type, meta)
VALUES (-30031, now(), now(), 'seed', 'usb-c-cables-are-not-equal', 'POST', 5, true, '65f023632bc46470c104b75f', 'PUBLISHED', now() - interval '55 days', null, 1, 'seed', 'seed', null, false, null, null, false, null, null, null, null, '{"heroMediaId": -390003, "categoryIds": [-352], "tags": ["usb-c", "cables", "charging"], "authorName": "Marcus Hale", "featured": false}')
on conflict (content_id) do nothing;
INSERT INTO content.content_description (description_id, date_created, date_modified, updt_id, description, name, title, meta_description, meta_keywords, meta_title, sef_url, language_code, content_id, state, excerpt, alt_text, cta_label, subtitle)
VALUES (-300061, now(), now(), 'seed', '<h2>One shape, four capabilities</h2><p>A USB-C cable can carry 60 W or 240 W, and 480 Mbps or 40 Gbps, in any combination. The connector tells you nothing.</p><h2>The e-marker</h2><p>Anything above 60 W needs a chip inside the cable declaring its rating. Without it the charger falls back to 60 W, which is why a 140 W laptop charges slowly on the wrong cable and nothing warns you.</p><h2>How to tell them apart</h2><ul><li>Look for the printed wattage or the certification logo on the connector shell</li><li>Charge-only cables are usually thinner and lighter; a 40 Gbps cable is noticeably stiff</li><li>Length matters: passive 40 Gbps cables stop working reliably past about 80 cm</li></ul><h2>What we stock</h2><p>Only certified cables, with the rating printed on the connector. It costs a little more and removes an entire category of support ticket.</p>', 'USB-C cables are not interchangeable', 'USB-C cables are not interchangeable', 'Power delivery, data rates, e-marker chips and how to tell a 240 W cable from a 60 W one.', 'usb-c, cables, charging', 'USB-C cables are not interchangeable | How-to', 'usb-c-cables-are-not-equal', 'en', -30031, 'TRANSLATED', 'Same connector, wildly different cables. The one in the drawer may be why your laptop charges slowly.', null, null, null)
on conflict (description_id) do nothing;
INSERT INTO content.content_description (description_id, date_created, date_modified, updt_id, description, name, title, meta_description, meta_keywords, meta_title, sef_url, language_code, content_id, state, excerpt, alt_text, cta_label, subtitle)
VALUES (-300062, now(), now(), 'seed', '<h2>Une forme, quatre capacités</h2><p>Un câble USB-C peut transporter 60 W ou 240 W, et 480 Mbit/s ou 40 Gbit/s, dans n''importe quelle combinaison. Le connecteur ne dit rien.</p><h2>La puce e-marker</h2><p>Au-delà de 60 W, une puce intégrée doit déclarer la capacité du câble. Sans elle, le chargeur retombe à 60 W : c''est pourquoi un portable de 140 W charge lentement sur le mauvais câble, sans le moindre avertissement.</p><h2>Comment les distinguer</h2><ul><li>Cherchez la puissance imprimée ou le logo de certification sur la coque du connecteur</li><li>Les câbles de charge seule sont plus fins et plus souples ; un câble 40 Gbit/s est nettement rigide</li><li>La longueur compte : un câble passif 40 Gbit/s décroche au-delà de 80 cm environ</li></ul><h2>Ce que nous référençons</h2><p>Uniquement des câbles certifiés, puissance imprimée sur le connecteur. Cela coûte un peu plus cher et supprime toute une catégorie de tickets de support.</p>', 'Les câbles USB-C ne se valent pas', 'Les câbles USB-C ne se valent pas', 'Puissance, débit de données, puce e-marker, et comment distinguer un câble 240 W d''un câble 60 W.', 'usb-c, cables, charging', 'Les câbles USB-C ne se valent pas | Tutoriels', 'les-cables-usb-c-ne-se-valent-pas', 'fr', -30031, 'TRANSLATED', 'Même connecteur, câbles radicalement différents. Celui du tiroir explique peut-être votre charge lente.', null, null, null)
on conflict (description_id) do nothing;
INSERT INTO content.media_usage (id, asset_id, owner_kind, owner_ref, owner_title, content_id, content_type, field)
VALUES (-3006, -390003, 'CONTENT', '-30031', 'USB-C cables are not interchangeable', -30031, 'POST', 'hero')
on conflict (id) do nothing;

-- post: holiday-gift-guide-2026 (DRAFT)
INSERT INTO content.content (content_id, date_created, date_modified, updt_id, code, content_type, sort_order, visible, store_merchant_id, status, publish_at, unpublish_at, version, created_by, updated_by, parent_id, noindex, canonical_url, og_media_id, show_in_footer, placement, starts_at, ends_at, policy_type, meta)
VALUES (-30032, now(), now(), 'seed', 'holiday-gift-guide-2026', 'POST', 6, true, '65f023632bc46470c104b75f', 'DRAFT', null, null, 1, 'seed', 'seed', null, false, null, null, false, null, null, null, null, '{"heroMediaId": -390004, "categoryIds": [-351], "tags": ["gift guide"], "authorName": "Priya Raman", "featured": false}')
on conflict (content_id) do nothing;
INSERT INTO content.content_description (description_id, date_created, date_modified, updt_id, description, name, title, meta_description, meta_keywords, meta_title, sef_url, language_code, content_id, state, excerpt, alt_text, cta_label, subtitle)
VALUES (-300063, now(), now(), 'seed', '<p>Draft. This post is the check that an unpublished POST stays off the blog while remaining editable in the console.</p>', 'Holiday gift guide 2026 (draft)', 'Holiday gift guide 2026 (draft)', null, 'gift guide', null, 'holiday-gift-guide-2026', 'en', -30032, 'DRAFT', 'Still being written — must not appear on the blog.', null, null, null)
on conflict (description_id) do nothing;
INSERT INTO content.content_description (description_id, date_created, date_modified, updt_id, description, name, title, meta_description, meta_keywords, meta_title, sef_url, language_code, content_id, state, excerpt, alt_text, cta_label, subtitle)
VALUES (-300064, now(), now(), 'seed', '<p>Brouillon. Cet article vérifie qu''un POST non publié reste hors du blog tout en restant éditable dans la console.</p>', 'Guide cadeaux 2026 (brouillon)', 'Guide cadeaux 2026 (brouillon)', null, 'gift guide', null, 'guide-cadeaux-2026', 'fr', -30032, 'DRAFT', 'En cours de rédaction — ne doit pas apparaître.', null, null, null)
on conflict (description_id) do nothing;

