// GENERATED by scripts/theme-routes.mjs — do not edit. The route logic lives in src/shell/routes.
import type {RegisteredThemeId} from './theme-id';

/** The themes with their own route tree under app/(storefront)/t/<id>/; proxy.ts rewrites their stores there. */
export const THEME_TREES: readonly RegisteredThemeId[] = ['fashion'];
