// GENERATED by scripts/theme-routes.mjs — do not edit. The route logic lives in src/shell/routes.
import theme from '@store-front/theme-grocery';
import {orderPage} from '@/shell/routes/order';

export {generateMetadata} from '@/shell/routes/order';
export default orderPage(theme);
