com:
  asrevo:
    cvhome:
      app:
        domain: "gateway.com"
      saas:
        domain: saas.${com.asrevo.cvhome.app.domain}
      services:
        uaa:
          name: uaa
          domain: uaa.${com.asrevo.cvhome.app.domain}
          port: 8001
          schema: http
          namespace: store-core.cvhome.lcl
          gateway-service-name: store-core-gateway
        store-core-gateway:
          name: store-core-gateway
          domain: ${com.asrevo.cvhome.app.domain}
          port: 8000
          schema: http
          namespace: store-core.cvhome.lcl
          gateway-service-name: store-core-gateway
        control-plane:
          name: control-plane
          domain: ${com.asrevo.cvhome.app.domain}
          port: 8020
          schema: http
          namespace: store-core.cvhome.lcl
          gateway-service-name: store-core-gateway
        seller-ui:
          name: seller-ui
          domain: seller-ui.${com.asrevo.cvhome.app.domain}
          port: 8010
          schema: http
          namespace: store-core.cvhome.lcl
          gateway-service-name: store-core-gateway
        store-pod-saas-gateway:
          name: store-pod-saas-gateway
          domain: ${com.asrevo.cvhome.saas.domain}
          port: 8443
          schema: https
          namespace: store-pod-507f1f77.cvhome.lcl
          gateway-service-name: store-pod-saas-gateway
        merchant:
          name: merchant
          domain: store-pod-507f1f77.${com.asrevo.cvhome.app.domain}
          port: 8120
          schema: http
          namespace: store-pod-507f1f77.cvhome.lcl
          gateway-service-name: store-pod-gateway
        catalog:
          name: catalog
          domain: store-pod-507f1f77.${com.asrevo.cvhome.app.domain}
          port: 8122
          schema: http
          namespace: store-pod-507f1f77.cvhome.lcl
          gateway-service-name: store-pod-gateway
        checkout:
          name: checkout
          domain: store-pod-507f1f77.${com.asrevo.cvhome.app.domain}
          port: 8123
          schema: http
          namespace: store-pod-507f1f77.cvhome.lcl
          gateway-service-name: store-pod-gateway
        cua:
          name: cua
          domain: store-pod-507f1f77.${com.asrevo.cvhome.app.domain}
          port: 8124
          schema: http
          namespace: store-pod-507f1f77.cvhome.lcl
          gateway-service-name: store-pod-gateway
        landing-ui:
          name: landing-ui
          domain: store-pod-507f1f77.${com.asrevo.cvhome.app.domain}
          port: 8110
          schema: http
          namespace: store-pod-507f1f77.cvhome.lcl
          gateway-service-name: store-pod-gateway
spring:
  docker:
    compose:
      file: ${spring.application.name}/compose.yml
  sql:
    init:
      mode: always
  datasource:
    driver-class-name: org.postgresql.Driver
    hikari:
      schema: ${spring.application.name}
  session:
    jdbc:
      initialize-schema: always
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  cloud:
    function:
      definition: events
    stream:
      input-bindings: events
      bindings:
        events-in-0:
          destination: events
          group: ${spring.application.name}
        events-out-0:
          content-type: application/json
          destination: events
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: false
          predicate:
            host:
              include-port: false
  security:
    oauth2:
      client:
        registration:
          uaa:
            client-id: web-app
            client-authentication-method: client_secret_basic
            authorization-grant-type: authorization_code
            scope: openid
            redirect-uri: "{baseUrl}/login/oauth2/code/uaa"
            provider: uaa
            client-secret: hLwOF59NEOdMzYYrfxUbQEGVK1uTczj7
        provider:
          uaa:
            #            comment issuer-uri to skip validation
            #            issuer-uri: ${com.asrevo.cvhome.services.uaa.schema}://${com.asrevo.cvhome.services.uaa.domain}:${com.asrevo.cvhome.services.uaa.port}
            jwk-set-uri: ${com.asrevo.cvhome.services.uaa.schema}://${com.asrevo.cvhome.services.uaa.domain}:${com.asrevo.cvhome.services.uaa.port}/oauth2/jwks
            authorization-uri: ${com.asrevo.cvhome.services.uaa.schema}://${com.asrevo.cvhome.services.uaa.domain}:${com.asrevo.cvhome.services.uaa.port}/oauth2/authorize
            user-info-uri: ${com.asrevo.cvhome.services.uaa.schema}://${com.asrevo.cvhome.services.uaa.domain}:${com.asrevo.cvhome.services.uaa.port}/userinfo
            token-uri: ${com.asrevo.cvhome.services.uaa.schema}://${com.asrevo.cvhome.services.uaa.domain}:${com.asrevo.cvhome.services.uaa.port}/oauth2/token
            end-session-endpoint: ${com.asrevo.cvhome.services.uaa.schema}://${com.asrevo.cvhome.services.uaa.domain}:${com.asrevo.cvhome.services.uaa.port}/connect/logout
            user-name-attribute: sub

      #            need to trace why getting 401 error=invalid_token, auth_method=validate_access_token is by issuer?
      #            user-info-uri: https://uaa.gateway.com:8443/realms/cvhome/protocol/openid-connect/userinfo
      #            user-name-attribute: sub
      resourceserver:
        jwt:
          #          jwk-set-uri: ${com.asrevo.cvhome.services.uaa.schema}://${com.asrevo.cvhome.services.uaa.domain}:${com.asrevo.cvhome.services.uaa.port}/realms/cvhome/protocol/openid-connect/certs
          #          issuer-uri: ${com.asrevo.cvhome.services.uaa.schema}://${com.asrevo.cvhome.services.uaa.domain}:${com.asrevo.cvhome.services.uaa.port}/realms/cvhome
          issuer-uri-set: ${com.asrevo.cvhome.services.uaa.schema}://${com.asrevo.cvhome.services.uaa.domain}:${com.asrevo.cvhome.services.uaa.port}
#          issuer-uri-set:
#            - ${com.asrevo.cvhome.services.uaa.schema}://${com.asrevo.cvhome.services.uaa.domain}:${com.asrevo.cvhome.services.uaa.port}/realms/cvhome
server:
  forward-headers-strategy: NATIVE
  port: ${com.asrevo.cvhome.services.${spring.application.name}.port}

springdoc:
  show-actuator: true
  api-docs:
    path: /api-docs
management:
  observations:
    key-values:
      application: ${spring.application.name}
  info:
    env:
      enabled: true
    os:
      enabled: true
  endpoint:
    health:
      show-details: always
    gateway:
      access: unrestricted
  endpoints:
    web:
      exposure:
        include: [ '*' ]
          #logging:
          #  level:
          #    org.springframework.boot: debug
          #    org.springframework.web: debug
          #    org.springframework.cloud.gateway: debug
          #    org.springframework.security: debug
          #    reactor.netty.http: debug
info:
  app:
    name: ${spring.application.name}
otel:
  sdk:
    disabled: true
  resource:
    attributes:
      service:
        name: ${spring.application.name}
  instrumentation:
    spring-webmvc:
      experimental-span-attributes: true
    spring-cloud-gateway:
      experimental-span-attributes: true
    spring-webflux:
      experimental-span-attributes: true
logging:
  level:
    com:
      asrevo: DEBUG