spring:
  datasource:
    url: jdbc:postgresql://${spring.datasource.host}:${spring.datasource.port}/${spring.datasource.database}
  cloud:
    loadbalancer:
      eager-load:
        clients:
          - "store-core-gateway"
          - "uaa"
          - "control-plane"
          - "billing"
          - "seller-ui"
          - "spg"
          - "merchant"
          - "catalog"
          - "checkout"
          - "cua"
          - "payment"
          - "landing-ui"
    ecs:
      discovery:
        namespace: "store-pod-507f1f77.cvhome.lcl"
        namespace-id: "ns-je7qri6wn7fbsrpn"
        enabled: true
        default-port: 8080
        service-ports:
          "uaa": 8001
          "store-core-gateway": 8000
          "seller-ui": 8010
          "control-plane": 8020
          "billing": 8021
          "landing-ui": 8110
          "merchant": 8120
          "catalog": 8122
          "checkout": 8123
          "cua": 8124
          "payment": 8125