spring:
  datasource:
    url: jdbc:postgresql://${spring.datasource.host}:${spring.datasource.port}/${spring.datasource.database}
  cloud:
    loadbalancer:
      eager-load:
        clients:
          - "store-core-gateway"
          - "core-auth"
          - "control-plane"
          - "seller-ui"
          - "store-pod-gateway"
          - "pod-auth"
          - "merchant"
          - "catalog"
          - "checkout"
          - "landing-ui"
    ecs:
      discovery:
        namespace: "store-pod-1.cvhome.lcl"
        namespace-id: "ns-je7qri6wn7fbsrpn"
        enabled: true
        default-port: 8080
        service-ports:
          "core-auth": 8001
          "store-core-gateway": 8000
          "seller-ui": 8010
          "control-plane": 8020
          "pod-auth": 8101
          "landing-ui": 8110
          "merchant": 8120
          "catalog": 8122
          "checkout": 8123
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: false