spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/cvhome
    username: postgres
    password: password
  cloud:
    discovery:
      client:
        simple:
          instances:
            core-auth:
              - uri: "http://localhost:8001"
                instance-id: core-auth-1
                metadata:
                  service-name: core-auth
                  instance: core-auth-1
            manager:
              - uri: "http://localhost:8020"
                instance-id: manager-1
                metadata:
                  service-name: manager
                  instance: manager-1
            subscription:
              - uri: "http://localhost:8021"
                instance-id: subscription-1
                metadata:
                  service-name: subscription
                  instance: subscription-1
            welcome-ui:
              - uri: "http://localhost:8011"
                instance-id: welcome-ui-1
                metadata:
                  service-name: welcome-ui
                  instance: welcome-ui-1
            store-core-gateway:
              - uri: "http://localhost:8000"
                instance-id: store-core-gateway-1
                metadata:
                  service-name: store-core-gateway
                  instance: store-core-gateway-1
            pod-auth:
              - uri: "http://localhost:8101"
                instance-id: pod-auth-1
                metadata:
                  service-name: pod-auth
                  instance: pod-auth-1
            store-ui:
              - uri: "http://localhost:8010"
                instance-id: store-ui-1
                metadata:
                  service-name: store-ui
                  instance: store-ui-1
            merchant:
              - uri: "http://localhost:8120"
                instance-id: merchant-1
                metadata:
                  service-name: merchant
                  instance: merchant-1
            content:
              - uri: "http://localhost:8121"
                instance-id: content-1
                metadata:
                  service-name: content
                  instance: content-1
            catalog:
              - uri: "http://localhost:8122"
                instance-id: catalog-1
                metadata:
                  service-name: catalog
                  instance: catalog-1
            order:
              - uri: "http://localhost:8123"
                instance-id: order-1
                metadata:
                  service-name: order
                  instance: order-1
            landing-ui:
              - uri: "http://localhost:8110"
                instance-id: landing-ui-1
                metadata:
                  service-name: landing-ui
                  instance: landing-ui-1
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: false