spring:
  sql:
    init:
      data-locations: classpath:init-sql/data-common.sql, classpath:init-sql/data-test-stores.sql, classpath:init-sql/stores/*/*.sql
com:
  asrevo:
    cvhome:
      pods:
        - id: 507f1f77bcf86cd799439011
          name: pod-507f1f77
          endpoint:
            endpoint: http://spg-507f1f77.gateway.com
            type: EXTERNAL
          domain: spg-507f1f77.gateway.com