com:
  asrevo:
    cvhome:
      pods:
        - id: 507f1f77bcf86cd799439011
          name: pod-507f1f77bcf86cd
          endpoint:
            endpoint: http://spg-507f1f77.gateway.com
            type: EXTERNAL
          domain: spg-507f1f77.gateway.com