spring:
  sql:
    init:
      data-locations: classpath:init-sql/data-common.sql, classpath:init-sql/data-test-stores.sql, classpath:init-sql/stores/*/*.sql
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri-set:
            - ${com.asrevo.cvhome.services.uaa.schema}://${com.asrevo.cvhome.services.uaa.domain}
            - ${com.asrevo.cvhome.services.uaa.schema}://${com.asrevo.cvhome.services.uaa.domain}:${com.asrevo.cvhome.services.uaa.port}
            - ${com.asrevo.cvhome.services.spg.schema}://${com.asrevo.cvhome.services.spg.domain}/cua
            - ${com.asrevo.cvhome.services.spg.schema}://${com.asrevo.cvhome.services.spg.domain}:${com.asrevo.cvhome.services.spg.port}/cua

com:
  asrevo:
    cvhome:
      cdn:
        storage:
          provider: MINIO
          bucket: "d0dd4299-963a-4458-b31f-8efe31c35e8e"
          s3-url: "http://localhost:9000"
          s3-access-key: "minioadmin"
          s3-secret-key: "minioadmin"
          region: "eu-central-1"
        base-path: "http://localhost:9000/d0dd4299-963a-4458-b31f-8efe31c35e8e"
      pod-info:
        pod:
          id: 507f1f77bcf86cd799439011
          name: pod-507f1f77bcf86cd
          endpoint:
            endpoint: http://spg-507f1f77.gateway.com
            type: EXTERNAL
          domain: spg-507f1f77.gateway.com