spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/storedb
    username: postgres
    password: password
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${com.asrevo.cvhome.services.core-gateway.schema}://${com.asrevo.cvhome.services.auth.domain}:${com.asrevo.cvhome.services.core-gateway.port}/realms/cvhome/protocol/openid-connect/certs
  cloud:
    local:
      discovery:
        enabled: true
        services:
          wallet:
            - url: "http://localhost:8087"
              metadata:
                service-name: wallet
                instance: wallet-1
          store:
            - url: "http://localhost:8086"
              metadata:
                service-name: store
                instance: store-1
          store-ui:
            - url: "http://localhost:4300"
              metadata:
                service-name: store-ui
                instance: store-ui-1