import type {Metadata} from "next";
import {Inter} from "next/font/google";
import "../../assets/scss/style.scss";
import {Header} from "@/componants/header/header";
import {Footer} from "@/componants/footer/footer";
import {Store} from "@/types/store";
import {extractStoreContext, StoreContext} from "@/types/store-context";
import {cookies, headers} from "next/headers";
import {StoreService} from "@/services/store-service";

const inter = Inter({subsets: ["latin"]});

export const metadata: Metadata = {
    title: "Explore our best products",
    description: "Generated by create next app",
};

export default async function RootLayout({
                                             children,
                                             params: {locale}

                                         }: Readonly<{
    children: React.ReactNode;
    params: { locale: string };

}>) {
    const storeContext: StoreContext = extractStoreContext(headers(), cookies(), locale);
    const store: Store = await StoreService.getStore(storeContext);
    return (
        <html lang={locale}>
        <body className={inter.className} suppressHydrationWarning={true}>
        <Header storeContext={storeContext} store={store}/>
        {children}
        <Footer store={store}/>
        </body>
        </html>
    );
}
