import type {Metadata} from "next";
import {Inter} from "next/font/google";
import "../../assets/scss/style.scss";
import {Header} from "@/componants/header/header";
import {Footer} from "@/componants/footer/footer";
import {Store} from "@/types/store";

const inter = Inter({subsets: ["latin"]});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default async function RootLayout({
                                             children,
                                             params: {locale}

                                         }: Readonly<{
    children: React.ReactNode;
    params: { locale: string };

}>) {

    const store: Store = await fetch('http://localhost:8080/api/v1/store/DEFAULT')
        .then(it => it.json())
        .then(it => it as Store);

    return (
        <html lang={locale}>
        <body className={inter.className}>
        <Header store={store}/>
        {children}
        <Footer store={store}/>
        </body>
        </html>
    );
}
