#!/usr/bin/env node
/**
 * One route tree per theme: storefront/src/app/(storefront)/t/<id>/[locale]/**. Every file in a tree is a one-line
 * binding of a factory from src/shell/routes to that theme. Next splits CSS and JS per route, so a tree that imports
 * only its own theme ships only that theme; proxy.ts rewrites a store's /<locale>/… to /t/<theme>/<locale>/….
 *
 *   node scripts/theme-routes.mjs               a tree for every theme in src/shell/theme/theme-id.ts
 *   node scripts/theme-routes.mjs fashion …     trees for these themes only
 *   node scripts/theme-routes.mjs --check       the trees on disk are exactly what src/shell/theme/theme-trees.ts
 *                                               lists, file for file; exit 1 (and say what differs) if not
 *
 * The files are committed (review sees them, `next dev` needs no generate step) and `npm test` runs --check.
 * They are created here and nowhere else: a tree adds no screen, it binds the existing ones to one theme.
 */
import {existsSync, mkdirSync, readdirSync, readFileSync, rmSync, statSync, writeFileSync} from 'node:fs';
import path from 'node:path';
import {fileURLToPath} from 'node:url';

const root = path.join(path.dirname(fileURLToPath(import.meta.url)), '..', 'storefront', 'src');
const TREES_DIR = path.join(root, 'app', '(storefront)', 't');
const THEME_ID_FILE = path.join(root, 'shell', 'theme', 'theme-id.ts');
const TREES_FILE = path.join(root, 'shell', 'theme', 'theme-trees.ts');
const SHARED_TREE = path.join(root, 'app', '(storefront)', '[locale]');
const HEADER = '// GENERATED by scripts/theme-routes.mjs — do not edit. The route logic lives in src/shell/routes.\n';

const themed = (factory, module, {metadata = true, args = '', css = false} = {}) => (id) =>
    HEADER +
    // The stylesheet before the theme: Tailwind's entry declares the cascade-layer order (theme, base, components,
    // utilities), and a theme's tokens.css that opened `@layer components` ahead of it would rank components below
    // base, letting preflight override the theme's component classes.
    (css ? `import '@/app/globals.css';\n` : '') +
    `import theme from '@store-front/theme-${id}';\n` +
    `import {${factory}} from '@/shell/routes/${module}';\n\n` +
    (metadata ? `export {generateMetadata} from '@/shell/routes/${module}';\n` : '') +
    `export default ${factory}(async () => theme${args});\n`;
const loading = (kind) => themed('loadingScreen', 'loading', {metadata: false, args: `, '${kind}'`});

/** Every file of the [locale] tree, relative to it, and what it binds. */
const ROUTES = {
    'layout.tsx': themed('storefrontLayout', 'layout', {css: true}),
    'not-found.tsx': themed('notFoundPage', 'not-found', {metadata: false}),
    'error.tsx': () => `'use client'\n\n${HEADER}export {default} from '@/shell/routes/error';\n`,
    '(home)/page.tsx': themed('homePage', 'home', {metadata: false}),
    '(home)/loading.tsx': loading('home'),
    'blog/page.tsx': themed('blogIndexPage', 'blog-index'),
    'blog/[slug]/page.tsx': themed('blogPostPage', 'blog-post'),
    'callback/page.tsx': () => `${HEADER}export {default, metadata} from '@/shell/routes/callback';\n`,
    'category/[url]/page.tsx': themed('categoryPage', 'category'),
    'checkout/page.tsx': themed('checkoutPage', 'checkout'),
    'checkout/loading.tsx': loading('checkout'),
    'checkout/success/page.tsx': themed('checkoutResultPage', 'checkout', {args: ", 'success'"}),
    'checkout/cancel/page.tsx': themed('checkoutResultPage', 'checkout', {args: ", 'cancel'"}),
    'content/[url]/page.tsx': themed('contentPage', 'content'),
    'customer/page.tsx': themed('customerPage', 'customer'),
    'customer/loading.tsx': loading('customer'),
    'customer/order/[id]/page.tsx': themed('orderPage', 'order'),
    'customer/order/[id]/loading.tsx': loading('order'),
    'help/page.tsx': themed('helpPage', 'help'),
    'login/page.tsx': themed('loginPage', 'login'),
    'policies/[type]/page.tsx': themed('policyPage', 'policy'),
    'product/[url]/page.tsx': themed('productPage', 'product'),
    'register/page.tsx': themed('registerPage', 'register'),
    'search/page.tsx': themed('searchPage', 'search'),
    'search/loading.tsx': loading('search'),
};

function registeredIds() {
    const text = readFileSync(THEME_ID_FILE, 'utf8');
    const block = text.slice(text.indexOf('// @themes:start'), text.indexOf('// @themes:end'));
    return [...block.matchAll(/'([a-z0-9-]+)'/g)].map((m) => m[1]);
}

function listedTrees() {
    if (!existsSync(TREES_FILE)) return [];
    const m = readFileSync(TREES_FILE, 'utf8').match(/THEME_TREES[^=]*=\s*\[([^\]]*)\]/);
    return m ? [...m[1].matchAll(/'([a-z0-9-]+)'/g)].map((x) => x[1]) : [];
}

function treesFile(ids) {
    return `${HEADER}import type {RegisteredThemeId} from './theme-id';\n\n` +
        '/** The themes with their own route tree under app/(storefront)/t/<id>/; proxy.ts rewrites their stores there. */\n' +
        `export const THEME_TREES: readonly RegisteredThemeId[] = [${ids.map((id) => `'${id}'`).join(', ')}];\n`;
}

/** Every file the trees for `ids` consist of, as absolute path → content. */
function expected(ids) {
    const files = new Map();
    for (const id of ids) {
        for (const [rel, render] of Object.entries(ROUTES)) {
            files.set(path.join(TREES_DIR, id, '[locale]', rel), render(id));
        }
    }
    files.set(TREES_FILE, treesFile(ids));
    return files;
}

function walk(dir) {
    if (!existsSync(dir)) return [];
    return readdirSync(dir).flatMap((name) => {
        const p = path.join(dir, name);
        return statSync(p).isDirectory() ? walk(p) : [p];
    });
}

const args = process.argv.slice(2);
const registered = registeredIds();

if (args.includes('--check')) {
    const ids = listedTrees();
    const problems = [];
    for (const id of ids) if (!registered.includes(id)) problems.push(`theme-trees.ts lists '${id}', which theme-id.ts does not register`);
    if (!existsSync(SHARED_TREE)) {
        // Without the shared tree a store whose theme has no tree has nowhere to render.
        for (const id of registered) if (!ids.includes(id)) problems.push(`theme '${id}' has no route tree; run npm run theme-routes`);
    }
    const want = expected(ids);
    for (const [file, content] of want) {
        if (!existsSync(file)) problems.push(`missing ${path.relative(root, file)}`);
        else if (readFileSync(file, 'utf8') !== content) problems.push(`stale ${path.relative(root, file)}`);
    }
    for (const file of walk(TREES_DIR)) if (!want.has(file)) problems.push(`not generated ${path.relative(root, file)}`);
    if (problems.length) {
        console.error(`theme-routes: ${problems.length} problem(s)\n  ${problems.join('\n  ')}\nRun: npm run theme-routes`);
        process.exit(1);
    }
    console.log(`theme-routes: ${ids.length} theme tree(s), ${want.size - 1} files, up to date`);
    process.exit(0);
}

const ids = args.length ? args : registered;
for (const id of ids) if (!registered.includes(id)) throw new Error(`unknown theme '${id}' (not in ${path.relative(root, THEME_ID_FILE)})`);
const want = expected(ids);
for (const file of walk(TREES_DIR)) if (!want.has(file)) rmSync(file);
for (const [file, content] of want) {
    mkdirSync(path.dirname(file), {recursive: true});
    writeFileSync(file, content);
}
// Drop directories left empty by a removed theme.
for (const name of existsSync(TREES_DIR) ? readdirSync(TREES_DIR) : []) {
    if (!ids.includes(name)) rmSync(path.join(TREES_DIR, name), {recursive: true, force: true});
}
console.log(`theme-routes: wrote ${want.size - 1} files for ${ids.length} theme(s): ${ids.join(', ')}`);
