#!/usr/bin/env node
/**
 * One route tree per theme: storefront/src/app/(storefront)/t/<id>/[locale]/**. Every file in a tree binds a factory
 * from src/shell/routes to that theme, imported statically. Next splits CSS and JS per route, so a tree that imports
 * only its own theme ships only that theme; proxy.ts rewrites a store's /<locale>/… to /t/<theme>/<locale>/….
 *
 *   npm run theme-routes              a tree for every theme registered in src/shell/theme/theme-id.ts
 *   npm run theme-routes -- --check   the trees on disk are exactly that, file for file; exit 1 (and say what
 *                                     differs) if not
 *
 * The files are committed (review sees them, `next dev` needs no generate step) and `npm test` runs --check.
 * They are created here and nowhere else: a tree adds no screen, it binds the existing ones to one theme.
 * `scripts/new-theme.mjs` runs this after it registers a theme.
 */
import {existsSync, mkdirSync, readdirSync, readFileSync, rmSync, statSync, writeFileSync} from 'node:fs';
import path from 'node:path';
import {fileURLToPath} from 'node:url';

const root = path.join(path.dirname(fileURLToPath(import.meta.url)), '..', 'storefront', 'src');
const TREES_DIR = path.join(root, 'app', '(storefront)', 't');
const THEME_ID_FILE = path.join(root, 'shell', 'theme', 'theme-id.ts');
const HEADER = '// GENERATED by scripts/theme-routes.mjs — do not edit. The route logic lives in src/shell/routes.\n';

const themed = (factory, module, {metadata = true, args = '', css = false} = {}) => (id) =>
    HEADER +
    // The stylesheet before the theme: Tailwind's entry declares the cascade-layer order (theme, base, components,
    // utilities), and a theme's tokens.css that opened `@layer components` ahead of it would rank components below
    // base, letting preflight override the theme's component classes.
    (css ? `import '@/app/globals.css';\n` : '') +
    `import theme from '@store-front/theme-${id}';\n` +
    `import {${factory}} from '@/shell/routes/${module}';\n\n` +
    (metadata ? `export {generateMetadata} from '@/shell/routes/${module}';\n` : '') +
    `export default ${factory}(theme${args});\n`;
const loading = (kind) => themed('loadingScreen', 'loading', {metadata: false, args: `, '${kind}'`});

/** Every file of the [locale] tree, relative to it, and what it binds. */
const ROUTES = {
    'layout.tsx': themed('storefrontLayout', 'layout', {css: true}),
    'not-found.tsx': themed('notFoundPage', 'not-found', {metadata: false}),
    'error.tsx': () => `'use client'\n\n${HEADER}export {default} from '@/shell/routes/error';\n`,
    '(home)/page.tsx': themed('homePage', 'home', {metadata: false}),
    '(home)/loading.tsx': loading('home'),
    'blog/page.tsx': themed('blogIndexPage', 'blog-index'),
    'blog/[slug]/page.tsx': themed('blogPostPage', 'blog-post'),
    'callback/page.tsx': () => `${HEADER}export {default, metadata} from '@/shell/routes/callback';\n`,
    'category/[url]/page.tsx': themed('categoryPage', 'category'),
    'checkout/page.tsx': themed('checkoutPage', 'checkout'),
    'checkout/loading.tsx': loading('checkout'),
    'checkout/success/page.tsx': themed('checkoutResultPage', 'checkout', {args: ", 'success'"}),
    'checkout/cancel/page.tsx': themed('checkoutResultPage', 'checkout', {args: ", 'cancel'"}),
    'content/[url]/page.tsx': themed('contentPage', 'content'),
    'customer/page.tsx': themed('customerPage', 'customer'),
    'customer/loading.tsx': loading('customer'),
    'customer/order/[id]/page.tsx': themed('orderPage', 'order'),
    'customer/order/[id]/loading.tsx': loading('order'),
    'help/page.tsx': themed('helpPage', 'help'),
    'login/page.tsx': themed('loginPage', 'login'),
    'policies/[type]/page.tsx': themed('policyPage', 'policy'),
    'product/[url]/page.tsx': themed('productPage', 'product'),
    'register/page.tsx': themed('registerPage', 'register'),
    'search/page.tsx': themed('searchPage', 'search'),
    'search/loading.tsx': loading('search'),
};

function registeredIds() {
    const text = readFileSync(THEME_ID_FILE, 'utf8');
    const block = text.slice(text.indexOf('// @themes:start'), text.indexOf('// @themes:end'));
    return [...block.matchAll(/'([a-z0-9-]+)'/g)].map((m) => m[1]);
}

/** Every file the trees for `ids` consist of, as absolute path → content. */
function expected(ids) {
    const files = new Map();
    for (const id of ids) {
        for (const [rel, render] of Object.entries(ROUTES)) {
            files.set(path.join(TREES_DIR, id, '[locale]', rel), render(id));
        }
    }
    return files;
}

function walk(dir) {
    if (!existsSync(dir)) return [];
    return readdirSync(dir).flatMap((name) => {
        const p = path.join(dir, name);
        return statSync(p).isDirectory() ? walk(p) : [p];
    });
}

const ids = registeredIds();
const want = expected(ids);

if (process.argv.includes('--check')) {
    const problems = [];
    for (const [file, content] of want) {
        if (!existsSync(file)) problems.push(`missing ${path.relative(root, file)}`);
        else if (readFileSync(file, 'utf8') !== content) problems.push(`stale ${path.relative(root, file)}`);
    }
    for (const file of walk(TREES_DIR)) if (!want.has(file)) problems.push(`not generated ${path.relative(root, file)}`);
    if (problems.length) {
        console.error(`theme-routes: ${problems.length} problem(s)\n  ${problems.join('\n  ')}\nRun: npm run theme-routes`);
        process.exit(1);
    }
    console.log(`theme-routes: ${ids.length} theme trees, ${want.size} files, up to date`);
    process.exit(0);
}

for (const file of walk(TREES_DIR)) if (!want.has(file)) rmSync(file);
for (const [file, content] of want) {
    mkdirSync(path.dirname(file), {recursive: true});
    writeFileSync(file, content);
}
// Drop the directories of a theme that is no longer registered.
for (const name of existsSync(TREES_DIR) ? readdirSync(TREES_DIR) : []) {
    if (!ids.includes(name)) rmSync(path.join(TREES_DIR, name), {recursive: true, force: true});
}
console.log(`theme-routes: wrote ${want.size} files for ${ids.length} themes`);
