spring:
  application:
    name: user
  docker:
    compose:
      file: ${spring.application.name}/compose.yml
  sql:
    init:
      mode: never
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/userdb
    username: postgres
    password: password
server:
  port: 8081
info:
  app:
    name: ${spring.application.name}
management:
  info:
    env:
      enabled: true
    os:
      enabled: true
  metrics:
    tags:
      application: ${spring.application.name}
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: [ '*' ]