spring:
  application:
    name: user
  docker:
    compose:
      file: ${spring.application.name}/compose.yml
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/userdb
    username: postgres
    password: password
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:9999/realms/cvhome/protocol/openid-connect/certs
server:
  forward-headers-strategy: FRAMEWORK
  port: 8081
info:
  app:
    name: ${spring.application.name}
management:
  info:
    env:
      enabled: true
    os:
      enabled: true
  metrics:
    tags:
      application: ${spring.application.name}
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: [ '*' ]
logging:
  level:
    org.springframework.boot: debug
    org.springframework.web: debug
    org.springframework.security: debug