spring:
  application:
    name: router
  datasource:
    driver-class-name: org.postgresql.Driver
    hikari:
      schema: router
server:
  forward-headers-strategy: FRAMEWORK
  port: ${com.asrevo.cvhome.services.router.port}
info:
  app:
    name: ${spring.application.name}
  observations:
    key-values:
      application: ${spring.application.name}