version: '3'
services:
  postgres:
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: cvhome
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
  spg:
    image: ashraf1abdelrasool/saas-gateway:sha-4a6d381
    ports:
      - "80:80"
      - "443:443"
      - "2019:2019"
    volumes:
      - ./store-pod/spg/Caddyfile:/etc/caddy/Caddyfile
    extra_hosts:
      - "host.docker.internal:host-gateway"
      - "merchant.gateway.com:host-gateway"
      - "catalog.gateway.com:host-gateway"
      - "checkout.gateway.com:host-gateway"
      - "cua.gateway.com:host-gateway"
      - "payment.gateway.com:host-gateway"
      - "landing-ui.gateway.com:host-gateway"
      - "spg-507f1f77.gateway.com:host-gateway"
    environment:
      NAMESPACE: gateway.com
      ASK_TLS_URL: http://spg-507f1f77.gateway.com:80/merchant/api/v1/router/public/ask-for-tls
      DOMAIN_LOOKUP_URL: http://spg-507f1f77.gateway.com:80/merchant/api/v1/router/public/lookup-by-domain
      CERT_BUCKET: random-bucket
      CERT_BUCKET_REGION: eu-central-1
      OTEL_EXPORTER_OTLP_ENDPOINT: http://host.docker.internal:4317
      OTEL_EXPORTER_OTLP_PROTOCOL: grpc
      OTEL_SERVICE_NAME: spg
  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.150.1
    command: [ "--config=/etc/logging-otel-collector-config.yml" ]
    volumes:
      - ./extra/monitoring/logging-otel-collector-config.yml:/etc/logging-otel-collector-config.yml
    ports:
      - "4317:4317"
      - "4318:4318"
      - "8889:8889"
      - "13133:13133"
    depends_on:
      - loki
      - tempo
    extra_hosts:
      - "host.docker.internal:host-gateway"
  loki:
    image: grafana/loki:3.6.10
    command: [ "-config.file=/etc/loki/loki.yml" ]
    volumes:
      - ./extra/monitoring/loki.yml:/etc/loki/loki.yml
    ports:
      - "3100:3100"
  tempo:
    image: grafana/tempo:2.10.5
    command: [ "-config.file=/etc/tempo/tempo.yml" ]
    volumes:
      - ./extra/monitoring/tempo.yml:/etc/tempo/tempo.yml
    ports:
      - "3200:3200"
  prometheus:
    image: prom/prometheus:v3.11.2
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--web.enable-remote-write-receiver"
    volumes:
      - ./extra/monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
  grafana:
    image: grafana/grafana:12.4
    environment:
      GF_AUTH_ANONYMOUS_ENABLED: "true"
      GF_AUTH_ANONYMOUS_ORG_ROLE: Admin
    volumes:
      - ./extra/monitoring/grafana-datasources.yml:/etc/grafana/provisioning/datasources/datasources.yml
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
      - loki
      - tempo
