plugins {
	alias(libs.plugins.java.library.conventions)
	alias(libs.plugins.spotless)
}

dependencies {
	api project(':store-commons:commons')
	compileOnly libs.jakarta.persistence.api
	compileOnly libs.jakarta.validation.api
	compileOnly libs.jackson.databind
	compileOnly libs.jackson.annotations
	compileOnly libs.spring.data.jpa
	compileOnly libs.apache.commons.lang3
	compileOnly libs.lombok
	implementation libs.commons.validator
	annotationProcessor libs.lombok
}
