import type {Metadata} from "next";
import {Inter} from "next/font/google";
import "./../assets/scss/style.scss";
import {Footer} from "@/componants/footer/footer";
import {Header} from "@/componants/header/header";
import {NextFont} from "next/dist/compiled/@next/font";

const inter: NextFont = Inter({subsets: ["latin"]});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
        <body className={inter.className}>
        <Header/>
        {children}
        <Footer/>
        </body>
        </html>
    );
}
