plugins {
    alias(libs.plugins.java.library.conventions)
}

dependencies {
    api project(':store-pod:commons:store-commons')
    api project(':store-pod:inventory:inventory-commons')
    api project(':store-pod:checkout:checkout-external-api')
    compileOnly libs.spring.data.jpa
    compileOnly libs.hibernate.core
    compileOnly libs.lombok
    annotationProcessor libs.lombok
}
