spring:
  config:
    import: "classpath:common-config.yml"
---
spring:
  application:
    name: manager
  security:
    oauth2:
      client:
        registration:
          s2s:
            provider: keycloak
            client-id: manager@service.store-core.internal
            client-secret: VobDxIhAGZz8hyhzz7p9G7QpfixjFjzW
            authorization-grant-type: client_credentials
  datasource:
    driver-class-name: org.postgresql.Driver
    hikari:
      schema: ${spring.application.name}
  cloud:
    function:
      definition: events
    stream:
      input-bindings: events
      bindings:
        events-in-0:
          destination: events
          group: ${spring.application.name}
        events-out-0:
          content-type: application/json
          destination: events
server:
  forward-headers-strategy: NATIVE
  port: ${com.asrevo.cvhome.services.manager.port}
info:
  app:
    name: ${spring.application.name}
management:
  observations:
    key-values:
      application: ${spring.application.name}
com:
  asrevo:
    cvhome:
      kc:
        credentials:
          server-url: ${com.asrevo.cvhome.services.core-auth.schema}://${com.asrevo.cvhome.services.core-auth.domain}:${com.asrevo.cvhome.services.core-auth.port}
          realm: cvhome
          client-id: internal-client
          client-secret: aKl0AKjjQ6zp2bnWhKOsnTOzl3J8Vqd0