spring:
  datasource:
    url: jdbc:postgresql://${spring.datasource.host}:${spring.datasource.port}/${spring.datasource.database}
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  cloud:
    loadbalancer:
      eager-load:
        clients:
          - "store-core-gateway"
          - "manager"
          - "wallet"
          - "store-ui"
    ecs:
      discovery:
        namespace: "store-core.cvhome.lcl"
        namespace-id: "ns-aacm3spcnftheq3b"
        enabled: true
        default-port: 8080
        service-ports:
          "store-core-gateway": 7000
          "manager": 7001
          "wallet": 7002
          "store-ui": 4300
