spring:
  datasource:
    url: jdbc:postgresql://${spring.datasource.host}:${spring.datasource.port}/${spring.datasource.database}
  cloud:
    loadbalancer:
      eager-load:
        clients:
          - "store-core-gateway"
          - "auth"
          - "manager"
          - "store-ui"
          - "welcome-ui"
    ecs:
      discovery:
        namespace: "store-core.cvhome.lcl"
        namespace-id: "ns-aacm3spcnftheq3b"
        enabled: true
        default-port: 8080
        service-ports:
          "store-core-gateway": 7000
          "auth": 9999
          "manager": 7001
          "store": 7101
          "store-ui": 4200
          "welcome-ui": 4200
