plugins {
	alias(libs.plugins.java.library.conventions)
	alias(libs.plugins.spring.javaformat)
}

dependencies {
	api libs.mongodb.bson
	compileOnly libs.jackson.databind
	compileOnly libs.spring.data.commons
	compileOnly libs.spring.cloud.stream
	compileOnly libs.lombok
	annotationProcessor libs.lombok
}
