version: "3.1"
services:
  postgres:
    image: "postgres:13"
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
#  rabbitmq:
#    image: "rabbitmq:3.12-management"
#    restart: always
#    ports:
#      - "15672:15672"
#      - "5672:5672"
  keycloak:
    image: quay.io/keycloak/keycloak:21.0
    environment:
      KC_HTTP_ENABLED: true
      KC_HOSTNAME_STRICT_HTTPS: false

      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres:5432/kc
      KC_DB_USERNAME: postgres
      KC_DB_PASSWORD: password

      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin

    command:  --verbose start --proxy=edge  --hostname-strict=false --import-realm
    #    command:  --verbose start --proxy=edge --hostname-strict=false --hostname-path=/auth --import-realm
    #    command:  --verbose start  --hostname-strict=false --import-realm
    volumes:
      - ../auth/keycloak/imports:/opt/keycloak/data/import
    ports:
      - "9999:8080"
    depends_on:
      - postgres
