version: "3.1"
services:
  collector:
    image: otel/opentelemetry-collector-contrib:0.80.0
    volumes:
      - ./logging-otel-collector-config.yml:/otel-config.yml
    command: [ "--config=/otel-config.yml" ]
    ports:
      - "4317:4317"
      - "4318:4318"