version: '3'
services:
  postgres:
    image: postgres:13
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: kc
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
  keycloak:
    image: quay.io/keycloak/keycloak:25.0.0
    environment:
      KC_HTTP_ENABLED: true
      KC_HOSTNAME_STRICT_HTTPS: false

      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres:5432/kc
      KC_DB_USERNAME: postgres
      KC_DB_PASSWORD: password

      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin

      KK_TO_RMQ_URL: rabbitmq
      KK_TO_RMQ_USERNAME: guest
      KK_TO_RMQ_PASSWORD: guest
      KK_TO_RMQ_VHOST: "/"
      KK_TO_RMQ_EXCHANGE: "com.asrevo.cvhome.sys-events"

    command: --verbose start --proxy=edge  --hostname-strict=false --import-realm
    #    command:  --verbose start --proxy=edge --hostname-strict=false --hostname-path=/auth --import-realm
    #    command:  --verbose start  --hostname-strict=false --import-realm
    volumes:
      - ./keycloak/imports:/opt/keycloak/data/import
      - ./keycloak/providers:/opt/keycloak/providers
    ports:
      - "9999:8080"
    depends_on:
      - postgres