### API for creating a manufacturer / Brand
POST http://localhost:8120/api/v1/private/manufacturer
Content-Type: application/json
Authorization: Bearer {{access_token}}

{
  "code": "s3imbeats1",
  "order": 2,
  "descriptions": [
    {
      "language": "en",
      "name": "SimBeats1"
    },
    {
      "language": "fr",
      "name": "SimBeats1"
    }
  ]
}



### Creates a category
POST http://localhost:8120/api/v1/private/category
Content-Type: application/json
Authorization: Bearer {{access_token}}

{
  "code": "headsets",
  "sortOrder": 0,
  "visible": true,
  "parent": null,
  "descriptions": [
    {
      "language": "en",
      "name": "Headsets",
      "friendlyUrl": "headsets",
      "title": "Headsets"
    },
    {
      "language": "fr",
      "name": "Écouteurs",
      "friendlyUrl": "ecouteurs",
      "title": "Écouteurs"
    }
  ]
}


### Create Product Definition SIMBEATS
POST http://localhost:8120/api/v2/private/product?lang=en
Content-Type: application/json
Authorization: Bearer {{access_token}}


{
  "canBePurchased": true,
  "price": 149.00,
  "quantity": 1000,
  "descriptions": [
    {
      "description": "The preferred choice of a vast range of acclaimed DJs. Punchy, bass-focused sound and high isolation. Sturdy headband and on-ear cushions suitable for live performance",
      "friendlyUrl": "simbeatsep",
      "name": "SIMBeats EP",
      "title": "SIMBeats EP",
      "language": "en"
    },
    {
      "description": "Le choix préféré des audiophiles, fréquences des basses améliorées et isolation incomparable pour les meilleures performances audio",
      "friendlyUrl": "simbeatsep",
      "name": "SIMBeats EP",
      "title": "SIMBeats EP",
      "language": "fr"
    }
  ],
  "identifier": "SIMBEATSEP",
  "productSpecifications": {
    "dimensionUnitOfMeasure": "in",
    "height": 8,
    "length": 4,
    "weight": 0.225,
    "weightUnitOfMeasure": "lb",
    "manufacturer": "s3imbeats1",
    "width": 12
  },
  "categories": [
    {
      "code": "headsets"
    }
  ],
  "shipeable": true,
  "sortOrder": 1,
  "type": "GENERAL",
  "virtual": false,
  "visible": true
}



