// GENERATED by scripts/theme-routes.mjs — do not edit. The route logic lives in src/shell/routes.
import theme from '@store-front/theme-jewellery';
import {registerPage} from '@/shell/routes/register';

export {generateMetadata} from '@/shell/routes/register';
export default registerPage(theme);
