plugins {
    id 'com.asrevo.java-application-conventions'
    id 'org.springframework.boot' version '3.1.4'
    id 'io.spring.dependency-management' version '1.1.3'
//    id 'org.graalvm.buildtools.native' version '0.9.24'
}
group = 'com.asrevo.cvhome'

java {
    sourceCompatibility = '17'
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
}

repositories {
    mavenLocal()
    mavenCentral()
    maven { url 'https://repo.spring.io/milestone' }
}

springBoot {
    buildInfo()
}

/*bootBuildImage {
    builder = "paketobuildpacks/builder:tiny"
    imageName = "ghcr.io/ashraf-revo/store"
    tags = ["ghcr.io/ashraf-revo/store:${project.version}", "ghcr.io/ashraf-revo/store:latest"]
    docker {
        publishRegistry {
            url = "https://ghcr.io"
            username = "ashraf-revo"
            password = System.getenv("GHCR_TOKEN")
        }
    }
}*/
bootBuildImage {
    builder = "paketobuildpacks/builder:tiny"
    imageName = "117535662239.dkr.ecr.eu-central-1.amazonaws.com/store"
    tags = ["117535662239.dkr.ecr.eu-central-1.amazonaws.com/store:${project.version}", "117535662239.dkr.ecr.eu-central-1.amazonaws.com/store:latest"]
}

ext {
    set('springCloudVersion', "2022.0.4")
}
dependencies {
    implementation 'org.springframework.cloud:spring-cloud-starter-loadbalancer'
    implementation 'org.springframework.boot:spring-boot-starter-webflux'
    implementation 'org.springframework.boot:spring-boot-starter-validation'
    implementation 'org.springframework.boot:spring-boot-starter-actuator'

    implementation 'org.springframework.boot:spring-boot-starter-security'
    implementation 'org.springframework.boot:spring-boot-starter-oauth2-resource-server'
    implementation 'org.springframework.boot:spring-boot-starter-data-jdbc'
    runtimeOnly 'org.postgresql:postgresql'

    implementation 'org.mapstruct:mapstruct:1.5.5.Final'
    annotationProcessor 'org.mapstruct:mapstruct-processor:1.5.5.Final'
    implementation 'org.springdoc:springdoc-openapi-starter-webflux-ui:2.2.0'

    implementation project(':store:store-events')

//    developmentOnly 'org.springframework.boot:spring-boot-docker-compose'
    compileOnly 'org.projectlombok:lombok'
    annotationProcessor 'org.projectlombok:lombok'
    annotationProcessor 'org.projectlombok:lombok-mapstruct-binding:0.2.0'
    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    implementation 'org.springframework.boot:spring-boot-starter-security'
    testImplementation 'org.springframework.security:spring-security-test'
    testImplementation 'org.springframework.boot:spring-boot-testcontainers'
    testImplementation 'io.projectreactor:reactor-test'
    testImplementation 'org.testcontainers:junit-jupiter'
    testImplementation 'org.testcontainers:postgresql'
}

dependencyManagement {
    imports {
        mavenBom "org.springframework.cloud:spring-cloud-dependencies:${springCloudVersion}"
    }
}
