plugins {
	alias(libs.plugins.java.library.conventions)
	alias(libs.plugins.spotless)
}

dependencies {
	api project(':store-commons:commons')
	compileOnly libs.jackson.databind
	compileOnly libs.jackson.annotations
	compileOnly libs.spring.data.relational
	compileOnly libs.lombok
	implementation libs.dnsjava
	annotationProcessor libs.lombok
}
