plugins {
	id 'com.asrevo.java-library-conventions'
	id("com.diffplug.spotless") version "6.25.0"
}

dependencies {
	api project(':store-pod:store-commons')
	api project(':store-pod:reference:reference-commons')
	compileOnly 'org.springframework.data:spring-data-jpa:3.5.0'
	compileOnly 'jakarta.validation:jakarta.validation-api:3.0.2'
	compileOnly 'org.projectlombok:lombok:1.18.38'
	compileOnly 'org.hibernate.orm:hibernate-core:6.6.15.Final'
	annotationProcessor 'org.projectlombok:lombok:1.18.38'
}
