// GENERATED by scripts/theme-routes.mjs — do not edit. The route logic lives in src/shell/routes.
import theme from '@store-front/theme-glasses';
import {homePage} from '@/shell/routes/home';

export default homePage(theme);
