plugins {
    id 'com.asrevo.java-application-conventions'
    id 'org.springframework.boot' version '3.5.0'
    id 'io.spring.dependency-management' version '1.1.7'
//    id 'org.hibernate.orm' version '6.6.15.Final'
//    id 'org.graalvm.buildtools.native' version '0.10.5'
}
apply from: "$rootDir/build-logic/helpers/common-methods.gradle"
group = 'com.asrevo.cvhome'


springBoot {
    buildInfo()
}

bootBuildImage {
/*
    builder = "bellsoft/buildpacks.builder:musl"
*/
    environment["BP_JVM_JLINK_ENABLED"] = "true"
    environment["BP_JVM_JLINK_ARGS"] = " --compress zip-6 --no-header-files --no-man-pages --vm client --add-modules java.base,java.se,jdk.unsupported,jdk.crypto.ec"
    imageName = createImageName("store-pod/order", project.version)
    tags = createImageTags("store-pod/order", project.version)
    docker {
        publishRegistry {
            url = System.getenv("REGISTRY")
            username = System.getenv("ECR_TOKEN") ? 'AWS' : null
            password = System.getenv("ECR_TOKEN")
        }
    }
}

ext {
    set('springCloudVersion', "2025.0.0")
}
dependencies {
    implementation 'org.springframework.cloud:spring-cloud-starter-loadbalancer'
    implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation 'org.springframework.boot:spring-boot-starter-validation'
    implementation 'org.springframework.boot:spring-boot-starter-actuator'

    implementation 'org.springframework.boot:spring-boot-starter-security'
    implementation 'org.springframework.boot:spring-boot-starter-oauth2-client'
    implementation 'org.springframework.boot:spring-boot-starter-oauth2-resource-server'
    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
    runtimeOnly 'org.postgresql:postgresql'

    implementation 'software.amazon.awssdk:s3:2.29.43'

    implementation 'commons-validator:commons-validator:1.9.0'
    implementation 'commons-io:commons-io:2.16.1'

    implementation project(':store-pod:reference:reference-core')
    implementation project(':store-pod:order:order-core')
    implementation project(':store-pod:merchant:merchant-external-api')
    implementation project(':store-pod:catalog:catalog-external-api')
    implementation project(':store-commons:ecs-commons:fargate-task-info')
    implementation project(':store-commons:ecs-commons:ecs-service-discoveryclient')

    implementation 'org.mapstruct:mapstruct:1.6.3'
    annotationProcessor 'org.mapstruct:mapstruct-processor:1.6.3'
    implementation 'org.springdoc:springdoc-openapi-starter-webmvc-ui:2.8.8'

    implementation project(':store-commons:autoconfigure')

//    developmentOnly 'org.springframework.boot:spring-boot-docker-compose'
    compileOnly 'org.projectlombok:lombok'
    annotationProcessor 'org.projectlombok:lombok'
    annotationProcessor 'org.projectlombok:lombok-mapstruct-binding:0.2.0'
    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    implementation 'org.springframework.boot:spring-boot-starter-security'
    testImplementation 'org.springframework.security:spring-security-test'
    testImplementation 'org.springframework.boot:spring-boot-testcontainers'
    testImplementation 'org.testcontainers:junit-jupiter'
    testImplementation 'org.testcontainers:postgresql'
    testImplementation 'rocks.cleancode:hamcrest-record:1.0.0'
}

dependencyManagement {
    imports {
        mavenBom "org.springframework.cloud:spring-cloud-dependencies:${springCloudVersion}"
    }
}

//tasks.withType(org.springframework.boot.gradle.tasks.aot.ProcessAot).configureEach {
//    args('--spring.profiles.active=lcl')
//}
//
//hibernate {
//    enhancement {
//        enableAssociationManagement = true
//    }
//}
