### get token from test application
POST http://localhost:8120/api/v1/test/sign
Content-Type: application/json

{
  "iat": 1711619569,
  "auth_time": 1711618828,
  "jti": "52596bdf-9b1a-478b-8116-0bc4571399cc",
  "iss": "http://auth.gateway.com:9999/realms/cvhome",
  "aud": "account",
  "sub": "3dea29fd-f6b2-48b1-8231-f4b5f1c68714",
  "typ": "Bearer",
  "azp": "web-app",
  "nonce": "CFetJG7x-JJ26dNX6DbX-aRtxmIR0fJUkK90EY0ia40",
  "session_state": "210caafe-2333-4f9e-8fa1-837f02d1affd",
  "acr": "0",
  "allowed-origins": [
    "https://gateway.com:8443"
  ],
  "realm_access": {
    "roles": [
      "ROLE_USER",
      "ROLE_STORE_ADMIN",
      "offline_access",
      "uma_authorization",
      "default-roles-cvhome"
    ]
  },
  "resource_access": {
    "account": {
      "roles": [
        "manage-account",
        "manage-account-links",
        "view-profile"
      ]
    }
  },
  "scope": "openid profile org email",
  "sid": "210caafe-2333-4f9e-8fa1-837f02d1affd",
  "email_verified": false,
  "org": "d1952c95-312e-4bb9-9a2d-b703d031276f",
  "preferred_username": "revo",
  "store": "65f023632bc46470c104b76f"
}

> {%
    client.global.set("access_token", response.body.access_token)
%}



### get token
POST http://auth.gateway.com:9999/realms/cvhome/protocol/openid-connect/token
Content-Type: application/x-www-form-urlencoded

client_id = microservice-app &
client_secret = r1nuVn4HefusLGwHIeRxbdOzdTZLEMvQ &
grant_type = password &
username = microservice-gateway
    &
password = microservice-gateway

> {%
    client.global.set("access_token", response.body.access_token)
%}




### API for creating a manufacturer / Brand
POST http://localhost:8120/api/v1/private/manufacturer
Content-Type: application/json
Authorization: Bearer {{access_token}}

{
  "code": "s3imbeats1",
  "order": 2,
  "descriptions": [
    {
      "language": "en",
      "name": "SimBeats1"
    },
    {
      "language": "fr",
      "name": "SimBeats1"
    }
  ]
}



### Creates a category
POST http://localhost:8120/api/v1/private/category
Content-Type: application/json
Authorization: Bearer {{access_token}}

{
  "code": "headsets",
  "sortOrder": 0,
  "visible": true,
  "parent": null,
  "descriptions": [
    {
      "language": "en",
      "name": "Headsets",
      "friendlyUrl": "headsets",
      "title": "Headsets"
    },
    {
      "language": "fr",
      "name": "Écouteurs",
      "friendlyUrl": "ecouteurs",
      "title": "Écouteurs"
    }
  ]
}


### Create Product Definition SIMBEATS
POST http://localhost:8120/api/v2/private/product?lang=en
Content-Type: application/json
Authorization: Bearer {{access_token}}


{
  "canBePurchased": true,
  "price": 149.00,
  "quantity": 1000,
  "descriptions": [
    {
      "description": "The preferred choice of a vast range of acclaimed DJs. Punchy, bass-focused sound and high isolation. Sturdy headband and on-ear cushions suitable for live performance",
      "friendlyUrl": "simbeatsep",
      "name": "SIMBeats EP",
      "title": "SIMBeats EP",
      "language": "en"
    },
    {
      "description": "Le choix préféré des audiophiles, fréquences des basses améliorées et isolation incomparable pour les meilleures performances audio",
      "friendlyUrl": "simbeatsep",
      "name": "SIMBeats EP",
      "title": "SIMBeats EP",
      "language": "fr"
    }
  ],
  "identifier": "SIMBEATSEP",
  "productSpecifications": {
    "dimensionUnitOfMeasure": "in",
    "height": 8,
    "length": 4,
    "weight": 0.225,
    "weightUnitOfMeasure": "lb",
    "manufacturer": "s3imbeats1",
    "width": 12
  },
  "categories": [
    {
      "code": "headsets"
    }
  ],
  "shipeable": true,
  "sortOrder": 1,
  "type": "GENERAL",
  "virtual": false,
  "visible": true
}



