-- Stock and price for the fashion store's combination variants.
--
-- One row per combination sku beyond the default variant, whose row the base seed already
-- carries. Prices differ per combination so a matrix shows real per-variant pricing, and a
-- few combinations are deliberately out of stock — that is the greyed-chip case on the PDP.

INSERT INTO inventory.product_availability (product_avail_id, store_merchant_id, product_id, sku, quantity, available, quantity_ord_min, quantity_ord_max)
VALUES (501, '65f023632bc46470c104b76f', 1, 'SKU-NK-RUN-001-L', 12, true, 1, 0)
on conflict (product_avail_id) do nothing;
INSERT INTO inventory.product_price (product_price_id, store_merchant_id, product_avail_id, product_price_code, default_price, product_price_amount)
VALUES (501, '65f023632bc46470c104b76f', 501, 'base', true, 780.00)
on conflict (product_price_id) do nothing;

INSERT INTO inventory.product_availability (product_avail_id, store_merchant_id, product_id, sku, quantity, available, quantity_ord_min, quantity_ord_max)
VALUES (502, '65f023632bc46470c104b76f', 2, 'SKU-ZR-CL-DRS02-BL-M', 8, true, 1, 0)
on conflict (product_avail_id) do nothing;
INSERT INTO inventory.product_price (product_price_id, store_merchant_id, product_avail_id, product_price_code, default_price, product_price_amount)
VALUES (502, '65f023632bc46470c104b76f', 502, 'base', true, 365.00)
on conflict (product_price_id) do nothing;

INSERT INTO inventory.product_availability (product_avail_id, store_merchant_id, product_id, sku, quantity, available, quantity_ord_min, quantity_ord_max)
VALUES (503, '65f023632bc46470c104b76f', 2, 'SKU-ZR-CL-DRS02-BL-L', 0, true, 1, 0)
on conflict (product_avail_id) do nothing;
INSERT INTO inventory.product_price (product_price_id, store_merchant_id, product_avail_id, product_price_code, default_price, product_price_amount)
VALUES (503, '65f023632bc46470c104b76f', 503, 'base', true, 380.00)
on conflict (product_price_id) do nothing;

-- ---------------------------------------------------------------------------------------------------------
-- Generated bulk: stock and price for the combination skus of 18-catalog-options-variants.sql.
--
-- One row per combination beyond the default variant, whose row the base seed already carries. Prices step
-- up with the combination so a matrix shows real per-variant pricing, and the quantity cycle leaves a few
-- combinations at zero — the greyed-chip case on the PDP.
--
-- Regenerated by extra/scripts/generate-demo-variants.py; edit that rather than these lines.
-- ---------------------------------------------------------------------------------------------------------

INSERT INTO inventory.product_availability (product_avail_id, store_merchant_id, product_id, sku, quantity, available, quantity_ord_min, quantity_ord_max)
VALUES (1001, '65f023632bc46470c104b76f', 5, 'SKU-GU-BG-MAR05-BLUE', 3, true, 1, 0)
on conflict (product_avail_id) do nothing;
INSERT INTO inventory.product_price (product_price_id, store_merchant_id, product_avail_id, product_price_code, default_price, product_price_amount)
VALUES (1001, '65f023632bc46470c104b76f', 1001, 'base', true, 8925.00)
on conflict (product_price_id) do nothing;

INSERT INTO inventory.product_availability (product_avail_id, store_merchant_id, product_id, sku, quantity, available, quantity_ord_min, quantity_ord_max)
VALUES (1002, '65f023632bc46470c104b76f', 6, 'SKU-CH-AC-SUN06-BLUE', 22, true, 1, 0)
on conflict (product_avail_id) do nothing;
INSERT INTO inventory.product_price (product_price_id, store_merchant_id, product_avail_id, product_price_code, default_price, product_price_amount)
VALUES (1002, '65f023632bc46470c104b76f', 1002, 'base', true, 2205.00)
on conflict (product_price_id) do nothing;

INSERT INTO inventory.product_availability (product_avail_id, store_merchant_id, product_id, sku, quantity, available, quantity_ord_min, quantity_ord_max)
VALUES (1003, '65f023632bc46470c104b76f', 6, 'SKU-CH-AC-SUN06-BLACK', 5, true, 1, 0)
on conflict (product_avail_id) do nothing;
INSERT INTO inventory.product_price (product_price_id, store_merchant_id, product_avail_id, product_price_code, default_price, product_price_amount)
VALUES (1003, '65f023632bc46470c104b76f', 1003, 'base', true, 2310.00)
on conflict (product_price_id) do nothing;

INSERT INTO inventory.product_availability (product_avail_id, store_merchant_id, product_id, sku, quantity, available, quantity_ord_min, quantity_ord_max)
VALUES (1004, '65f023632bc46470c104b76f', 7, 'SKU-NK-CL-KHD07-M', 5, true, 1, 0)
on conflict (product_avail_id) do nothing;
INSERT INTO inventory.product_price (product_price_id, store_merchant_id, product_avail_id, product_price_code, default_price, product_price_amount)
VALUES (1004, '65f023632bc46470c104b76f', 1004, 'base', true, 315.00)
on conflict (product_price_id) do nothing;

INSERT INTO inventory.product_availability (product_avail_id, store_merchant_id, product_id, sku, quantity, available, quantity_ord_min, quantity_ord_max)
VALUES (1005, '65f023632bc46470c104b76f', 7, 'SKU-NK-CL-KHD07-L', 18, true, 1, 0)
on conflict (product_avail_id) do nothing;
INSERT INTO inventory.product_price (product_price_id, store_merchant_id, product_avail_id, product_price_code, default_price, product_price_amount)
VALUES (1005, '65f023632bc46470c104b76f', 1005, 'base', true, 330.00)
on conflict (product_price_id) do nothing;

INSERT INTO inventory.product_availability (product_avail_id, store_merchant_id, product_id, sku, quantity, available, quantity_ord_min, quantity_ord_max)
VALUES (1006, '65f023632bc46470c104b76f', 8, 'SKU-ZR-SH-SNK08-RED-M', 18, true, 1, 0)
on conflict (product_avail_id) do nothing;
INSERT INTO inventory.product_price (product_price_id, store_merchant_id, product_avail_id, product_price_code, default_price, product_price_amount)
VALUES (1006, '65f023632bc46470c104b76f', 1006, 'base', true, 441.00)
on conflict (product_price_id) do nothing;

INSERT INTO inventory.product_availability (product_avail_id, store_merchant_id, product_id, sku, quantity, available, quantity_ord_min, quantity_ord_max)
VALUES (1007, '65f023632bc46470c104b76f', 8, 'SKU-ZR-SH-SNK08-BLUE-S', 14, true, 1, 0)
on conflict (product_avail_id) do nothing;
INSERT INTO inventory.product_price (product_price_id, store_merchant_id, product_avail_id, product_price_code, default_price, product_price_amount)
VALUES (1007, '65f023632bc46470c104b76f', 1007, 'base', true, 462.00)
on conflict (product_price_id) do nothing;

INSERT INTO inventory.product_availability (product_avail_id, store_merchant_id, product_id, sku, quantity, available, quantity_ord_min, quantity_ord_max)
VALUES (1008, '65f023632bc46470c104b76f', 8, 'SKU-ZR-SH-SNK08-BLUE-M', 9, true, 1, 0)
on conflict (product_avail_id) do nothing;
INSERT INTO inventory.product_price (product_price_id, store_merchant_id, product_avail_id, product_price_code, default_price, product_price_amount)
VALUES (1008, '65f023632bc46470c104b76f', 1008, 'base', true, 483.00)
on conflict (product_price_id) do nothing;

INSERT INTO inventory.product_availability (product_avail_id, store_merchant_id, product_id, sku, quantity, available, quantity_ord_min, quantity_ord_max)
VALUES (1009, '65f023632bc46470c104b76f', 9, 'SKU-AD-BG-BPK09-BLUE', 14, true, 1, 0)
on conflict (product_avail_id) do nothing;
INSERT INTO inventory.product_price (product_price_id, store_merchant_id, product_avail_id, product_price_code, default_price, product_price_amount)
VALUES (1009, '65f023632bc46470c104b76f', 1009, 'base', true, 262.50)
on conflict (product_price_id) do nothing;

INSERT INTO inventory.product_availability (product_avail_id, store_merchant_id, product_id, sku, quantity, available, quantity_ord_min, quantity_ord_max)
VALUES (1010, '65f023632bc46470c104b76f', 9, 'SKU-AD-BG-BPK09-BLACK', 9, true, 1, 0)
on conflict (product_avail_id) do nothing;
INSERT INTO inventory.product_price (product_price_id, store_merchant_id, product_avail_id, product_price_code, default_price, product_price_amount)
VALUES (1010, '65f023632bc46470c104b76f', 1010, 'base', true, 275.00)
on conflict (product_price_id) do nothing;

INSERT INTO inventory.product_availability (product_avail_id, store_merchant_id, product_id, sku, quantity, available, quantity_ord_min, quantity_ord_max)
VALUES (1011, '65f023632bc46470c104b76f', 9, 'SKU-AD-BG-BPK09-WHITE', 6, true, 1, 0)
on conflict (product_avail_id) do nothing;
INSERT INTO inventory.product_price (product_price_id, store_merchant_id, product_avail_id, product_price_code, default_price, product_price_amount)
VALUES (1011, '65f023632bc46470c104b76f', 1011, 'base', true, 287.50)
on conflict (product_price_id) do nothing;

INSERT INTO inventory.product_availability (product_avail_id, store_merchant_id, product_id, sku, quantity, available, quantity_ord_min, quantity_ord_max)
VALUES (1012, '65f023632bc46470c104b76f', 10, 'SKU-HM-AC-BLT10-BLUE', 9, true, 1, 0)
on conflict (product_avail_id) do nothing;
INSERT INTO inventory.product_price (product_price_id, store_merchant_id, product_avail_id, product_price_code, default_price, product_price_amount)
VALUES (1012, '65f023632bc46470c104b76f', 1012, 'base', true, 126.00)
on conflict (product_price_id) do nothing;

INSERT INTO inventory.product_availability (product_avail_id, store_merchant_id, product_id, sku, quantity, available, quantity_ord_min, quantity_ord_max)
VALUES (1013, '65f023632bc46470c104b76f', 10, 'SKU-HM-AC-BLT10-BLACK', 6, true, 1, 0)
on conflict (product_avail_id) do nothing;
INSERT INTO inventory.product_price (product_price_id, store_merchant_id, product_avail_id, product_price_code, default_price, product_price_amount)
VALUES (1013, '65f023632bc46470c104b76f', 1013, 'base', true, 132.00)
on conflict (product_price_id) do nothing;

INSERT INTO inventory.product_availability (product_avail_id, store_merchant_id, product_id, sku, quantity, available, quantity_ord_min, quantity_ord_max)
VALUES (1014, '65f023632bc46470c104b76f', 12, 'SKU-CH-AC-CRD12-BLUE', 0, true, 1, 0)
on conflict (product_avail_id) do nothing;
INSERT INTO inventory.product_price (product_price_id, store_merchant_id, product_avail_id, product_price_code, default_price, product_price_amount)
VALUES (1014, '65f023632bc46470c104b76f', 1014, 'base', true, 2520.00)
on conflict (product_price_id) do nothing;

INSERT INTO inventory.product_availability (product_avail_id, store_merchant_id, product_id, sku, quantity, available, quantity_ord_min, quantity_ord_max)
VALUES (1015, '65f023632bc46470c104b76f', 13, 'SKU-NK-CL-LEG13-M', 11, true, 1, 0)
on conflict (product_avail_id) do nothing;
INSERT INTO inventory.product_price (product_price_id, store_merchant_id, product_avail_id, product_price_code, default_price, product_price_amount)
VALUES (1015, '65f023632bc46470c104b76f', 1015, 'base', true, 399.00)
on conflict (product_price_id) do nothing;

INSERT INTO inventory.product_availability (product_avail_id, store_merchant_id, product_id, sku, quantity, available, quantity_ord_min, quantity_ord_max)
VALUES (1016, '65f023632bc46470c104b76f', 13, 'SKU-NK-CL-LEG13-L', 7, true, 1, 0)
on conflict (product_avail_id) do nothing;
INSERT INTO inventory.product_price (product_price_id, store_merchant_id, product_avail_id, product_price_code, default_price, product_price_amount)
VALUES (1016, '65f023632bc46470c104b76f', 1016, 'base', true, 418.00)
on conflict (product_price_id) do nothing;

INSERT INTO inventory.product_availability (product_avail_id, store_merchant_id, product_id, sku, quantity, available, quantity_ord_min, quantity_ord_max)
VALUES (1017, '65f023632bc46470c104b76f', 13, 'SKU-NK-CL-LEG13-XL', 3, true, 1, 0)
on conflict (product_avail_id) do nothing;
INSERT INTO inventory.product_price (product_price_id, store_merchant_id, product_avail_id, product_price_code, default_price, product_price_amount)
VALUES (1017, '65f023632bc46470c104b76f', 1017, 'base', true, 437.00)
on conflict (product_price_id) do nothing;

INSERT INTO inventory.product_availability (product_avail_id, store_merchant_id, product_id, sku, quantity, available, quantity_ord_min, quantity_ord_max)
VALUES (1018, '65f023632bc46470c104b76f', 14, 'SKU-ZR-CL-POL14-RED-M', 7, true, 1, 0)
on conflict (product_avail_id) do nothing;
INSERT INTO inventory.product_price (product_price_id, store_merchant_id, product_avail_id, product_price_code, default_price, product_price_amount)
VALUES (1018, '65f023632bc46470c104b76f', 1018, 'base', true, 199.50)
on conflict (product_price_id) do nothing;

INSERT INTO inventory.product_availability (product_avail_id, store_merchant_id, product_id, sku, quantity, available, quantity_ord_min, quantity_ord_max)
VALUES (1019, '65f023632bc46470c104b76f', 14, 'SKU-ZR-CL-POL14-BLUE-S', 3, true, 1, 0)
on conflict (product_avail_id) do nothing;
INSERT INTO inventory.product_price (product_price_id, store_merchant_id, product_avail_id, product_price_code, default_price, product_price_amount)
VALUES (1019, '65f023632bc46470c104b76f', 1019, 'base', true, 209.00)
on conflict (product_price_id) do nothing;

INSERT INTO inventory.product_availability (product_avail_id, store_merchant_id, product_id, sku, quantity, available, quantity_ord_min, quantity_ord_max)
VALUES (1020, '65f023632bc46470c104b76f', 14, 'SKU-ZR-CL-POL14-BLUE-M', 22, true, 1, 0)
on conflict (product_avail_id) do nothing;
INSERT INTO inventory.product_price (product_price_id, store_merchant_id, product_avail_id, product_price_code, default_price, product_price_amount)
VALUES (1020, '65f023632bc46470c104b76f', 1020, 'base', true, 218.50)
on conflict (product_price_id) do nothing;

INSERT INTO inventory.product_availability (product_avail_id, store_merchant_id, product_id, sku, quantity, available, quantity_ord_min, quantity_ord_max)
VALUES (1021, '65f023632bc46470c104b76f', 14, 'SKU-ZR-CL-POL14-BLACK-S', 5, true, 1, 0)
on conflict (product_avail_id) do nothing;
INSERT INTO inventory.product_price (product_price_id, store_merchant_id, product_avail_id, product_price_code, default_price, product_price_amount)
VALUES (1021, '65f023632bc46470c104b76f', 1021, 'base', true, 228.00)
on conflict (product_price_id) do nothing;

INSERT INTO inventory.product_availability (product_avail_id, store_merchant_id, product_id, sku, quantity, available, quantity_ord_min, quantity_ord_max)
VALUES (1022, '65f023632bc46470c104b76f', 14, 'SKU-ZR-CL-POL14-BLACK-M', 18, true, 1, 0)
on conflict (product_avail_id) do nothing;
INSERT INTO inventory.product_price (product_price_id, store_merchant_id, product_avail_id, product_price_code, default_price, product_price_amount)
VALUES (1022, '65f023632bc46470c104b76f', 1022, 'base', true, 237.50)
on conflict (product_price_id) do nothing;

INSERT INTO inventory.product_availability (product_avail_id, store_merchant_id, product_id, sku, quantity, available, quantity_ord_min, quantity_ord_max)
VALUES (1023, '65f023632bc46470c104b76f', 15, 'SKU-AD-SH-SND15-RED-M', 3, true, 1, 0)
on conflict (product_avail_id) do nothing;
INSERT INTO inventory.product_price (product_price_id, store_merchant_id, product_avail_id, product_price_code, default_price, product_price_amount)
VALUES (1023, '65f023632bc46470c104b76f', 1023, 'base', true, 157.50)
on conflict (product_price_id) do nothing;

INSERT INTO inventory.product_availability (product_avail_id, store_merchant_id, product_id, sku, quantity, available, quantity_ord_min, quantity_ord_max)
VALUES (1024, '65f023632bc46470c104b76f', 15, 'SKU-AD-SH-SND15-RED-L', 22, true, 1, 0)
on conflict (product_avail_id) do nothing;
INSERT INTO inventory.product_price (product_price_id, store_merchant_id, product_avail_id, product_price_code, default_price, product_price_amount)
VALUES (1024, '65f023632bc46470c104b76f', 1024, 'base', true, 165.00)
on conflict (product_price_id) do nothing;

INSERT INTO inventory.product_availability (product_avail_id, store_merchant_id, product_id, sku, quantity, available, quantity_ord_min, quantity_ord_max)
VALUES (1025, '65f023632bc46470c104b76f', 15, 'SKU-AD-SH-SND15-BLUE-S', 5, true, 1, 0)
on conflict (product_avail_id) do nothing;
INSERT INTO inventory.product_price (product_price_id, store_merchant_id, product_avail_id, product_price_code, default_price, product_price_amount)
VALUES (1025, '65f023632bc46470c104b76f', 1025, 'base', true, 172.50)
on conflict (product_price_id) do nothing;

INSERT INTO inventory.product_availability (product_avail_id, store_merchant_id, product_id, sku, quantity, available, quantity_ord_min, quantity_ord_max)
VALUES (1026, '65f023632bc46470c104b76f', 15, 'SKU-AD-SH-SND15-BLUE-M', 18, true, 1, 0)
on conflict (product_avail_id) do nothing;
INSERT INTO inventory.product_price (product_price_id, store_merchant_id, product_avail_id, product_price_code, default_price, product_price_amount)
VALUES (1026, '65f023632bc46470c104b76f', 1026, 'base', true, 180.00)
on conflict (product_price_id) do nothing;

INSERT INTO inventory.product_availability (product_avail_id, store_merchant_id, product_id, sku, quantity, available, quantity_ord_min, quantity_ord_max)
VALUES (1027, '65f023632bc46470c104b76f', 15, 'SKU-AD-SH-SND15-BLUE-L', 14, true, 1, 0)
on conflict (product_avail_id) do nothing;
INSERT INTO inventory.product_price (product_price_id, store_merchant_id, product_avail_id, product_price_code, default_price, product_price_amount)
VALUES (1027, '65f023632bc46470c104b76f', 1027, 'base', true, 187.50)
on conflict (product_price_id) do nothing;

INSERT INTO inventory.product_availability (product_avail_id, store_merchant_id, product_id, sku, quantity, available, quantity_ord_min, quantity_ord_max)
VALUES (1028, '65f023632bc46470c104b76f', 17, 'SKU-GU-AC-WAL17-BLUE', 5, true, 1, 0)
on conflict (product_avail_id) do nothing;
INSERT INTO inventory.product_price (product_price_id, store_merchant_id, product_avail_id, product_price_code, default_price, product_price_amount)
VALUES (1028, '65f023632bc46470c104b76f', 1028, 'base', true, 1890.00)
on conflict (product_price_id) do nothing;

INSERT INTO inventory.product_availability (product_avail_id, store_merchant_id, product_id, sku, quantity, available, quantity_ord_min, quantity_ord_max)
VALUES (1029, '65f023632bc46470c104b76f', 17, 'SKU-GU-AC-WAL17-BLACK', 18, true, 1, 0)
on conflict (product_avail_id) do nothing;
INSERT INTO inventory.product_price (product_price_id, store_merchant_id, product_avail_id, product_price_code, default_price, product_price_amount)
VALUES (1029, '65f023632bc46470c104b76f', 1029, 'base', true, 1980.00)
on conflict (product_price_id) do nothing;

INSERT INTO inventory.product_availability (product_avail_id, store_merchant_id, product_id, sku, quantity, available, quantity_ord_min, quantity_ord_max)
VALUES (1030, '65f023632bc46470c104b76f', 18, 'SKU-CH-AC-BRH18-BLUE', 18, true, 1, 0)
on conflict (product_avail_id) do nothing;
INSERT INTO inventory.product_price (product_price_id, store_merchant_id, product_avail_id, product_price_code, default_price, product_price_amount)
VALUES (1030, '65f023632bc46470c104b76f', 1030, 'base', true, 2625.00)
on conflict (product_price_id) do nothing;

INSERT INTO inventory.product_availability (product_avail_id, store_merchant_id, product_id, sku, quantity, available, quantity_ord_min, quantity_ord_max)
VALUES (1031, '65f023632bc46470c104b76f', 18, 'SKU-CH-AC-BRH18-BLACK', 14, true, 1, 0)
on conflict (product_avail_id) do nothing;
INSERT INTO inventory.product_price (product_price_id, store_merchant_id, product_avail_id, product_price_code, default_price, product_price_amount)
VALUES (1031, '65f023632bc46470c104b76f', 1031, 'base', true, 2750.00)
on conflict (product_price_id) do nothing;

INSERT INTO inventory.product_availability (product_avail_id, store_merchant_id, product_id, sku, quantity, available, quantity_ord_min, quantity_ord_max)
VALUES (1032, '65f023632bc46470c104b76f', 18, 'SKU-CH-AC-BRH18-WHITE', 9, true, 1, 0)
on conflict (product_avail_id) do nothing;
INSERT INTO inventory.product_price (product_price_id, store_merchant_id, product_avail_id, product_price_code, default_price, product_price_amount)
VALUES (1032, '65f023632bc46470c104b76f', 1032, 'base', true, 2875.00)
on conflict (product_price_id) do nothing;

INSERT INTO inventory.product_availability (product_avail_id, store_merchant_id, product_id, sku, quantity, available, quantity_ord_min, quantity_ord_max)
VALUES (1033, '65f023632bc46470c104b76f', 19, 'SKU-NK-CL-BBS19-M', 14, true, 1, 0)
on conflict (product_avail_id) do nothing;
INSERT INTO inventory.product_price (product_price_id, store_merchant_id, product_avail_id, product_price_code, default_price, product_price_amount)
VALUES (1033, '65f023632bc46470c104b76f', 1033, 'base', true, 294.00)
on conflict (product_price_id) do nothing;

INSERT INTO inventory.product_availability (product_avail_id, store_merchant_id, product_id, sku, quantity, available, quantity_ord_min, quantity_ord_max)
VALUES (1034, '65f023632bc46470c104b76f', 20, 'SKU-ZR-SH-SND20-M', 9, true, 1, 0)
on conflict (product_avail_id) do nothing;
INSERT INTO inventory.product_price (product_price_id, store_merchant_id, product_avail_id, product_price_code, default_price, product_price_amount)
VALUES (1034, '65f023632bc46470c104b76f', 1034, 'base', true, 304.50)
on conflict (product_price_id) do nothing;

INSERT INTO inventory.product_availability (product_avail_id, store_merchant_id, product_id, sku, quantity, available, quantity_ord_min, quantity_ord_max)
VALUES (1035, '65f023632bc46470c104b76f', 20, 'SKU-ZR-SH-SND20-L', 6, true, 1, 0)
on conflict (product_avail_id) do nothing;
INSERT INTO inventory.product_price (product_price_id, store_merchant_id, product_avail_id, product_price_code, default_price, product_price_amount)
VALUES (1035, '65f023632bc46470c104b76f', 1035, 'base', true, 319.00)
on conflict (product_price_id) do nothing;

INSERT INTO inventory.product_availability (product_avail_id, store_merchant_id, product_id, sku, quantity, available, quantity_ord_min, quantity_ord_max)
VALUES (1036, '65f023632bc46470c104b76f', 22, 'SKU-HM-CL-KTP22-RED-M', 0, true, 1, 0)
on conflict (product_avail_id) do nothing;
INSERT INTO inventory.product_price (product_price_id, store_merchant_id, product_avail_id, product_price_code, default_price, product_price_amount)
VALUES (1036, '65f023632bc46470c104b76f', 1036, 'base', true, 262.50)
on conflict (product_price_id) do nothing;

INSERT INTO inventory.product_availability (product_avail_id, store_merchant_id, product_id, sku, quantity, available, quantity_ord_min, quantity_ord_max)
VALUES (1037, '65f023632bc46470c104b76f', 22, 'SKU-HM-CL-KTP22-BLUE-S', 11, true, 1, 0)
on conflict (product_avail_id) do nothing;
INSERT INTO inventory.product_price (product_price_id, store_merchant_id, product_avail_id, product_price_code, default_price, product_price_amount)
VALUES (1037, '65f023632bc46470c104b76f', 1037, 'base', true, 275.00)
on conflict (product_price_id) do nothing;

INSERT INTO inventory.product_availability (product_avail_id, store_merchant_id, product_id, sku, quantity, available, quantity_ord_min, quantity_ord_max)
VALUES (1038, '65f023632bc46470c104b76f', 22, 'SKU-HM-CL-KTP22-BLUE-M', 7, true, 1, 0)
on conflict (product_avail_id) do nothing;
INSERT INTO inventory.product_price (product_price_id, store_merchant_id, product_avail_id, product_price_code, default_price, product_price_amount)
VALUES (1038, '65f023632bc46470c104b76f', 1038, 'base', true, 287.50)
on conflict (product_price_id) do nothing;

INSERT INTO inventory.product_availability (product_avail_id, store_merchant_id, product_id, sku, quantity, available, quantity_ord_min, quantity_ord_max)
VALUES (1039, '65f023632bc46470c104b76f', 23, 'SKU-GU-SH-SNK23-M', 11, true, 1, 0)
on conflict (product_avail_id) do nothing;
INSERT INTO inventory.product_price (product_price_id, store_merchant_id, product_avail_id, product_price_code, default_price, product_price_amount)
VALUES (1039, '65f023632bc46470c104b76f', 1039, 'base', true, 3360.00)
on conflict (product_price_id) do nothing;

INSERT INTO inventory.product_availability (product_avail_id, store_merchant_id, product_id, sku, quantity, available, quantity_ord_min, quantity_ord_max)
VALUES (1040, '65f023632bc46470c104b76f', 23, 'SKU-GU-SH-SNK23-L', 7, true, 1, 0)
on conflict (product_avail_id) do nothing;
INSERT INTO inventory.product_price (product_price_id, store_merchant_id, product_avail_id, product_price_code, default_price, product_price_amount)
VALUES (1040, '65f023632bc46470c104b76f', 1040, 'base', true, 3520.00)
on conflict (product_price_id) do nothing;

INSERT INTO inventory.product_availability (product_avail_id, store_merchant_id, product_id, sku, quantity, available, quantity_ord_min, quantity_ord_max)
VALUES (1041, '65f023632bc46470c104b76f', 23, 'SKU-GU-SH-SNK23-XL', 3, true, 1, 0)
on conflict (product_avail_id) do nothing;
INSERT INTO inventory.product_price (product_price_id, store_merchant_id, product_avail_id, product_price_code, default_price, product_price_amount)
VALUES (1041, '65f023632bc46470c104b76f', 1041, 'base', true, 3680.00)
on conflict (product_price_id) do nothing;

INSERT INTO inventory.product_availability (product_avail_id, store_merchant_id, product_id, sku, quantity, available, quantity_ord_min, quantity_ord_max)
VALUES (1042, '65f023632bc46470c104b76f', 24, 'SKU-CH-SH-BAL24-RED-M', 7, true, 1, 0)
on conflict (product_avail_id) do nothing;
INSERT INTO inventory.product_price (product_price_id, store_merchant_id, product_avail_id, product_price_code, default_price, product_price_amount)
VALUES (1042, '65f023632bc46470c104b76f', 1042, 'base', true, 3675.00)
on conflict (product_price_id) do nothing;

INSERT INTO inventory.product_availability (product_avail_id, store_merchant_id, product_id, sku, quantity, available, quantity_ord_min, quantity_ord_max)
VALUES (1043, '65f023632bc46470c104b76f', 24, 'SKU-CH-SH-BAL24-BLUE-S', 3, true, 1, 0)
on conflict (product_avail_id) do nothing;
INSERT INTO inventory.product_price (product_price_id, store_merchant_id, product_avail_id, product_price_code, default_price, product_price_amount)
VALUES (1043, '65f023632bc46470c104b76f', 1043, 'base', true, 3850.00)
on conflict (product_price_id) do nothing;

INSERT INTO inventory.product_availability (product_avail_id, store_merchant_id, product_id, sku, quantity, available, quantity_ord_min, quantity_ord_max)
VALUES (1044, '65f023632bc46470c104b76f', 24, 'SKU-CH-SH-BAL24-BLUE-M', 22, true, 1, 0)
on conflict (product_avail_id) do nothing;
INSERT INTO inventory.product_price (product_price_id, store_merchant_id, product_avail_id, product_price_code, default_price, product_price_amount)
VALUES (1044, '65f023632bc46470c104b76f', 1044, 'base', true, 4025.00)
on conflict (product_price_id) do nothing;

INSERT INTO inventory.product_availability (product_avail_id, store_merchant_id, product_id, sku, quantity, available, quantity_ord_min, quantity_ord_max)
VALUES (1045, '65f023632bc46470c104b76f', 24, 'SKU-CH-SH-BAL24-BLACK-S', 5, true, 1, 0)
on conflict (product_avail_id) do nothing;
INSERT INTO inventory.product_price (product_price_id, store_merchant_id, product_avail_id, product_price_code, default_price, product_price_amount)
VALUES (1045, '65f023632bc46470c104b76f', 1045, 'base', true, 4200.00)
on conflict (product_price_id) do nothing;

INSERT INTO inventory.product_availability (product_avail_id, store_merchant_id, product_id, sku, quantity, available, quantity_ord_min, quantity_ord_max)
VALUES (1046, '65f023632bc46470c104b76f', 24, 'SKU-CH-SH-BAL24-BLACK-M', 18, true, 1, 0)
on conflict (product_avail_id) do nothing;
INSERT INTO inventory.product_price (product_price_id, store_merchant_id, product_avail_id, product_price_code, default_price, product_price_amount)
VALUES (1046, '65f023632bc46470c104b76f', 1046, 'base', true, 4375.00)
on conflict (product_price_id) do nothing;

INSERT INTO inventory.product_availability (product_avail_id, store_merchant_id, product_id, sku, quantity, available, quantity_ord_min, quantity_ord_max)
VALUES (1047, '65f023632bc46470c104b76f', 25, 'SKU-NK-CL-TNK25-RED-M', 3, true, 1, 0)
on conflict (product_avail_id) do nothing;
INSERT INTO inventory.product_price (product_price_id, store_merchant_id, product_avail_id, product_price_code, default_price, product_price_amount)
VALUES (1047, '65f023632bc46470c104b76f', 1047, 'base', true, 189.00)
on conflict (product_price_id) do nothing;

INSERT INTO inventory.product_availability (product_avail_id, store_merchant_id, product_id, sku, quantity, available, quantity_ord_min, quantity_ord_max)
VALUES (1048, '65f023632bc46470c104b76f', 25, 'SKU-NK-CL-TNK25-RED-L', 22, true, 1, 0)
on conflict (product_avail_id) do nothing;
INSERT INTO inventory.product_price (product_price_id, store_merchant_id, product_avail_id, product_price_code, default_price, product_price_amount)
VALUES (1048, '65f023632bc46470c104b76f', 1048, 'base', true, 198.00)
on conflict (product_price_id) do nothing;

INSERT INTO inventory.product_availability (product_avail_id, store_merchant_id, product_id, sku, quantity, available, quantity_ord_min, quantity_ord_max)
VALUES (1049, '65f023632bc46470c104b76f', 25, 'SKU-NK-CL-TNK25-BLUE-S', 5, true, 1, 0)
on conflict (product_avail_id) do nothing;
INSERT INTO inventory.product_price (product_price_id, store_merchant_id, product_avail_id, product_price_code, default_price, product_price_amount)
VALUES (1049, '65f023632bc46470c104b76f', 1049, 'base', true, 207.00)
on conflict (product_price_id) do nothing;

INSERT INTO inventory.product_availability (product_avail_id, store_merchant_id, product_id, sku, quantity, available, quantity_ord_min, quantity_ord_max)
VALUES (1050, '65f023632bc46470c104b76f', 25, 'SKU-NK-CL-TNK25-BLUE-M', 18, true, 1, 0)
on conflict (product_avail_id) do nothing;
INSERT INTO inventory.product_price (product_price_id, store_merchant_id, product_avail_id, product_price_code, default_price, product_price_amount)
VALUES (1050, '65f023632bc46470c104b76f', 1050, 'base', true, 216.00)
on conflict (product_price_id) do nothing;

INSERT INTO inventory.product_availability (product_avail_id, store_merchant_id, product_id, sku, quantity, available, quantity_ord_min, quantity_ord_max)
VALUES (1051, '65f023632bc46470c104b76f', 25, 'SKU-NK-CL-TNK25-BLUE-L', 14, true, 1, 0)
on conflict (product_avail_id) do nothing;
INSERT INTO inventory.product_price (product_price_id, store_merchant_id, product_avail_id, product_price_code, default_price, product_price_amount)
VALUES (1051, '65f023632bc46470c104b76f', 1051, 'base', true, 225.00)
on conflict (product_price_id) do nothing;

INSERT INTO inventory.product_availability (product_avail_id, store_merchant_id, product_id, sku, quantity, available, quantity_ord_min, quantity_ord_max)
VALUES (1052, '65f023632bc46470c104b76f', 27, 'SKU-AD-CL-KTS27-M', 5, true, 1, 0)
on conflict (product_avail_id) do nothing;
INSERT INTO inventory.product_price (product_price_id, store_merchant_id, product_avail_id, product_price_code, default_price, product_price_amount)
VALUES (1052, '65f023632bc46470c104b76f', 1052, 'base', true, 504.00)
on conflict (product_price_id) do nothing;

INSERT INTO inventory.product_availability (product_avail_id, store_merchant_id, product_id, sku, quantity, available, quantity_ord_min, quantity_ord_max)
VALUES (1053, '65f023632bc46470c104b76f', 28, 'SKU-HM-AC-SCF28-BLUE', 18, true, 1, 0)
on conflict (product_avail_id) do nothing;
INSERT INTO inventory.product_price (product_price_id, store_merchant_id, product_avail_id, product_price_code, default_price, product_price_amount)
VALUES (1053, '65f023632bc46470c104b76f', 1053, 'base', true, 157.50)
on conflict (product_price_id) do nothing;

INSERT INTO inventory.product_availability (product_avail_id, store_merchant_id, product_id, sku, quantity, available, quantity_ord_min, quantity_ord_max)
VALUES (1054, '65f023632bc46470c104b76f', 28, 'SKU-HM-AC-SCF28-BLACK', 14, true, 1, 0)
on conflict (product_avail_id) do nothing;
INSERT INTO inventory.product_price (product_price_id, store_merchant_id, product_avail_id, product_price_code, default_price, product_price_amount)
VALUES (1054, '65f023632bc46470c104b76f', 1054, 'base', true, 165.00)
on conflict (product_price_id) do nothing;

INSERT INTO inventory.product_availability (product_avail_id, store_merchant_id, product_id, sku, quantity, available, quantity_ord_min, quantity_ord_max)
VALUES (1055, '65f023632bc46470c104b76f', 29, 'SKU-GU-BG-BBG29-BLUE', 14, true, 1, 0)
on conflict (product_avail_id) do nothing;
INSERT INTO inventory.product_price (product_price_id, store_merchant_id, product_avail_id, product_price_code, default_price, product_price_amount)
VALUES (1055, '65f023632bc46470c104b76f', 1055, 'base', true, 4725.00)
on conflict (product_price_id) do nothing;

INSERT INTO inventory.product_availability (product_avail_id, store_merchant_id, product_id, sku, quantity, available, quantity_ord_min, quantity_ord_max)
VALUES (1056, '65f023632bc46470c104b76f', 30, 'SKU-CH-SH-SNK30-M', 9, true, 1, 0)
on conflict (product_avail_id) do nothing;
INSERT INTO inventory.product_price (product_price_id, store_merchant_id, product_avail_id, product_price_code, default_price, product_price_amount)
VALUES (1056, '65f023632bc46470c104b76f', 1056, 'base', true, 5775.00)
on conflict (product_price_id) do nothing;

INSERT INTO inventory.product_availability (product_avail_id, store_merchant_id, product_id, sku, quantity, available, quantity_ord_min, quantity_ord_max)
VALUES (1057, '65f023632bc46470c104b76f', 30, 'SKU-CH-SH-SNK30-L', 6, true, 1, 0)
on conflict (product_avail_id) do nothing;
INSERT INTO inventory.product_price (product_price_id, store_merchant_id, product_avail_id, product_price_code, default_price, product_price_amount)
VALUES (1057, '65f023632bc46470c104b76f', 1057, 'base', true, 6050.00)
on conflict (product_price_id) do nothing;

INSERT INTO inventory.product_availability (product_avail_id, store_merchant_id, product_id, sku, quantity, available, quantity_ord_min, quantity_ord_max)
VALUES (1058, '65f023632bc46470c104b76f', 32, 'SKU-ZR-CL-JNS32-RED-M', 0, true, 1, 0)
on conflict (product_avail_id) do nothing;
INSERT INTO inventory.product_price (product_price_id, store_merchant_id, product_avail_id, product_price_code, default_price, product_price_amount)
VALUES (1058, '65f023632bc46470c104b76f', 1058, 'base', true, 399.00)
on conflict (product_price_id) do nothing;

INSERT INTO inventory.product_availability (product_avail_id, store_merchant_id, product_id, sku, quantity, available, quantity_ord_min, quantity_ord_max)
VALUES (1059, '65f023632bc46470c104b76f', 32, 'SKU-ZR-CL-JNS32-BLUE-S', 11, true, 1, 0)
on conflict (product_avail_id) do nothing;
INSERT INTO inventory.product_price (product_price_id, store_merchant_id, product_avail_id, product_price_code, default_price, product_price_amount)
VALUES (1059, '65f023632bc46470c104b76f', 1059, 'base', true, 418.00)
on conflict (product_price_id) do nothing;

INSERT INTO inventory.product_availability (product_avail_id, store_merchant_id, product_id, sku, quantity, available, quantity_ord_min, quantity_ord_max)
VALUES (1060, '65f023632bc46470c104b76f', 32, 'SKU-ZR-CL-JNS32-BLUE-M', 7, true, 1, 0)
on conflict (product_avail_id) do nothing;
INSERT INTO inventory.product_price (product_price_id, store_merchant_id, product_avail_id, product_price_code, default_price, product_price_amount)
VALUES (1060, '65f023632bc46470c104b76f', 1060, 'base', true, 437.00)
on conflict (product_price_id) do nothing;

INSERT INTO inventory.product_availability (product_avail_id, store_merchant_id, product_id, sku, quantity, available, quantity_ord_min, quantity_ord_max)
VALUES (1061, '65f023632bc46470c104b76f', 33, 'SKU-AD-AC-CAP33-BLUE', 11, true, 1, 0)
on conflict (product_avail_id) do nothing;
INSERT INTO inventory.product_price (product_price_id, store_merchant_id, product_avail_id, product_price_code, default_price, product_price_amount)
VALUES (1061, '65f023632bc46470c104b76f', 1061, 'base', true, 126.00)
on conflict (product_price_id) do nothing;

INSERT INTO inventory.product_availability (product_avail_id, store_merchant_id, product_id, sku, quantity, available, quantity_ord_min, quantity_ord_max)
VALUES (1062, '65f023632bc46470c104b76f', 33, 'SKU-AD-AC-CAP33-BLACK', 7, true, 1, 0)
on conflict (product_avail_id) do nothing;
INSERT INTO inventory.product_price (product_price_id, store_merchant_id, product_avail_id, product_price_code, default_price, product_price_amount)
VALUES (1062, '65f023632bc46470c104b76f', 1062, 'base', true, 132.00)
on conflict (product_price_id) do nothing;

INSERT INTO inventory.product_availability (product_avail_id, store_merchant_id, product_id, sku, quantity, available, quantity_ord_min, quantity_ord_max)
VALUES (1063, '65f023632bc46470c104b76f', 34, 'SKU-HM-CL-KRJ34-M', 7, true, 1, 0)
on conflict (product_avail_id) do nothing;
INSERT INTO inventory.product_price (product_price_id, store_merchant_id, product_avail_id, product_price_code, default_price, product_price_amount)
VALUES (1063, '65f023632bc46470c104b76f', 1063, 'base', true, 315.00)
on conflict (product_price_id) do nothing;

INSERT INTO inventory.product_availability (product_avail_id, store_merchant_id, product_id, sku, quantity, available, quantity_ord_min, quantity_ord_max)
VALUES (1064, '65f023632bc46470c104b76f', 34, 'SKU-HM-CL-KRJ34-L', 3, true, 1, 0)
on conflict (product_avail_id) do nothing;
INSERT INTO inventory.product_price (product_price_id, store_merchant_id, product_avail_id, product_price_code, default_price, product_price_amount)
VALUES (1064, '65f023632bc46470c104b76f', 1064, 'base', true, 330.00)
on conflict (product_price_id) do nothing;

INSERT INTO inventory.product_availability (product_avail_id, store_merchant_id, product_id, sku, quantity, available, quantity_ord_min, quantity_ord_max)
VALUES (1065, '65f023632bc46470c104b76f', 34, 'SKU-HM-CL-KRJ34-XL', 22, true, 1, 0)
on conflict (product_avail_id) do nothing;
INSERT INTO inventory.product_price (product_price_id, store_merchant_id, product_avail_id, product_price_code, default_price, product_price_amount)
VALUES (1065, '65f023632bc46470c104b76f', 1065, 'base', true, 345.00)
on conflict (product_price_id) do nothing;

INSERT INTO inventory.product_availability (product_avail_id, store_merchant_id, product_id, sku, quantity, available, quantity_ord_min, quantity_ord_max)
VALUES (1066, '65f023632bc46470c104b76f', 35, 'SKU-GU-AC-SCF35-BLUE', 3, true, 1, 0)
on conflict (product_avail_id) do nothing;
INSERT INTO inventory.product_price (product_price_id, store_merchant_id, product_avail_id, product_price_code, default_price, product_price_amount)
VALUES (1066, '65f023632bc46470c104b76f', 1066, 'base', true, 2310.00)
on conflict (product_price_id) do nothing;

INSERT INTO inventory.product_availability (product_avail_id, store_merchant_id, product_id, sku, quantity, available, quantity_ord_min, quantity_ord_max)
VALUES (1067, '65f023632bc46470c104b76f', 35, 'SKU-GU-AC-SCF35-BLACK', 22, true, 1, 0)
on conflict (product_avail_id) do nothing;
INSERT INTO inventory.product_price (product_price_id, store_merchant_id, product_avail_id, product_price_code, default_price, product_price_amount)
VALUES (1067, '65f023632bc46470c104b76f', 1067, 'base', true, 2420.00)
on conflict (product_price_id) do nothing;

INSERT INTO inventory.product_availability (product_avail_id, store_merchant_id, product_id, sku, quantity, available, quantity_ord_min, quantity_ord_max)
VALUES (1068, '65f023632bc46470c104b76f', 35, 'SKU-GU-AC-SCF35-WHITE', 5, true, 1, 0)
on conflict (product_avail_id) do nothing;
INSERT INTO inventory.product_price (product_price_id, store_merchant_id, product_avail_id, product_price_code, default_price, product_price_amount)
VALUES (1068, '65f023632bc46470c104b76f', 1068, 'base', true, 2530.00)
on conflict (product_price_id) do nothing;

INSERT INTO inventory.product_availability (product_avail_id, store_merchant_id, product_id, sku, quantity, available, quantity_ord_min, quantity_ord_max)
VALUES (1069, '65f023632bc46470c104b76f', 37, 'SKU-NK-CL-WRS37-RED-M', 5, true, 1, 0)
on conflict (product_avail_id) do nothing;
INSERT INTO inventory.product_price (product_price_id, store_merchant_id, product_avail_id, product_price_code, default_price, product_price_amount)
VALUES (1069, '65f023632bc46470c104b76f', 1069, 'base', true, 210.00)
on conflict (product_price_id) do nothing;

INSERT INTO inventory.product_availability (product_avail_id, store_merchant_id, product_id, sku, quantity, available, quantity_ord_min, quantity_ord_max)
VALUES (1070, '65f023632bc46470c104b76f', 37, 'SKU-NK-CL-WRS37-BLUE-S', 18, true, 1, 0)
on conflict (product_avail_id) do nothing;
INSERT INTO inventory.product_price (product_price_id, store_merchant_id, product_avail_id, product_price_code, default_price, product_price_amount)
VALUES (1070, '65f023632bc46470c104b76f', 1070, 'base', true, 220.00)
on conflict (product_price_id) do nothing;

INSERT INTO inventory.product_availability (product_avail_id, store_merchant_id, product_id, sku, quantity, available, quantity_ord_min, quantity_ord_max)
VALUES (1071, '65f023632bc46470c104b76f', 37, 'SKU-NK-CL-WRS37-BLUE-M', 14, true, 1, 0)
on conflict (product_avail_id) do nothing;
INSERT INTO inventory.product_price (product_price_id, store_merchant_id, product_avail_id, product_price_code, default_price, product_price_amount)
VALUES (1071, '65f023632bc46470c104b76f', 1071, 'base', true, 230.00)
on conflict (product_price_id) do nothing;

INSERT INTO inventory.product_availability (product_avail_id, store_merchant_id, product_id, sku, quantity, available, quantity_ord_min, quantity_ord_max)
VALUES (1072, '65f023632bc46470c104b76f', 37, 'SKU-NK-CL-WRS37-BLACK-S', 9, true, 1, 0)
on conflict (product_avail_id) do nothing;
INSERT INTO inventory.product_price (product_price_id, store_merchant_id, product_avail_id, product_price_code, default_price, product_price_amount)
VALUES (1072, '65f023632bc46470c104b76f', 1072, 'base', true, 240.00)
on conflict (product_price_id) do nothing;

INSERT INTO inventory.product_availability (product_avail_id, store_merchant_id, product_id, sku, quantity, available, quantity_ord_min, quantity_ord_max)
VALUES (1073, '65f023632bc46470c104b76f', 37, 'SKU-NK-CL-WRS37-BLACK-M', 6, true, 1, 0)
on conflict (product_avail_id) do nothing;
INSERT INTO inventory.product_price (product_price_id, store_merchant_id, product_avail_id, product_price_code, default_price, product_price_amount)
VALUES (1073, '65f023632bc46470c104b76f', 1073, 'base', true, 250.00)
on conflict (product_price_id) do nothing;

INSERT INTO inventory.product_availability (product_avail_id, store_merchant_id, product_id, sku, quantity, available, quantity_ord_min, quantity_ord_max)
VALUES (1074, '65f023632bc46470c104b76f', 38, 'SKU-ZR-CL-KSW38-RED-M', 18, true, 1, 0)
on conflict (product_avail_id) do nothing;
INSERT INTO inventory.product_price (product_price_id, store_merchant_id, product_avail_id, product_price_code, default_price, product_price_amount)
VALUES (1074, '65f023632bc46470c104b76f', 1074, 'base', true, 231.00)
on conflict (product_price_id) do nothing;

INSERT INTO inventory.product_availability (product_avail_id, store_merchant_id, product_id, sku, quantity, available, quantity_ord_min, quantity_ord_max)
VALUES (1075, '65f023632bc46470c104b76f', 38, 'SKU-ZR-CL-KSW38-RED-L', 14, true, 1, 0)
on conflict (product_avail_id) do nothing;
INSERT INTO inventory.product_price (product_price_id, store_merchant_id, product_avail_id, product_price_code, default_price, product_price_amount)
VALUES (1075, '65f023632bc46470c104b76f', 1075, 'base', true, 242.00)
on conflict (product_price_id) do nothing;

INSERT INTO inventory.product_availability (product_avail_id, store_merchant_id, product_id, sku, quantity, available, quantity_ord_min, quantity_ord_max)
VALUES (1076, '65f023632bc46470c104b76f', 38, 'SKU-ZR-CL-KSW38-BLUE-S', 9, true, 1, 0)
on conflict (product_avail_id) do nothing;
INSERT INTO inventory.product_price (product_price_id, store_merchant_id, product_avail_id, product_price_code, default_price, product_price_amount)
VALUES (1076, '65f023632bc46470c104b76f', 1076, 'base', true, 253.00)
on conflict (product_price_id) do nothing;

INSERT INTO inventory.product_availability (product_avail_id, store_merchant_id, product_id, sku, quantity, available, quantity_ord_min, quantity_ord_max)
VALUES (1077, '65f023632bc46470c104b76f', 38, 'SKU-ZR-CL-KSW38-BLUE-M', 6, true, 1, 0)
on conflict (product_avail_id) do nothing;
INSERT INTO inventory.product_price (product_price_id, store_merchant_id, product_avail_id, product_price_code, default_price, product_price_amount)
VALUES (1077, '65f023632bc46470c104b76f', 1077, 'base', true, 264.00)
on conflict (product_price_id) do nothing;

INSERT INTO inventory.product_availability (product_avail_id, store_merchant_id, product_id, sku, quantity, available, quantity_ord_min, quantity_ord_max)
VALUES (1078, '65f023632bc46470c104b76f', 38, 'SKU-ZR-CL-KSW38-BLUE-L', 0, true, 1, 0)
on conflict (product_avail_id) do nothing;
INSERT INTO inventory.product_price (product_price_id, store_merchant_id, product_avail_id, product_price_code, default_price, product_price_amount)
VALUES (1078, '65f023632bc46470c104b76f', 1078, 'base', true, 275.00)
on conflict (product_price_id) do nothing;

INSERT INTO inventory.product_availability (product_avail_id, store_merchant_id, product_id, sku, quantity, available, quantity_ord_min, quantity_ord_max)
VALUES (1079, '65f023632bc46470c104b76f', 39, 'SKU-AD-AC-SCK39-BLUE', 14, true, 1, 0)
on conflict (product_avail_id) do nothing;
INSERT INTO inventory.product_price (product_price_id, store_merchant_id, product_avail_id, product_price_code, default_price, product_price_amount)
VALUES (1079, '65f023632bc46470c104b76f', 1079, 'base', true, 84.00)
on conflict (product_price_id) do nothing;

INSERT INTO inventory.product_availability (product_avail_id, store_merchant_id, product_id, sku, quantity, available, quantity_ord_min, quantity_ord_max)
VALUES (1080, '65f023632bc46470c104b76f', 39, 'SKU-AD-AC-SCK39-BLACK', 9, true, 1, 0)
on conflict (product_avail_id) do nothing;
INSERT INTO inventory.product_price (product_price_id, store_merchant_id, product_avail_id, product_price_code, default_price, product_price_amount)
VALUES (1080, '65f023632bc46470c104b76f', 1080, 'base', true, 88.00)
on conflict (product_price_id) do nothing;

INSERT INTO inventory.product_availability (product_avail_id, store_merchant_id, product_id, sku, quantity, available, quantity_ord_min, quantity_ord_max)
VALUES (1081, '65f023632bc46470c104b76f', 40, 'SKU-HM-CL-SWM40-M', 9, true, 1, 0)
on conflict (product_avail_id) do nothing;
INSERT INTO inventory.product_price (product_price_id, store_merchant_id, product_avail_id, product_price_code, default_price, product_price_amount)
VALUES (1081, '65f023632bc46470c104b76f', 1081, 'base', true, 199.50)
on conflict (product_price_id) do nothing;

INSERT INTO inventory.product_availability (product_avail_id, store_merchant_id, product_id, sku, quantity, available, quantity_ord_min, quantity_ord_max)
VALUES (1082, '65f023632bc46470c104b76f', 42, 'SKU-CH-AC-EAR42-BLUE', 0, true, 1, 0)
on conflict (product_avail_id) do nothing;
INSERT INTO inventory.product_price (product_price_id, store_merchant_id, product_avail_id, product_price_code, default_price, product_price_amount)
VALUES (1082, '65f023632bc46470c104b76f', 1082, 'base', true, 2940.00)
on conflict (product_price_id) do nothing;

INSERT INTO inventory.product_availability (product_avail_id, store_merchant_id, product_id, sku, quantity, available, quantity_ord_min, quantity_ord_max)
VALUES (1083, '65f023632bc46470c104b76f', 43, 'SKU-NK-BG-DUF43-BLUE', 11, true, 1, 0)
on conflict (product_avail_id) do nothing;
INSERT INTO inventory.product_price (product_price_id, store_merchant_id, product_avail_id, product_price_code, default_price, product_price_amount)
VALUES (1083, '65f023632bc46470c104b76f', 1083, 'base', true, 367.50)
on conflict (product_price_id) do nothing;

INSERT INTO inventory.product_availability (product_avail_id, store_merchant_id, product_id, sku, quantity, available, quantity_ord_min, quantity_ord_max)
VALUES (1084, '65f023632bc46470c104b76f', 43, 'SKU-NK-BG-DUF43-BLACK', 7, true, 1, 0)
on conflict (product_avail_id) do nothing;
INSERT INTO inventory.product_price (product_price_id, store_merchant_id, product_avail_id, product_price_code, default_price, product_price_amount)
VALUES (1084, '65f023632bc46470c104b76f', 1084, 'base', true, 385.00)
on conflict (product_price_id) do nothing;

INSERT INTO inventory.product_availability (product_avail_id, store_merchant_id, product_id, sku, quantity, available, quantity_ord_min, quantity_ord_max)
VALUES (1085, '65f023632bc46470c104b76f', 44, 'SKU-ZR-CL-BLS44-M', 7, true, 1, 0)
on conflict (product_avail_id) do nothing;
INSERT INTO inventory.product_price (product_price_id, store_merchant_id, product_avail_id, product_price_code, default_price, product_price_amount)
VALUES (1085, '65f023632bc46470c104b76f', 1085, 'base', true, 273.00)
on conflict (product_price_id) do nothing;

INSERT INTO inventory.product_availability (product_avail_id, store_merchant_id, product_id, sku, quantity, available, quantity_ord_min, quantity_ord_max)
VALUES (1086, '65f023632bc46470c104b76f', 44, 'SKU-ZR-CL-BLS44-L', 3, true, 1, 0)
on conflict (product_avail_id) do nothing;
INSERT INTO inventory.product_price (product_price_id, store_merchant_id, product_avail_id, product_price_code, default_price, product_price_amount)
VALUES (1086, '65f023632bc46470c104b76f', 1086, 'base', true, 286.00)
on conflict (product_price_id) do nothing;

INSERT INTO inventory.product_availability (product_avail_id, store_merchant_id, product_id, sku, quantity, available, quantity_ord_min, quantity_ord_max)
VALUES (1087, '65f023632bc46470c104b76f', 45, 'SKU-AD-SH-SLD45-RED-M', 3, true, 1, 0)
on conflict (product_avail_id) do nothing;
INSERT INTO inventory.product_price (product_price_id, store_merchant_id, product_avail_id, product_price_code, default_price, product_price_amount)
VALUES (1087, '65f023632bc46470c104b76f', 1087, 'base', true, 157.50)
on conflict (product_price_id) do nothing;

INSERT INTO inventory.product_availability (product_avail_id, store_merchant_id, product_id, sku, quantity, available, quantity_ord_min, quantity_ord_max)
VALUES (1088, '65f023632bc46470c104b76f', 45, 'SKU-AD-SH-SLD45-BLUE-S', 22, true, 1, 0)
on conflict (product_avail_id) do nothing;
INSERT INTO inventory.product_price (product_price_id, store_merchant_id, product_avail_id, product_price_code, default_price, product_price_amount)
VALUES (1088, '65f023632bc46470c104b76f', 1088, 'base', true, 165.00)
on conflict (product_price_id) do nothing;

INSERT INTO inventory.product_availability (product_avail_id, store_merchant_id, product_id, sku, quantity, available, quantity_ord_min, quantity_ord_max)
VALUES (1089, '65f023632bc46470c104b76f', 45, 'SKU-AD-SH-SLD45-BLUE-M', 5, true, 1, 0)
on conflict (product_avail_id) do nothing;
INSERT INTO inventory.product_price (product_price_id, store_merchant_id, product_avail_id, product_price_code, default_price, product_price_amount)
VALUES (1089, '65f023632bc46470c104b76f', 1089, 'base', true, 172.50)
on conflict (product_price_id) do nothing;
