// GENERATED by scripts/theme-routes.mjs — do not edit. The route logic lives in src/shell/routes.
import theme from '@store-front/theme-beauty';
import {blogIndexPage} from '@/shell/routes/blog-index';

export {generateMetadata} from '@/shell/routes/blog-index';
export default blogIndexPage(theme);
