version: '3'
services:
  gateway-service-v2:
    image: gateway-service-v2
    network_mode: "host"
    ports:
      - "80:80"
      - "443:443"
      - "2019:2019"
    environment:
      STORE_POD_GATEWAY: http://store-pod-1.gateway.com:8100
      ASK_TLS_URL: http://gateway.com:8000/manager/api/v1/router/public/ask-for-tls
