// GENERATED by scripts/theme-routes.mjs — do not edit. The route logic lives in src/shell/routes.
import theme from '@store-front/theme-cosmetics';
import {loginPage} from '@/shell/routes/login';

export {generateMetadata} from '@/shell/routes/login';
export default loginPage(theme);
