plugins {
	alias(libs.plugins.java.library.conventions)
	alias(libs.plugins.spotless)
}

dependencies {
	api project(':store-pod:store-commons')
	implementation libs.aws.sdk.s3
	implementation libs.commons.io
	compileOnly libs.apache.commons.lang3
	compileOnly libs.lombok
	annotationProcessor libs.lombok
}
