// GENERATED by scripts/theme-routes.mjs — do not edit. The route logic lives in src/shell/routes.
import theme from '@store-front/theme-pink';
import {contentPage} from '@/shell/routes/content';

export {generateMetadata} from '@/shell/routes/content';
export default contentPage(theme);
