// GENERATED by libs/types/scripts/build-color-schemas.mjs (THEME_DEFAULTS.hunger) — edit the seed there, then
// `npm run gen:colors` in libs/types. Same rules as the merchant presets (see that file's header).
import type {ColorSchema} from '@store-front/types';

/**
 * The Letterbox Menu: white menu stock, black ink, a menu-red second plate on mastheads, section bands and every ADD; 20%-tint red wash; spot-green offer and mark ink. (light)
 *
 * The theme's own palette — what renders when the merchant's colour theme is `DEFAULT` or unset. Wired as
 * `tokens.defaultColors` in `./index.ts`; any fixed preset the merchant picks replaces it whole.
 */
export const DEFAULT_COLORS: ColorSchema = {
    primary: "#AD0010",
    secondary: "#FFD4CD",
    accent: "#00663E",
    background: "#FEFBF8",
    foreground: "#16100D",
    error: "#B7191C",
    warning: "#EE9E10",
    success: "#007533",
    info: "#0065A1",
    neutral: "#B2A9A5",
    border: "#E2D9CF",
    ring: "#AD0010",
    outline: "#963731",
    hoverPrimary: "#8B000A",
    focusPrimary: "#6F0006",
    hoverSecondary: "#E8BEB6",
    focusSecondary: "#D4ABA3",
    hoverAccent: "#00502F",
    focusAccent: "#003E23",
    hoverError: "#99000D",
    focusError: "#7D0008",
    hoverWarning: "#D38A00",
    focusWarning: "#BA7900",
    hoverSuccess: "#005E28",
    focusSuccess: "#004B1E",
    hoverInfo: "#005182",
    focusInfo: "#004069",
    hoverNeutral: "#9C938F",
    focusNeutral: "#8A817D",
};
