spring:
  application:
    name: certificate-manager
  docker:
    compose:
      file: ${spring.application.name}/compose.yml
  datasource:
    url: jdbc:postgresql://localhost:5432/certificatemanagerdb
    username: postgres
    password: password
  main:
    lazy-initialization: true
server:
  forward-headers-strategy: FRAMEWORK
  port: 8082
info:
  app:
    name: ${spring.application.name}
management:
  info:
    env:
      enabled: true
    os:
      enabled: true
  metrics:
    tags:
      application: ${spring.application.name}
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: [ '*' ]
logging:
  level:
    org.springframework.boot: debug
    org.springframework.web: debug
    org.springframework.security: debug
