spring:
  application:
    name: certificate-manager
  docker:
    compose:
      file: ${spring.application.name}/compose.yml
  sql:
    init:
      mode: always
  datasource:
    url: jdbc:postgresql://localhost:5432/certificatemanagerdb
    username: postgres
    password: password
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:9999/realms/cvhome/protocol/openid-connect/certs
  cloud:
    function:
      definition: ";"
    stream:
      bindings:
        logOrderEvents-out-0:
          destination: "com.asrevo.cvhome.domain-certificate-order-events"
          content-type: "application/json"
    discovery:
      client:
        simple:
          instances:
            domain:
              - uri: "http://localhost:8081"
                metadata:
                  service-name: domain
                  instance: domain-1
            certificate-manager:
              - uri: "http://localhost:8082"
                metadata:
                  service-name: certificate-manager
                  instance: certificate-manager-1
            auth:
              - uri: "http://localhost:9999"
                metadata:
                  service-name: auth
                  instance: auth-1
            ui:
              - uri: "http://localhost:4200"
                metadata:
                  service-name: ui
                  instance: ui-1
            profile:
              - uri: "http://localhost:4300"
                metadata:
                  service-name: profile
                  instance: profile-1
            gateway:
              - uri: "http://localhost:8080"
                metadata:
                  service-name: gateway
                  instance: gateway-1
server:
  forward-headers-strategy: FRAMEWORK
  port: 8082
info:
  app:
    name: ${spring.application.name}
management:
  info:
    env:
      enabled: true
    os:
      enabled: true
  metrics:
    tags:
      application: ${spring.application.name}
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: [ '*' ]
logging:
  level:
    org.springframework.boot: debug
    org.springframework.web: debug
    org.springframework.security: debug
    reactor.netty.http: debug
