### get token from test application
POST http://localhost:8082/api/v1/test/sign
Content-Type: application/json

{
  "sub": "fcad941c-aea5-426f-8f17-428add82aeb1",
  "resource_access": {
    "account": {
      "roles": [
        "manage-account",
        "manage-account-links",
        "view-profile"
      ]
    }
  },
  "email_verified": "false",
  "allowed-origins": [
    "/*"
  ],
  "iss": "http://auth.gateway.com:9999/realms/cvhome",
  "typ": "Bearer",
  "preferred_username": "microservice-gateway",
  "given_name": "",
  "sid": "ea59acba-c673-42f5-a374-5e0a30802683",
  "aud": "account",
  "realm_access": {
    "roles": [
      "ROLE_MICROSERVICE",
      "offline_access",
      "uma_authorization",
      "default-roles-cvhome",
      "ROLE_MICROSERVICE_GATEWAY"
    ]
  },
  "azp": "microservice-app",
  "scope": "profile email",
  "session_state": "ea59acba-c673-42f5-a374-5e0a30802683",
  "family_name": "",
  "jti": "84a4b2a4-b463-4df4-9640-c669124402d3"
}

> {%
    client.global.set("access_token", response.body.access_token)
%}



### get token for microservice-certificate-manager
POST http://auth.gateway.com:9999/realms/cvhome/protocol/openid-connect/token
Content-Type: application/x-www-form-urlencoded

client_id = microservice-app &
client_secret = r1nuVn4HefusLGwHIeRxbdOzdTZLEMvQ &
grant_type = password &
username = microservice-gateway
    &
password = microservice-gateway

> {%
    client.global.set("access_token", response.body.access_token)
%}


### order a domain certificate
POST http://localhost:8082/api/v1/acm/order
Content-Type: application/json
Authorization: Bearer {{access_token}}

{
  "domain": {
    "domain": "gateway.com"
  },
  "challengeValidationType": "Dns01"
}

### order a domain certificate xyz.asrevo.com as dns
POST http://localhost:8082/api/v1/acm/order
Content-Type: application/json
Authorization: Bearer {{access_token}}

{
  "domain": {
    "domain": "xaayz.asrevo.com"
  },
  "challengeValidationType": "Dns01"
}



### order a domain certificate xyz.asrevo.com as http
POST http://localhost:8082/api/v1/acm/order
Content-Type: application/json
Authorization: Bearer {{access_token}}

{
  "domain": {
    "domain": "xyz.asrevo.com"
  },
  "challengeValidationType": "Http01"
}



### order a domain certificate xyz.asrevo.com as TlsAlpn01
POST http://localhost:8082/api/v1/acm/order
Content-Type: application/json
Authorization: Bearer {{access_token}}

{
  "domain": {
    "domain": "xywz.asrevo.com"
  },
  "challengeValidationType": "TlsAlpn01"
}


### ask validate certificate xyz.asrevo.com
POST http://localhost:8082/api/v1/acm/validate
Content-Type: application/json
Authorization: Bearer {{access_token}}

{
  "id": {
    "id": "6512c464929f5771f02d4646"
  }
}


### downoad a domain crt file
POST http://localhost:8082/api/v1/acm/domain-certificate-file?domain=gateway.com&fileType=CRT
Authorization: Bearer {{access_token}}


### downoad a domain key file
POST http://localhost:8082/api/v1/acm/domain-certificate-file?domain=gateway.com&fileType=KEY
Authorization: Bearer {{access_token}}


### downoad a domain csr file
POST http://localhost:8082/api/v1/acm/domain-certificate-file?domain=gateway.com&fileType=CSR
Authorization: Bearer {{access_token}}
