[versions]
springBoot = "4.0.1"
springDataCommons = "4.0.1"
springDependencyManagement = "1.1.7"
springWeb = "7.0.2"
springCloudCommons = "5.0.0"
springdoc = "3.0.1"
hibernate = "7.2.0.Final"
postgresql = "42.7.8"
jakartaPersistenceApi = "3.2.0"
jakartaServletApi = "6.1.0"
lombok = "1.18.42"
lombokMapstructBinding = "0.2.0"
mapstruct = "1.6.3"
jackson = "3.0.3"
fasterxml = "2.19.0"
swagger = "2.2.8"
testcontainers = "1.19.7"
testcontainersjupiter = "2.0.3"
caffeine = "3.2.3"
mongodbBson = "5.6.2"
dnsjava = "3.6.3"
awsSdk = "2.41.5"
stripe = "31.1.0"
gson = "2.13.2"
jakartaValidationApi = "3.1.1"
apacheCommonsLang3 = "3.20.0"
commonsIo = "2.20.0"
commonsValidator = "1.10.1"
hamcrestRecord = "1.0.0"
commonsBeanutils = "1.10.1"
nodeGradle = "7.0.2"

[libraries]
spring-boot-starter-web = { module = "org.springframework.boot:spring-boot-starter-web", version.ref = "springBoot" }
spring-boot-starter-security = { module = "org.springframework.boot:spring-boot-starter-security", version.ref = "springBoot" }
spring-boot-starter-webflux = { module = "org.springframework.boot:spring-boot-starter-webflux", version.ref = "springBoot" }
spring-boot-starter-validation = { module = "org.springframework.boot:spring-boot-starter-validation", version.ref = "springBoot" }
spring-boot-starter-actuator = { module = "org.springframework.boot:spring-boot-starter-actuator", version.ref = "springBoot" }
spring-boot-starter-jackson = { module = "org.springframework.boot:spring-boot-starter-jackson", version.ref = "springBoot" }
spring-boot-starter-oauth2-client = { module = "org.springframework.boot:spring-boot-starter-oauth2-client", version.ref = "springBoot" }
spring-boot-starter-security-oauth2-resource-server = { module = "org.springframework.boot:spring-boot-starter-security-oauth2-resource-server", version.ref = "springBoot" }
spring-boot-starter-oauth2-authorization-server = { module = "org.springframework.boot:spring-boot-starter-oauth2-authorization-server", version.ref = "springBoot" }
spring-boot-starter-thymeleaf = { module = "org.springframework.boot:spring-boot-starter-thymeleaf", version.ref = "springBoot" }
spring-boot-starter-session-jdbc = { module = "org.springframework.boot:spring-boot-starter-session-jdbc", version.ref = "springBoot" }
spring-boot-starter-data-jdbc = { module = "org.springframework.boot:spring-boot-starter-data-jdbc", version.ref = "springDataCommons" }
spring-boot-starter-data-jpa = { module = "org.springframework.boot:spring-boot-starter-data-jpa", version.ref = "springDataCommons" }
spring-boot-starter-test = { module = "org.springframework.boot:spring-boot-starter-test", version.ref = "springBoot" }
spring-boot-starter-actuator-test = { module = "org.springframework.boot:spring-boot-starter-actuator-test", version.ref = "springBoot" }
spring-boot-starter-data-jpa-test = { module = "org.springframework.boot:spring-boot-starter-data-jpa-test", version.ref = "springBoot" }
spring-boot-starter-security-oauth2-authorization-server-test = { module = "org.springframework.boot:spring-boot-starter-security-oauth2-authorization-server-test", version.ref = "springBoot" }
spring-boot-starter-security-oauth2-resource-server-test = { module = "org.springframework.boot:spring-boot-starter-security-oauth2-resource-server-test", version.ref = "springBoot" }
spring-boot-starter-session-jdbc-test = { module = "org.springframework.boot:spring-boot-starter-session-jdbc-test", version.ref = "springBoot" }
spring-boot-starter-thymeleaf-test = { module = "org.springframework.boot:spring-boot-starter-thymeleaf-test", version.ref = "springBoot" }
spring-boot-starter-validation-test = { module = "org.springframework.boot:spring-boot-starter-validation-test", version.ref = "springBoot" }
spring-boot-starter-webmvc-test = { module = "org.springframework.boot:spring-boot-starter-webmvc-test", version.ref = "springBoot" }
spring-boot-testcontainers = { module = "org.springframework.boot:spring-boot-testcontainers", version.ref = "springBoot" }
spring-boot-starter-cache = { module = "org.springframework.boot:spring-boot-starter-cache", version.ref = "springBoot" }

spring-boot-starter-restclient = { module = "org.springframework.boot:spring-boot-starter-restclient", version.ref = "springBoot" }
spring-boot-starter-restclient-test = { module = "org.springframework.boot:spring-boot-starter-restclient-test", version.ref = "springBoot" }

io-opentelemetry-instrumentation-opentelemetry-spring-boot-starter = { module = "io.opentelemetry.instrumentation:opentelemetry-spring-boot-starter"}
spring-boot-starter-opentelemetry = { module = "org.springframework.boot:spring-boot-starter-opentelemetry"}

spring-cloud-starter = { module = "org.springframework.cloud:spring-cloud-starter", version.ref = "springCloudCommons" }
spring-cloud-starter-gateway-server-webflux = { module = "org.springframework.cloud:spring-cloud-starter-gateway-server-webflux", version.ref = "springCloudCommons" }
spring-cloud-starter-loadbalancer = { module = "org.springframework.cloud:spring-cloud-starter-loadbalancer", version.ref = "springCloudCommons" }
spring-cloud-stream = { module = "org.springframework.cloud:spring-cloud-stream", version.ref = "springCloudCommons" }
spring-cloud-commons = { module = "org.springframework.cloud:spring-cloud-commons", version.ref = "springCloudCommons" }
spring-cloud-gateway-server-webflux = { module = "org.springframework.cloud:spring-cloud-gateway-server-webflux", version.ref = "springCloudCommons" }


spring-security-test = { module = "org.springframework.security:spring-security-test" }
spring-web = { module = "org.springframework:spring-web", version.ref = "springWeb" }
spring-webmvc = { module = "org.springframework:spring-webmvc", version.ref = "springWeb" }
spring-webflux = { module = "org.springframework:spring-webflux", version.ref = "springWeb" }
spring-data-jpa = { module = "org.springframework.data:spring-data-jpa", version.ref = "springDataCommons" }
spring-data-commons = { module = "org.springframework.data:spring-data-commons", version.ref = "springDataCommons" }
spring-data-relational = { module = "org.springframework.data:spring-data-relational", version.ref = "springDataCommons" }

lombok = { module = "org.projectlombok:lombok", version.ref = "lombok" }
lombok-mapstruct-binding = { module = "org.projectlombok:lombok-mapstruct-binding", version.ref = "lombokMapstructBinding" }

jackson-databind = { module = "tools.jackson.core:jackson-databind", version.ref = "jackson" }
jackson-core = { module = "tools.jackson.core:jackson-core", version.ref = "jackson" }
jackson-annotations = { module = "com.fasterxml.jackson.core:jackson-annotations", version.ref = "fasterxml" }

springdoc-openapi-starter-webflux-ui = { module = "org.springdoc:springdoc-openapi-starter-webflux-ui", version.ref = "springdoc" }
springdoc-openapi-starter-webmvc-ui = { module = "org.springdoc:springdoc-openapi-starter-webmvc-ui", version.ref = "springdoc" }

swagger-models = { module = "io.swagger.core.v3:swagger-models", version.ref = "swagger" }

mapstruct = { module = "org.mapstruct:mapstruct", version.ref = "mapstruct" }
mapstruct-processor = { module = "org.mapstruct:mapstruct-processor", version.ref = "mapstruct" }

caffeine = { module = "com.github.ben-manes.caffeine:caffeine", version.ref = "caffeine" }

testcontainers-junit-jupiter = { module = "org.testcontainers:testcontainers-junit-jupiter", version.ref = "testcontainersjupiter" }
testcontainers-postgresql = { module = "org.testcontainers:postgresql", version.ref = "testcontainers" }
testcontainers-minio = { module = "org.testcontainers:minio", version.ref = "testcontainers" }

reactor-test = { module = "io.projectreactor:reactor-test" }
junit-platform-launcher = { module = "org.junit.platform:junit-platform-launcher" }

mongodb-bson = { module = "org.mongodb:bson", version.ref = "mongodbBson" }
dnsjava = { module = "dnsjava:dnsjava", version.ref = "dnsjava" }
aws-sdk-servicediscovery = { module = "software.amazon.awssdk:servicediscovery", version.ref = "awsSdk" }
aws-sdk-s3 = { module = "software.amazon.awssdk:s3", version.ref = "awsSdk" }
postgresql = { module = "org.postgresql:postgresql", version.ref = "postgresql" }
stripe-java = { module = "com.stripe:stripe-java", version.ref = "stripe" }
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
jakarta-validation-api = { module = "jakarta.validation:jakarta.validation-api", version.ref = "jakartaValidationApi" }
jakarta-persistence-api = { module = "jakarta.persistence:jakarta.persistence-api", version.ref = "jakartaPersistenceApi" }
jakarta-servlet-api = { module = "jakarta.servlet:jakarta.servlet-api", version.ref = "jakartaServletApi" }
apache-commons-lang3 = { module = "org.apache.commons:commons-lang3", version.ref = "apacheCommonsLang3" }
hibernate-core = { module = "org.hibernate.orm:hibernate-core", version.ref = "hibernate" }
thymeleaf-extras-springsecurity6 = { module = "org.thymeleaf.extras:thymeleaf-extras-springsecurity6" }
commons-io = { module = "commons-io:commons-io", version.ref = "commonsIo" }
commons-validator = { module = "commons-validator:commons-validator", version.ref = "commonsValidator" }
hamcrest-record = { module = "rocks.cleancode:hamcrest-record", version.ref = "hamcrestRecord" }
commons-beanutils = { module = "commons-beanutils:commons-beanutils", version.ref = "commonsBeanutils" }

[plugins]
spring-boot = { id = "org.springframework.boot", version.ref = "springBoot" }
spring-dependency-management = { id = "io.spring.dependency-management", version.ref = "springDependencyManagement" }
hibernate-orm = { id = "org.hibernate.orm", version.ref = "hibernate" }
groovy-gradle-plugin = { id = "groovy-gradle-plugin" }
java-library-conventions = { id = "com.asrevo.java-library-conventions" }
java-application-conventions = { id = "com.asrevo.java-application-conventions" }
node = { id = "com.github.node-gradle.node", version.ref = "nodeGradle" }
docker-conventions = { id = "com.asrevo.docker-conventions" }
ui-conventions = { id = "com.asrevo.ui-conventions" }
