spring:
  application:
    name: gateway
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/gatewaydb
    username: postgres
    password: password
  cloud:
    local:
      discovery:
        services:
          user:
            - url: "http://localhost:8081"
              metadata:
                service-name: user
                instance: user-1
          certificate-manager:
            - url: "http://localhost:8082"
              metadata:
                service-name: certificate-manager
                instance: certificate-manager-1
          auth:
            - url: "http://localhost:9999"
              metadata:
                service-name: auth
                instance: auth-1
          ui:
            - url: "http://localhost:4200"
              metadata:
                service-name: ui
                instance: ui-1
          gateway:
            - url: "http://localhost:8080"
              metadata:
                service-name: gateway
                instance: gateway-1
    gateway:
      discovery:
        locator:
          enabled: true
      default-filters:
        - MapHostAsRequestParam=userId
        - TokenRelay
        - PreserveHostHeader
      routes:
        - id: user
          uri: lb://user
          predicates:
            - Path=/user/**
          filters:
            - StripPrefix=1
        - id: certificate-manager
          uri: lb://certificate-manager
          predicates:
            - Path=/certificate-manager/**
          filters:
            - StripPrefix=1
        - id: auth
          uri: lb://auth
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1
        - id: ui
          uri: lb://ui:4200
          predicates:
            - Host={domain}.{x},{sub}.{domain}.{x}
  security:
    oauth2:
      client:
        registration:
          microservice:
            provider: microservice
            client-id: microservice-app
            client-secret: r1nuVn4HefusLGwHIeRxbdOzdTZLEMvQ
            authorization-grant-type: password
          keycloak:
            client-id: web-app
            client-authentication-method: client_secret_basic
            authorization-grant-type: authorization_code
            scope: openid, profile, email
            redirect-uri: https://wl.asrevo.com:8443/login/oauth2/code/keycloak
            provider: keycloak
        provider:
          microservice:
            token-uri: http://localhost:9999/realms/cvhome/protocol/openid-connect/token?username=microservice-gateway&password=microservice-gateway
          keycloak:
            issuer-uri: http://localhost:9999/realms/cvhome
            jwk-set-uri: http://localhost:9999/realms/cvhome/protocol/openid-connect/certs
            authorization-uri: http://localhost:9999/realms/cvhome/protocol/openid-connect/auth
            token-uri: http://localhost:9999/realms/cvhome/protocol/openid-connect/token
server:
  port: 8443
info:
  app:
    name: ${spring.application.name}
management:
  info:
    env:
      enabled: true
    os:
      enabled: true
  metrics:
    tags:
      application: ${spring.application.name}
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: [ '*' ]
com:
  asrevo:
    cvhome:
      ssl:
        default-domain: "wl.asrevo.com"
        sub-domain-fallback: "*.wl.asrevo.com"
logging:
  level:
    org.springframework.boot: debug
    org.springframework.web: debug
    org.springframework.security: debug
    reactor.netty.http: debug