spring:
  application:
    name: gateway
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/gatewaydb
    username: postgres
    password: password
  cloud:
    gateway:
      default-filters:
        - MapHostAsRequestParam=userId
      routes:
        - id: user
          uri: http://localhost:8081
          predicates:
            - Path=/user/**
          filters:
            - StripPrefix=1
        - id: ui
          uri: http://localhost:4200
          predicates:
            - Host={domain}.{x},{sub}.{domain}.{x}
server:
  port: 8443
info:
  app:
    name: ${spring.application.name}
management:
  info:
    env:
      enabled: true
    os:
      enabled: true
  metrics:
    tags:
      application: ${spring.application.name}
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: [ '*' ]