spring:
  application:
    name: gateway
  cloud:
    gateway:
      default-filters:
        - MapHostAsRequestParam=userId
      routes:
        - id: user
          uri: http://localhost:8081
          predicates:
            - Path=/user/**
          filters:
            - StripPrefix=1
        - id: ui
          uri: http://localhost:4200
          predicates:
            - Host={domain}.{x},{sub}.{domain}.{x}
server:
  port: 8443
