plugins {
    alias(libs.plugins.java.library.conventions)
}

dependencies {
    api project(':store-pod:commons:store-commons')
    api project(':store-pod:catalog:catalog-commons')
    api project(':store-pod:checkout:checkout-external-api')
    api project(':store-pod:merchant:merchant-external-api')
    api project(':store-core:billing:billing-external-api')
    implementation project(':store-pod:commons:store-modules:store-cms-commons')
    compileOnly libs.spring.data.jpa
    compileOnly libs.jakarta.validation.api
    compileOnly libs.jackson.annotations
    compileOnly libs.lombok
    compileOnly libs.apache.commons.lang3
    compileOnly libs.commons.io
    compileOnly libs.hibernate.core
    implementation libs.commons.validator
    compileOnly libs.hibernate.core
    annotationProcessor libs.lombok
}
