plugins {
	id 'com.asrevo.java-library-conventions'
	id("com.diffplug.spotless") version "6.25.0"
}

dependencies {
	api project(':store-pod:store-commons')
	api project(':store-pod:catalog:catalog-commons')
	api project(':store-pod:merchant:merchant-external-api')
	implementation project(':store-pod:store-modules:store-cms-commons')
	compileOnly 'org.springframework.data:spring-data-jpa:3.4.3'
	compileOnly 'jakarta.validation:jakarta.validation-api:3.0.2'
	compileOnly 'com.fasterxml.jackson.core:jackson-annotations:2.18.2'
	compileOnly 'org.projectlombok:lombok:1.18.36'
	compileOnly 'org.apache.commons:commons-lang3:3.17.0'
	compileOnly 'commons-io:commons-io:2.16.1'
	compileOnly 'org.hibernate.orm:hibernate-core:6.6.8.Final'
	implementation 'commons-validator:commons-validator:1.9.0'
	compileOnly 'org.hibernate.orm:hibernate-core:6.6.8.Final'
	annotationProcessor 'org.projectlombok:lombok:1.18.36'
}
