-- Pages beyond the six the store shipped with.
--
-- Demo content for the test store 65f023632bc26470c104b75f (Egypt Car Sales), in every language the store sells in.
-- Generated seed: ids are negative on purpose — content, media and menu ids all come from sequences that
-- only grow upward, so a seed row below zero can never collide with one the running service creates.

-- page: financing (PUBLISHED)
INSERT INTO content.content (content_id, date_created, date_modified, updt_id, code, content_type, sort_order, visible, store_merchant_id, status, publish_at, unpublish_at, version, created_by, updated_by, parent_id, noindex, canonical_url, og_media_id, show_in_footer, placement, starts_at, ends_at, policy_type, meta)
VALUES (-20001, now(), now(), 'seed', 'financing', 'PAGE', 10, true, '65f023632bc26470c104b75f', 'PUBLISHED', null, null, 1, 'seed', 'seed', null, false, null, null, true, null, null, null, null, null)
on conflict (content_id) do nothing;
INSERT INTO content.content_description (description_id, date_created, date_modified, updt_id, description, name, title, meta_description, meta_keywords, meta_title, sef_url, language_code, content_id, state, excerpt, alt_text, cta_label, subtitle)
VALUES (-200001, now(), now(), 'seed', '<h2>خطط التمويل</h2><p>نعمل مع البنك الأهلي المصري وبنك مصر وشركة كونتكت للتمويل. المقدم يبدأ من 20% من قيمة السيارة، ومدة التقسيط تصل إلى ستين شهرًا.</p><ul><li>مقدم 20% — قسط 60 شهرًا</li><li>مقدم 35% — قسط 48 شهرًا بفائدة أقل</li><li>مقدم 50% — قسط 36 شهرًا</li></ul><h2>المستندات المطلوبة</h2><ul><li>صورة بطاقة الرقم القومي سارية</li><li>مفردات مرتب حديثة أو سجل تجاري وبطاقة ضريبية</li><li>كشف حساب بنكي لآخر ستة أشهر</li></ul><p>الموافقة المبدئية تصدر خلال 48 ساعة عمل، والتسليم بعد استكمال الترخيص.</p>', 'التمويل والتقسيط', 'التمويل والتقسيط', 'خطط تقسيط حتى 60 شهرًا بالتعاون مع البنك الأهلي وبنك مصر، مع حاسبة أقساط تقريبية.', 'تمويل, تقسيط, أقساط سيارات', 'التمويل والتقسيط | Egypt Car Sales', 'financing-ar', 'ar', -20001, 'TRANSLATED', null, null, null, null)
on conflict (description_id) do nothing;
INSERT INTO content.content_description (description_id, date_created, date_modified, updt_id, description, name, title, meta_description, meta_keywords, meta_title, sef_url, language_code, content_id, state, excerpt, alt_text, cta_label, subtitle)
VALUES (-200002, now(), now(), 'seed', '<h2>Nos plans de financement</h2><p>Nous travaillons avec la Banque Nationale d''Égypte, Banque Misr et Contact Financial. L''apport démarre à 20 % du prix du véhicule, sur une durée pouvant aller jusqu''à soixante mois.</p><ul><li>Apport 20 % — 60 mensualités</li><li>Apport 35 % — 48 mensualités, taux réduit</li><li>Apport 50 % — 36 mensualités</li></ul><h2>Pièces à fournir</h2><ul><li>Carte nationale d''identité en cours de validité</li><li>Bulletins de salaire récents, ou registre de commerce et carte fiscale</li><li>Relevés bancaires des six derniers mois</li></ul><p>L''accord de principe est rendu sous 48 heures ouvrées ; la livraison suit l''immatriculation.</p>', 'Financement', 'Financement', 'Des plans de financement jusqu''à 60 mois avec la Banque Nationale d''Égypte et Banque Misr.', 'financement, crédit auto, mensualités', 'Financement | Egypt Car Sales', 'financement', 'fr', -20001, 'TRANSLATED', null, null, null, null)
on conflict (description_id) do nothing;

-- page: inspection-report (PUBLISHED)
INSERT INTO content.content (content_id, date_created, date_modified, updt_id, code, content_type, sort_order, visible, store_merchant_id, status, publish_at, unpublish_at, version, created_by, updated_by, parent_id, noindex, canonical_url, og_media_id, show_in_footer, placement, starts_at, ends_at, policy_type, meta)
VALUES (-20002, now(), now(), 'seed', 'inspection-report', 'PAGE', 11, true, '65f023632bc26470c104b75f', 'PUBLISHED', null, null, 1, 'seed', 'seed', null, false, null, null, false, null, null, null, null, null)
on conflict (content_id) do nothing;
INSERT INTO content.content_description (description_id, date_created, date_modified, updt_id, description, name, title, meta_description, meta_keywords, meta_title, sef_url, language_code, content_id, state, excerpt, alt_text, cta_label, subtitle)
VALUES (-200003, now(), now(), 'seed', '<h2>لماذا 150 نقطة؟</h2><p>لأن ما لا يُقاس لا يُباع بثقة. كل سيارة مستعملة تدخل معرضنا تمر على ورشة الفحص في المعادي قبل أن تُعرض.</p><h3>ما يشمله الفحص</h3><ul><li>المحرك وناقل الحركة: ضغط الاسطوانات، تسريبات، حالة الزيوت</li><li>الهيكل: قياس سماكة الطلاء في 18 موضعًا لكشف الإصلاحات</li><li>نظام الفرامل والتعليق والإطارات</li><li>الكهرباء وأنظمة الأمان والوسائد الهوائية</li><li>قراءة كمبيوتر السيارة وسجل الأعطال المخزّنة</li></ul><h3>التقرير</h3><p>يُسلَّم التقرير كاملًا قبل التوقيع، بما فيه الملاحظات السلبية. السيارة التي ترسب في بند سلامة لا تُعرض أصلًا.</p>', 'تقرير الفحص الـ 150 نقطة', 'تقرير الفحص الـ 150 نقطة', 'كل سيارة مستعملة تمر بفحص من 150 نقطة قبل عرضها، والتقرير متاح لك قبل الشراء.', 'فحص سيارات, سيارات مستعملة, تقرير فني', 'تقرير الفحص | Egypt Car Sales', 'inspection-report-ar', 'ar', -20002, 'TRANSLATED', null, null, null, null)
on conflict (description_id) do nothing;
INSERT INTO content.content_description (description_id, date_created, date_modified, updt_id, description, name, title, meta_description, meta_keywords, meta_title, sef_url, language_code, content_id, state, excerpt, alt_text, cta_label, subtitle)
VALUES (-200004, now(), now(), 'seed', '<h2>Pourquoi 150 points ?</h2><p>Parce qu''on ne vend pas en confiance ce qu''on n''a pas mesuré. Chaque véhicule d''occasion passe par l''atelier de Maadi avant d''être exposé.</p><h3>Ce que couvre l''inspection</h3><ul><li>Moteur et boîte : compression, fuites, état des huiles</li><li>Carrosserie : épaisseur de peinture relevée en 18 points pour détecter les reprises</li><li>Freinage, suspension et pneumatiques</li><li>Électricité, équipements de sécurité et airbags</li><li>Lecture du calculateur et des défauts mémorisés</li></ul><h3>Le rapport</h3><p>Il est remis intégralement avant signature, remarques négatives comprises. Un véhicule recalé sur un point de sécurité n''est pas mis en vente.</p>', 'Le rapport d''inspection en 150 points', 'Le rapport d''inspection en 150 points', 'Chaque véhicule d''occasion passe une inspection en 150 points ; le rapport vous est remis avant l''achat.', 'inspection, occasion, rapport technique', 'Rapport d''inspection | Egypt Car Sales', 'rapport-inspection', 'fr', -20002, 'TRANSLATED', null, null, null, null)
on conflict (description_id) do nothing;

-- page: trade-in (PUBLISHED)
INSERT INTO content.content (content_id, date_created, date_modified, updt_id, code, content_type, sort_order, visible, store_merchant_id, status, publish_at, unpublish_at, version, created_by, updated_by, parent_id, noindex, canonical_url, og_media_id, show_in_footer, placement, starts_at, ends_at, policy_type, meta)
VALUES (-20003, now(), now(), 'seed', 'trade-in', 'PAGE', 12, true, '65f023632bc26470c104b75f', 'PUBLISHED', null, null, 1, 'seed', 'seed', null, false, null, null, true, null, null, null, null, null)
on conflict (content_id) do nothing;
INSERT INTO content.content_description (description_id, date_created, date_modified, updt_id, description, name, title, meta_description, meta_keywords, meta_title, sef_url, language_code, content_id, state, excerpt, alt_text, cta_label, subtitle)
VALUES (-200005, now(), now(), 'seed', '<h2>كيف يعمل الاستبدال</h2><ol><li>احجز موعد تقييم مجاني في فرع مدينة نصر أو المعادي</li><li>الفحص يستغرق ساعة، والعرض ساري لسبعة أيام</li><li>إن قبلت، نخصم القيمة مباشرة من السيارة الجديدة</li></ol><h2>ما يرفع قيمة سيارتك</h2><ul><li>سجل صيانة كامل من مركز معتمد</li><li>عدد كيلومترات منطقي بالنسبة لسنة الصنع</li><li>هيكل خالٍ من إصلاحات الحوادث</li></ul><p>نتولى إجراءات نقل الملكية بالكامل، بما فيها المرور.</p>', 'استبدال سيارتك', 'استبدال سيارتك', 'قيّم سيارتك القديمة واخصم قيمتها من سيارتك الجديدة في نفس اليوم.', 'استبدال, تقييم سيارات, بيع سيارتك', 'استبدال سيارتك | Egypt Car Sales', 'trade-in-ar', 'ar', -20003, 'TRANSLATED', null, null, null, null)
on conflict (description_id) do nothing;
INSERT INTO content.content_description (description_id, date_created, date_modified, updt_id, description, name, title, meta_description, meta_keywords, meta_title, sef_url, language_code, content_id, state, excerpt, alt_text, cta_label, subtitle)
VALUES (-200006, now(), now(), 'seed', '<h2>Comment se passe une reprise</h2><ol><li>Prenez rendez-vous pour une estimation gratuite à Nasr City ou à Maadi</li><li>L''expertise dure une heure ; l''offre reste valable sept jours</li><li>Si vous l''acceptez, la valeur est déduite du prix de votre nouvelle voiture</li></ol><h2>Ce qui fait monter l''estimation</h2><ul><li>Un carnet d''entretien complet dans un centre agréé</li><li>Un kilométrage cohérent avec l''année</li><li>Une carrosserie sans reprise accidentelle</li></ul><p>Nous prenons en charge la totalité du transfert de propriété, formalités administratives comprises.</p>', 'Reprise de votre véhicule', 'Reprise de votre véhicule', 'Faites évaluer votre véhicule et déduisez sa valeur de votre prochaine voiture, le jour même.', 'reprise, estimation, revendre sa voiture', 'Reprise | Egypt Car Sales', 'reprise', 'fr', -20003, 'TRANSLATED', null, null, null, null)
on conflict (description_id) do nothing;

-- page: showrooms (PUBLISHED)
INSERT INTO content.content (content_id, date_created, date_modified, updt_id, code, content_type, sort_order, visible, store_merchant_id, status, publish_at, unpublish_at, version, created_by, updated_by, parent_id, noindex, canonical_url, og_media_id, show_in_footer, placement, starts_at, ends_at, policy_type, meta)
VALUES (-20004, now(), now(), 'seed', 'showrooms', 'PAGE', 13, true, '65f023632bc26470c104b75f', 'PUBLISHED', null, null, 1, 'seed', 'seed', (select content_id from content.content where store_merchant_id = '65f023632bc26470c104b75f' and code = 'location'), false, null, null, false, null, null, null, null, null)
on conflict (content_id) do nothing;
INSERT INTO content.content_description (description_id, date_created, date_modified, updt_id, description, name, title, meta_description, meta_keywords, meta_title, sef_url, language_code, content_id, state, excerpt, alt_text, cta_label, subtitle)
VALUES (-200007, now(), now(), 'seed', '<h2>فروعنا</h2><p>هذه الصفحة تابعة لصفحة « موقعنا »، وتستخدم أيضًا للتحقق من مسار التنقل: الرئيسية › موقعنا › فروعنا.</p><ul><li><strong>مدينة نصر</strong> — 123 شارع أوتو رود — يوميًا 10ص إلى 9م</li><li><strong>المعادي</strong> — ورشة الفحص ومركز الخدمة — السبت إلى الخميس 9ص إلى 6م</li><li><strong>الشيخ زايد</strong> — معرض السيارات الكهربائية — يوميًا 11ص إلى 10م</li></ul>', 'فروعنا', 'فروعنا', 'ثلاثة معارض في القاهرة الكبرى: مدينة نصر، المعادي، والشيخ زايد.', 'فروع, معارض سيارات, القاهرة', 'فروعنا | Egypt Car Sales', 'showrooms-ar', 'ar', -20004, 'TRANSLATED', null, null, null, null)
on conflict (description_id) do nothing;
INSERT INTO content.content_description (description_id, date_created, date_modified, updt_id, description, name, title, meta_description, meta_keywords, meta_title, sef_url, language_code, content_id, state, excerpt, alt_text, cta_label, subtitle)
VALUES (-200008, now(), now(), 'seed', '<h2>Nos showrooms</h2><p>Cette page est rattachée à « Notre emplacement », ce qui en fait aussi le contrôle du fil d''Ariane : Accueil › Notre emplacement › Nos showrooms.</p><ul><li><strong>Nasr City</strong> — 123 Auto Road — tous les jours, 10h–21h</li><li><strong>Maadi</strong> — atelier d''inspection et service — samedi au jeudi, 9h–18h</li><li><strong>Sheikh Zayed</strong> — showroom véhicules électriques — tous les jours, 11h–22h</li></ul>', 'Nos showrooms', 'Nos showrooms', 'Trois showrooms au Grand Caire : Nasr City, Maadi et Sheikh Zayed.', 'showroom, concession, Le Caire', 'Nos showrooms | Egypt Car Sales', 'showrooms', 'fr', -20004, 'TRANSLATED', null, null, null, null)
on conflict (description_id) do nothing;

-- page: ev-charging (PUBLISHED)
INSERT INTO content.content (content_id, date_created, date_modified, updt_id, code, content_type, sort_order, visible, store_merchant_id, status, publish_at, unpublish_at, version, created_by, updated_by, parent_id, noindex, canonical_url, og_media_id, show_in_footer, placement, starts_at, ends_at, policy_type, meta)
VALUES (-20005, now(), now(), 'seed', 'ev-charging', 'PAGE', 14, true, '65f023632bc26470c104b75f', 'PUBLISHED', null, null, 1, 'seed', 'seed', null, false, 'https://org2-store2.asrevo.com/content/ev-charging', -290002, true, null, null, null, null, null)
on conflict (content_id) do nothing;
INSERT INTO content.content_description (description_id, date_created, date_modified, updt_id, description, name, title, meta_description, meta_keywords, meta_title, sef_url, language_code, content_id, state, excerpt, alt_text, cta_label, subtitle)
VALUES (-200009, now(), now(), 'seed', '<h2>الشاحن المنزلي</h2><p>مع كل سيارة كهربائية نركّب شاحنًا منزليًا 7 كيلوواط مجانًا داخل القاهرة الكبرى، ويشمل ذلك الكابل ولوحة الحماية.</p><h2>الشحن على الطريق</h2><p>شبكة الشحن السريع في مصر تجاوزت 320 نقطة، أغلبها على محاور القاهرة–الإسكندرية والقاهرة–العين السخنة.</p><ul><li>شحن منزلي 7 كيلوواط: من 20% إلى 80% في نحو ست ساعات</li><li>شحن سريع 60 كيلوواط: نفس المدى في أربعين دقيقة تقريبًا</li></ul><p>هذه الصفحة تحمل رابطًا قانونيًا وصورة Open Graph للتحقق من بيانات الـ SEO في المتجر.</p>', 'شحن السيارات الكهربائية', 'شحن السيارات الكهربائية', 'شاحن منزلي مركّب مجانًا مع كل سيارة كهربائية، وخريطة نقاط الشحن في مصر.', 'شحن كهربائي, سيارات كهربائية, شاحن منزلي', 'شحن السيارات الكهربائية | Egypt Car Sales', 'ev-charging-ar', 'ar', -20005, 'TRANSLATED', null, null, null, null)
on conflict (description_id) do nothing;
INSERT INTO content.content_description (description_id, date_created, date_modified, updt_id, description, name, title, meta_description, meta_keywords, meta_title, sef_url, language_code, content_id, state, excerpt, alt_text, cta_label, subtitle)
VALUES (-200010, now(), now(), 'seed', '<h2>La borne domestique</h2><p>Chaque véhicule électrique est livré avec une borne domestique de 7 kW installée gratuitement dans le Grand Caire, câble et tableau de protection compris.</p><h2>Recharger sur la route</h2><p>Le réseau de charge rapide égyptien dépasse 320 points, concentrés sur les axes Le Caire–Alexandrie et Le Caire–Aïn Sokhna.</p><ul><li>Borne domestique 7 kW : de 20 % à 80 % en six heures environ</li><li>Charge rapide 60 kW : la même plage en une quarantaine de minutes</li></ul><p>Cette page porte une URL canonique et une image Open Graph, ce qui en fait le contrôle du rendu SEO.</p>', 'Recharge des véhicules électriques', 'Recharge des véhicules électriques', 'Borne domestique installée gratuitement avec chaque véhicule électrique, et la carte des points de charge en Égypte.', 'recharge, véhicule électrique, borne domestique', 'Recharge électrique | Egypt Car Sales', 'recharge-electrique', 'fr', -20005, 'TRANSLATED', null, null, null, null)
on conflict (description_id) do nothing;

-- page: fleet-sales (PUBLISHED)
INSERT INTO content.content (content_id, date_created, date_modified, updt_id, code, content_type, sort_order, visible, store_merchant_id, status, publish_at, unpublish_at, version, created_by, updated_by, parent_id, noindex, canonical_url, og_media_id, show_in_footer, placement, starts_at, ends_at, policy_type, meta)
VALUES (-20006, now(), now(), 'seed', 'fleet-sales', 'PAGE', 15, true, '65f023632bc26470c104b75f', 'PUBLISHED', null, null, 1, 'seed', 'seed', null, true, null, null, false, null, null, null, null, null)
on conflict (content_id) do nothing;
INSERT INTO content.content_description (description_id, date_created, date_modified, updt_id, description, name, title, meta_description, meta_keywords, meta_title, sef_url, language_code, content_id, state, excerpt, alt_text, cta_label, subtitle)
VALUES (-200011, now(), now(), 'seed', '<h2>عروض الشركات</h2><p>هذه الصفحة مُعلَّمة بـ <code>noindex</code>: يجب أن تظهر داخل المتجر لكن تختفي من خريطة الموقع. هذا هو اختبار العلامة.</p><ul><li>خصم يبدأ من خمس سيارات</li><li>عقود صيانة ثلاث سنوات</li><li>سيارة بديلة أثناء الصيانة</li></ul>', 'مبيعات الأساطيل', 'مبيعات الأساطيل', 'صفحة موجّهة لعملاء الشركات، ومستبعدة عمدًا من الفهرسة.', 'أساطيل, شركات, عقود', 'مبيعات الأساطيل | Egypt Car Sales', 'fleet-sales-ar', 'ar', -20006, 'TRANSLATED', null, null, null, null)
on conflict (description_id) do nothing;
INSERT INTO content.content_description (description_id, date_created, date_modified, updt_id, description, name, title, meta_description, meta_keywords, meta_title, sef_url, language_code, content_id, state, excerpt, alt_text, cta_label, subtitle)
VALUES (-200012, now(), now(), 'seed', '<h2>Offres entreprises</h2><p>Cette page est marquée <code>noindex</code> : elle doit s''afficher dans la boutique mais disparaître du sitemap. C''est le contrôle du drapeau.</p><ul><li>Remise à partir de cinq véhicules</li><li>Contrats d''entretien sur trois ans</li><li>Véhicule de remplacement pendant les immobilisations</li></ul>', 'Ventes aux flottes', 'Ventes aux flottes', 'Une page destinée aux clients entreprises, volontairement exclue de l''indexation.', 'flotte, entreprise, contrat', 'Ventes aux flottes | Egypt Car Sales', 'ventes-flottes', 'fr', -20006, 'TRANSLATED', null, null, null, null)
on conflict (description_id) do nothing;

-- page: summer-offers (SCHEDULED)
INSERT INTO content.content (content_id, date_created, date_modified, updt_id, code, content_type, sort_order, visible, store_merchant_id, status, publish_at, unpublish_at, version, created_by, updated_by, parent_id, noindex, canonical_url, og_media_id, show_in_footer, placement, starts_at, ends_at, policy_type, meta)
VALUES (-20007, now(), now(), 'seed', 'summer-offers', 'PAGE', 16, true, '65f023632bc26470c104b75f', 'SCHEDULED', now() + interval '21 days', null, 1, 'seed', 'seed', null, false, null, null, false, null, null, null, null, null)
on conflict (content_id) do nothing;
INSERT INTO content.content_description (description_id, date_created, date_modified, updt_id, description, name, title, meta_description, meta_keywords, meta_title, sef_url, language_code, content_id, state, excerpt, alt_text, cta_label, subtitle)
VALUES (-200013, now(), now(), 'seed', '<h2>عروض الصيف</h2><p>هذه الصفحة بحالة <strong>SCHEDULED</strong> وتُنشر بعد ثلاثة أسابيع. يجب أن تظهر في لوحة التحكم وتعطي 404 في المتجر.</p>', 'عروض الصيف (مجدولة)', 'عروض الصيف (مجدولة)', 'صفحة مجدولة: يجب ألا تظهر في المتجر قبل موعد نشرها.', 'عروض, صيف', 'عروض الصيف | Egypt Car Sales', 'summer-offers-ar', 'ar', -20007, 'TRANSLATED', null, null, null, null)
on conflict (description_id) do nothing;
INSERT INTO content.content_description (description_id, date_created, date_modified, updt_id, description, name, title, meta_description, meta_keywords, meta_title, sef_url, language_code, content_id, state, excerpt, alt_text, cta_label, subtitle)
VALUES (-200014, now(), now(), 'seed', '<h2>Offres d''été</h2><p>Cette page est en statut <strong>SCHEDULED</strong>, publication dans trois semaines. Visible dans la console, 404 côté boutique.</p>', 'Offres d''été (programmée)', 'Offres d''été (programmée)', 'Page programmée : elle ne doit pas apparaître avant sa date de publication.', 'offres, été', 'Offres d''été | Egypt Car Sales', 'offres-ete', 'fr', -20007, 'TRANSLATED', null, null, null, null)
on conflict (description_id) do nothing;

-- page: price-list-2024 (ARCHIVED)
INSERT INTO content.content (content_id, date_created, date_modified, updt_id, code, content_type, sort_order, visible, store_merchant_id, status, publish_at, unpublish_at, version, created_by, updated_by, parent_id, noindex, canonical_url, og_media_id, show_in_footer, placement, starts_at, ends_at, policy_type, meta)
VALUES (-20008, now(), now(), 'seed', 'price-list-2024', 'PAGE', 17, false, '65f023632bc26470c104b75f', 'ARCHIVED', null, null, 1, 'seed', 'seed', null, false, null, null, false, null, null, null, null, null)
on conflict (content_id) do nothing;
INSERT INTO content.content_description (description_id, date_created, date_modified, updt_id, description, name, title, meta_description, meta_keywords, meta_title, sef_url, language_code, content_id, state, excerpt, alt_text, cta_label, subtitle)
VALUES (-200015, now(), now(), 'seed', '<h2>قائمة أسعار 2024</h2><p>مؤرشفة واستُبدلت بقائمة 2026. يجب أن تبقى غير مرئية في المتجر.</p>', 'قائمة أسعار 2024 (مؤرشفة)', 'قائمة أسعار 2024 (مؤرشفة)', null, null, null, 'price-list-2024-ar', 'ar', -20008, 'TRANSLATED', null, null, null, null)
on conflict (description_id) do nothing;
INSERT INTO content.content_description (description_id, date_created, date_modified, updt_id, description, name, title, meta_description, meta_keywords, meta_title, sef_url, language_code, content_id, state, excerpt, alt_text, cta_label, subtitle)
VALUES (-200016, now(), now(), 'seed', '<h2>Tarifs 2024</h2><p>Archivé, remplacé par la grille 2026. Doit rester invisible côté boutique.</p>', 'Tarifs 2024 (archivé)', 'Tarifs 2024 (archivé)', null, null, null, 'tarifs-2024', 'fr', -20008, 'TRANSLATED', null, null, null, null)
on conflict (description_id) do nothing;

-- page: insurance-partners (DRAFT)
INSERT INTO content.content (content_id, date_created, date_modified, updt_id, code, content_type, sort_order, visible, store_merchant_id, status, publish_at, unpublish_at, version, created_by, updated_by, parent_id, noindex, canonical_url, og_media_id, show_in_footer, placement, starts_at, ends_at, policy_type, meta)
VALUES (-20009, now(), now(), 'seed', 'insurance-partners', 'PAGE', 18, true, '65f023632bc26470c104b75f', 'DRAFT', null, null, 1, 'seed', 'seed', null, false, null, null, false, null, null, null, null, null)
on conflict (content_id) do nothing;
INSERT INTO content.content_description (description_id, date_created, date_modified, updt_id, description, name, title, meta_description, meta_keywords, meta_title, sef_url, language_code, content_id, state, excerpt, alt_text, cta_label, subtitle)
VALUES (-200017, now(), now(), 'seed', '<h2>شركاء التأمين</h2><p>مسودة قيد الكتابة. غير مرئية في المتجر، وقابلة للتحرير في لوحة التحكم.</p>', 'شركاء التأمين (مسودة)', 'شركاء التأمين (مسودة)', null, null, null, 'insurance-partners-ar', 'ar', -20009, 'DRAFT', null, null, null, null)
on conflict (description_id) do nothing;
INSERT INTO content.content_description (description_id, date_created, date_modified, updt_id, description, name, title, meta_description, meta_keywords, meta_title, sef_url, language_code, content_id, state, excerpt, alt_text, cta_label, subtitle)
VALUES (-200018, now(), now(), 'seed', '<h2>Partenaires assurance</h2><p>Brouillon en cours. Invisible côté boutique, éditable dans la console.</p>', 'Partenaires assurance (brouillon)', 'Partenaires assurance (brouillon)', null, null, null, 'partenaires-assurance', 'fr', -20009, 'DRAFT', null, null, null, null)
on conflict (description_id) do nothing;

-- pages the store already had, promoted into the footer
UPDATE content.content SET show_in_footer = true
 WHERE store_merchant_id = '65f023632bc26470c104b75f' AND content_type = 'PAGE' AND code IN ('about-us', 'contact-us', 'location');
