-- Legal policies, each with a live version.
--
-- Demo content for the test store 65f023632bc26470c104b75f (Egypt Car Sales), in every language the store sells in.
-- Generated seed: ids are negative on purpose — content, media and menu ids all come from sequences that
-- only grow upward, so a seed row below zero can never collide with one the running service creates.

-- policy: PRIVACY
INSERT INTO content.content (content_id, date_created, date_modified, updt_id, code, content_type, sort_order, visible, store_merchant_id, status, publish_at, unpublish_at, version, created_by, updated_by, parent_id, noindex, canonical_url, og_media_id, show_in_footer, placement, starts_at, ends_at, policy_type, meta)
VALUES (-20010, now(), now(), 'seed', 'privacy-policy', 'POLICY', 100, true, '65f023632bc26470c104b75f', 'PUBLISHED', null, null, 1, 'seed', 'seed', null, false, null, null, false, null, null, null, 'PRIVACY', '{"jurisdiction": null, "requiresAcceptance": false, "notifyCustomers": false, "displayAt": {"footer": true, "checkout": false, "signup": false}}')
on conflict (content_id) do nothing;
INSERT INTO content.content_description (description_id, date_created, date_modified, updt_id, description, name, title, meta_description, meta_keywords, meta_title, sef_url, language_code, content_id, state, excerpt, alt_text, cta_label, subtitle)
VALUES (-200019, now(), now(), 'seed', '<h2>سياسة الخصوصية</h2><p>شركة Egypt Car Sales، 123 شارع أوتو رود، القاهرة، هي المسؤولة عن معالجة بياناتك.</p><h3>البيانات التي نجمعها</h3><ul><li>الاسم ورقم الهاتف والرقم القومي لإجراءات الترخيص</li><li>بيانات التمويل التي يطلبها البنك الشريك</li><li>سجل زيارات الصيانة والفحص</li></ul><h3>مدة الاحتفاظ</h3><p>نحتفظ بمستندات البيع عشر سنوات وفقًا لالتزاماتنا الضريبية، وببيانات الحساب ثلاث سنوات من آخر نشاط.</p><h3>حقوقك</h3><p>يمكنك طلب الاطلاع أو التصحيح أو الحذف عبر <a href="mailto:privacy@egyptcarsales.com">privacy@egyptcarsales.com</a>.</p>', 'سياسة الخصوصية', 'سياسة الخصوصية', null, null, null, null, 'ar', -20010, 'TRANSLATED', null, null, null, null)
on conflict (description_id) do nothing;
INSERT INTO content.content_description (description_id, date_created, date_modified, updt_id, description, name, title, meta_description, meta_keywords, meta_title, sef_url, language_code, content_id, state, excerpt, alt_text, cta_label, subtitle)
VALUES (-200020, now(), now(), 'seed', '<h2>Politique de confidentialité</h2><p>Egypt Car Sales, 123 Auto Road, Le Caire, est responsable du traitement de vos données.</p><h3>Données collectées</h3><ul><li>Nom, téléphone et numéro national pour les formalités d''immatriculation</li><li>Données de financement exigées par la banque partenaire</li><li>Historique des passages en atelier et des inspections</li></ul><h3>Conservation</h3><p>Les documents de vente sont conservés dix ans au titre de nos obligations fiscales, les données de compte trois ans après la dernière activité.</p><h3>Vos droits</h3><p>Accès, rectification et effacement s''exercent auprès de <a href="mailto:privacy@egyptcarsales.com">privacy@egyptcarsales.com</a>.</p>', 'Politique de confidentialité', 'Politique de confidentialité', null, null, null, null, 'fr', -20010, 'TRANSLATED', null, null, null, null)
on conflict (description_id) do nothing;
INSERT INTO content.policy_version (id, store_merchant_id, content_id, version, status, effective_from, note, translations, published_at, published_by)
VALUES (-2001, '65f023632bc26470c104b75f', -20010, 1, 'LIVE', now() - interval '30 days', null, '[{"language": "ar", "title": "سياسة الخصوصية", "body": "<h2>سياسة الخصوصية</h2><p>شركة Egypt Car Sales، 123 شارع أوتو رود، القاهرة، هي المسؤولة عن معالجة بياناتك.</p><h3>البيانات التي نجمعها</h3><ul><li>الاسم ورقم الهاتف والرقم القومي لإجراءات الترخيص</li><li>بيانات التمويل التي يطلبها البنك الشريك</li><li>سجل زيارات الصيانة والفحص</li></ul><h3>مدة الاحتفاظ</h3><p>نحتفظ بمستندات البيع عشر سنوات وفقًا لالتزاماتنا الضريبية، وببيانات الحساب ثلاث سنوات من آخر نشاط.</p><h3>حقوقك</h3><p>يمكنك طلب الاطلاع أو التصحيح أو الحذف عبر <a href=\"mailto:privacy@egyptcarsales.com\">privacy@egyptcarsales.com</a>.</p>", "state": "TRANSLATED"}, {"language": "fr", "title": "Politique de confidentialité", "body": "<h2>Politique de confidentialité</h2><p>Egypt Car Sales, 123 Auto Road, Le Caire, est responsable du traitement de vos données.</p><h3>Données collectées</h3><ul><li>Nom, téléphone et numéro national pour les formalités d''immatriculation</li><li>Données de financement exigées par la banque partenaire</li><li>Historique des passages en atelier et des inspections</li></ul><h3>Conservation</h3><p>Les documents de vente sont conservés dix ans au titre de nos obligations fiscales, les données de compte trois ans après la dernière activité.</p><h3>Vos droits</h3><p>Accès, rectification et effacement s''exercent auprès de <a href=\"mailto:privacy@egyptcarsales.com\">privacy@egyptcarsales.com</a>.</p>", "state": "TRANSLATED"}]', now(), 'seed')
on conflict (id) do nothing;

-- policy: RETURNS
INSERT INTO content.content (content_id, date_created, date_modified, updt_id, code, content_type, sort_order, visible, store_merchant_id, status, publish_at, unpublish_at, version, created_by, updated_by, parent_id, noindex, canonical_url, og_media_id, show_in_footer, placement, starts_at, ends_at, policy_type, meta)
VALUES (-20011, now(), now(), 'seed', 'return-policy', 'POLICY', 101, true, '65f023632bc26470c104b75f', 'PUBLISHED', null, null, 1, 'seed', 'seed', null, false, null, null, false, null, null, null, 'RETURNS', '{"jurisdiction": null, "requiresAcceptance": false, "notifyCustomers": false, "displayAt": {"footer": true, "checkout": false, "signup": false}}')
on conflict (content_id) do nothing;
INSERT INTO content.content_description (description_id, date_created, date_modified, updt_id, description, name, title, meta_description, meta_keywords, meta_title, sef_url, language_code, content_id, state, excerpt, alt_text, cta_label, subtitle)
VALUES (-200021, now(), now(), 'seed', '<h2>سياسة الإرجاع</h2><p>السيارات الجديدة تخضع لضمان الوكيل. أما السيارات المستعملة فلها سبعة أيام أو 300 كيلومتر، أيهما أقرب.</p><h3>ما يشمله الضمان</h3><ul><li>المحرك وناقل الحركة لمدة ستة أشهر</li><li>الأعطال المخالفة لتقرير الفحص المسلَّم إليك</li></ul><h3>ما لا يشمله</h3><ul><li>قطع الاستهلاك: الإطارات، الفرامل، البطارية</li><li>الأضرار الناتجة عن حادث أو سوء استخدام</li></ul><p><em>النسخة الثانية — رفعنا المدة من ثلاثة أيام إلى سبعة.</em></p>', 'سياسة الإرجاع والضمان', 'سياسة الإرجاع والضمان', null, null, null, null, 'ar', -20011, 'TRANSLATED', null, null, null, null)
on conflict (description_id) do nothing;
INSERT INTO content.content_description (description_id, date_created, date_modified, updt_id, description, name, title, meta_description, meta_keywords, meta_title, sef_url, language_code, content_id, state, excerpt, alt_text, cta_label, subtitle)
VALUES (-200022, now(), now(), 'seed', '<h2>Politique de retour</h2><p>Les véhicules neufs sont couverts par la garantie constructeur. Les véhicules d''occasion disposent de sept jours ou 300 kilomètres, au premier des deux termes atteint.</p><h3>Ce que couvre la garantie</h3><ul><li>Moteur et boîte de vitesses pendant six mois</li><li>Tout défaut contredisant le rapport d''inspection qui vous a été remis</li></ul><h3>Ce qu''elle ne couvre pas</h3><ul><li>Pièces d''usure : pneumatiques, freins, batterie</li><li>Dommages liés à un accident ou à un mauvais usage</li></ul><p><em>Version 2 — le délai passe de trois à sept jours.</em></p>', 'Politique de retour et garantie', 'Politique de retour et garantie', null, null, null, null, 'fr', -20011, 'TRANSLATED', null, null, null, null)
on conflict (description_id) do nothing;
INSERT INTO content.policy_version (id, store_merchant_id, content_id, version, status, effective_from, note, translations, published_at, published_by)
VALUES (-2002, '65f023632bc26470c104b75f', -20011, 1, 'ARCHIVED', now() - interval '400 days', 'Initial version', '[{"language": "ar", "title": "سياسة الإرجاع والضمان", "body": "<h2>سياسة الإرجاع</h2><p>ثلاثة أيام أو 150 كيلومترًا للسيارات المستعملة.</p><p><em>النسخة الأولى — مؤرشفة.</em></p>", "state": "TRANSLATED"}, {"language": "fr", "title": "Politique de retour et garantie", "body": "<h2>Politique de retour</h2><p>Trois jours ou 150 kilomètres pour les véhicules d''occasion.</p><p><em>Version 1 — archivée.</em></p>", "state": "TRANSLATED"}]', now(), 'seed')
on conflict (id) do nothing;
INSERT INTO content.policy_version (id, store_merchant_id, content_id, version, status, effective_from, note, translations, published_at, published_by)
VALUES (-2003, '65f023632bc26470c104b75f', -20011, 2, 'LIVE', now() - interval '30 days', 'Second version', '[{"language": "ar", "title": "سياسة الإرجاع والضمان", "body": "<h2>سياسة الإرجاع</h2><p>السيارات الجديدة تخضع لضمان الوكيل. أما السيارات المستعملة فلها سبعة أيام أو 300 كيلومتر، أيهما أقرب.</p><h3>ما يشمله الضمان</h3><ul><li>المحرك وناقل الحركة لمدة ستة أشهر</li><li>الأعطال المخالفة لتقرير الفحص المسلَّم إليك</li></ul><h3>ما لا يشمله</h3><ul><li>قطع الاستهلاك: الإطارات، الفرامل، البطارية</li><li>الأضرار الناتجة عن حادث أو سوء استخدام</li></ul><p><em>النسخة الثانية — رفعنا المدة من ثلاثة أيام إلى سبعة.</em></p>", "state": "TRANSLATED"}, {"language": "fr", "title": "Politique de retour et garantie", "body": "<h2>Politique de retour</h2><p>Les véhicules neufs sont couverts par la garantie constructeur. Les véhicules d''occasion disposent de sept jours ou 300 kilomètres, au premier des deux termes atteint.</p><h3>Ce que couvre la garantie</h3><ul><li>Moteur et boîte de vitesses pendant six mois</li><li>Tout défaut contredisant le rapport d''inspection qui vous a été remis</li></ul><h3>Ce qu''elle ne couvre pas</h3><ul><li>Pièces d''usure : pneumatiques, freins, batterie</li><li>Dommages liés à un accident ou à un mauvais usage</li></ul><p><em>Version 2 — le délai passe de trois à sept jours.</em></p>", "state": "TRANSLATED"}]', now(), 'seed')
on conflict (id) do nothing;

-- policy: SHIPPING
INSERT INTO content.content (content_id, date_created, date_modified, updt_id, code, content_type, sort_order, visible, store_merchant_id, status, publish_at, unpublish_at, version, created_by, updated_by, parent_id, noindex, canonical_url, og_media_id, show_in_footer, placement, starts_at, ends_at, policy_type, meta)
VALUES (-20012, now(), now(), 'seed', 'delivery-policy', 'POLICY', 102, true, '65f023632bc26470c104b75f', 'PUBLISHED', null, null, 1, 'seed', 'seed', null, false, null, null, false, null, null, null, 'SHIPPING', '{"jurisdiction": null, "requiresAcceptance": false, "notifyCustomers": false, "displayAt": {"footer": true, "checkout": false, "signup": false}}')
on conflict (content_id) do nothing;
INSERT INTO content.content_description (description_id, date_created, date_modified, updt_id, description, name, title, meta_description, meta_keywords, meta_title, sef_url, language_code, content_id, state, excerpt, alt_text, cta_label, subtitle)
VALUES (-200023, now(), now(), 'seed', '<h2>التسليم</h2><p>التسليم يتم من المعرض أو أمام باب منزلك داخل الجمهورية.</p><table><tr><th>الوجهة</th><th>المدة</th><th>التكلفة</th></tr><tr><td>القاهرة الكبرى</td><td>يوم إلى يومين</td><td>مجانًا</td></tr><tr><td>الإسكندرية والدلتا</td><td>يومان إلى ثلاثة</td><td>1500 جنيه</td></tr><tr><td>الصعيد والبحر الأحمر</td><td>ثلاثة إلى خمسة أيام</td><td>2500 جنيه</td></tr></table><p>لا تُسلَّم أي سيارة قبل استكمال الترخيص ونقل الملكية.</p>', 'سياسة التسليم', 'سياسة التسليم', null, null, null, null, 'ar', -20012, 'TRANSLATED', null, null, null, null)
on conflict (description_id) do nothing;
INSERT INTO content.content_description (description_id, date_created, date_modified, updt_id, description, name, title, meta_description, meta_keywords, meta_title, sef_url, language_code, content_id, state, excerpt, alt_text, cta_label, subtitle)
VALUES (-200024, now(), now(), 'seed', '<h2>Livraison</h2><p>La livraison se fait au showroom ou devant chez vous, partout en Égypte.</p><table><tr><th>Destination</th><th>Délai</th><th>Tarif</th></tr><tr><td>Grand Caire</td><td>1 à 2 jours</td><td>Offerte</td></tr><tr><td>Alexandrie et Delta</td><td>2 à 3 jours</td><td>1 500 EGP</td></tr><tr><td>Haute-Égypte et mer Rouge</td><td>3 à 5 jours</td><td>2 500 EGP</td></tr></table><p>Aucun véhicule n''est livré avant l''immatriculation et le transfert de propriété.</p>', 'Politique de livraison', 'Politique de livraison', null, null, null, null, 'fr', -20012, 'TRANSLATED', null, null, null, null)
on conflict (description_id) do nothing;
INSERT INTO content.policy_version (id, store_merchant_id, content_id, version, status, effective_from, note, translations, published_at, published_by)
VALUES (-2004, '65f023632bc26470c104b75f', -20012, 1, 'LIVE', now() - interval '30 days', null, '[{"language": "ar", "title": "سياسة التسليم", "body": "<h2>التسليم</h2><p>التسليم يتم من المعرض أو أمام باب منزلك داخل الجمهورية.</p><table><tr><th>الوجهة</th><th>المدة</th><th>التكلفة</th></tr><tr><td>القاهرة الكبرى</td><td>يوم إلى يومين</td><td>مجانًا</td></tr><tr><td>الإسكندرية والدلتا</td><td>يومان إلى ثلاثة</td><td>1500 جنيه</td></tr><tr><td>الصعيد والبحر الأحمر</td><td>ثلاثة إلى خمسة أيام</td><td>2500 جنيه</td></tr></table><p>لا تُسلَّم أي سيارة قبل استكمال الترخيص ونقل الملكية.</p>", "state": "TRANSLATED"}, {"language": "fr", "title": "Politique de livraison", "body": "<h2>Livraison</h2><p>La livraison se fait au showroom ou devant chez vous, partout en Égypte.</p><table><tr><th>Destination</th><th>Délai</th><th>Tarif</th></tr><tr><td>Grand Caire</td><td>1 à 2 jours</td><td>Offerte</td></tr><tr><td>Alexandrie et Delta</td><td>2 à 3 jours</td><td>1 500 EGP</td></tr><tr><td>Haute-Égypte et mer Rouge</td><td>3 à 5 jours</td><td>2 500 EGP</td></tr></table><p>Aucun véhicule n''est livré avant l''immatriculation et le transfert de propriété.</p>", "state": "TRANSLATED"}]', now(), 'seed')
on conflict (id) do nothing;

-- policy: COOKIES
INSERT INTO content.content (content_id, date_created, date_modified, updt_id, code, content_type, sort_order, visible, store_merchant_id, status, publish_at, unpublish_at, version, created_by, updated_by, parent_id, noindex, canonical_url, og_media_id, show_in_footer, placement, starts_at, ends_at, policy_type, meta)
VALUES (-20013, now(), now(), 'seed', 'cookie-policy', 'POLICY', 103, true, '65f023632bc26470c104b75f', 'PUBLISHED', null, null, 1, 'seed', 'seed', null, false, null, null, false, null, null, null, 'COOKIES', '{"jurisdiction": null, "requiresAcceptance": false, "notifyCustomers": false, "displayAt": {"footer": true, "checkout": false, "signup": false}}')
on conflict (content_id) do nothing;
INSERT INTO content.content_description (description_id, date_created, date_modified, updt_id, description, name, title, meta_description, meta_keywords, meta_title, sef_url, language_code, content_id, state, excerpt, alt_text, cta_label, subtitle)
VALUES (-200025, now(), now(), 'seed', '<h2>ملفات تعريف الارتباط</h2><p>نستخدم ثلاث فئات، واحدة منها فقط لا تحتاج موافقتك.</p><ul><li><strong>أساسية</strong> — الجلسة والمقارنة والأمان. تعمل دائمًا.</li><li><strong>قياس</strong> — إحصاءات مجمّعة، ثلاثة عشر شهرًا.</li><li><strong>تخصيص</strong> — اقتراح سيارات مشابهة، ستة أشهر.</li></ul><p>يُحفظ اختيارك ستة أشهر ويمكن تعديله من رابط « تفضيلات الكوكيز » أسفل الصفحة.</p>', 'سياسة ملفات تعريف الارتباط', 'سياسة ملفات تعريف الارتباط', null, null, null, null, 'ar', -20013, 'TRANSLATED', null, null, null, null)
on conflict (description_id) do nothing;
INSERT INTO content.content_description (description_id, date_created, date_modified, updt_id, description, name, title, meta_description, meta_keywords, meta_title, sef_url, language_code, content_id, state, excerpt, alt_text, cta_label, subtitle)
VALUES (-200026, now(), now(), 'seed', '<h2>Cookies</h2><p>Nous utilisons trois familles, dont une seule est exemptée de consentement.</p><ul><li><strong>Essentiels</strong> — session, comparateur, sécurité. Toujours actifs.</li><li><strong>Mesure</strong> — statistiques agrégées, 13 mois.</li><li><strong>Personnalisation</strong> — suggestions de véhicules similaires, 6 mois.</li></ul><p>Votre choix est conservé six mois et modifiable depuis « Préférences cookies » en pied de page.</p>', 'Politique relative aux cookies', 'Politique relative aux cookies', null, null, null, null, 'fr', -20013, 'TRANSLATED', null, null, null, null)
on conflict (description_id) do nothing;
INSERT INTO content.policy_version (id, store_merchant_id, content_id, version, status, effective_from, note, translations, published_at, published_by)
VALUES (-2005, '65f023632bc26470c104b75f', -20013, 1, 'LIVE', now() - interval '30 days', null, '[{"language": "ar", "title": "سياسة ملفات تعريف الارتباط", "body": "<h2>ملفات تعريف الارتباط</h2><p>نستخدم ثلاث فئات، واحدة منها فقط لا تحتاج موافقتك.</p><ul><li><strong>أساسية</strong> — الجلسة والمقارنة والأمان. تعمل دائمًا.</li><li><strong>قياس</strong> — إحصاءات مجمّعة، ثلاثة عشر شهرًا.</li><li><strong>تخصيص</strong> — اقتراح سيارات مشابهة، ستة أشهر.</li></ul><p>يُحفظ اختيارك ستة أشهر ويمكن تعديله من رابط « تفضيلات الكوكيز » أسفل الصفحة.</p>", "state": "TRANSLATED"}, {"language": "fr", "title": "Politique relative aux cookies", "body": "<h2>Cookies</h2><p>Nous utilisons trois familles, dont une seule est exemptée de consentement.</p><ul><li><strong>Essentiels</strong> — session, comparateur, sécurité. Toujours actifs.</li><li><strong>Mesure</strong> — statistiques agrégées, 13 mois.</li><li><strong>Personnalisation</strong> — suggestions de véhicules similaires, 6 mois.</li></ul><p>Votre choix est conservé six mois et modifiable depuis « Préférences cookies » en pied de page.</p>", "state": "TRANSLATED"}]', now(), 'seed')
on conflict (id) do nothing;

