-- Blog categories and posts.
--
-- Demo content for the test store 65f023632bc26470c104b75f (Egypt Car Sales), in every language the store sells in.
-- Generated seed: ids are negative on purpose — content, media and menu ids all come from sequences that
-- only grow upward, so a seed row below zero can never collide with one the running service creates.

INSERT INTO content.post_category (id, store_merchant_id, slug, position, names)
VALUES (-251, '65f023632bc26470c104b75f', 'buying-guide', 0, '{"ar": "دليل الشراء", "fr": "Guide d''achat"}')
on conflict (store_merchant_id, slug) do nothing;
INSERT INTO content.post_category (id, store_merchant_id, slug, position, names)
VALUES (-252, '65f023632bc26470c104b75f', 'maintenance', 1, '{"ar": "الصيانة", "fr": "Entretien"}')
on conflict (store_merchant_id, slug) do nothing;
INSERT INTO content.post_category (id, store_merchant_id, slug, position, names)
VALUES (-253, '65f023632bc26470c104b75f', 'electric', 2, '{"ar": "السيارات الكهربائية", "fr": "Électrique"}')
on conflict (store_merchant_id, slug) do nothing;

-- post: seven-checks-before-buying-used (PUBLISHED)
INSERT INTO content.content (content_id, date_created, date_modified, updt_id, code, content_type, sort_order, visible, store_merchant_id, status, publish_at, unpublish_at, version, created_by, updated_by, parent_id, noindex, canonical_url, og_media_id, show_in_footer, placement, starts_at, ends_at, policy_type, meta)
VALUES (-20026, now(), now(), 'seed', 'seven-checks-before-buying-used', 'POST', 0, true, '65f023632bc26470c104b75f', 'PUBLISHED', now() - interval '4 days', null, 1, 'seed', 'seed', null, false, null, null, false, null, null, null, null, '{"heroMediaId": -290003, "categoryIds": [-251], "tags": ["مستعمل", "فحص", "occasion"], "authorName": "كريم عبد الحميد", "featured": true}')
on conflict (content_id) do nothing;
INSERT INTO content.content_description (description_id, date_created, date_modified, updt_id, description, name, title, meta_description, meta_keywords, meta_title, sef_url, language_code, content_id, state, excerpt, alt_text, cta_label, subtitle)
VALUES (-200051, now(), now(), 'seed', '<p>معظم المشترين يفحصون لون السيارة ولا يفحصون سمك طلائها. هذه قائمة بما ننصح كل عميل بالنظر إليه بنفسه، حتى مع وجود تقرير مكتوب.</p><h2>1. سمك الطلاء</h2><p>جهاز قياس بسيط يكشف إن كانت اللوحة قد أُعيد رشها. الفرق بين 110 و 250 ميكرون يعني إصلاح حادث.</p><h2>2. فواصل الأبواب والكبوت</h2><p>يجب أن تكون متساوية العرض من أعلى إلى أسفل. الفارق يعني تعديلًا في الهيكل.</p><h2>3. أرقام الشاسيه</h2><p>قارن الرقم على الهيكل بالرقم في الرخصة. أي اختلاف ينهي الصفقة فورًا.</p><h2>4. الزيوت</h2><p>زيت المحرك الأسود اللزج يعني إهمال صيانة. زيت الفتيس بلون بني محروق يعني تكلفة قادمة.</p><h2>5. الإطارات</h2><p>أربعة إطارات من ماركات مختلفة وتواريخ متباعدة تدل على مالك يقتصد في غير موضعه.</p><h2>6. كمبيوتر السيارة</h2><p>اطلب قراءة الأعطال المخزّنة. الأعطال الممسوحة حديثًا تظهر في عدّاد الجاهزية.</p><h2>7. التجربة على طريق سريع</h2><p>عشرون دقيقة داخل المدينة لا تكشف اهتزاز الفرامل أو انحراف المقود. اخرج على الدائري.</p>', 'سبعة فحوص قبل شراء سيارة مستعملة', 'سبعة فحوص قبل شراء سيارة مستعملة', 'ما يجب أن تنظر إليه بنفسك قبل توقيع عقد سيارة مستعملة: الهيكل، الطلاء، الزيوت، والكمبيوتر.', 'مستعمل, فحص, occasion', 'سبعة فحوص قبل شراء سيارة مستعملة | المدونة', 'seven-checks-ar', 'ar', -20026, 'TRANSLATED', 'خمس دقائق في المعرض توفّر عليك خمسة آلاف جنيه في الورشة. هذه أهم سبع نقاط.', null, null, null)
on conflict (description_id) do nothing;
INSERT INTO content.content_description (description_id, date_created, date_modified, updt_id, description, name, title, meta_description, meta_keywords, meta_title, sef_url, language_code, content_id, state, excerpt, alt_text, cta_label, subtitle)
VALUES (-200052, now(), now(), 'seed', '<p>La plupart des acheteurs regardent la couleur de la voiture et jamais l''épaisseur de sa peinture. Voici ce que nous conseillons de vérifier soi-même, rapport écrit ou pas.</p><h2>1. L''épaisseur de peinture</h2><p>Un simple mesureur révèle une aile repeinte. L''écart entre 110 et 250 microns signe une reprise accidentelle.</p><h2>2. Les jeux de portes et de capot</h2><p>Ils doivent être constants du haut vers le bas. Une variation trahit une déformation de structure.</p><h2>3. Les numéros de série</h2><p>Comparez le numéro frappé sur la caisse et celui de la carte grise. La moindre différence met fin à la discussion.</p><h2>4. Les fluides</h2><p>Une huile moteur noire et épaisse annonce un entretien négligé. Une huile de boîte brun brûlé annonce une facture.</p><h2>5. Les pneumatiques</h2><p>Quatre marques différentes à des dates éloignées désignent un propriétaire qui a économisé au mauvais endroit.</p><h2>6. Le calculateur</h2><p>Demandez la lecture des défauts mémorisés. Un effacement récent se voit aux compteurs de disponibilité.</p><h2>7. L''essai sur voie rapide</h2><p>Vingt minutes en ville ne révèlent ni vibration au freinage ni tirage de direction. Sortez sur le périphérique.</p>', 'Sept vérifications avant d''acheter une occasion', 'Sept vérifications avant d''acheter une occasion', 'Ce qu''il faut regarder soi-même avant de signer : carrosserie, peinture, fluides, calculateur.', 'مستعمل, فحص, occasion', 'Sept vérifications avant d''acheter une occasion | Le blog', 'sept-verifications-occasion', 'fr', -20026, 'TRANSLATED', 'Cinq minutes au showroom vous épargnent cinq mille livres à l''atelier. Voici les sept points.', null, null, null)
on conflict (description_id) do nothing;
INSERT INTO content.media_usage (id, asset_id, owner_kind, owner_ref, owner_title, content_id, content_type, field)
VALUES (-2001, -290003, 'CONTENT', '-20026', 'سبعة فحوص قبل شراء سيارة مستعملة', -20026, 'POST', 'hero')
on conflict (id) do nothing;

-- post: ev-running-costs-egypt (PUBLISHED)
INSERT INTO content.content (content_id, date_created, date_modified, updt_id, code, content_type, sort_order, visible, store_merchant_id, status, publish_at, unpublish_at, version, created_by, updated_by, parent_id, noindex, canonical_url, og_media_id, show_in_footer, placement, starts_at, ends_at, policy_type, meta)
VALUES (-20027, now(), now(), 'seed', 'ev-running-costs-egypt', 'POST', 1, true, '65f023632bc26470c104b75f', 'PUBLISHED', now() - interval '11 days', null, 1, 'seed', 'seed', null, false, null, null, false, null, null, null, null, '{"heroMediaId": -290004, "categoryIds": [-253, -251], "tags": ["كهربائي", "تكلفة", "électrique"], "authorName": "د. منى شاهين", "featured": false}')
on conflict (content_id) do nothing;
INSERT INTO content.content_description (description_id, date_created, date_modified, updt_id, description, name, title, meta_description, meta_keywords, meta_title, sef_url, language_code, content_id, state, excerpt, alt_text, cta_label, subtitle)
VALUES (-200053, now(), now(), 'seed', '<h2>تكلفة الكيلومتر</h2><p>سيارة كهربائية متوسطة تستهلك نحو 17 كيلوواط/ساعة لكل مئة كيلومتر. بشرائح الاستهلاك المنزلي، هذا أقل من ثلث تكلفة سيارة بنزين مكافئة.</p><h2>ما لا يظهر في الحسبة السريعة</h2><ul><li>التأمين أعلى بنحو 15% بسبب تكلفة البطارية</li><li>الإطارات تتآكل أسرع بفعل الوزن والعزم</li><li>الصيانة الدورية أرخص: لا زيت، لا فلاتر، فرامل تدوم أطول</li></ul><h2>نقطة التعادل</h2><p>عند خمسة عشر ألف كيلومتر سنويًا، يستغرق فارق السعر الابتدائي نحو أربع سنوات ليُسترد.</p>', 'كم تكلّف السيارة الكهربائية فعليًا في مصر؟', 'كم تكلّف السيارة الكهربائية فعليًا في مصر؟', 'حساب واقعي لتكلفة الكيلومتر في السيارة الكهربائية مقابل البنزين في الظروف المصرية.', 'كهربائي, تكلفة, électrique', 'تكلفة السيارة الكهربائية في مصر | المدونة', 'ev-running-costs-ar', 'ar', -20027, 'TRANSLATED', 'الكهرباء أرخص من البنزين بفارق كبير، لكن التأمين وقطع الغيار يقلّصان الفارق.', null, null, null)
on conflict (description_id) do nothing;
INSERT INTO content.content_description (description_id, date_created, date_modified, updt_id, description, name, title, meta_description, meta_keywords, meta_title, sef_url, language_code, content_id, state, excerpt, alt_text, cta_label, subtitle)
VALUES (-200054, now(), now(), 'seed', '<h2>Le coût au kilomètre</h2><p>Un électrique moyen consomme environ 17 kWh aux cent kilomètres. Aux tarifs résidentiels, cela représente moins du tiers d''une essence équivalente.</p><h2>Ce que le calcul rapide oublie</h2><ul><li>L''assurance est environ 15 % plus chère, à cause de la batterie</li><li>Les pneumatiques s''usent plus vite, sous l''effet du poids et du couple</li><li>L''entretien courant coûte moins : pas d''huile, pas de filtres, des freins qui durent</li></ul><h2>Le point d''équilibre</h2><p>À quinze mille kilomètres par an, le surcoût à l''achat est amorti en quatre ans environ.</p>', 'Ce que coûte réellement un véhicule électrique en Égypte', 'Ce que coûte réellement un véhicule électrique en Égypte', 'Un calcul honnête du coût au kilomètre d''un véhicule électrique face à l''essence, en conditions égyptiennes.', 'كهربائي, تكلفة, électrique', 'Le coût réel d''un électrique en Égypte | Le blog', 'cout-reel-electrique-egypte', 'fr', -20027, 'TRANSLATED', 'L''électricité est bien moins chère que l''essence, mais l''assurance et les pièces réduisent l''écart.', null, null, null)
on conflict (description_id) do nothing;
INSERT INTO content.media_usage (id, asset_id, owner_kind, owner_ref, owner_title, content_id, content_type, field)
VALUES (-2002, -290004, 'CONTENT', '-20027', 'كم تكلّف السيارة الكهربائية فعليًا في مصر؟', -20027, 'POST', 'hero')
on conflict (id) do nothing;

-- post: summer-cooling-checklist (PUBLISHED)
INSERT INTO content.content (content_id, date_created, date_modified, updt_id, code, content_type, sort_order, visible, store_merchant_id, status, publish_at, unpublish_at, version, created_by, updated_by, parent_id, noindex, canonical_url, og_media_id, show_in_footer, placement, starts_at, ends_at, policy_type, meta)
VALUES (-20028, now(), now(), 'seed', 'summer-cooling-checklist', 'POST', 2, true, '65f023632bc26470c104b75f', 'PUBLISHED', now() - interval '20 days', null, 1, 'seed', 'seed', null, false, null, null, false, null, null, null, null, '{"heroMediaId": -290005, "categoryIds": [-252], "tags": ["صيانة", "تكييف", "entretien"], "authorName": "محمود فاروق", "featured": false}')
on conflict (content_id) do nothing;
INSERT INTO content.content_description (description_id, date_created, date_modified, updt_id, description, name, title, meta_description, meta_keywords, meta_title, sef_url, language_code, content_id, state, excerpt, alt_text, cta_label, subtitle)
VALUES (-200055, now(), now(), 'seed', '<p>الأعطال الصيفية ليست مفاجئة، بل مؤجلة من الشتاء. هذه قائمة مايو.</p><h2>الرادياتير</h2><p>افحص تركيز سائل التبريد لا مستواه فقط. الماء وحده يغلي عند مئة درجة، بينما الخليط الصحيح يتحمل حتى 128.</p><h2>التكييف</h2><p>إن احتاج شحن غاز كل صيف، فهناك تسريب. الشحن المتكرر يفسد الضاغط.</p><h2>البطارية</h2><p>الحرارة تقتل البطاريات أكثر من البرد. بطارية عمرها أربع سنوات في مصر تعادل ستًا في أوروبا.</p><h2>ضغط الإطارات</h2><p>اضبطه على البارد صباحًا. الارتفاع الظاهر بعد القيادة طبيعي ولا يُفرَّغ منه هواء.</p>', 'تجهيز السيارة لصيف القاهرة', 'تجهيز السيارة لصيف القاهرة', 'فحص الرادياتير والتكييف والبطارية والإطارات قبل موجة الحر.', 'صيانة, تكييف, entretien', 'تجهيز السيارة لصيف القاهرة | المدونة', 'summer-cooling-ar', 'ar', -20028, 'TRANSLATED', 'خمسون درجة على الأسفلت تكشف كل تهاون في نظام التبريد. قائمة ما يجب فحصه في مايو.', null, null, null)
on conflict (description_id) do nothing;
INSERT INTO content.content_description (description_id, date_created, date_modified, updt_id, description, name, title, meta_description, meta_keywords, meta_title, sef_url, language_code, content_id, state, excerpt, alt_text, cta_label, subtitle)
VALUES (-200056, now(), now(), 'seed', '<p>Les pannes d''été ne sont pas des surprises : ce sont des négligences d''hiver. Voici la liste de mai.</p><h2>Le radiateur</h2><p>Contrôlez la concentration du liquide, pas seulement le niveau. L''eau seule bout à cent degrés ; un mélange correct tient jusqu''à 128.</p><h2>La climatisation</h2><p>Si elle demande une recharge chaque été, c''est qu''elle fuit. Les recharges répétées détruisent le compresseur.</p><h2>La batterie</h2><p>La chaleur tue plus de batteries que le froid. Quatre ans en Égypte valent six en Europe.</p><h2>La pression des pneus</h2><p>Réglez-la à froid, le matin. La hausse constatée après roulage est normale : on ne dégonfle pas.</p>', 'Préparer sa voiture à l''été cairote', 'Préparer sa voiture à l''été cairote', 'Radiateur, climatisation, batterie et pneumatiques : les contrôles à faire avant la canicule.', 'صيانة, تكييف, entretien', 'Préparer sa voiture à l''été cairote | Le blog', 'preparer-ete-cairote', 'fr', -20028, 'TRANSLATED', 'Cinquante degrés sur le bitume révèlent toute négligence du circuit de refroidissement. La liste de mai.', null, null, null)
on conflict (description_id) do nothing;
INSERT INTO content.media_usage (id, asset_id, owner_kind, owner_ref, owner_title, content_id, content_type, field)
VALUES (-2003, -290005, 'CONTENT', '-20028', 'تجهيز السيارة لصيف القاهرة', -20028, 'POST', 'hero')
on conflict (id) do nothing;

-- post: suv-or-sedan (PUBLISHED)
INSERT INTO content.content (content_id, date_created, date_modified, updt_id, code, content_type, sort_order, visible, store_merchant_id, status, publish_at, unpublish_at, version, created_by, updated_by, parent_id, noindex, canonical_url, og_media_id, show_in_footer, placement, starts_at, ends_at, policy_type, meta)
VALUES (-20029, now(), now(), 'seed', 'suv-or-sedan', 'POST', 3, true, '65f023632bc26470c104b75f', 'PUBLISHED', now() - interval '31 days', null, 1, 'seed', 'seed', null, false, null, null, false, null, null, null, null, '{"heroMediaId": -290006, "categoryIds": [-251], "tags": ["SUV", "سيدان", "comparatif"], "authorName": "كريم عبد الحميد", "featured": false}')
on conflict (content_id) do nothing;
INSERT INTO content.content_description (description_id, date_created, date_modified, updt_id, description, name, title, meta_description, meta_keywords, meta_title, sef_url, language_code, content_id, state, excerpt, alt_text, cta_label, subtitle)
VALUES (-200057, now(), now(), 'seed', '<p>السؤال الشائع « أيهما أفضل » لا إجابة له. السؤال المفيد: أين تقود، وكم يومًا في الأسبوع؟</p><h2>المطبات والأرصفة</h2><p>ارتفاع الـ SUV ميزة حقيقية على الطرق الجانبية والمطبات غير المدهونة. هنا يتفوق بوضوح.</p><h2>الزحام واستهلاك الوقود</h2><p>الوزن الأعلى يعني استهلاكًا أعلى بنحو 15% في الزحام، وهو ما يشعر به من يقود يوميًا في وسط القاهرة.</p><h2>الركن</h2><p>طول السيدان أقل بنصف متر تقريبًا، وهو فارق يقرر أحيانًا وجود مكان من عدمه.</p><h2>الخلاصة</h2><p>القيادة اليومية داخل المدينة: سيدان. الطرق الصحراوية والعائلة الكبيرة والرحلات: SUV.</p>', 'سيدان أم SUV؟ السؤال الخطأ', 'سيدان أم SUV؟ السؤال الخطأ', 'مقارنة عملية بين السيدان والـ SUV في ظروف القيادة المصرية.', 'SUV, سيدان, comparatif', 'سيدان أم SUV؟ | المدونة', 'suv-or-sedan-ar', 'ar', -20029, 'TRANSLATED', 'الفارق الحقيقي ليس في الشكل بل في المطبات والزحام واستهلاك الوقود.', null, null, null)
on conflict (description_id) do nothing;
INSERT INTO content.content_description (description_id, date_created, date_modified, updt_id, description, name, title, meta_description, meta_keywords, meta_title, sef_url, language_code, content_id, state, excerpt, alt_text, cta_label, subtitle)
VALUES (-200058, now(), now(), 'seed', '<p>« Lequel est le mieux » n''a pas de réponse. La question utile est : où conduisez-vous, et combien de jours par semaine ?</p><h2>Dos-d''âne et trottoirs</h2><p>La garde au sol d''un SUV est un avantage réel sur les voies secondaires et les ralentisseurs non peints. Il gagne nettement ici.</p><h2>Embouteillages et consommation</h2><p>Le surpoids coûte environ 15 % de consommation en circulation dense — ce que ressent quiconque traverse le centre du Caire chaque jour.</p><h2>Le stationnement</h2><p>Une berline mesure environ un demi-mètre de moins, et ce demi-mètre décide parfois de l''existence d''une place.</p><h2>En résumé</h2><p>Trajets urbains quotidiens : berline. Pistes désertiques, grande famille, longs trajets : SUV.</p>', 'Berline ou SUV ? La mauvaise question', 'Berline ou SUV ? La mauvaise question', 'Une comparaison concrète entre berline et SUV dans les conditions de conduite égyptiennes.', 'SUV, سيدان, comparatif', 'Berline ou SUV ? | Le blog', 'berline-ou-suv', 'fr', -20029, 'TRANSLATED', 'La vraie différence ne tient pas à la silhouette mais aux dos-d''âne, aux embouteillages et à la consommation.', null, null, null)
on conflict (description_id) do nothing;
INSERT INTO content.media_usage (id, asset_id, owner_kind, owner_ref, owner_title, content_id, content_type, field)
VALUES (-2004, -290006, 'CONTENT', '-20029', 'سيدان أم SUV؟ السؤال الخطأ', -20029, 'POST', 'hero')
on conflict (id) do nothing;

-- post: inside-maadi-workshop (PUBLISHED)
INSERT INTO content.content (content_id, date_created, date_modified, updt_id, code, content_type, sort_order, visible, store_merchant_id, status, publish_at, unpublish_at, version, created_by, updated_by, parent_id, noindex, canonical_url, og_media_id, show_in_footer, placement, starts_at, ends_at, policy_type, meta)
VALUES (-20030, now(), now(), 'seed', 'inside-maadi-workshop', 'POST', 4, true, '65f023632bc26470c104b75f', 'PUBLISHED', now() - interval '45 days', null, 1, 'seed', 'seed', null, false, null, null, false, null, null, null, null, '{"heroMediaId": -290007, "categoryIds": [-252], "tags": ["ورشة", "فحص", "atelier"], "authorName": "محمود فاروق", "featured": false}')
on conflict (content_id) do nothing;
INSERT INTO content.content_description (description_id, date_created, date_modified, updt_id, description, name, title, meta_description, meta_keywords, meta_title, sef_url, language_code, content_id, state, excerpt, alt_text, cta_label, subtitle)
VALUES (-200059, now(), now(), 'seed', '<p>الورشة في المعادي هي المكان الذي تُرفض فيه السيارات، لا الذي تُجمَّل فيه.</p><h2>ثلاثون سيارة في الأسبوع</h2><p>يدخل الورشة نحو ثلاثين سيارة أسبوعيًا، ويُرفض منها بين خمس وثماني في المتوسط. أكثر أسباب الرفض شيوعًا: إصلاح هيكل غير معلن.</p><h2>ساعتان لكل سيارة</h2><p>الفحص الكامل يستغرق ساعتين، منها أربعون دقيقة على الرافعة وحدها.</p><h2>لماذا لا نصلح ونبيع؟</h2><p>لأن إصلاح الهيكل يمكن إخفاؤه، ولا يمكن ضمانه. ما لا نستطيع ضمانه لا نبيعه.</p>', 'داخل ورشة المعادي', 'داخل ورشة المعادي', 'جولة في الورشة التي يمر بها كل سيارة مستعملة قبل العرض.', 'ورشة, فحص, atelier', 'داخل ورشة المعادي | المدونة', 'inside-maadi-ar', 'ar', -20030, 'TRANSLATED', 'أربع رافعات، جهازا قياس طلاء، وثلاثون سيارة أسبوعيًا لا يمر منها الجميع.', null, null, null)
on conflict (description_id) do nothing;
INSERT INTO content.content_description (description_id, date_created, date_modified, updt_id, description, name, title, meta_description, meta_keywords, meta_title, sef_url, language_code, content_id, state, excerpt, alt_text, cta_label, subtitle)
VALUES (-200060, now(), now(), 'seed', '<p>L''atelier de Maadi est l''endroit où l''on refuse des voitures, pas celui où on les maquille.</p><h2>Trente voitures par semaine</h2><p>Une trentaine de véhicules y entrent chaque semaine ; cinq à huit sont refusés. Motif le plus fréquent : une reprise de structure non déclarée.</p><h2>Deux heures par véhicule</h2><p>L''inspection complète dure deux heures, dont quarante minutes sur le pont.</p><h2>Pourquoi ne pas réparer et vendre ?</h2><p>Parce qu''une reprise de structure peut se cacher mais pas se garantir. Ce que nous ne pouvons pas garantir, nous ne le vendons pas.</p>', 'Dans l''atelier de Maadi', 'Dans l''atelier de Maadi', 'Visite de l''atelier par lequel passe chaque véhicule d''occasion avant la mise en vente.', 'ورشة, فحص, atelier', 'Dans l''atelier de Maadi | Le blog', 'dans-latelier-de-maadi', 'fr', -20030, 'TRANSLATED', 'Quatre ponts, deux mesureurs de peinture, et trente voitures par semaine dont toutes ne passent pas.', null, null, null)
on conflict (description_id) do nothing;
INSERT INTO content.media_usage (id, asset_id, owner_kind, owner_ref, owner_title, content_id, content_type, field)
VALUES (-2005, -290007, 'CONTENT', '-20030', 'داخل ورشة المعادي', -20030, 'POST', 'hero')
on conflict (id) do nothing;

-- post: reading-the-service-book (PUBLISHED)
INSERT INTO content.content (content_id, date_created, date_modified, updt_id, code, content_type, sort_order, visible, store_merchant_id, status, publish_at, unpublish_at, version, created_by, updated_by, parent_id, noindex, canonical_url, og_media_id, show_in_footer, placement, starts_at, ends_at, policy_type, meta)
VALUES (-20031, now(), now(), 'seed', 'reading-the-service-book', 'POST', 5, true, '65f023632bc26470c104b75f', 'PUBLISHED', now() - interval '66 days', null, 1, 'seed', 'seed', null, false, null, null, false, null, null, null, null, '{"heroMediaId": -290003, "categoryIds": [-252, -251], "tags": ["صيانة", "سجل", "entretien"], "authorName": "د. منى شاهين", "featured": false}')
on conflict (content_id) do nothing;
INSERT INTO content.content_description (description_id, date_created, date_modified, updt_id, description, name, title, meta_description, meta_keywords, meta_title, sef_url, language_code, content_id, state, excerpt, alt_text, cta_label, subtitle)
VALUES (-200061, now(), now(), 'seed', '<h2>الفجوات أهم من الأختام</h2><p>ابحث عن الفترات الطويلة بين الزيارات، لا عن عدد الأختام. فجوة ثمانية عشر شهرًا أخطر من صفحة ناقصة.</p><h2>القفزات في العداد</h2><p>عشرة آلاف كيلومتر في زيارة، ثم أربعون ألفًا في التالية، تعني إما استخدامًا مختلفًا أو عدادًا معدَّلًا.</p><h2>البنود المتكررة</h2><p>تغيير نفس الحساس ثلاث مرات يعني أن أحدًا لم يعالج السبب.</p>', 'كيف تقرأ سجل الصيانة', 'كيف تقرأ سجل الصيانة', 'ما تكشفه دفاتر الصيانة فعلًا عن حالة السيارة، وما لا تكشفه.', 'صيانة, سجل, entretien', 'كيف تقرأ سجل الصيانة | المدونة', 'reading-service-book-ar', 'ar', -20031, 'TRANSLATED', 'سجل ممتلئ بالأختام ليس دليل عناية. المهم هو المسافات بين الزيارات.', null, null, null)
on conflict (description_id) do nothing;
INSERT INTO content.content_description (description_id, date_created, date_modified, updt_id, description, name, title, meta_description, meta_keywords, meta_title, sef_url, language_code, content_id, state, excerpt, alt_text, cta_label, subtitle)
VALUES (-200062, now(), now(), 'seed', '<h2>Les trous comptent plus que les tampons</h2><p>Cherchez les longues périodes sans passage, pas le nombre de cachets. Un trou de dix-huit mois est plus inquiétant qu''une page manquante.</p><h2>Les sauts de compteur</h2><p>Dix mille kilomètres entre deux visites puis quarante mille : soit l''usage a changé, soit le compteur.</p><h2>Les lignes qui reviennent</h2><p>Le même capteur remplacé trois fois signifie que personne n''a traité la cause.</p>', 'Lire un carnet d''entretien', 'Lire un carnet d''entretien', 'Ce que les carnets d''entretien révèlent vraiment de l''état d''un véhicule, et ce qu''ils taisent.', 'صيانة, سجل, entretien', 'Lire un carnet d''entretien | Le blog', 'lire-un-carnet-dentretien', 'fr', -20031, 'TRANSLATED', 'Un carnet plein de tampons ne prouve rien. Ce qui compte, ce sont les intervalles.', null, null, null)
on conflict (description_id) do nothing;
INSERT INTO content.media_usage (id, asset_id, owner_kind, owner_ref, owner_title, content_id, content_type, field)
VALUES (-2006, -290003, 'CONTENT', '-20031', 'كيف تقرأ سجل الصيانة', -20031, 'POST', 'hero')
on conflict (id) do nothing;

-- post: model-year-2026-preview (DRAFT)
INSERT INTO content.content (content_id, date_created, date_modified, updt_id, code, content_type, sort_order, visible, store_merchant_id, status, publish_at, unpublish_at, version, created_by, updated_by, parent_id, noindex, canonical_url, og_media_id, show_in_footer, placement, starts_at, ends_at, policy_type, meta)
VALUES (-20032, now(), now(), 'seed', 'model-year-2026-preview', 'POST', 6, true, '65f023632bc26470c104b75f', 'DRAFT', null, null, 1, 'seed', 'seed', null, false, null, null, false, null, null, null, null, '{"heroMediaId": -290004, "categoryIds": [-251], "tags": ["2026"], "authorName": "كريم عبد الحميد", "featured": false}')
on conflict (content_id) do nothing;
INSERT INTO content.content_description (description_id, date_created, date_modified, updt_id, description, name, title, meta_description, meta_keywords, meta_title, sef_url, language_code, content_id, state, excerpt, alt_text, cta_label, subtitle)
VALUES (-200063, now(), now(), 'seed', '<p>مسودة. هذا المقال يتحقق من أن منشور POST غير منشور يبقى خارج المدونة وقابلًا للتحرير في لوحة التحكم.</p>', 'موديلات 2026 (مسودة)', 'موديلات 2026 (مسودة)', null, '2026', null, 'model-year-2026-ar', 'ar', -20032, 'DRAFT', 'مقال قيد الكتابة — يجب ألا يظهر في المدونة.', null, null, null)
on conflict (description_id) do nothing;
INSERT INTO content.content_description (description_id, date_created, date_modified, updt_id, description, name, title, meta_description, meta_keywords, meta_title, sef_url, language_code, content_id, state, excerpt, alt_text, cta_label, subtitle)
VALUES (-200064, now(), now(), 'seed', '<p>Brouillon. Cet article vérifie qu''un POST non publié reste hors du blog tout en restant éditable dans la console.</p>', 'Millésime 2026 (brouillon)', 'Millésime 2026 (brouillon)', null, '2026', null, 'millesime-2026', 'fr', -20032, 'DRAFT', 'Article en cours de rédaction — ne doit pas apparaître.', null, null, null)
on conflict (description_id) do nothing;

