plugins {
    id 'com.asrevo.java-library-conventions'
}

dependencies {
    implementation 'org.shredzone.acme4j:acme4j-client:2.15'
    implementation 'org.shredzone.acme4j:acme4j-utils:2.15'
    compileOnly 'org.projectlombok:lombok:1.18.28'
    compileOnly 'org.springframework.data:spring-data-commons:3.1.2'
    compileOnly 'org.springframework.data:spring-data-relational:3.1.2'
    compileOnly 'jakarta.validation:jakarta.validation-api:3.0.2'
    annotationProcessor 'org.projectlombok:lombok:1.18.28'
}
