### Register new Org user
POST http://localhost:8020/api/v1/user-account/public/create
Content-Type: application/json

{
  "user": {
    "firstName": "ash1raf",
    "lastName": "ashra1f",
    "emailAddress": "ne10s0w-user@mail.com",
    "password": "admin"
  },
  "subscriptionPlan": "FREE"
}
