### get token from test application
POST http://localhost:8083/api/v1/test/sign
Content-Type: application/json

{
  "sub": "fcad941c-aea5-426f-8f17-428add82aeb1",
  "resource_access": {
    "account": {
      "roles": [
        "manage-account",
        "manage-account-links",
        "view-profile"
      ]
    }
  },
  "email_verified": "false",
  "allowed-origins": [
    "/*"
  ],
  "iss": "http://core-auth.gateway.com:8001/realms/cvhome",
  "typ": "Bearer",
  "preferred_username": "microservice-gateway",
  "given_name": "",
  "sid": "ea59acba-c673-42f5-a374-5e0a30802683",
  "aud": "account",
  "realm_access": {
    "roles": [
      "ADMIN",
      "ROLE_MICROSERVICE",
      "offline_access",
      "uma_authorization",
      "default-roles-cvhome",
      "ROLE_MICROSERVICE_GATEWAY"
    ]
  },
  "azp": "microservice-app",
  "scope": "profile email",
  "session_state": "ea59acba-c673-42f5-a374-5e0a30802683",
  "family_name": "",
  "jti": "84a4b2a4-b463-4df4-9640-c669124402d3"
}

> {%
    client.global.set("access_token", response.body.access_token)
%}



### get token for microservice-dcm
POST http://core-auth.gateway.com:8001/realms/cvhome/protocol/openid-connect/token
Content-Type: application/x-www-form-urlencoded

client_id = microservice-app &
client_secret = r1nuVn4HefusLGwHIeRxbdOzdTZLEMvQ &
grant_type = password &
username = microservice-gateway
    &
password = microservice-gateway

> {%
    client.global.set("access_token", response.body.access_token)
%}


### create store
POST http://localhost:8020/api/v1/store-manager/private/store
Content-Type: application/json
Authorization: Bearer {{access_token}}

{
  "name": "ORG_ADMINss",
  "code": "123456",
  "phone": "+201100000009",
  "email": "email@gmail.com",
  "address": {
    "searchControl": "",
    "stateProvince": "Cario",
    "country": "EG",
    "address": "ashraf",
    "postalCode": "63263",
    "city": "wwwwwwwwww"
  },
  "supportedLanguages": [
    "fr",
    "en"
  ],
  "defaultLanguage": "en",
  "currency": "EGP",
  "currencyFormatNational": true,
  "weight": "KG",
  "dimension": "CM",
  "inBusinessSince": "2024-04-20T19:59:25.053Z",
  "useCache": true,
  "retailer": true
}

### get my stores
GET http://localhost:8083/api/v1/store/me
Authorization: Bearer {{access_token}}


### check store
GET http://localhost:8020/api/v1/store-manager/private/store/unique?name=ali
Content-Type: application/json
Authorization: Bearer {{access_token}}
