spring:
  cloud:
    local:
      discovery:
        enabled: true
        services:
          store:
            - url: "http://localhost:6001"
              metadata:
                service-name: store
                instance: store-1
          landing-ui:
            - url: "http://localhost:6002"
              metadata:
                service-name: landing-ui
                instance: landing-ui-1
    gateway:
      discovery:
        locator:
          enabled: true
      default-filters:
        - TokenRelay
        - PreserveHostHeader
        - AddResponseHeader=X-Frame-Options, SAMEORIGIN
