spring:
  cloud:
    local:
      discovery:
        enabled: true
        services:
          auth:
            - url: "http://localhost:9999"
              metadata:
                service-name: auth
                instance: auth-1
          manager:
            - url: "http://localhost:7001"
              metadata:
                service-name: manager
                instance: manager-1
          'manager.store-core.cvhome.lcl':
            - url: "http://localhost:7001"
              metadata:
                service-name: manager
                instance: manager-1
          store-ui:
            - url: "http://localhost:4200"
              metadata:
                service-name: store-ui
                instance: store-ui-1
          store:
            - url: "http://localhost:7101"
              metadata:
                service-name: store
                instance: store-1
          landing-ui:
            - url: "http://localhost:7102"
              metadata:
                service-name: landing-ui
                instance: landing-ui-1
    gateway:
      discovery:
        locator:
          enabled: true
      default-filters:
        - TokenRelay
        - PreserveHostHeader
        - AddResponseHeader=X-Frame-Options, SAMEORIGIN
      routes:
        - id: landing-ui
          order: 10
          uri: lb://landing-ui
          predicates:
            - FNotService=store,manager,auth
          filters:
            - name: AddStoreParam
              args:
                addRequestHeader: true
                addResponseHeader: true
      x-forwarded:
        host-append: false
        for-append: false