spring:
  cloud:
    loadbalancer:
      eager-load:
        clients:
          - "store-pod-gateway"
          - "store"
          - "landing-ui"
    ecs:
      discovery:
        namespace: "store-pod.cvhome.lcl"
        namespace-id: "ns-je7qri6wn7fbsrpn"
        enabled: true
        default-port: 8080
        service-ports:
          "store": 7101
          "landing-ui": 7102
    gateway:
      discovery:
        locator:
          enabled: true
      default-filters:
        - TokenRelay
        - PreserveHostHeader
        - AddResponseHeader=X-Frame-Options, SAMEORIGIN
      routes:
        - id: landing-ui
          order: 10
          uri: lb://landing-ui
          predicates:
            - FNotService=store,manager,auth
          filters:
            - name: AddStoreParam
              args:
                addRequestHeader: true
                addResponseHeader: true