com:
  asrevo:
    cvhome:
      app:
        domain: "gateway.com"
      saas:
        domain: "gateway.click"
      services:
        auth:
          name: auth
          domain: auth.${com.asrevo.cvhome.app.domain}
          port: 9999
          schema: http
          namespace: store-core.cvhome.lcl
          gateway-service-name: store-core-gateway
        store-core-gateway:
          name: store-core-gateway
          domain: ${com.asrevo.cvhome.app.domain}
          port: 7000
          schema: http
          namespace: store-core.cvhome.lcl
          gateway-service-name: store-core-gateway
        manager:
          name: manager
          domain: ${com.asrevo.cvhome.app.domain}
          port: 7001
          schema: http
          namespace: store-core.cvhome.lcl
          gateway-service-name: store-core-gateway
        store-ui:
          name: store-ui
          domain: store-ui.${com.asrevo.cvhome.app.domain}
          port: 4200
          schema: http
          namespace: store-core.cvhome.lcl
          gateway-service-name: store-core-gateway
        saas-pod-gateway:
          name: saas-pod-gateway
          domain: ${com.asrevo.cvhome.saas.domain}
          port: 8443
          schema: https
          namespace: saas-pod.cvhome.lcl
          gateway-service-name: saas-pod-gateway
        store-pod-gateway:
          name: store-pod-gateway
          domain: store-pod-1.${com.asrevo.cvhome.app.domain}
          port: 7100
          schema: http
          namespace: store-pod.cvhome.lcl
          gateway-service-name: store-pod-gateway
        store:
          name: store
          domain: store-pod-1.${com.asrevo.cvhome.app.domain}
          port: 7101
          schema: http
          namespace: store-pod.cvhome.lcl
          gateway-service-name: store-pod-gateway
        landing-ui:
          name: landing-ui
          domain: store-pod-1.${com.asrevo.cvhome.app.domain}
          port: 7102
          schema: http
          namespace: store-pod.cvhome.lcl
          gateway-service-name: store-pod-gateway
spring:
  security:
    oauth2:
      client:
        registration:
          microservice:
            provider: keycloak
            client-id: microservice-app
            client-secret: r1nuVn4HefusLGwHIeRxbdOzdTZLEMvQ
            authorization-grant-type: password
          keycloak:
            client-id: web-app
            client-authentication-method: client_secret_basic
            authorization-grant-type: authorization_code
            scope: openid, profile, email
            redirect-uri: "{baseUrl}/login/oauth2/code/keycloak"
            provider: keycloak
            client-secret: hLwOF59NEOdMzYYrfxUbQEGVK1uTczj7
        provider:
          keycloak:
            #            comment issuer-uri to skip validation
            #            issuer-uri: https://gateway.com:8443/realms/cvhome
            jwk-set-uri: ${com.asrevo.cvhome.services.auth.schema}://${com.asrevo.cvhome.services.auth.domain}:${com.asrevo.cvhome.services.auth.port}/realms/cvhome/protocol/openid-connect/certs
            authorization-uri: ${com.asrevo.cvhome.services.auth.schema}://${com.asrevo.cvhome.services.auth.domain}:${com.asrevo.cvhome.services.auth.port}/realms/cvhome/protocol/openid-connect/auth
            token-uri: ${com.asrevo.cvhome.services.auth.schema}://${com.asrevo.cvhome.services.auth.domain}:${com.asrevo.cvhome.services.auth.port}/realms/cvhome/protocol/openid-connect/token

      #            need to trace why getting 401 error=invalid_token, auth_method=validate_access_token is by issuer?
      #            user-info-uri: https://auth.gateway.com:8443/realms/cvhome/protocol/openid-connect/userinfo
      #            user-name-attribute: sub
      resourceserver:
        jwt:
          jwk-set-uri: ${com.asrevo.cvhome.services.auth.schema}://${com.asrevo.cvhome.services.auth.domain}:${com.asrevo.cvhome.services.auth.port}/realms/cvhome/protocol/openid-connect/certs
  docker:
    compose:
      file: ${spring.application.name}/compose.yml
  sql:
    init:
      mode: always

springdoc:
  show-actuator: true
  api-docs:
    path: /api-docs
management:
  info:
    env:
      enabled: true
    os:
      enabled: true
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: [ '*' ]
logging:
  level:
    org.springframework.boot: debug
    org.springframework.web: debug
    org.springframework.cloud.gateway: debug
    org.springframework.security: debug
    reactor.netty.http: debug
---
spring:
  application:
    name: store-pod-gateway
server:
  port: ${com.asrevo.cvhome.services.store-pod-gateway.port}
info:
  app:
    name: ${spring.application.name}
management:
  observations:
    key-values:
      application: ${spring.application.name}
