spring:
  config:
    import: "classpath:common-config.yml"
---
spring:
  application:
    name: store-pod-gateway
  security:
    oauth2:
      client:
        registration:
          s2s:
            provider: keycloak
            client-id: gateway@service.store-pod.internal
            client-secret: c27HPNwTPMRI1wstTx9f6EAxFB9J4Ba7
            authorization-grant-type: client_credentials
server:
  forward-headers-strategy: NATIVE
  port: ${com.asrevo.cvhome.services.store-pod-gateway.port}
info:
  app:
    name: ${spring.application.name}
management:
  observations:
    key-values:
      application: ${spring.application.name}
