spring:
  config:
    import: "classpath:lcl-config.yml"
  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: true
          globalcors:
            cors-configurations:
              '[/**]':
                          allowedOrigins: "*"
                          allowedMethods: "*"
                          allowedHeaders: "*"
          x-forwarded:
            host-append: false
            for-append: false
          default-filters:
            - TokenRelay
            - PreserveHostHeader
            - AddResponseHeader=X-Frame-Options, SAMEORIGIN
