// GENERATED by libs/types/scripts/build-color-schemas.mjs (THEME_DEFAULTS.beauty) — edit the seed there, then
// `npm run gen:colors` in libs/types. Same rules as the merchant presets (see that file's header).
import type {ColorSchema} from '@store-front/types';

/**
 * Industrial Quote Grammar: white stockroom cotton, ink plates, the safety-orange zip-tie tag with dark text; hazard-yellow statement. (light)
 *
 * The theme's own palette — what renders when the merchant's colour theme is `DEFAULT` or unset. Wired as
 * `tokens.defaultColors` in `./index.ts`; any fixed preset the merchant picks replaces it whole.
 */
export const DEFAULT_COLORS: ColorSchema = {
    primary: "#FE6A00",
    secondary: "#E9E8E5",
    accent: "#F9C718",
    background: "#FFFFFF",
    foreground: "#0F0F0F",
    error: "#B7191C",
    warning: "#EE9E10",
    success: "#007533",
    info: "#0065A1",
    neutral: "#ABABAB",
    border: "#DEDEDE",
    ring: "#F56600",
    outline: "#CE7951",
    hoverPrimary: "#FF9462",
    focusPrimary: "#FFB390",
    hoverSecondary: "#D2D1CE",
    focusSecondary: "#BFBEBB",
    hoverAccent: "#DFB100",
    focusAccent: "#C89F00",
    hoverError: "#99000D",
    focusError: "#7D0008",
    hoverWarning: "#D38A00",
    focusWarning: "#BA7900",
    hoverSuccess: "#005E28",
    focusSuccess: "#004B1E",
    hoverInfo: "#005182",
    focusInfo: "#004069",
    hoverNeutral: "#959595",
    focusNeutral: "#838383",
};
