-- Pages beyond the six the store shipped with.
--
-- Demo content for the test store 65f020632bc46470c104b76f (Beauté Élégante Paris), in every language the store sells in.
-- Generated seed: ids are negative on purpose — content, media and menu ids all come from sequences that
-- only grow upward, so a seed row below zero can never collide with one the running service creates.

-- page: livraison-et-retours (PUBLISHED)
INSERT INTO content.content (content_id, date_created, date_modified, updt_id, code, content_type, sort_order, visible, store_merchant_id, status, publish_at, unpublish_at, version, created_by, updated_by, parent_id, noindex, canonical_url, og_media_id, show_in_footer, placement, starts_at, ends_at, policy_type, meta)
VALUES (-10001, now(), now(), 'seed', 'livraison-et-retours', 'PAGE', 10, true, '65f020632bc46470c104b76f', 'PUBLISHED', null, null, 1, 'seed', 'seed', null, false, null, null, true, null, null, null, null, null)
on conflict (content_id) do nothing;
INSERT INTO content.content_description (description_id, date_created, date_modified, updt_id, description, name, title, meta_description, meta_keywords, meta_title, sef_url, language_code, content_id, state, excerpt, alt_text, cta_label, subtitle)
VALUES (-100001, now(), now(), 'seed', '<h2>Livraison</h2><p>Toutes les commandes passées avant 14h sont préparées le jour même dans notre atelier du 15 rue de la Paix. Nous expédions en Colissimo suivi (2 à 3 jours ouvrés) et en Chronopost 13h pour Paris intra-muros.</p><ul><li>France métropolitaine : 4,90 € — offerte dès 60 €</li><li>Union européenne : 9,90 € — offerte dès 120 €</li><li>Retrait boutique : gratuit, sous 2 heures</li></ul><h2>Retours</h2><p>Vous disposez de 30 jours pour changer d''avis. Les produits doivent être non ouverts et dans leur emballage d''origine ; les cosmétiques descellés ne peuvent être repris pour des raisons d''hygiène.</p><p>Le remboursement est effectué sous 5 jours ouvrés après réception du colis, sur le moyen de paiement d''origine.</p>', 'Livraison et retours', 'Livraison et retours', 'Délais, tarifs et conditions de retour pour toutes vos commandes en France métropolitaine et en Europe.', 'livraison, retours, colissimo, chronopost', 'Livraison et retours | Beauté Élégante Paris', 'livraison-et-retours', 'fr', -10001, 'TRANSLATED', null, null, null, null)
on conflict (description_id) do nothing;
INSERT INTO content.content_description (description_id, date_created, date_modified, updt_id, description, name, title, meta_description, meta_keywords, meta_title, sef_url, language_code, content_id, state, excerpt, alt_text, cta_label, subtitle)
VALUES (-100002, now(), now(), 'seed', '<h2>Shipping</h2><p>Orders placed before 2pm are packed the same day in our workshop at 15 rue de la Paix. We ship with tracked Colissimo (2–3 working days) and Chronopost 13h inside Paris.</p><ul><li>Mainland France: €4.90 — free over €60</li><li>European Union: €9.90 — free over €120</li><li>Boutique pickup: free, ready in 2 hours</li></ul><h2>Returns</h2><p>You have 30 days to change your mind. Items must be unopened and in their original packaging; for hygiene reasons unsealed cosmetics cannot be taken back.</p><p>Refunds are issued within 5 working days of the parcel arriving, to the original payment method.</p>', 'Shipping & returns', 'Shipping & returns', 'Delivery times, rates and return conditions for orders across France and the European Union.', 'shipping, returns, delivery, europe', 'Shipping & returns | Beauté Élégante Paris', 'shipping-and-returns', 'en', -10001, 'TRANSLATED', null, null, null, null)
on conflict (description_id) do nothing;

-- page: nos-ingredients (PUBLISHED)
INSERT INTO content.content (content_id, date_created, date_modified, updt_id, code, content_type, sort_order, visible, store_merchant_id, status, publish_at, unpublish_at, version, created_by, updated_by, parent_id, noindex, canonical_url, og_media_id, show_in_footer, placement, starts_at, ends_at, policy_type, meta)
VALUES (-10002, now(), now(), 'seed', 'nos-ingredients', 'PAGE', 11, true, '65f020632bc46470c104b76f', 'PUBLISHED', null, null, 1, 'seed', 'seed', null, false, null, null, false, null, null, null, null, null)
on conflict (content_id) do nothing;
INSERT INTO content.content_description (description_id, date_created, date_modified, updt_id, description, name, title, meta_description, meta_keywords, meta_title, sef_url, language_code, content_id, state, excerpt, alt_text, cta_label, subtitle)
VALUES (-100003, now(), now(), 'seed', '<h2>Une charte, pas un argument</h2><p>Chaque formule Beauté Élégante est développée avec un laboratoire de Loire-Atlantique et validée par une évaluation toxicologique indépendante avant sa mise sur le marché.</p><h3>Ce que nous utilisons</h3><ul><li>Actifs dosés au pourcentage utile : niacinamide 5 %, acide hyaluronique 2 %, rétinal 0,05 %</li><li>Émulsions à 92 % minimum d''ingrédients d''origine naturelle</li><li>Parfums sans allergènes listés au règlement CE 1223/2009</li></ul><h3>Ce que nous excluons</h3><ul><li>Sulfates agressifs (SLS, SLES)</li><li>Silicones non biodégradables</li><li>Filtres UV controversés (oxybenzone, octinoxate)</li></ul><p>La liste INCI complète figure sur chaque fiche produit, dans l''ordre décroissant de concentration.</p>', 'Nos ingrédients', 'Nos ingrédients', 'La charte de formulation Beauté Élégante : origine naturelle, actifs dosés, listes noires et traçabilité.', 'ingrédients, clean beauty, formulation', 'Nos ingrédients | Beauté Élégante Paris', 'nos-ingredients', 'fr', -10002, 'TRANSLATED', null, null, null, null)
on conflict (description_id) do nothing;
INSERT INTO content.content_description (description_id, date_created, date_modified, updt_id, description, name, title, meta_description, meta_keywords, meta_title, sef_url, language_code, content_id, state, excerpt, alt_text, cta_label, subtitle)
VALUES (-100004, now(), now(), 'seed', '<h2>A charter, not a slogan</h2><p>Every Beauté Élégante formula is developed with a laboratory in Loire-Atlantique and cleared by an independent toxicological assessment before it goes on sale.</p><h3>What we use</h3><ul><li>Actives at a useful percentage: 5% niacinamide, 2% hyaluronic acid, 0.05% retinal</li><li>Emulsions with at least 92% ingredients of natural origin</li><li>Fragrances free of the allergens listed in EC regulation 1223/2009</li></ul><h3>What we leave out</h3><ul><li>Harsh sulfates (SLS, SLES)</li><li>Non-biodegradable silicones</li><li>Contested UV filters (oxybenzone, octinoxate)</li></ul><p>The full INCI list is on every product page, in descending order of concentration.</p>', 'Our ingredients', 'Our ingredients', 'The Beauté Élégante formulation charter: natural origin, active percentages, blacklists and traceability.', 'ingredients, clean beauty, formulation', 'Our ingredients | Beauté Élégante Paris', 'our-ingredients', 'en', -10002, 'TRANSLATED', null, null, null, null)
on conflict (description_id) do nothing;

-- page: carrieres (PUBLISHED)
INSERT INTO content.content (content_id, date_created, date_modified, updt_id, code, content_type, sort_order, visible, store_merchant_id, status, publish_at, unpublish_at, version, created_by, updated_by, parent_id, noindex, canonical_url, og_media_id, show_in_footer, placement, starts_at, ends_at, policy_type, meta)
VALUES (-10003, now(), now(), 'seed', 'carrieres', 'PAGE', 12, true, '65f020632bc46470c104b76f', 'PUBLISHED', null, null, 1, 'seed', 'seed', null, false, null, null, true, null, null, null, null, null)
on conflict (content_id) do nothing;
INSERT INTO content.content_description (description_id, date_created, date_modified, updt_id, description, name, title, meta_description, meta_keywords, meta_title, sef_url, language_code, content_id, state, excerpt, alt_text, cta_label, subtitle)
VALUES (-100005, now(), now(), 'seed', '<h2>Travailler chez Beauté Élégante</h2><p>Nous sommes vingt-quatre, entre la boutique du 2e arrondissement, l''atelier de préparation et une petite équipe produit.</p><h3>Postes ouverts</h3><ul><li>Conseiller·ère beauté — CDI, Paris 2e</li><li>Chargé·e de formulation — CDI, Nantes</li><li>Alternance e-commerce — 12 mois, Paris</li></ul><p>Écrivez à <a href="mailto:recrutement@beaute-elegante.fr">recrutement@beaute-elegante.fr</a> en nous disant surtout pourquoi ce métier-là.</p>', 'Carrières', 'Carrières', 'Postes ouverts en boutique, à l''atelier et au siège parisien.', 'emploi, recrutement, carrière', 'Carrières | Beauté Élégante Paris', 'carrieres', 'fr', -10003, 'TRANSLATED', null, null, null, null)
on conflict (description_id) do nothing;
INSERT INTO content.content_description (description_id, date_created, date_modified, updt_id, description, name, title, meta_description, meta_keywords, meta_title, sef_url, language_code, content_id, state, excerpt, alt_text, cta_label, subtitle)
VALUES (-100006, now(), now(), 'seed', '<h2>Working at Beauté Élégante</h2><p>There are twenty-four of us, between the boutique in the 2nd arrondissement, the packing workshop and a small product team.</p><h3>Open roles</h3><ul><li>Beauty advisor — permanent, Paris 2e</li><li>Formulation lead — permanent, Nantes</li><li>E-commerce apprentice — 12 months, Paris</li></ul><p>Write to <a href="mailto:recrutement@beaute-elegante.fr">recrutement@beaute-elegante.fr</a> and tell us, above all, why this particular craft.</p>', 'Careers', 'Careers', 'Open roles in the boutique, the workshop and the Paris head office.', 'jobs, hiring, careers', 'Careers | Beauté Élégante Paris', 'careers', 'en', -10003, 'TRANSLATED', null, null, null, null)
on conflict (description_id) do nothing;

-- page: presse (PUBLISHED)
INSERT INTO content.content (content_id, date_created, date_modified, updt_id, code, content_type, sort_order, visible, store_merchant_id, status, publish_at, unpublish_at, version, created_by, updated_by, parent_id, noindex, canonical_url, og_media_id, show_in_footer, placement, starts_at, ends_at, policy_type, meta)
VALUES (-10004, now(), now(), 'seed', 'presse', 'PAGE', 13, true, '65f020632bc46470c104b76f', 'PUBLISHED', null, null, 1, 'seed', 'seed', (select content_id from content.content where store_merchant_id = '65f020632bc46470c104b76f' and code = 'about-us'), false, null, null, false, null, null, null, null, null)
on conflict (content_id) do nothing;
INSERT INTO content.content_description (description_id, date_created, date_modified, updt_id, description, name, title, meta_description, meta_keywords, meta_title, sef_url, language_code, content_id, state, excerpt, alt_text, cta_label, subtitle)
VALUES (-100007, now(), now(), 'seed', '<h2>Espace presse</h2><p>Cette page est rattachée à « À propos » : elle sert aussi à vérifier le fil d''Ariane du storefront, qui doit afficher Accueil › À propos › Espace presse.</p><p>Contact : Claire Bouvier — <a href="mailto:presse@beaute-elegante.fr">presse@beaute-elegante.fr</a> — +33 1 23 45 67 90.</p><h3>Derniers communiqués</h3><ul><li>Ouverture de l''atelier de Nantes — mars 2026</li><li>Recharges verre consignées pour toute la gamme soin — janvier 2026</li></ul>', 'Espace presse', 'Espace presse', 'Communiqués, visuels haute définition et contacts presse.', 'presse, média, communiqué', 'Espace presse | Beauté Élégante Paris', 'presse', 'fr', -10004, 'TRANSLATED', null, null, null, null)
on conflict (description_id) do nothing;
INSERT INTO content.content_description (description_id, date_created, date_modified, updt_id, description, name, title, meta_description, meta_keywords, meta_title, sef_url, language_code, content_id, state, excerpt, alt_text, cta_label, subtitle)
VALUES (-100008, now(), now(), 'seed', '<h2>Press room</h2><p>This page hangs off “About us”, which also makes it the check on the storefront breadcrumb: it should read Home › About us › Press room.</p><p>Contact: Claire Bouvier — <a href="mailto:presse@beaute-elegante.fr">presse@beaute-elegante.fr</a> — +33 1 23 45 67 90.</p><h3>Recent releases</h3><ul><li>The Nantes workshop opens — March 2026</li><li>Returnable glass refills across the skincare range — January 2026</li></ul>', 'Press room', 'Press room', 'Press releases, high-resolution imagery and media contacts.', 'press, media, releases', 'Press room | Beauté Élégante Paris', 'press-room', 'en', -10004, 'TRANSLATED', null, null, null, null)
on conflict (description_id) do nothing;

-- page: cartes-cadeaux (PUBLISHED)
INSERT INTO content.content (content_id, date_created, date_modified, updt_id, code, content_type, sort_order, visible, store_merchant_id, status, publish_at, unpublish_at, version, created_by, updated_by, parent_id, noindex, canonical_url, og_media_id, show_in_footer, placement, starts_at, ends_at, policy_type, meta)
VALUES (-10005, now(), now(), 'seed', 'cartes-cadeaux', 'PAGE', 14, true, '65f020632bc46470c104b76f', 'PUBLISHED', null, null, 1, 'seed', 'seed', null, false, 'https://org2-store1.asrevo.com/content/cartes-cadeaux', -190002, true, null, null, null, null, null)
on conflict (content_id) do nothing;
INSERT INTO content.content_description (description_id, date_created, date_modified, updt_id, description, name, title, meta_description, meta_keywords, meta_title, sef_url, language_code, content_id, state, excerpt, alt_text, cta_label, subtitle)
VALUES (-100009, now(), now(), 'seed', '<h2>Offrir le bon geste</h2><p>Nos cartes cadeaux existent de 25 à 250 €, en version numérique envoyée immédiatement ou en carte imprimée sur papier Munken, glissée dans un étui toilé.</p><p>Elles sont valables deux ans, utilisables en ligne comme en boutique, et le solde restant est conservé.</p><p>Cette page porte une URL canonique et une image Open Graph : de quoi vérifier le rendu SEO du storefront.</p>', 'Cartes cadeaux', 'Cartes cadeaux', 'Cartes cadeaux de 25 à 250 €, valables deux ans en ligne et en boutique.', 'carte cadeau, bon d''achat', 'Cartes cadeaux | Beauté Élégante Paris', 'cartes-cadeaux', 'fr', -10005, 'TRANSLATED', null, null, null, null)
on conflict (description_id) do nothing;
INSERT INTO content.content_description (description_id, date_created, date_modified, updt_id, description, name, title, meta_description, meta_keywords, meta_title, sef_url, language_code, content_id, state, excerpt, alt_text, cta_label, subtitle)
VALUES (-100010, now(), now(), 'seed', '<h2>The right gesture, wrapped</h2><p>Our gift cards run from €25 to €250, either digital and sent straight away or printed on Munken paper and slipped into a cloth sleeve.</p><p>They are valid for two years, usable online and in the boutique, and any remaining balance is kept.</p><p>This page carries a canonical URL and an Open Graph image, which makes it the check on the storefront''s SEO rendering.</p>', 'Gift cards', 'Gift cards', 'Gift cards from €25 to €250, valid for two years online and in the boutique.', 'gift card, voucher', 'Gift cards | Beauté Élégante Paris', 'gift-cards', 'en', -10005, 'TRANSLATED', null, null, null, null)
on conflict (description_id) do nothing;

-- page: engagement-durable (PUBLISHED)
INSERT INTO content.content (content_id, date_created, date_modified, updt_id, code, content_type, sort_order, visible, store_merchant_id, status, publish_at, unpublish_at, version, created_by, updated_by, parent_id, noindex, canonical_url, og_media_id, show_in_footer, placement, starts_at, ends_at, policy_type, meta)
VALUES (-10006, now(), now(), 'seed', 'engagement-durable', 'PAGE', 15, true, '65f020632bc46470c104b76f', 'PUBLISHED', null, null, 1, 'seed', 'seed', null, true, null, null, false, null, null, null, null, null)
on conflict (content_id) do nothing;
INSERT INTO content.content_description (description_id, date_created, date_modified, updt_id, description, name, title, meta_description, meta_keywords, meta_title, sef_url, language_code, content_id, state, excerpt, alt_text, cta_label, subtitle)
VALUES (-100011, now(), now(), 'seed', '<h2>Ce que nous mesurons</h2><p>Cette page est marquée <code>noindex</code> : elle doit s''afficher normalement dans la boutique mais sortir du sitemap. C''est le contrôle du drapeau SEO.</p><ul><li>78 % de la gamme soin disponible en recharge</li><li>Consigne verre remboursée 3 € en boutique</li><li>Livraison neutre en carbone via compensation Colissimo</li></ul>', 'Engagement durable', 'Engagement durable', 'Recharges, consigne verre et empreinte carbone — page volontairement exclue de l''indexation.', 'durable, recharge, consigne', 'Engagement durable | Beauté Élégante Paris', 'engagement-durable', 'fr', -10006, 'TRANSLATED', null, null, null, null)
on conflict (description_id) do nothing;
INSERT INTO content.content_description (description_id, date_created, date_modified, updt_id, description, name, title, meta_description, meta_keywords, meta_title, sef_url, language_code, content_id, state, excerpt, alt_text, cta_label, subtitle)
VALUES (-100012, now(), now(), 'seed', '<h2>What we measure</h2><p>This page is flagged <code>noindex</code>: it should render normally in the storefront but stay out of the sitemap. That is the check on the SEO flag.</p><ul><li>78% of the skincare range available as a refill</li><li>€3 back in the boutique on returned glass</li><li>Carbon-neutral delivery through Colissimo offsetting</li></ul>', 'Sustainability', 'Sustainability', 'Refills, glass deposit and carbon footprint — a page deliberately kept out of the index.', 'sustainability, refill, deposit', 'Sustainability | Beauté Élégante Paris', 'sustainability', 'en', -10006, 'TRANSLATED', null, null, null, null)
on conflict (description_id) do nothing;

-- page: soldes-privees (SCHEDULED)
INSERT INTO content.content (content_id, date_created, date_modified, updt_id, code, content_type, sort_order, visible, store_merchant_id, status, publish_at, unpublish_at, version, created_by, updated_by, parent_id, noindex, canonical_url, og_media_id, show_in_footer, placement, starts_at, ends_at, policy_type, meta)
VALUES (-10007, now(), now(), 'seed', 'soldes-privees', 'PAGE', 16, true, '65f020632bc46470c104b76f', 'SCHEDULED', now() + interval '21 days', null, 1, 'seed', 'seed', null, false, null, null, false, null, null, null, null, null)
on conflict (content_id) do nothing;
INSERT INTO content.content_description (description_id, date_created, date_modified, updt_id, description, name, title, meta_description, meta_keywords, meta_title, sef_url, language_code, content_id, state, excerpt, alt_text, cta_label, subtitle)
VALUES (-100013, now(), now(), 'seed', '<h2>Ventes privées</h2><p>Cette page est en statut <strong>SCHEDULED</strong> avec une publication dans trois semaines. Elle doit être visible dans la console et renvoyer 404 côté boutique.</p>', 'Ventes privées (programmée)', 'Ventes privées (programmée)', 'Page programmée : elle ne doit pas apparaître dans la boutique avant sa date de publication.', 'ventes privées, soldes', 'Ventes privées | Beauté Élégante Paris', 'soldes-privees', 'fr', -10007, 'TRANSLATED', null, null, null, null)
on conflict (description_id) do nothing;
INSERT INTO content.content_description (description_id, date_created, date_modified, updt_id, description, name, title, meta_description, meta_keywords, meta_title, sef_url, language_code, content_id, state, excerpt, alt_text, cta_label, subtitle)
VALUES (-100014, now(), now(), 'seed', '<h2>Private sale</h2><p>This page is <strong>SCHEDULED</strong> to publish in three weeks. It should be visible in the console and 404 in the storefront.</p>', 'Private sale (scheduled)', 'Private sale (scheduled)', 'A scheduled page: it must not appear in the storefront before its publish date.', 'private sale, promotion', 'Private sale | Beauté Élégante Paris', 'private-sale', 'en', -10007, 'TRANSLATED', null, null, null, null)
on conflict (description_id) do nothing;

-- page: guide-teintes-2024 (ARCHIVED)
INSERT INTO content.content (content_id, date_created, date_modified, updt_id, code, content_type, sort_order, visible, store_merchant_id, status, publish_at, unpublish_at, version, created_by, updated_by, parent_id, noindex, canonical_url, og_media_id, show_in_footer, placement, starts_at, ends_at, policy_type, meta)
VALUES (-10008, now(), now(), 'seed', 'guide-teintes-2024', 'PAGE', 17, false, '65f020632bc46470c104b76f', 'ARCHIVED', null, null, 1, 'seed', 'seed', null, false, null, null, false, null, null, null, null, null)
on conflict (content_id) do nothing;
INSERT INTO content.content_description (description_id, date_created, date_modified, updt_id, description, name, title, meta_description, meta_keywords, meta_title, sef_url, language_code, content_id, state, excerpt, alt_text, cta_label, subtitle)
VALUES (-100015, now(), now(), 'seed', '<h2>Guide des teintes 2024</h2><p>Archivé : remplacé par le guide 2026. Doit rester invisible dans la boutique.</p>', 'Guide des teintes 2024 (archivé)', 'Guide des teintes 2024 (archivé)', null, null, null, 'guide-teintes-2024', 'fr', -10008, 'TRANSLATED', null, null, null, null)
on conflict (description_id) do nothing;
INSERT INTO content.content_description (description_id, date_created, date_modified, updt_id, description, name, title, meta_description, meta_keywords, meta_title, sef_url, language_code, content_id, state, excerpt, alt_text, cta_label, subtitle)
VALUES (-100016, now(), now(), 'seed', '<h2>Shade guide 2024</h2><p>Archived, replaced by the 2026 guide. Must stay invisible in the storefront.</p>', 'Shade guide 2024 (archived)', 'Shade guide 2024 (archived)', null, null, null, 'shade-guide-2024', 'en', -10008, 'TRANSLATED', null, null, null, null)
on conflict (description_id) do nothing;

-- page: ateliers-maquillage (DRAFT)
INSERT INTO content.content (content_id, date_created, date_modified, updt_id, code, content_type, sort_order, visible, store_merchant_id, status, publish_at, unpublish_at, version, created_by, updated_by, parent_id, noindex, canonical_url, og_media_id, show_in_footer, placement, starts_at, ends_at, policy_type, meta)
VALUES (-10009, now(), now(), 'seed', 'ateliers-maquillage', 'PAGE', 18, true, '65f020632bc46470c104b76f', 'DRAFT', null, null, 1, 'seed', 'seed', null, false, null, null, false, null, null, null, null, null)
on conflict (content_id) do nothing;
INSERT INTO content.content_description (description_id, date_created, date_modified, updt_id, description, name, title, meta_description, meta_keywords, meta_title, sef_url, language_code, content_id, state, excerpt, alt_text, cta_label, subtitle)
VALUES (-100017, now(), now(), 'seed', '<h2>Ateliers maquillage</h2><p>Brouillon en cours de rédaction. Invisible côté boutique, éditable dans la console.</p>', 'Ateliers maquillage (brouillon)', 'Ateliers maquillage (brouillon)', null, null, null, 'ateliers-maquillage', 'fr', -10009, 'DRAFT', null, null, null, null)
on conflict (description_id) do nothing;
INSERT INTO content.content_description (description_id, date_created, date_modified, updt_id, description, name, title, meta_description, meta_keywords, meta_title, sef_url, language_code, content_id, state, excerpt, alt_text, cta_label, subtitle)
VALUES (-100018, now(), now(), 'seed', '<h2>Make-up workshops</h2><p>A draft still being written. Invisible in the storefront, editable in the console.</p>', 'Make-up workshops (draft)', 'Make-up workshops (draft)', null, null, null, 'makeup-workshops', 'en', -10009, 'DRAFT', null, null, null, null)
on conflict (description_id) do nothing;

-- pages the store already had, promoted into the footer
UPDATE content.content SET show_in_footer = true
 WHERE store_merchant_id = '65f020632bc46470c104b76f' AND content_type = 'PAGE' AND code IN ('about-us', 'contact-us');
