-- Legal policies, each with a live version.
--
-- Demo content for the test store 65f020632bc46470c104b76f (Beauté Élégante Paris), in every language the store sells in.
-- Generated seed: ids are negative on purpose — content, media and menu ids all come from sequences that
-- only grow upward, so a seed row below zero can never collide with one the running service creates.

-- policy: PRIVACY
INSERT INTO content.content (content_id, date_created, date_modified, updt_id, code, content_type, sort_order, visible, store_merchant_id, status, publish_at, unpublish_at, version, created_by, updated_by, parent_id, noindex, canonical_url, og_media_id, show_in_footer, placement, starts_at, ends_at, policy_type, meta)
VALUES (-10010, now(), now(), 'seed', 'politique-confidentialite', 'POLICY', 100, true, '65f020632bc46470c104b76f', 'PUBLISHED', null, null, 1, 'seed', 'seed', null, false, null, null, false, null, null, null, 'PRIVACY', '{"jurisdiction": null, "requiresAcceptance": false, "notifyCustomers": false, "displayAt": {"footer": true, "checkout": false, "signup": false}}')
on conflict (content_id) do nothing;
INSERT INTO content.content_description (description_id, date_created, date_modified, updt_id, description, name, title, meta_description, meta_keywords, meta_title, sef_url, language_code, content_id, state, excerpt, alt_text, cta_label, subtitle)
VALUES (-100019, now(), now(), 'seed', '<h2>Politique de confidentialité</h2><p>Beauté Élégante Paris, 15 rue de la Paix, 75002 Paris, est responsable du traitement de vos données au sens du RGPD.</p><h3>Données collectées</h3><ul><li>Identité et coordonnées de livraison</li><li>Historique de commandes et de retours</li><li>Données de navigation, si vous acceptez les cookies de mesure</li></ul><h3>Durées de conservation</h3><p>Les données de commande sont conservées dix ans au titre des obligations comptables ; les données de compte, trois ans après votre dernière activité.</p><h3>Vos droits</h3><p>Accès, rectification, effacement, portabilité et opposition s''exercent auprès de <a href="mailto:dpo@beaute-elegante.fr">dpo@beaute-elegante.fr</a>. Vous pouvez saisir la CNIL à tout moment.</p>', 'Politique de confidentialité', 'Politique de confidentialité', null, null, null, null, 'fr', -10010, 'TRANSLATED', null, null, null, null)
on conflict (description_id) do nothing;
INSERT INTO content.content_description (description_id, date_created, date_modified, updt_id, description, name, title, meta_description, meta_keywords, meta_title, sef_url, language_code, content_id, state, excerpt, alt_text, cta_label, subtitle)
VALUES (-100020, now(), now(), 'seed', '<h2>Privacy policy</h2><p>Beauté Élégante Paris, 15 rue de la Paix, 75002 Paris, is the controller of your data under the GDPR.</p><h3>What we collect</h3><ul><li>Identity and delivery details</li><li>Order and return history</li><li>Browsing data, if you accept measurement cookies</li></ul><h3>How long we keep it</h3><p>Order data is kept for ten years under accounting obligations; account data for three years after your last activity.</p><h3>Your rights</h3><p>Access, rectification, erasure, portability and objection can be exercised at <a href="mailto:dpo@beaute-elegante.fr">dpo@beaute-elegante.fr</a>. You may lodge a complaint with the CNIL at any time.</p>', 'Privacy policy', 'Privacy policy', null, null, null, null, 'en', -10010, 'TRANSLATED', null, null, null, null)
on conflict (description_id) do nothing;
INSERT INTO content.policy_version (id, store_merchant_id, content_id, version, status, effective_from, note, translations, published_at, published_by)
VALUES (-1001, '65f020632bc46470c104b76f', -10010, 1, 'LIVE', now() - interval '30 days', null, '[{"language": "fr", "title": "Politique de confidentialité", "body": "<h2>Politique de confidentialité</h2><p>Beauté Élégante Paris, 15 rue de la Paix, 75002 Paris, est responsable du traitement de vos données au sens du RGPD.</p><h3>Données collectées</h3><ul><li>Identité et coordonnées de livraison</li><li>Historique de commandes et de retours</li><li>Données de navigation, si vous acceptez les cookies de mesure</li></ul><h3>Durées de conservation</h3><p>Les données de commande sont conservées dix ans au titre des obligations comptables ; les données de compte, trois ans après votre dernière activité.</p><h3>Vos droits</h3><p>Accès, rectification, effacement, portabilité et opposition s''exercent auprès de <a href=\"mailto:dpo@beaute-elegante.fr\">dpo@beaute-elegante.fr</a>. Vous pouvez saisir la CNIL à tout moment.</p>", "state": "TRANSLATED"}, {"language": "en", "title": "Privacy policy", "body": "<h2>Privacy policy</h2><p>Beauté Élégante Paris, 15 rue de la Paix, 75002 Paris, is the controller of your data under the GDPR.</p><h3>What we collect</h3><ul><li>Identity and delivery details</li><li>Order and return history</li><li>Browsing data, if you accept measurement cookies</li></ul><h3>How long we keep it</h3><p>Order data is kept for ten years under accounting obligations; account data for three years after your last activity.</p><h3>Your rights</h3><p>Access, rectification, erasure, portability and objection can be exercised at <a href=\"mailto:dpo@beaute-elegante.fr\">dpo@beaute-elegante.fr</a>. You may lodge a complaint with the CNIL at any time.</p>", "state": "TRANSLATED"}]', now(), 'seed')
on conflict (id) do nothing;

-- policy: RETURNS
INSERT INTO content.content (content_id, date_created, date_modified, updt_id, code, content_type, sort_order, visible, store_merchant_id, status, publish_at, unpublish_at, version, created_by, updated_by, parent_id, noindex, canonical_url, og_media_id, show_in_footer, placement, starts_at, ends_at, policy_type, meta)
VALUES (-10011, now(), now(), 'seed', 'politique-retours', 'POLICY', 101, true, '65f020632bc46470c104b76f', 'PUBLISHED', null, null, 1, 'seed', 'seed', null, false, null, null, false, null, null, null, 'RETURNS', '{"jurisdiction": null, "requiresAcceptance": false, "notifyCustomers": false, "displayAt": {"footer": true, "checkout": false, "signup": false}}')
on conflict (content_id) do nothing;
INSERT INTO content.content_description (description_id, date_created, date_modified, updt_id, description, name, title, meta_description, meta_keywords, meta_title, sef_url, language_code, content_id, state, excerpt, alt_text, cta_label, subtitle)
VALUES (-100021, now(), now(), 'seed', '<h2>Politique de retour</h2><p>Trente jours pour changer d''avis, à compter de la réception du colis.</p><h3>Conditions</h3><ul><li>Produit non ouvert, scellé d''hygiène intact</li><li>Emballage d''origine et preuve d''achat</li><li>Étiquette de retour prépayée fournie dans votre espace client</li></ul><h3>Remboursement</h3><p>Sous cinq jours ouvrés après réception, sur le moyen de paiement d''origine. Les frais de livraison initiaux sont remboursés en cas de produit défectueux.</p><p><em>Version 2 — les retours en boutique sont désormais acceptés sans rendez-vous.</em></p>', 'Politique de retour', 'Politique de retour', null, null, null, null, 'fr', -10011, 'TRANSLATED', null, null, null, null)
on conflict (description_id) do nothing;
INSERT INTO content.content_description (description_id, date_created, date_modified, updt_id, description, name, title, meta_description, meta_keywords, meta_title, sef_url, language_code, content_id, state, excerpt, alt_text, cta_label, subtitle)
VALUES (-100022, now(), now(), 'seed', '<h2>Returns policy</h2><p>Thirty days to change your mind, counted from the day the parcel arrives.</p><h3>Conditions</h3><ul><li>Unopened item with the hygiene seal intact</li><li>Original packaging and proof of purchase</li><li>A prepaid return label, available in your account</li></ul><h3>Refunds</h3><p>Within five working days of receipt, to the original payment method. Original delivery charges are refunded when the item is faulty.</p><p><em>Version 2 — boutique returns are now accepted without an appointment.</em></p>', 'Returns policy', 'Returns policy', null, null, null, null, 'en', -10011, 'TRANSLATED', null, null, null, null)
on conflict (description_id) do nothing;
INSERT INTO content.policy_version (id, store_merchant_id, content_id, version, status, effective_from, note, translations, published_at, published_by)
VALUES (-1002, '65f020632bc46470c104b76f', -10011, 1, 'ARCHIVED', now() - interval '400 days', 'Initial version', '[{"language": "fr", "title": "Politique de retour", "body": "<h2>Politique de retour</h2><p>Quatorze jours pour changer d''avis. Retours en boutique sur rendez-vous uniquement.</p><p><em>Version 1 — archivée.</em></p>", "state": "TRANSLATED"}, {"language": "en", "title": "Returns policy", "body": "<h2>Returns policy</h2><p>Fourteen days to change your mind. Boutique returns by appointment only.</p><p><em>Version 1 — archived.</em></p>", "state": "TRANSLATED"}]', now(), 'seed')
on conflict (id) do nothing;
INSERT INTO content.policy_version (id, store_merchant_id, content_id, version, status, effective_from, note, translations, published_at, published_by)
VALUES (-1003, '65f020632bc46470c104b76f', -10011, 2, 'LIVE', now() - interval '30 days', 'Second version', '[{"language": "fr", "title": "Politique de retour", "body": "<h2>Politique de retour</h2><p>Trente jours pour changer d''avis, à compter de la réception du colis.</p><h3>Conditions</h3><ul><li>Produit non ouvert, scellé d''hygiène intact</li><li>Emballage d''origine et preuve d''achat</li><li>Étiquette de retour prépayée fournie dans votre espace client</li></ul><h3>Remboursement</h3><p>Sous cinq jours ouvrés après réception, sur le moyen de paiement d''origine. Les frais de livraison initiaux sont remboursés en cas de produit défectueux.</p><p><em>Version 2 — les retours en boutique sont désormais acceptés sans rendez-vous.</em></p>", "state": "TRANSLATED"}, {"language": "en", "title": "Returns policy", "body": "<h2>Returns policy</h2><p>Thirty days to change your mind, counted from the day the parcel arrives.</p><h3>Conditions</h3><ul><li>Unopened item with the hygiene seal intact</li><li>Original packaging and proof of purchase</li><li>A prepaid return label, available in your account</li></ul><h3>Refunds</h3><p>Within five working days of receipt, to the original payment method. Original delivery charges are refunded when the item is faulty.</p><p><em>Version 2 — boutique returns are now accepted without an appointment.</em></p>", "state": "TRANSLATED"}]', now(), 'seed')
on conflict (id) do nothing;

-- policy: SHIPPING
INSERT INTO content.content (content_id, date_created, date_modified, updt_id, code, content_type, sort_order, visible, store_merchant_id, status, publish_at, unpublish_at, version, created_by, updated_by, parent_id, noindex, canonical_url, og_media_id, show_in_footer, placement, starts_at, ends_at, policy_type, meta)
VALUES (-10012, now(), now(), 'seed', 'politique-expedition', 'POLICY', 102, true, '65f020632bc46470c104b76f', 'PUBLISHED', null, null, 1, 'seed', 'seed', null, false, null, null, false, null, null, null, 'SHIPPING', '{"jurisdiction": null, "requiresAcceptance": false, "notifyCustomers": false, "displayAt": {"footer": true, "checkout": false, "signup": false}}')
on conflict (content_id) do nothing;
INSERT INTO content.content_description (description_id, date_created, date_modified, updt_id, description, name, title, meta_description, meta_keywords, meta_title, sef_url, language_code, content_id, state, excerpt, alt_text, cta_label, subtitle)
VALUES (-100023, now(), now(), 'seed', '<h2>Conditions de livraison</h2><p>Préparation le jour même pour toute commande validée avant 14h, du lundi au vendredi.</p><table><tr><th>Destination</th><th>Délai</th><th>Tarif</th></tr><tr><td>France métropolitaine</td><td>2–3 jours</td><td>4,90 €</td></tr><tr><td>Union européenne</td><td>3–6 jours</td><td>9,90 €</td></tr><tr><td>Suisse et Royaume-Uni</td><td>4–8 jours</td><td>14,90 €</td></tr></table><p>Les droits de douane éventuels hors UE restent à la charge du destinataire.</p>', 'Conditions de livraison', 'Conditions de livraison', null, null, null, null, 'fr', -10012, 'TRANSLATED', null, null, null, null)
on conflict (description_id) do nothing;
INSERT INTO content.content_description (description_id, date_created, date_modified, updt_id, description, name, title, meta_description, meta_keywords, meta_title, sef_url, language_code, content_id, state, excerpt, alt_text, cta_label, subtitle)
VALUES (-100024, now(), now(), 'seed', '<h2>Shipping policy</h2><p>Same-day packing for every order confirmed before 2pm, Monday to Friday.</p><table><tr><th>Destination</th><th>Time</th><th>Rate</th></tr><tr><td>Mainland France</td><td>2–3 days</td><td>€4.90</td></tr><tr><td>European Union</td><td>3–6 days</td><td>€9.90</td></tr><tr><td>Switzerland and the UK</td><td>4–8 days</td><td>€14.90</td></tr></table><p>Any customs duties outside the EU are payable by the recipient.</p>', 'Shipping policy', 'Shipping policy', null, null, null, null, 'en', -10012, 'TRANSLATED', null, null, null, null)
on conflict (description_id) do nothing;
INSERT INTO content.policy_version (id, store_merchant_id, content_id, version, status, effective_from, note, translations, published_at, published_by)
VALUES (-1004, '65f020632bc46470c104b76f', -10012, 1, 'LIVE', now() - interval '30 days', null, '[{"language": "fr", "title": "Conditions de livraison", "body": "<h2>Conditions de livraison</h2><p>Préparation le jour même pour toute commande validée avant 14h, du lundi au vendredi.</p><table><tr><th>Destination</th><th>Délai</th><th>Tarif</th></tr><tr><td>France métropolitaine</td><td>2–3 jours</td><td>4,90 €</td></tr><tr><td>Union européenne</td><td>3–6 jours</td><td>9,90 €</td></tr><tr><td>Suisse et Royaume-Uni</td><td>4–8 jours</td><td>14,90 €</td></tr></table><p>Les droits de douane éventuels hors UE restent à la charge du destinataire.</p>", "state": "TRANSLATED"}, {"language": "en", "title": "Shipping policy", "body": "<h2>Shipping policy</h2><p>Same-day packing for every order confirmed before 2pm, Monday to Friday.</p><table><tr><th>Destination</th><th>Time</th><th>Rate</th></tr><tr><td>Mainland France</td><td>2–3 days</td><td>€4.90</td></tr><tr><td>European Union</td><td>3–6 days</td><td>€9.90</td></tr><tr><td>Switzerland and the UK</td><td>4–8 days</td><td>€14.90</td></tr></table><p>Any customs duties outside the EU are payable by the recipient.</p>", "state": "TRANSLATED"}]', now(), 'seed')
on conflict (id) do nothing;

-- policy: COOKIES
INSERT INTO content.content (content_id, date_created, date_modified, updt_id, code, content_type, sort_order, visible, store_merchant_id, status, publish_at, unpublish_at, version, created_by, updated_by, parent_id, noindex, canonical_url, og_media_id, show_in_footer, placement, starts_at, ends_at, policy_type, meta)
VALUES (-10013, now(), now(), 'seed', 'politique-cookies', 'POLICY', 103, true, '65f020632bc46470c104b76f', 'PUBLISHED', null, null, 1, 'seed', 'seed', null, false, null, null, false, null, null, null, 'COOKIES', '{"jurisdiction": null, "requiresAcceptance": false, "notifyCustomers": false, "displayAt": {"footer": true, "checkout": false, "signup": false}}')
on conflict (content_id) do nothing;
INSERT INTO content.content_description (description_id, date_created, date_modified, updt_id, description, name, title, meta_description, meta_keywords, meta_title, sef_url, language_code, content_id, state, excerpt, alt_text, cta_label, subtitle)
VALUES (-100025, now(), now(), 'seed', '<h2>Cookies</h2><p>Nous déposons trois familles de cookies, dont une seule est exemptée de consentement.</p><ul><li><strong>Essentiels</strong> — panier, session, sécurité. Toujours actifs.</li><li><strong>Mesure d''audience</strong> — statistiques agrégées, 13 mois.</li><li><strong>Personnalisation</strong> — recommandations produits, 6 mois.</li></ul><p>Votre choix est enregistré pour six mois et modifiable à tout moment depuis le lien « Préférences cookies » en pied de page.</p>', 'Politique relative aux cookies', 'Politique relative aux cookies', null, null, null, null, 'fr', -10013, 'TRANSLATED', null, null, null, null)
on conflict (description_id) do nothing;
INSERT INTO content.content_description (description_id, date_created, date_modified, updt_id, description, name, title, meta_description, meta_keywords, meta_title, sef_url, language_code, content_id, state, excerpt, alt_text, cta_label, subtitle)
VALUES (-100026, now(), now(), 'seed', '<h2>Cookies</h2><p>We set three families of cookies, only one of which is exempt from consent.</p><ul><li><strong>Essential</strong> — cart, session, security. Always on.</li><li><strong>Measurement</strong> — aggregate statistics, 13 months.</li><li><strong>Personalisation</strong> — product recommendations, 6 months.</li></ul><p>Your choice is stored for six months and can be changed at any time from the “Cookie preferences” link in the footer.</p>', 'Cookie policy', 'Cookie policy', null, null, null, null, 'en', -10013, 'TRANSLATED', null, null, null, null)
on conflict (description_id) do nothing;
INSERT INTO content.policy_version (id, store_merchant_id, content_id, version, status, effective_from, note, translations, published_at, published_by)
VALUES (-1005, '65f020632bc46470c104b76f', -10013, 1, 'LIVE', now() - interval '30 days', null, '[{"language": "fr", "title": "Politique relative aux cookies", "body": "<h2>Cookies</h2><p>Nous déposons trois familles de cookies, dont une seule est exemptée de consentement.</p><ul><li><strong>Essentiels</strong> — panier, session, sécurité. Toujours actifs.</li><li><strong>Mesure d''audience</strong> — statistiques agrégées, 13 mois.</li><li><strong>Personnalisation</strong> — recommandations produits, 6 mois.</li></ul><p>Votre choix est enregistré pour six mois et modifiable à tout moment depuis le lien « Préférences cookies » en pied de page.</p>", "state": "TRANSLATED"}, {"language": "en", "title": "Cookie policy", "body": "<h2>Cookies</h2><p>We set three families of cookies, only one of which is exempt from consent.</p><ul><li><strong>Essential</strong> — cart, session, security. Always on.</li><li><strong>Measurement</strong> — aggregate statistics, 13 months.</li><li><strong>Personalisation</strong> — product recommendations, 6 months.</li></ul><p>Your choice is stored for six months and can be changed at any time from the “Cookie preferences” link in the footer.</p>", "state": "TRANSLATED"}]', now(), 'seed')
on conflict (id) do nothing;

