-- Blog categories and posts.
--
-- Demo content for the test store 65f020632bc46470c104b76f (Beauté Élégante Paris), in every language the store sells in.
-- Generated seed: ids are negative on purpose — content, media and menu ids all come from sequences that
-- only grow upward, so a seed row below zero can never collide with one the running service creates.

INSERT INTO content.post_category (id, store_merchant_id, slug, position, names)
VALUES (-151, '65f020632bc46470c104b76f', 'rituels', 0, '{"fr": "Rituels", "en": "Rituals"}')
on conflict (store_merchant_id, slug) do nothing;
INSERT INTO content.post_category (id, store_merchant_id, slug, position, names)
VALUES (-152, '65f020632bc46470c104b76f', 'ingredients', 1, '{"fr": "Ingrédients", "en": "Ingredients"}')
on conflict (store_merchant_id, slug) do nothing;
INSERT INTO content.post_category (id, store_merchant_id, slug, position, names)
VALUES (-153, '65f020632bc46470c104b76f', 'coulisses', 2, '{"fr": "Coulisses", "en": "Behind the scenes"}')
on conflict (store_merchant_id, slug) do nothing;

-- post: routine-du-soir-en-quatre-gestes (PUBLISHED)
INSERT INTO content.content (content_id, date_created, date_modified, updt_id, code, content_type, sort_order, visible, store_merchant_id, status, publish_at, unpublish_at, version, created_by, updated_by, parent_id, noindex, canonical_url, og_media_id, show_in_footer, placement, starts_at, ends_at, policy_type, meta)
VALUES (-10026, now(), now(), 'seed', 'routine-du-soir-en-quatre-gestes', 'POST', 0, true, '65f020632bc46470c104b76f', 'PUBLISHED', now() - interval '3 days', null, 1, 'seed', 'seed', null, false, null, null, false, null, null, null, null, '{"heroMediaId": -190003, "categoryIds": [-151], "tags": ["routine", "soir", "peau sèche"], "authorName": "Claire Bouvier", "featured": true}')
on conflict (content_id) do nothing;
INSERT INTO content.content_description (description_id, date_created, date_modified, updt_id, description, name, title, meta_description, meta_keywords, meta_title, sef_url, language_code, content_id, state, excerpt, alt_text, cta_label, subtitle)
VALUES (-100051, now(), now(), 'seed', '<p>La peau ne se répare pas la nuit par magie : elle le fait parce que la barrière cutanée est enfin débarrassée de ce qui l''encombre. D''où quatre gestes, pas douze.</p><h2>1. Démaquiller à l''huile</h2><p>Une huile démaquillante dissout le maquillage, le sébum et les filtres solaires, que l''eau seule ne délogera jamais. Massez deux minutes sur peau sèche, puis émulsionnez.</p><h2>2. Nettoyer en douceur</h2><p>Un gel sans sulfates, à pH 5,5. La peau doit être souple après rinçage, jamais tiraillée : le tiraillement est le signe d''un nettoyant trop décapant.</p><h2>3. Traiter</h2><p>Un seul actif par soir. Le rétinal le lundi et le jeudi, l''acide lactique le mercredi, rien les autres jours. Empiler les actifs abîme la barrière plus vite qu''il ne corrige quoi que ce soit.</p><h2>4. Sceller</h2><p>Une crème plus riche que celle du matin, avec des céramides. Elle limite la perte insensible en eau, qui culmine entre 23h et 4h.</p><p>Quatre semaines suffisent pour juger. Avant, vous ne mesurez que la lumière de votre salle de bains.</p>', 'La routine du soir en quatre gestes', 'La routine du soir en quatre gestes', 'Démaquillage à l''huile, nettoyant doux, actif ciblé, crème occlusive : la routine du soir expliquée geste par geste.', 'routine, soir, peau sèche', 'La routine du soir en quatre gestes | Le Journal', 'routine-du-soir-en-quatre-gestes', 'fr', -10026, 'TRANSLATED', 'Démaquiller, nettoyer, traiter, sceller : quatre gestes suffisent, à condition de les faire dans cet ordre.', null, null, null)
on conflict (description_id) do nothing;
INSERT INTO content.content_description (description_id, date_created, date_modified, updt_id, description, name, title, meta_description, meta_keywords, meta_title, sef_url, language_code, content_id, state, excerpt, alt_text, cta_label, subtitle)
VALUES (-100052, now(), now(), 'seed', '<p>Skin does not repair itself overnight by magic. It does it because the barrier is finally free of what was sitting on it. Hence four steps, not twelve.</p><h2>1. Take it off with oil</h2><p>A cleansing oil dissolves make-up, sebum and sunscreen filters that water alone will never shift. Massage for two minutes on dry skin, then emulsify.</p><h2>2. Cleanse gently</h2><p>A sulfate-free gel at pH 5.5. Skin should feel supple after rinsing, never tight: tightness is the sign of a cleanser that has stripped it.</p><h2>3. Treat</h2><p>One active per evening. Retinal on Monday and Thursday, lactic acid on Wednesday, nothing the rest of the week. Stacking actives damages the barrier faster than it corrects anything.</p><h2>4. Seal</h2><p>A richer cream than the morning one, with ceramides. It limits transepidermal water loss, which peaks between 11pm and 4am.</p><p>Four weeks is enough to judge. Before that, all you are measuring is your bathroom lighting.</p>', 'The evening routine in four steps', 'The evening routine in four steps', 'Oil cleansing, a gentle wash, one targeted active, an occlusive cream: the evening routine, step by step.', 'routine, soir, peau sèche', 'The evening routine in four steps | The Journal', 'the-evening-routine-in-four-steps', 'en', -10026, 'TRANSLATED', 'Remove, cleanse, treat, seal: four steps are enough, provided you do them in that order.', null, null, null)
on conflict (description_id) do nothing;
INSERT INTO content.media_usage (id, asset_id, owner_kind, owner_ref, owner_title, content_id, content_type, field)
VALUES (-1001, -190003, 'CONTENT', '-10026', 'La routine du soir en quatre gestes', -10026, 'POST', 'hero')
on conflict (id) do nothing;

-- post: niacinamide-ce-quelle-fait-vraiment (PUBLISHED)
INSERT INTO content.content (content_id, date_created, date_modified, updt_id, code, content_type, sort_order, visible, store_merchant_id, status, publish_at, unpublish_at, version, created_by, updated_by, parent_id, noindex, canonical_url, og_media_id, show_in_footer, placement, starts_at, ends_at, policy_type, meta)
VALUES (-10027, now(), now(), 'seed', 'niacinamide-ce-quelle-fait-vraiment', 'POST', 1, true, '65f020632bc46470c104b76f', 'PUBLISHED', now() - interval '9 days', null, 1, 'seed', 'seed', null, false, null, null, false, null, null, null, null, '{"heroMediaId": -190004, "categoryIds": [-152], "tags": ["niacinamide", "actifs"], "authorName": "Dr. Amina Roussel", "featured": false}')
on conflict (content_id) do nothing;
INSERT INTO content.content_description (description_id, date_created, date_modified, updt_id, description, name, title, meta_description, meta_keywords, meta_title, sef_url, language_code, content_id, state, excerpt, alt_text, cta_label, subtitle)
VALUES (-100053, now(), now(), 'seed', '<p>La niacinamide, ou vitamine B3, est l''actif le plus consensuel de la cosmétique — ce qui explique qu''on la trouve partout, y compris là où elle ne sert à rien.</p><h2>Ce qui est documenté</h2><ul><li>Réduction de la production de sébum à partir de 2 %</li><li>Éclaircissement des taches post-inflammatoires à 4–5 %, sur douze semaines</li><li>Renforcement de la barrière lipidique par stimulation des céramides</li></ul><h2>Le mythe des 20 %</h2><p>Au-delà de 10 %, les études ne montrent aucun bénéfice supplémentaire, mais une nette hausse des rougeurs et des picotements. Nos sérums s''arrêtent à 5 %.</p><h2>Avec quoi l''associer</h2><p>Avec à peu près tout, y compris la vitamine C : l''incompatibilité rapportée date d''expériences menées à 60 °C, pas sur un visage.</p>', 'Niacinamide : ce qu''elle fait vraiment', 'Niacinamide : ce qu''elle fait vraiment', 'Ce que la littérature dit de la niacinamide : sébum, taches pigmentaires, barrière cutanée, et le pourcentage utile.', 'niacinamide, actifs', 'Niacinamide : ce qu''elle fait vraiment | Le Journal', 'niacinamide-ce-quelle-fait-vraiment', 'fr', -10027, 'TRANSLATED', 'À 5 %, la niacinamide régule le sébum et éclaircit les taches. À 20 %, elle irrite. La dose fait tout.', null, null, null)
on conflict (description_id) do nothing;
INSERT INTO content.content_description (description_id, date_created, date_modified, updt_id, description, name, title, meta_description, meta_keywords, meta_title, sef_url, language_code, content_id, state, excerpt, alt_text, cta_label, subtitle)
VALUES (-100054, now(), now(), 'seed', '<p>Niacinamide, or vitamin B3, is the least contested active in cosmetics — which is why it turns up everywhere, including where it does nothing.</p><h2>What is documented</h2><ul><li>Lower sebum production from 2% upward</li><li>Fading of post-inflammatory marks at 4–5%, over twelve weeks</li><li>A stronger lipid barrier through ceramide synthesis</li></ul><h2>The 20% myth</h2><p>Above 10%, studies show no further benefit but a clear rise in redness and stinging. Our serums stop at 5%.</p><h2>What to pair it with</h2><p>Almost anything, vitamin C included: the incompatibility people repeat comes from experiments run at 60°C, not on a face.</p>', 'Niacinamide: what it actually does', 'Niacinamide: what it actually does', 'What the literature says about niacinamide: sebum, pigmentation, barrier function, and the percentage that is useful.', 'niacinamide, actifs', 'Niacinamide: what it actually does | The Journal', 'niacinamide-what-it-actually-does', 'en', -10027, 'TRANSLATED', 'At 5%, niacinamide regulates sebum and fades marks. At 20%, it irritates. The dose is the whole story.', null, null, null)
on conflict (description_id) do nothing;
INSERT INTO content.media_usage (id, asset_id, owner_kind, owner_ref, owner_title, content_id, content_type, field)
VALUES (-1002, -190004, 'CONTENT', '-10027', 'Niacinamide : ce qu''elle fait vraiment', -10027, 'POST', 'hero')
on conflict (id) do nothing;

-- post: dans-latelier-de-nantes (PUBLISHED)
INSERT INTO content.content (content_id, date_created, date_modified, updt_id, code, content_type, sort_order, visible, store_merchant_id, status, publish_at, unpublish_at, version, created_by, updated_by, parent_id, noindex, canonical_url, og_media_id, show_in_footer, placement, starts_at, ends_at, policy_type, meta)
VALUES (-10028, now(), now(), 'seed', 'dans-latelier-de-nantes', 'POST', 2, true, '65f020632bc46470c104b76f', 'PUBLISHED', now() - interval '18 days', null, 1, 'seed', 'seed', null, false, null, null, false, null, null, null, null, '{"heroMediaId": -190005, "categoryIds": [-153], "tags": ["atelier", "fabrication"], "authorName": "Claire Bouvier", "featured": false}')
on conflict (content_id) do nothing;
INSERT INTO content.content_description (description_id, date_created, date_modified, updt_id, description, name, title, meta_description, meta_keywords, meta_title, sef_url, language_code, content_id, state, excerpt, alt_text, cta_label, subtitle)
VALUES (-100055, now(), now(), 'seed', '<p>L''atelier tient dans quatre cents mètres carrés d''une ancienne imprimerie. Trois cuves inox, une salle de pesée sous flux, et Marion, qui formule depuis onze ans.</p><h2>Un lot, une journée</h2><p>Une émulsion demande six heures : chauffe des phases à 75 °C, homogénéisation, refroidissement lent sous agitation, puis ajout des actifs thermosensibles sous les 40 °C.</p><h2>Le contrôle qui coûte cher</h2><p>Chaque lot part en challenge test microbiologique pendant vingt-huit jours avant expédition. C''est long, c''est cher, et c''est ce qui nous permet de ne pas surcharger les formules en conservateurs.</p>', 'Dans l''atelier de Nantes', 'Dans l''atelier de Nantes', 'Reportage dans l''atelier où sont fabriquées les émulsions Beauté Élégante.', 'atelier, fabrication', 'Dans l''atelier de Nantes | Le Journal', 'dans-latelier-de-nantes', 'fr', -10028, 'TRANSLATED', 'Six cents litres par semaine, trois cuves, une chimiste et beaucoup de nettoyage entre deux lots.', null, null, null)
on conflict (description_id) do nothing;
INSERT INTO content.content_description (description_id, date_created, date_modified, updt_id, description, name, title, meta_description, meta_keywords, meta_title, sef_url, language_code, content_id, state, excerpt, alt_text, cta_label, subtitle)
VALUES (-100056, now(), now(), 'seed', '<p>The workshop fits into four hundred square metres of a former print house. Three stainless vessels, a weighing room under laminar flow, and Marion, who has been formulating for eleven years.</p><h2>One batch, one day</h2><p>An emulsion takes six hours: phases heated to 75°C, homogenised, cooled slowly under agitation, then the heat-sensitive actives added below 40°C.</p><h2>The expensive control</h2><p>Every batch goes through a twenty-eight-day microbiological challenge test before it ships. It is slow and it is costly, and it is what lets us keep the preservative load low.</p>', 'Inside the Nantes workshop', 'Inside the Nantes workshop', 'A visit to the workshop where the Beauté Élégante emulsions are made.', 'atelier, fabrication', 'Inside the Nantes workshop | The Journal', 'inside-the-nantes-workshop', 'en', -10028, 'TRANSLATED', 'Six hundred litres a week, three vessels, one chemist, and a great deal of cleaning between batches.', null, null, null)
on conflict (description_id) do nothing;
INSERT INTO content.media_usage (id, asset_id, owner_kind, owner_ref, owner_title, content_id, content_type, field)
VALUES (-1003, -190005, 'CONTENT', '-10028', 'Dans l''atelier de Nantes', -10028, 'POST', 'hero')
on conflict (id) do nothing;

-- post: choisir-son-spf (PUBLISHED)
INSERT INTO content.content (content_id, date_created, date_modified, updt_id, code, content_type, sort_order, visible, store_merchant_id, status, publish_at, unpublish_at, version, created_by, updated_by, parent_id, noindex, canonical_url, og_media_id, show_in_footer, placement, starts_at, ends_at, policy_type, meta)
VALUES (-10029, now(), now(), 'seed', 'choisir-son-spf', 'POST', 3, true, '65f020632bc46470c104b76f', 'PUBLISHED', now() - interval '27 days', null, 1, 'seed', 'seed', null, false, null, null, false, null, null, null, null, '{"heroMediaId": -190006, "categoryIds": [-151, -152], "tags": ["spf", "protection solaire", "routine"], "authorName": "Dr. Amina Roussel", "featured": false}')
on conflict (content_id) do nothing;
INSERT INTO content.content_description (description_id, date_created, date_modified, updt_id, description, name, title, meta_description, meta_keywords, meta_title, sef_url, language_code, content_id, state, excerpt, alt_text, cta_label, subtitle)
VALUES (-100057, now(), now(), 'seed', '<h2>La quantité d''abord</h2><p>L''indice est mesuré à 2 mg/cm², soit environ une cuillère à café pour le visage et le cou. Presque personne n''en met autant : un SPF 50 appliqué au tiers protège comme un SPF 15.</p><h2>Minéral ou organique ?</h2><p>Les filtres minéraux (oxyde de zinc, dioxyde de titane) conviennent aux peaux réactives mais laissent un voile blanc. Les filtres organiques modernes sont photostables et invisibles. Les deux protègent.</p><h2>Renouveler</h2><p>Toutes les deux heures en extérieur, après chaque baignade. En intérieur derrière une fenêtre, une application le matin suffit.</p>', 'Choisir son SPF sans se tromper', 'Choisir son SPF sans se tromper', 'Indice, quantité, filtres minéraux ou organiques, renouvellement : comment choisir et appliquer une protection solaire.', 'spf, protection solaire, routine', 'Choisir son SPF sans se tromper | Le Journal', 'choisir-son-spf', 'fr', -10029, 'TRANSLATED', 'SPF 30 appliqué correctement bat SPF 50 appliqué à moitié. La quantité compte plus que l''indice.', null, null, null)
on conflict (description_id) do nothing;
INSERT INTO content.content_description (description_id, date_created, date_modified, updt_id, description, name, title, meta_description, meta_keywords, meta_title, sef_url, language_code, content_id, state, excerpt, alt_text, cta_label, subtitle)
VALUES (-100058, now(), now(), 'seed', '<h2>Quantity first</h2><p>The factor is measured at 2 mg/cm², roughly a teaspoon for face and neck. Almost nobody applies that much: an SPF 50 laid on at a third of the dose protects like an SPF 15.</p><h2>Mineral or organic?</h2><p>Mineral filters (zinc oxide, titanium dioxide) suit reactive skin but leave a white cast. Modern organic filters are photostable and invisible. Both protect.</p><h2>Reapply</h2><p>Every two hours outdoors, and after every swim. Indoors behind a window, one morning application is enough.</p>', 'Choosing an SPF without getting it wrong', 'Choosing an SPF without getting it wrong', 'Factor, quantity, mineral or organic filters, reapplication: how to choose and use a sunscreen.', 'spf, protection solaire, routine', 'Choosing an SPF without getting it wrong | The Journal', 'choosing-an-spf', 'en', -10029, 'TRANSLATED', 'SPF 30 applied properly beats SPF 50 applied by half. Quantity matters more than the number.', null, null, null)
on conflict (description_id) do nothing;
INSERT INTO content.media_usage (id, asset_id, owner_kind, owner_ref, owner_title, content_id, content_type, field)
VALUES (-1004, -190006, 'CONTENT', '-10029', 'Choisir son SPF sans se tromper', -10029, 'POST', 'hero')
on conflict (id) do nothing;

-- post: peau-mixte-en-hiver (PUBLISHED)
INSERT INTO content.content (content_id, date_created, date_modified, updt_id, code, content_type, sort_order, visible, store_merchant_id, status, publish_at, unpublish_at, version, created_by, updated_by, parent_id, noindex, canonical_url, og_media_id, show_in_footer, placement, starts_at, ends_at, policy_type, meta)
VALUES (-10030, now(), now(), 'seed', 'peau-mixte-en-hiver', 'POST', 4, true, '65f020632bc46470c104b76f', 'PUBLISHED', now() - interval '41 days', null, 1, 'seed', 'seed', null, false, null, null, false, null, null, null, null, '{"heroMediaId": -190007, "categoryIds": [-151], "tags": ["peau mixte", "hiver", "routine"], "authorName": "Marion Lefèvre", "featured": false}')
on conflict (content_id) do nothing;
INSERT INTO content.content_description (description_id, date_created, date_modified, updt_id, description, name, title, meta_description, meta_keywords, meta_title, sef_url, language_code, content_id, state, excerpt, alt_text, cta_label, subtitle)
VALUES (-100059, now(), now(), 'seed', '<p>Le froid ne rend pas la peau mixte plus sèche partout : il assèche les joues pendant que la zone T continue son travail.</p><h2>Deux textures, un visage</h2><p>Rien n''interdit d''appliquer un fluide léger sur la zone T et une crème riche sur les joues. C''est même la seule réponse sensée.</p><h2>Baisser la fréquence, pas la dose</h2><p>Passez vos exfoliants de trois fois à une fois par semaine plutôt que de diluer le produit. La peau supporte mieux un geste fort espacé qu''un geste faible quotidien.</p><h2>Le nettoyage du matin</h2><p>À l''eau tiède seule, si la peau tiraille. Le nettoyant du soir a déjà fait le travail.</p>', 'Peau mixte en hiver : arrêter de sur-traiter', 'Peau mixte en hiver : arrêter de sur-traiter', 'Comment adapter une routine peau mixte au froid sans assécher les joues ni relancer la zone T.', 'peau mixte, hiver, routine', 'Peau mixte en hiver | Le Journal', 'peau-mixte-en-hiver', 'fr', -10030, 'TRANSLATED', 'La zone T brille, les joues tirent, et la réponse habituelle — décaper partout — aggrave les deux.', null, null, null)
on conflict (description_id) do nothing;
INSERT INTO content.content_description (description_id, date_created, date_modified, updt_id, description, name, title, meta_description, meta_keywords, meta_title, sef_url, language_code, content_id, state, excerpt, alt_text, cta_label, subtitle)
VALUES (-100060, now(), now(), 'seed', '<p>Cold weather does not make combination skin uniformly dry: it dries the cheeks while the T-zone carries on as before.</p><h2>Two textures, one face</h2><p>Nothing stops you putting a light fluid on the T-zone and a rich cream on the cheeks. It is in fact the only sensible answer.</p><h2>Lower the frequency, not the dose</h2><p>Take exfoliants from three times a week to once, rather than diluting the product. Skin tolerates a strong step spaced out better than a weak step every day.</p><h2>The morning cleanse</h2><p>Lukewarm water alone, if skin feels tight. The evening cleanser already did the work.</p>', 'Combination skin in winter: stop over-treating', 'Combination skin in winter: stop over-treating', 'How to adapt a combination-skin routine to the cold without drying the cheeks or provoking the T-zone.', 'peau mixte, hiver, routine', 'Combination skin in winter | The Journal', 'combination-skin-in-winter', 'en', -10030, 'TRANSLATED', 'The T-zone shines, the cheeks feel tight, and the usual answer — stripping everything — makes both worse.', null, null, null)
on conflict (description_id) do nothing;
INSERT INTO content.media_usage (id, asset_id, owner_kind, owner_ref, owner_title, content_id, content_type, field)
VALUES (-1005, -190007, 'CONTENT', '-10030', 'Peau mixte en hiver : arrêter de sur-traiter', -10030, 'POST', 'hero')
on conflict (id) do nothing;

-- post: le-verre-consigne (PUBLISHED)
INSERT INTO content.content (content_id, date_created, date_modified, updt_id, code, content_type, sort_order, visible, store_merchant_id, status, publish_at, unpublish_at, version, created_by, updated_by, parent_id, noindex, canonical_url, og_media_id, show_in_footer, placement, starts_at, ends_at, policy_type, meta)
VALUES (-10031, now(), now(), 'seed', 'le-verre-consigne', 'POST', 5, true, '65f020632bc46470c104b76f', 'PUBLISHED', now() - interval '60 days', null, 1, 'seed', 'seed', null, false, null, null, false, null, null, null, null, '{"heroMediaId": -190003, "categoryIds": [-153], "tags": ["durable", "recharge"], "authorName": "Claire Bouvier", "featured": false}')
on conflict (content_id) do nothing;
INSERT INTO content.content_description (description_id, date_created, date_modified, updt_id, description, name, title, meta_description, meta_keywords, meta_title, sef_url, language_code, content_id, state, excerpt, alt_text, cta_label, subtitle)
VALUES (-100061, now(), now(), 'seed', '<p>Recycler du verre veut dire le fondre à 1 500 °C. Le relaver demande de l''eau chaude à 80 °C. L''écart d''énergie est d''un facteur quatre environ.</p><h2>Le circuit</h2><p>Vous rapportez le flacon en boutique, nous vous rendons trois euros, le flacon part au laveur de Rezé et revient dans le circuit sous trois semaines.</p><h2>La limite</h2><p>Cela ne marche qu''en boutique : renvoyer un flacon vide par la poste annulerait le gain. C''est la raison pour laquelle la consigne n''existe pas en ligne.</p>', 'Pourquoi nous consignons le verre', 'Pourquoi nous consignons le verre', 'Le bilan carbone comparé du verre recyclé et du verre consigné, et ce que cela change en boutique.', 'durable, recharge', 'Pourquoi nous consignons le verre | Le Journal', 'le-verre-consigne', 'fr', -10031, 'TRANSLATED', 'Un flacon rapporté et relavé pèse quatre fois moins qu''un flacon recyclé. Le calcul nous a surpris.', null, null, null)
on conflict (description_id) do nothing;
INSERT INTO content.content_description (description_id, date_created, date_modified, updt_id, description, name, title, meta_description, meta_keywords, meta_title, sef_url, language_code, content_id, state, excerpt, alt_text, cta_label, subtitle)
VALUES (-100062, now(), now(), 'seed', '<p>Recycling glass means melting it at 1,500°C. Rewashing it needs hot water at 80°C. The energy gap is roughly a factor of four.</p><h2>The loop</h2><p>You bring the bottle back to the boutique, we hand you three euros, the bottle goes to the washer in Rezé and is back in circulation within three weeks.</p><h2>The catch</h2><p>It only works in the boutique: posting an empty bottle back would cancel the gain. That is why there is no deposit online.</p>', 'Why we put a deposit on glass', 'Why we put a deposit on glass', 'The comparative carbon cost of recycled and returnable glass, and what it changes in the boutique.', 'durable, recharge', 'Why we put a deposit on glass | The Journal', 'why-we-put-a-deposit-on-glass', 'en', -10031, 'TRANSLATED', 'A bottle brought back and rewashed costs about a quarter of what recycling it does. The maths surprised us.', null, null, null)
on conflict (description_id) do nothing;
INSERT INTO content.media_usage (id, asset_id, owner_kind, owner_ref, owner_title, content_id, content_type, field)
VALUES (-1006, -190003, 'CONTENT', '-10031', 'Pourquoi nous consignons le verre', -10031, 'POST', 'hero')
on conflict (id) do nothing;

-- post: collection-printemps-2026 (DRAFT)
INSERT INTO content.content (content_id, date_created, date_modified, updt_id, code, content_type, sort_order, visible, store_merchant_id, status, publish_at, unpublish_at, version, created_by, updated_by, parent_id, noindex, canonical_url, og_media_id, show_in_footer, placement, starts_at, ends_at, policy_type, meta)
VALUES (-10032, now(), now(), 'seed', 'collection-printemps-2026', 'POST', 6, true, '65f020632bc46470c104b76f', 'DRAFT', null, null, 1, 'seed', 'seed', null, false, null, null, false, null, null, null, null, '{"heroMediaId": -190004, "categoryIds": [-153], "tags": ["collection"], "authorName": "Claire Bouvier", "featured": false}')
on conflict (content_id) do nothing;
INSERT INTO content.content_description (description_id, date_created, date_modified, updt_id, description, name, title, meta_description, meta_keywords, meta_title, sef_url, language_code, content_id, state, excerpt, alt_text, cta_label, subtitle)
VALUES (-100063, now(), now(), 'seed', '<p>Brouillon. Cet article vérifie qu''un POST non publié reste hors du blog tout en restant éditable dans la console.</p>', 'Collection printemps 2026 (brouillon)', 'Collection printemps 2026 (brouillon)', null, 'collection', null, 'collection-printemps-2026', 'fr', -10032, 'DRAFT', 'Article en cours de rédaction — ne doit pas apparaître dans le blog.', null, null, null)
on conflict (description_id) do nothing;
INSERT INTO content.content_description (description_id, date_created, date_modified, updt_id, description, name, title, meta_description, meta_keywords, meta_title, sef_url, language_code, content_id, state, excerpt, alt_text, cta_label, subtitle)
VALUES (-100064, now(), now(), 'seed', '<p>Draft. This post is the check that an unpublished POST stays off the blog while remaining editable in the console.</p>', 'Spring 2026 collection (draft)', 'Spring 2026 collection (draft)', null, 'collection', null, 'spring-2026-collection', 'en', -10032, 'DRAFT', 'Still being written — must not appear on the blog.', null, null, null)
on conflict (description_id) do nothing;

