version: '3'
services:
  saas-gateway-service:
    build:
      context: .
      dockerfile: Dockerfile
      no_cache: true
    network_mode: "host"
    ports:
      - "80:80"
      - "443:443"
      - "2019:2019"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
    environment:
      NAMESPACE: gateway.com
      ASK_TLS_URL: http://store-pod-saas-gateway-1.gateway.com:80/merchant/api/v1/router/public/ask-for-tls
      DOMAIN_LOOKUP_URL: http://store-pod-saas-gateway-1.gateway.com:80/merchant/api/v1/router/public/lookup-by-domain
      CERT_BUCKET: random-bucket
      CERT_BUCKET_REGION: eu-central-1