#http://localhost:8080/oauth2/authorize?response_type=code&client_id=webapp&redirect_uri=https://app.example.com/callback&scope=openid%20profile%20api.read&code_challenge=YOUR_CODE_CHALLENGE&code_challenge_method=S256

#http://localhost:8080/oauth2/authorize?response_type=code&client_id=web-app&scope=openid&state=U1E9ME0qfLpLfvMPhdBdTee1G6aXeDn7tcP0YEomNeM%3D&redirect_uri=http://localhost:8000/login/oauth2/code/keycloak&nonce=urKkucl0JiiHH8clPXD5W0PTBX4iUIQwhcbw2YIjOmU&code_challenge=jNEXKgeT6hJMpWQYEMBbSdrhQHr5AOmdpoASkAsR8wQ&code_challenge_method=S256


### create a client
POST localhost:8080/api/v1/admin/clients
Content-Type: application/json

{
  "id": "66666666-6666-6666-6666-666666666666",
  "clientId": "webapp",
  "clientIdIssuedAt": "2025-12-04T18:46:01.222677Z",
  "clientSecretExpiresAt": "2025-12-04T18:46:01.222677Z",
  "clientName": "Web App",
  "clientAuthenticationMethods": [
    "client_secret_basic",
    "client_secret_post"
  ],
  "authorizationGrantTypes": [
    "authorization_code",
    "refresh_token"
  ],
  "redirectUris": [
    "https://app.example.com/callback"
  ],
  "postLogoutRedirectUris": [
    "naitaing"
  ],
  "scopes": [
    "openid",
    "profile",
    "api.read"
  ],
  "clientSettings": {
    "requireProofKey": true,
    "requireAuthorizationConsent": true,
    "jwkSetUrl": "gogole.com",
    "tokenEndpointAuthenticationSigningAlgorithm": "RS256",
    "x509CertificateSubjectDN": "domain.example"
  },
  "tokenSettings": {
    "accessTokenTimeToLive": "PT24H",
    "refreshTokenTimeToLive": "PT20H",
    "reuseRefreshTokens": true,
    "idTokenSignatureAlgorithm": "RS256",
    "authorizationCodeTimeToLive": "PT24H",
    "deviceCodeTimeToLive": "PT5M",
    "x509CertificateBoundAccessTokens": true,
    "accessTokenFormat": "self-contained"
  }
}

### client credentails
POST http://localhost:8001/oauth2/token
Content-Type: application/x-www-form-urlencoded
Authorization: Basic store-pod-1@service.store-pod.internal hLwOF59NEOdMzYYrfxUbQEGVK1uTczj7

grant_type=client_credentials&scope=internal

###
# http://org1-store1.spg-507f1f77.gateway.com:80/cua/oauth2/authorize?response_type=code&client_id=65f020632bc46470c104b76f&scope=openid&state=wluMmDBnDBX9ukT3ngWhC2vSTrhAZu10pGBXOtcZ9Qo%3D&redirect_uri=http://org1-store1.spg-507f1f77.gateway.com/callback&nonce=U6H2w96cGF3jSEpaCNNtKpkYgUWRAhGf3Wuu0W536oc&code_challenge=E9Melhoa2OwvFrEMTJguCHaoeK1t8URWbuGJSstw-cM&code_challenge_method=S256
# code_verifier = dBjftJeZ4CVP-mB92K27uhbUJU1p1r_wW1gFWFOEjXk
# BASE64URL(SHA256(code_verifier)) = E9Melhoa2OwvFrEMTJguCHaoeK1t8URWbuGJSstw-cM
POST http://org1-store1.spg-507f1f77.gateway.com:80/cua/oauth2/token
Content-Type: application/x-www-form-urlencoded

grant_type = authorization_code &
code = 1tRF_77x5w0wccQg0BswzeW4JlH97OB_BCzXEK5Zld_2XPwm37bZQDHP0F9yAtX9nKrWLxkSiw5Bic6L42B1tRsCE01krMOjypyi0UguGyKjpqoo38SkyDkS3h7x5Cle &
redirect_uri = http://org1-store1.spg-507f1f77.gateway.com/callback &
client_id = 65f020632bc46470c104b76f &
code_verifier = dBjftJeZ4CVP-mB92K27uhbUJU1p1r_wW1gFWFOEjXk

###