plugins {
    id 'com.asrevo.java-application-conventions'
    id 'org.springframework.boot' version '3.3.1'
    id 'io.spring.dependency-management' version '1.1.5'
//    id 'org.graalvm.buildtools.native' version '0.10.2'
    id("com.diffplug.spotless") version "7.0.0.BETA2"
}
apply from: "$rootDir/helpers/common-methods.gradle"
group = 'com.asrevo.cvhome'

repositories {
    mavenLocal()
    mavenCentral()
    maven { url 'https://repo.spring.io/milestone' }
}

springBoot {
    buildInfo()
}

bootBuildImage {
    builder = "paketobuildpacks/builder-jammy-tiny:latest"
    imageName = createImageName("store-pod/store-pod-gateway")
    tags = createImageTags("store-pod/store-pod-gateway",project.version)
    docker {
        publishRegistry {
            url = System.getenv("REGISTRY")
            username = System.getenv("ECR_TOKEN") ? 'AWS' : null
            password = System.getenv("ECR_TOKEN")
        }
    }
}

ext {
    set('springCloudVersion', "2023.0.2")
}
dependencies {
    implementation 'org.springframework.cloud:spring-cloud-starter-gateway'
    implementation 'org.springframework.cloud:spring-cloud-starter-loadbalancer'
    implementation 'org.springframework.boot:spring-boot-starter-actuator'
    implementation 'org.springframework.boot:spring-boot-starter-oauth2-client'

    implementation 'com.github.ben-manes.caffeine:caffeine:3.1.8'

    implementation project(':commons:cvhome-commons')

    implementation project(':commons:s2sc-commons')
    implementation project(':commons:ecs-commons:fargate-task-info')
    implementation project(':commons:ecs-commons:ecs-service-discoveryclient')
    compileOnly 'org.projectlombok:lombok'
    annotationProcessor 'org.projectlombok:lombok'
    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    testImplementation 'io.projectreactor:reactor-test'
    testImplementation 'org.springframework.boot:spring-boot-testcontainers'
    testImplementation 'org.testcontainers:junit-jupiter'
    testImplementation 'org.testcontainers:mockserver:1.19.6'
    testImplementation 'org.mock-server:mockserver-client-java:5.15.0'
}

//tasks.withType(org.springframework.boot.gradle.tasks.aot.ProcessAot).configureEach {
//    args('--spring.profiles.active=lcl')
//}

dependencyManagement {
    imports {
        mavenBom "org.springframework.cloud:spring-cloud-dependencies:${springCloudVersion}"
    }
}
