### test find products in a store through gateway
GET http://localhost:8080/store/api/v1/public/products/find-all?storeId=65f023632bc46470c104b76f
Accept: application/json

### test find products in a store through gateway with mapping
GET http://ashraf.gateway.me:8080/store/api/v1/public/products/find-all
Accept: application/json
Map-Host-As-Request-Param: true

