plugins {
	alias(libs.plugins.java.library.conventions)
}

dependencies {
	compileOnly project(":store-commons:commons")
	compileOnly project(":store-commons:ecs-commons:fargate-task-info")
	compileOnly libs.spring.webflux
	compileOnly libs.spring.webmvc
	compileOnly libs.jakarta.servlet.api
	compileOnly libs.spring.boot.starter.jackson
	compileOnly libs.spring.data.commons
	compileOnly libs.spring.boot.starter.oauth2.client
	compileOnly libs.spring.boot.starter.security.oauth2.resource.server
	compileOnly libs.spring.cloud.gateway.server.webflux
	compileOnly libs.spring.cloud.commons
	compileOnly libs.spring.cloud.stream
	compileOnly libs.spring.boot.starter.actuator
	compileOnly libs.jackson.databind
	compileOnly libs.jackson.core
	compileOnly libs.swagger.models

	compileOnly libs.lombok
	annotationProcessor libs.lombok
}
