// GENERATED by libs/types/scripts/build-color-schemas.mjs (THEME_DEFAULTS.fashion) — edit the seed there, then
// `npm run gen:colors` in libs/types. Same rules as the merchant presets (see that file's header).
import type {ColorSchema} from '@store-front/types';

/**
 * The Wheatpaste Wall: poster paper, ink, day-glo pink paper with dark text on every primary action; acid-green statement. (light)
 *
 * The theme's own palette — what renders when the merchant's colour theme is `DEFAULT` or unset. Wired as
 * `tokens.defaultColors` in `./index.ts`; any fixed preset the merchant picks replaces it whole.
 */
export const DEFAULT_COLORS: ColorSchema = {
    primary: "#FB40AD",
    secondary: "#121212",
    accent: "#DBEC1A",
    background: "#F5F2E9",
    foreground: "#121212",
    error: "#B7191C",
    warning: "#EE9E10",
    success: "#007533",
    info: "#0065A1",
    neutral: "#ABABAB",
    border: "#D7D1C0",
    ring: "#F438A6",
    outline: "#CB6398",
    hoverPrimary: "#FF78BE",
    focusPrimary: "#FF9ECD",
    hoverSecondary: "#040404",
    focusSecondary: "#000000",
    hoverAccent: "#C5D400",
    focusAccent: "#B2C000",
    hoverError: "#99000D",
    focusError: "#7D0008",
    hoverWarning: "#D38A00",
    focusWarning: "#BA7900",
    hoverSuccess: "#005E28",
    focusSuccess: "#004B1E",
    hoverInfo: "#005182",
    focusInfo: "#004069",
    hoverNeutral: "#959595",
    focusNeutral: "#838383",
};
