// GENERATED by scripts/theme-routes.mjs — do not edit. The route logic lives in src/shell/routes.
import theme from '@store-front/theme-fashion';
import {checkoutResultPage} from '@/shell/routes/checkout';

export {generateMetadata} from '@/shell/routes/checkout';
export default checkoutResultPage(async () => theme, 'success');
