# curl '{{SELLER-UI_URL}}/manager/api/v1/store-manager/private/store?lang=en&count=10&page=0'
GET {{SELLER-UI_URL}}/manager/api/v1/store-manager/private/store?lang=en&count=10&page=0
Cookie: STORE-CORE-GATEWAY-JSESSIONID={{ORG_ADMIN_SESSION_ID}};Store-Id=65f023632bc46470c104b76f

###

# curl 'GET {{SELLER-UI_URL}}/store-pod-gateway/merchant/api/v1/store/65f023632bc46470c104b75f?store=65f023632bc46470c104b75f'
GET {{SELLER-UI_URL}}/store-pod-gateway/merchant/api/v1/store/65f023632bc46470c104b75f?store=65f023632bc46470c104b75f
Cookie: STORE-CORE-GATEWAY-JSESSIONID={{ORG_ADMIN_SESSION_ID}};Store-Id=65f023632bc46470c104b76f

###

# curl '{{SELLER-UI_URL}}/store-pod-gateway/merchant/api/v1/router/private/allocates?store=65f023632bc46470c104b75f'
GET {{SELLER-UI_URL}}/store-pod-gateway/merchant/api/v1/router/private/allocates?store=65f023632bc46470c104b75f
Cookie: STORE-CORE-GATEWAY-JSESSIONID={{ORG_ADMIN_SESSION_ID}};Store-Id=65f023632bc46470c104b76f

###

