spring:
  application:
    name: saas-pod-gateway
server:
  port: ${com.asrevo.cvhome.services.saas-pod-gateway.port}
info:
  app:
    name: ${spring.application.name}
management:
  observations:
    key-values:
      application: ${spring.application.name}