spring:
  cloud:
    loadbalancer:
      eager-load:
        clients:
          - "saas-pod-gateway"
    ecs:
      discovery:
        namespace: "saas-pod.cvhome.lcl"
        namespace-id: "ns-je7qri6wn7fbsrpn"
        enabled: true
        default-port: 8080
    gateway:
      discovery:
        locator:
          enabled: true
      default-filters:
        - TokenRelay
        - PreserveHostHeader
        - AddResponseHeader=X-Frame-Options, SAMEORIGIN
      routes:
        - id: landing-ui
          order: -1
          uri: ${com.asrevo.cvhome.services.landing-ui.schema}://${com.asrevo.cvhome.services.landing-ui.domain}:${com.asrevo.cvhome.services.landing-ui.port}
          predicates:
            - FHost={domain}.{x},{sub}.{domain}.{x}