spring:
  security:
    oauth2:
      client:
        registration:
          microservice:
            provider: keycloak
            client-id: microservice-app
            client-secret: r1nuVn4HefusLGwHIeRxbdOzdTZLEMvQ
            authorization-grant-type: password
          keycloak:
            client-id: web-app
            client-authentication-method: client_secret_basic
            authorization-grant-type: authorization_code
            scope: openid, profile, email
            redirect-uri: "{baseUrl}/login/oauth2/code/keycloak"
            provider: keycloak
            client-secret: hLwOF59NEOdMzYYrfxUbQEGVK1uTczj7
        provider:
          keycloak:
            jwk-set-uri: ${com.asrevo.cvhome.services.core-gateway.schema}://${com.asrevo.cvhome.services.auth.domain}:${com.asrevo.cvhome.services.core-gateway.port}/realms/cvhome/protocol/openid-connect/certs
            authorization-uri: ${com.asrevo.cvhome.services.core-gateway.schema}://${com.asrevo.cvhome.services.auth.domain}:${com.asrevo.cvhome.services.core-gateway.port}/realms/cvhome/protocol/openid-connect/auth
            token-uri: ${com.asrevo.cvhome.services.core-gateway.schema}://${com.asrevo.cvhome.services.auth.domain}:${com.asrevo.cvhome.services.core-gateway.port}/realms/cvhome/protocol/openid-connect/token
  cloud:
    local:
      discovery:
        enabled: true
        services:
            dcm:
              - url: "http://localhost:8082"
                metadata:
                  service-name: dcm
                  instance: dcm-1
            store-pod-gateway:
              - url: "http://localhost:8085"
                metadata:
                  service-name: store-pod-gateway
                  instance: store-pod-gateway-1
    gateway:
      discovery:
        locator:
          enabled: true
      default-filters:
        - TokenRelay
        - PreserveHostHeader
        - AddResponseHeader=X-Frame-Options, SAMEORIGIN
      routes:
        - id: dcm
          order: -1
          uri: lb://dcm
          predicates:
            - Path=/dcm/**
          filters:
            - StripPrefix=1
        - id: store-pod-gateway
          order: -1
          uri: lb://store-pod-gateway
          predicates:
            - FHost={domain}.{x},{sub}.{domain}.{x}
          filters:
            - MapHostAsRequestParam=userId
