###

# curl 'http://localhost:8120/api/v1/cart/a0a9ddc9b9704f95aa1d6dc7e6da6819/checkout'
#  -H 'Accept: application/json, text/plain, */*'
#  -H 'Accept-Language: en-US,en;q=0.9'
#  -H 'Authorization;'
#  -H 'Connection: keep-alive'
#  -H 'Content-Type: application/json'
#  -H 'Origin: http://localhost'
#  -H 'Referer: http://localhost/'
#  -H 'Sec-Fetch-Dest: empty'
#  -H 'Sec-Fetch-Mode: cors'
#  -H 'Sec-Fetch-Site: same-site'
#  -H 'User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36'
#  -H 'sec-ch-ua: "Google Chrome";v="123", "Not:A-Brand";v="8", "Chromium";v="123"'
#  -H 'sec-ch-ua-mobile: ?0'
#  -H 'sec-ch-ua-platform: "Linux"'
#  --data-raw '{"shippingQuote":"","currency":"CAD","payment":{"paymentType":"CREDITCARD","transactionType":"CAPTURE","paymentModule":"stripe","amount":200},"customer":{"emailAddress":"asga@sfa.ca","billing":{"address":"eeeeee","city":"fdfd","postalCode":"eeee","country":"CA","zone":"YT","firstName":"sfasdf","lastName":"asdfasdf"}}}'
POST http://localhost:8120/api/v1/cart/a0a9ddc9b9704f95aa1d6dc7e6da6819/checkout
Accept: application/json, text/plain, */*
Accept-Language: en-US,en;q=0.9
Authorization:
Connection: keep-alive
Origin: http://localhost
Referer: http://localhost/
Sec-Fetch-Dest: empty
Sec-Fetch-Mode: cors
Sec-Fetch-Site: same-site
User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36
sec-ch-ua: "Google Chrome";v="123", "Not:A-Brand";v="8", "Chromium";v="123"
sec-ch-ua-mobile: ?0
sec-ch-ua-platform: "Linux"
Content-Type: application/json

{
  "shippingQuote": "",
  "currency": "CAD",
  "payment": {
    "paymentType": "CREDITCARD",
    "transactionType": "CAPTURE",
    "paymentModule": "stripe",
    "amount": 200
  },
  "customer": {
    "emailAddress": "asga@sfa.ca",
    "billing": {
      "address": "eeeeee",
      "city": "fdfd",
      "postalCode": "eeee",
      "country": "CA",
      "zone": "YT",
      "firstName": "sfasdf",
      "lastName": "asdfasdf"
    }
  }
}

###

