{
  "__comment": "generated by lcl for stack ${stack} (offset +${offset}) from extra/lcl-config/spring-instance.yml.tpl — do not edit",
  "com": { "asrevo": { "cvhome": {
    "app": { "handlers": [ { "schema": "http", "port": ${port.store-core-gateway} } ] },
    "services": {
{{#each services}}
      "{{name}}": { "port": {{port}} }{{#unless last}},{{/unless}}
{{/each}}
    },
    "pods": [ { "id": "507f1f77bcf86cd799439011", "name": "pod-507f1f77", "domain": "spg-507f1f77.gateway.com",
                "endpoint": { "endpoint": "http://spg-507f1f77.gateway.com:${port.spg}", "type": "EXTERNAL" } } ],
    "pod-info": { "pod": { "id": "507f1f77bcf86cd799439011", "name": "pod-507f1f77", "domain": "spg-507f1f77.gateway.com",
                           "endpoint": { "endpoint": "http://spg-507f1f77.gateway.com:${port.spg}", "type": "EXTERNAL" } } },
    "cdn": { "storage": { "s3-url": "http://localhost:${port.minio:9000}" },
             "base-path": "http://localhost:${port.minio:9000}/d0dd4299-963a-4458-b31f-8efe31c35e8e" }
  } } },
  "spring": {
    "datasource": { "url": "jdbc:postgresql://localhost:${port.postgres:5432}/cvhome" },
    "cloud": { "discovery": { "client": { "simple": { "instances": {
{{#each services}}
      "{{name}}": [ { "uri": "http://localhost:{{port}}", "instance-id": "{{name}}-1", "metadata": { "service-name": "{{name}}", "instance": "{{name}}-1" } } ],
{{/each}}
      "store-core-gateway.store-core.cvhome.lcl": [ { "uri": "http://localhost:${port.store-core-gateway}", "instance-id": "store-core-gateway-ns-1", "metadata": { "service-name": "store-core-gateway", "instance": "store-core-gateway-ns-1" } } ]
    } } } } }
  },
  "management": { "otlp": { "tracing": { "endpoint": "http://localhost:${port.otel-collector:4318}/v1/traces" },
                            "metrics": { "export": { "url": "http://localhost:${port.otel-collector:4318}/v1/metrics" } } } },
  "otel": { "exporter": { "otlp": { "endpoint": "http://localhost:${port.otel-collector:4317}" } } }
}
