GET http://localhost:8020/api/v1/router/public/ask-for-tls?domain=org1-store1.spg-507f1f77.gateway.com
Accept: application/json

###
GET http://localhost:8020/api/v1/router/public/lookup-by-domain?domain=org1-store1.spg-507f1f77.gateway.com
Accept: application/json

###
