### create store
POST http://localhost:8020/api/v1/store-manager/private/store
Content-Type: application/json
Authorization: Bearer {{access_token}}

{
  "name": "ORG_ADMINss",
  "code": "123456",
  "phone": "+201100000009",
  "email": "email@gmail.com",
  "address": {
    "searchControl": "",
    "stateProvince": "Cario",
    "country": "EG",
    "address": "ashraf",
    "postalCode": "63263",
    "city": "wwwwwwwwww"
  },
  "supportedLanguages": [
    "fr",
    "en"
  ],
  "defaultLanguage": "en",
  "theme": "DEFAULT",
  "currency": "EGP",
  "currencyFormatNational": true,
  "weight": "KG",
  "dimension": "CM",
  "inBusinessSince": "2024-04-20T19:59:25.053Z",
  "useCache": true,
  "retailer": true
}

### get my stores
GET http://localhost:8083/api/v1/store/me
Authorization: Bearer {{access_token}}


### check store
GET http://localhost:8020/api/v1/store-manager/private/store/unique?name=ali
Content-Type: application/json
Authorization: Bearer {{access_token}}
