### list my users
GET http://localhost:8020/api/v1/user-account/list?store=65f023632bc46470c104b76f
Authorization: Bearer {{access_token}}



### create user
POST http://localhost:8020/api/v1/user-account/create?store=65f023632bc46470c104b76f
Authorization: Bearer {{access_token}}
Content-Type: application/json

{
  "username": "eertrrtr",
  "password": "eertrrtr",
  "userRoles": [
    "ROLE_STORE_MANAGER",
    "ROLE_CATALOG_MANAGER",
    "ROLE_ORDERS_MANAGER"
  ]
}



### disable user
POST http://localhost:8020/api/v1/user-account/disable?store=65f023632bc46470c104b76f&
    userId=0ea70fdd-4828-4a0d-a742-59a87334eec6
Authorization: Bearer {{access_token}}
Content-Type: application/json

{
}

### enable user
POST http://localhost:8020/api/v1/user-account/enable?store=65f023632bc46470c104b76f&
    userId=0ea70fdd-4828-4a0d-a742-59a87334eec6
Authorization: Bearer {{access_token}}
Content-Type: application/json

{
}
