spring:
  application:
    name: manager
  config:
    import: "classpath:common-config.yml"
  security:
    oauth2:
      client:
        registration:
          s2s:
            provider: keycloak
            client-id: manager@service.store-core.internal
            client-secret: VobDxIhAGZz8hyhzz7p9G7QpfixjFjzW
            authorization-grant-type: client_credentials
com:
  asrevo:
    cvhome:
      kc:
        credentials:
          server-url: ${com.asrevo.cvhome.services.core-auth.schema}://${com.asrevo.cvhome.services.core-auth.domain}:${com.asrevo.cvhome.services.core-auth.port}
          realm: cvhome
          client-id: internal-client
          client-secret: aKl0AKjjQ6zp2bnWhKOsnTOzl3J8Vqd0