// GENERATED by scripts/theme-routes.mjs — do not edit. The route logic lives in src/shell/routes.
import theme from '@store-front/theme-fashion';
import {notFoundPage} from '@/shell/routes/not-found';

export default notFoundPage(async () => theme);
