plugins {
    id "application"
    alias(libs.plugins.docker.conventions)
}
String kcModule = "kc-providers"
String kcProviders = ":store-core:core-auth:${kcModule}"
dependencies {
    implementation project(kcProviders)
}
tasks.register('cleanKcProviders') {
    doLast {
        delete fileTree('keycloak/providers') {
            include("*.jar")
        }
    }
}

tasks.register("copyKcProviders", Copy) {
    dependsOn(":store-core:core-auth:kc-providers:fatJar")

    from(project(kcProviders).tasks.named("fatJar").flatMap { it.archiveFile })
    into("$projectDir/keycloak/providers")
}

tasks.named("build") {
    dependsOn("copyKcProviders")
}

tasks.named("clean") {
    dependsOn("cleanKcProviders")
}

bootBuildImage {
    imageGroup = "store-core"
}
