### get token for microservice-gateway
POST http://localhost:8001/realms/cvhome/protocol/openid-connect/token
Content-Type: application/x-www-form-urlencoded

client_id = s2s &
client_secret = r1nuVn4HefusLGwHIeRxbdOzdTZLEMvQ &
grant_type = password &
username = auth@service.internal
    &
password = password

### get token for microservice with client
POST http://localhost:8001/realms/cvhome/protocol/openid-connect/token
Content-Type: application/x-www-form-urlencoded

client_id = communication@service.internal &
client_secret = c27HPNwTPMRI1wstTx9f6EAxFB9J4Ba7 &
grant_type = client_credentials




### get token for admin
POST http://localhost:8001/realms/master/protocol/openid-connect/token
Content-Type: application/x-www-form-urlencoded

client_id = admin-cli &
grant_type = password &
username = sys-admin@mail.com&
password = admin &
scope = roles

### get token for microservice-domain-ownership
POST http://localhost:8001/realms/cvhome/protocol/openid-connect/token
Content-Type: application/x-www-form-urlencoded

client_id = s2s &
client_secret = r1nuVn4HefusLGwHIeRxbdOzdTZLEMvQ &
grant_type = password &
username = microservice-domain-ownership
    &
password = microservice-domain-ownership


### get token for microservice-dcm
POST http://localhost:8001/realms/cvhome/protocol/openid-connect/token
Content-Type: application/x-www-form-urlencoded

client_id = s2s &
client_secret = r1nuVn4HefusLGwHIeRxbdOzdTZLEMvQ &
grant_type = password &
username = microservice-dcm
    &
password = microservice-dcm


