spring:
  datasource:
    url: jdbc:postgresql://${spring.datasource.host}:${spring.datasource.port}/${spring.datasource.database}
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${com.asrevo.cvhome.services.core-gateway.schema}://${com.asrevo.cvhome.services.auth.domain}:${com.asrevo.cvhome.services.core-gateway.port}/realms/cvhome/protocol/openid-connect/certs
  cloud:
    loadbalancer:
      eager-load:
        clients:
          - "gateway"
          - "domain-certificate-manager"
          - "store"
          - "streamer"
          - "auth"
          - "welcome-ui"
          - "admin-ui"
          - "store-ui"
    ecs:
      discovery:
        namespace: "cvhome.lcl"
        namespace-id: "ns-je7qri6wn7fbsrpn"
        enabled: true
        default-port: 8080
        service-ports:
          "domain-certificate-manager": 8082
          "store": 8083
          "auth": 9999
          "welcome-ui": 4400
          "store-ui": 4300
          "admin-ui": 4200
