plugins {
    alias(libs.plugins.java.library.conventions)
}

dependencies {
    compileOnly project(":store-commons:commons")
    implementation libs.mapstruct
    compileOnly libs.lombok
    annotationProcessor libs.mapstruct.processor
    annotationProcessor libs.lombok
    annotationProcessor libs.lombok.mapstruct.binding
}
