plugins {
	alias(libs.plugins.java.library.conventions)
	alias(libs.plugins.spring.javaformat)
}

dependencies {
	compileOnly libs.spring.web
	api project(':store-pod:commons:store-commons')
	api project(':store-pod:merchant:merchant-commons')
	api project(':store-pod:commons:customer:customer-commons')
	api project(':store-pod:commons:reference:reference-commons')
	compileOnly libs.spring.data.jpa
	compileOnly libs.jakarta.validation.api
	compileOnly libs.apache.commons.lang3
	compileOnly libs.lombok
	compileOnly libs.hibernate.core
	annotationProcessor libs.lombok
}
