version: "3.1"
services:
  otel-collector:
    network_mode: host
    image: otel/opentelemetry-collector-contrib:0.139.0
    command: ["--config=/etc/logging-otel-collector-config.yml"]
    volumes:
      - ./logging-otel-collector-config.yml:/etc/logging-otel-collector-config.yml
    ports:
      - "4317:4317"
      - "4318:4318"