version: "3.1"
services:
  postgres:
    image: "postgres:15-alpine"
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
  rabbitmq:
    image: "rabbitmq:3.12-management"
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: guest  # not real check rabbitmq/definitions.json
      RABBITMQ_DEFAULT_PASS: guest  # not real check rabbitmq/definitions.json
      RABBITMQ_DEFAULT_VHOST: "/"
    volumes:
      - ./rabbitmq/definitions.json:/etc/rabbitmq/definitions.json:ro
      - ./rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf:ro

    ports:
      - "15672:15672"
      - "5672:5672"
  keycloak:
    image: quay.io/keycloak/keycloak:21.0
    environment:
      KC_HTTP_ENABLED: true
      KC_HOSTNAME_STRICT_HTTPS: false

      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres:5432/kc
      KC_DB_USERNAME: postgres
      KC_DB_PASSWORD: password

      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin

      KK_TO_RMQ_URL: rabbitmq
      KK_TO_RMQ_USERNAME: guest
      KK_TO_RMQ_PASSWORD: guest
      KK_TO_RMQ_VHOST: "/"
      KK_TO_RMQ_EXCHANGE: "com.asrevo.cvhome.sys-events"

    command: --verbose start  --hostname-strict=false --import-realm
    #        command:  --verbose start  --hostname-strict=false --import-realm --log-level=DEBUG
    #        command:  --verbose start --hostname-strict=false --hostname-path=/auth --import-realm
    #        command:  --verbose start  --hostname-strict=false --import-realm
    volumes:
      - ../auth/keycloak/imports:/opt/keycloak/data/import
      - ../auth/keycloak/providers:/opt/keycloak/providers
    ports:
      - "9999:8080"
    depends_on:
      - postgres
      - rabbitmq