// GENERATED by scripts/theme-routes.mjs — do not edit. The route logic lives in src/shell/routes.
import theme from '@store-front/theme-cosmetics';
import {searchPage} from '@/shell/routes/search';

export {generateMetadata} from '@/shell/routes/search';
export default searchPage(theme);
