// GENERATED by libs/types/scripts/build-color-schemas.mjs (THEME_DEFAULTS.furniture) — edit the seed there, then
// `npm run gen:colors` in libs/types. Same rules as the merchant presets (see that file's header).
import type {ColorSchema} from '@store-front/types';

/**
 * The Home Floor Directory: bone-plaster ground, warm-graphite ink, deep enamel-green directory boards and every action; bone wash support; signal-orange plate statement. (light)
 *
 * The theme's own palette — what renders when the merchant's colour theme is `DEFAULT` or unset. Wired as
 * `tokens.defaultColors` in `./index.ts`; any fixed preset the merchant picks replaces it whole.
 */
export const DEFAULT_COLORS: ColorSchema = {
    primary: "#005A43",
    secondary: "#E2DDD4",
    accent: "#A82000",
    background: "#F9F6F2",
    foreground: "#1B1612",
    error: "#B7191C",
    warning: "#EE9E10",
    success: "#007533",
    info: "#0065A1",
    neutral: "#B1A9A3",
    border: "#DBD5C9",
    ring: "#005A43",
    outline: "#235745",
    hoverPrimary: "#004532",
    focusPrimary: "#003324",
    hoverSecondary: "#CBC7BD",
    focusSecondary: "#B8B4AA",
    hoverAccent: "#881700",
    focusAccent: "#6C1000",
    hoverError: "#99000D",
    focusError: "#7D0008",
    hoverWarning: "#D38A00",
    focusWarning: "#BA7900",
    hoverSuccess: "#005E28",
    focusSuccess: "#004B1E",
    hoverInfo: "#005182",
    focusInfo: "#004069",
    hoverNeutral: "#9B948E",
    focusNeutral: "#89827C",
};
