spring:
  config:
    import: "classpath:common-config.yml"
---
spring:
  application:
    name: subscription
  security:
    oauth2:
      client:
        registration:
          s2s:
            provider: keycloak
            client-id: subscription@service.store-core.internal
            client-secret: TxbDxIhATuz8hyhzz899G7QpfixjFjzW
            authorization-grant-type: client_credentials
server:
  port: ${com.asrevo.cvhome.services.subscription.port}