spring:
  config:
    import: "classpath:common-config.yml"
---
spring:
  application:
    name: subscription
  security:
    oauth2:
      client:
        registration:
          s2s:
            provider: keycloak
            client-id: subscription@service.store-core.internal
            client-secret: TxbDxIhATuz8hyhzz899G7QpfixjFjzW
            authorization-grant-type: client_credentials
  datasource:
    driver-class-name: org.postgresql.Driver
    hikari:
      schema: ${spring.application.name}
  cloud:
    function:
      definition: events
    stream:
      input-bindings: events
      bindings:
        events-in-0:
          destination: events
          group: ${spring.application.name}
        events-out-0:
          content-type: application/json
          destination: events
server:
  forward-headers-strategy: NATIVE
  port: ${com.asrevo.cvhome.services.subscription.port}
info:
  app:
    name: ${spring.application.name}
management:
  observations:
    key-values:
      application: ${spring.application.name}