###

# curl 'http://localhost:6001/api/v1/cart/3010e2168bd949e0a741456c94d31e72/total/'
#  -H 'Accept: application/json, text/plain, */*'
#  -H 'Accept-Language: en-US,en;q=0.9,ar;q=0.8'
#  -H 'Authorization;'
#  -H 'Connection: keep-alive'
#  -H 'Origin: http://localhost'
#  -H 'Referer: http://localhost/'
#  -H 'Sec-Fetch-Dest: empty'
#  -H 'Sec-Fetch-Mode: cors'
#  -H 'Sec-Fetch-Site: same-site'
#  -H 'User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36'
#  -H 'sec-ch-ua: "Google Chrome";v="123", "Not:A-Brand";v="8", "Chromium";v="123"'
#  -H 'sec-ch-ua-mobile: ?0'
#  -H 'sec-ch-ua-platform: "Linux"'
GET http://localhost:6001/api/v1/cart/3010e2168bd949e0a741456c94d31e72/total/
Accept: application/json, text/plain, */*
Accept-Language: en-US,en;q=0.9,ar;q=0.8
Authorization:
Connection: keep-alive
Origin: http://localhost
Referer: http://localhost/
Sec-Fetch-Dest: empty
Sec-Fetch-Mode: cors
Sec-Fetch-Site: same-site
User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36
sec-ch-ua: "Google Chrome";v="123", "Not:A-Brand";v="8", "Chromium";v="123"
sec-ch-ua-mobile: ?0
sec-ch-ua-platform: "Linux"

###












# curl 'http://localhost:6001/api/v1/config/'
#  -H 'Accept: application/json, text/plain, */*'
#  -H 'Accept-Language: en-US,en;q=0.9,ar;q=0.8'
#  -H 'Authorization;'
#  -H 'Connection: keep-alive'
#  -H 'Origin: http://localhost'
#  -H 'Referer: http://localhost/'
#  -H 'Sec-Fetch-Dest: empty'
#  -H 'Sec-Fetch-Mode: cors'
#  -H 'Sec-Fetch-Site: same-site'
#  -H 'User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36'
#  -H 'sec-ch-ua: "Google Chrome";v="123", "Not:A-Brand";v="8", "Chromium";v="123"'
#  -H 'sec-ch-ua-mobile: ?0'
#  -H 'sec-ch-ua-platform: "Linux"'
GET http://localhost:6001/api/v1/config/
Accept: application/json, text/plain, */*
Accept-Language: en-US,en;q=0.9,ar;q=0.8
Authorization:
Connection: keep-alive
Origin: http://localhost
Referer: http://localhost/
Sec-Fetch-Dest: empty
Sec-Fetch-Mode: cors
Sec-Fetch-Site: same-site
User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36
sec-ch-ua: "Google Chrome";v="123", "Not:A-Brand";v="8", "Chromium";v="123"
sec-ch-ua-mobile: ?0
sec-ch-ua-platform: "Linux"

###














# curl 'http://localhost:6001/api/v1/cart/3010e2168bd949e0a741456c94d31e72/shipping'
#  -H 'Accept: application/json, text/plain, */*'
#  -H 'Accept-Language: en-US,en;q=0.9,ar;q=0.8'
#  -H 'Authorization;'
#  -H 'Connection: keep-alive'
#  -H 'Content-Type: application/json'
#  -H 'Origin: http://localhost'
#  -H 'Referer: http://localhost/'
#  -H 'Sec-Fetch-Dest: empty'
#  -H 'Sec-Fetch-Mode: cors'
#  -H 'Sec-Fetch-Site: same-site'
#  -H 'User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36'
#  -H 'sec-ch-ua: "Google Chrome";v="123", "Not:A-Brand";v="8", "Chromium";v="123"'
#  -H 'sec-ch-ua-mobile: ?0'
#  -H 'sec-ch-ua-platform: "Linux"'
#  --data-raw '{}'
POST http://localhost:6001/api/v1/cart/3010e2168bd949e0a741456c94d31e72/shipping
Accept: application/json, text/plain, */*
Accept-Language: en-US,en;q=0.9,ar;q=0.8
Authorization:
Connection: keep-alive
Origin: http://localhost
Referer: http://localhost/
Sec-Fetch-Dest: empty
Sec-Fetch-Mode: cors
Sec-Fetch-Site: same-site
User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36
sec-ch-ua: "Google Chrome";v="123", "Not:A-Brand";v="8", "Chromium";v="123"
sec-ch-ua-mobile: ?0
sec-ch-ua-platform: "Linux"
Content-Type: application/json

{}

###


















# curl 'http://localhost:6001/api/v1/zones/?code=CA'
#  -H 'Accept: application/json, text/plain, */*'
#  -H 'Accept-Language: en-US,en;q=0.9,ar;q=0.8'
#  -H 'Authorization;'
#  -H 'Connection: keep-alive'
#  -H 'Origin: http://localhost'
#  -H 'Referer: http://localhost/'
#  -H 'Sec-Fetch-Dest: empty'
#  -H 'Sec-Fetch-Mode: cors'
#  -H 'Sec-Fetch-Site: same-site'
#  -H 'User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36'
#  -H 'sec-ch-ua: "Google Chrome";v="123", "Not:A-Brand";v="8", "Chromium";v="123"'
#  -H 'sec-ch-ua-mobile: ?0'
#  -H 'sec-ch-ua-platform: "Linux"'
GET http://localhost:6001/api/v1/zones/?code=CA
Accept: application/json, text/plain, */*
Accept-Language: en-US,en;q=0.9,ar;q=0.8
Authorization:
Connection: keep-alive
Origin: http://localhost
Referer: http://localhost/
Sec-Fetch-Dest: empty
Sec-Fetch-Mode: cors
Sec-Fetch-Site: same-site
User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36
sec-ch-ua: "Google Chrome";v="123", "Not:A-Brand";v="8", "Chromium";v="123"
sec-ch-ua-mobile: ?0
sec-ch-ua-platform: "Linux"

###











# curl 'http://localhost:6001/api/v1/newsletter/'
#  -H 'Accept: application/json, text/plain, */*'
#  -H 'Accept-Language: en-US,en;q=0.9,ar;q=0.8'
#  -H 'Authorization;'
#  -H 'Connection: keep-alive'
#  -H 'Content-Type: application/json'
#  -H 'Origin: http://localhost'
#  -H 'Referer: http://localhost/'
#  -H 'Sec-Fetch-Dest: empty'
#  -H 'Sec-Fetch-Mode: cors'
#  -H 'Sec-Fetch-Site: same-site'
#  -H 'User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36'
#  -H 'sec-ch-ua: "Google Chrome";v="123", "Not:A-Brand";v="8", "Chromium";v="123"'
#  -H 'sec-ch-ua-mobile: ?0'
#  -H 'sec-ch-ua-platform: "Linux"'
#  --data-raw '{"email":"fdfdf@sfd.com"}'
POST http://localhost:6001/api/v1/newsletter/
Accept: application/json, text/plain, */*
Accept-Language: en-US,en;q=0.9,ar;q=0.8
Authorization:
Connection: keep-alive
Origin: http://localhost
Referer: http://localhost/
Sec-Fetch-Dest: empty
Sec-Fetch-Mode: cors
Sec-Fetch-Site: same-site
User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36
sec-ch-ua: "Google Chrome";v="123", "Not:A-Brand";v="8", "Chromium";v="123"
sec-ch-ua-mobile: ?0
sec-ch-ua-platform: "Linux"
Content-Type: application/json

{
  "email": "fdfdf@sfd.com"
}

###











# curl 'http://localhost:6001/api/v1/contact/'
#  -H 'Accept: application/json, text/plain, */*'
#  -H 'Accept-Language: en-US,en;q=0.9,ar;q=0.8'
#  -H 'Authorization;'
#  -H 'Connection: keep-alive'
#  -H 'Content-Type: application/json'
#  -H 'Origin: http://localhost'
#  -H 'Referer: http://localhost/'
#  -H 'Sec-Fetch-Dest: empty'
#  -H 'Sec-Fetch-Mode: cors'
#  -H 'Sec-Fetch-Site: same-site'
#  -H 'User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36'
#  -H 'sec-ch-ua: "Google Chrome";v="123", "Not:A-Brand";v="8", "Chromium";v="123"'
#  -H 'sec-ch-ua-mobile: ?0'
#  -H 'sec-ch-ua-platform: "Linux"'
#  --data-raw '{"comment":"fdfdfdfdfdfd","email":"afsdf@sdfs.com","subject":"dfdfd"}'
POST http://localhost:6001/api/v1/contact/
Accept: application/json, text/plain, */*
Accept-Language: en-US,en;q=0.9,ar;q=0.8
Authorization:
Connection: keep-alive
Origin: http://localhost
Referer: http://localhost/
Sec-Fetch-Dest: empty
Sec-Fetch-Mode: cors
Sec-Fetch-Site: same-site
User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36
sec-ch-ua: "Google Chrome";v="123", "Not:A-Brand";v="8", "Chromium";v="123"
sec-ch-ua-mobile: ?0
sec-ch-ua-platform: "Linux"
Content-Type: application/json

{
  "comment": "fdfdfdfdfdfd",
  "email": "afsdf@sdfs.com",
  "subject": "dfdfd"
}

###

