### get token from test application
POST http://localhost:8089/api/v1/test/sign
Content-Type: application/json

{
  "sub": "fcad941c-aea5-426f-8f17-428add82aeb1",
  "resource_access": {
    "account": {
      "roles": [
        "manage-account",
        "manage-account-links",
        "view-profile"
      ]
    }
  },
  "email_verified": "false",
  "allowed-origins": [
    "/*"
  ],
  "iss": "http://auth.gateway.com:9999/realms/cvhome",
  "typ": "Bearer",
  "preferred_username": "microservice-gateway",
  "given_name": "",
  "sid": "ea59acba-c673-42f5-a374-5e0a30802683",
  "aud": "account",
  "realm_access": {
    "roles": [
      "ADMIN",
      "ROLE_MICROSERVICE",
      "offline_access",
      "uma_authorization",
      "default-roles-cvhome",
      "ROLE_MICROSERVICE_GATEWAY"
    ]
  },
  "azp": "microservice-app",
  "scope": "profile email",
  "session_state": "ea59acba-c673-42f5-a374-5e0a30802683",
  "family_name": "",
  "jti": "84a4b2a4-b463-4df4-9640-c669124402d3"
}

> {%
    client.global.set("access_token", response.body.access_token)
%}

### create category
POST http://localhost:8089/api/v1/admin/category/create?storeId=65f023632bc46470c104b76f
Content-Type: application/json
Authorization: Bearer {{access_token}}

{
  "name": "string",
  "imageLink": {
    "imageLink": "https://google.com"
  },
  "sequence": 0
}

### create single product
POST http://localhost:8089/api/v1/admin/products/create?storeId=65f023632bc46470c104b76f
Content-Type: application/json
Authorization: Bearer {{access_token}}

{
  "dto": {
    "name": "string",
    "description": "string",
    "price": {
      "price": 20,
      "currency": "USD"
    },
    "imageLink": {
      "imageLink": "https://google.com"
    },
    "amount": {
      "amount": 15
    },
    "productType": "SINGLE",
    "imageLinks": {
      "imagesLinks": [
        {
          "imageLink": "https://google.com"
        }
      ]
    },
    "category": {
      "id": {
        "id": "65f5b471c919a450ab3f8649"
      }
    }
  }
}


### get product details
GET http://localhost:8089/api/v1/admin/products/detailed-product?storeId=65f023632bc46470c104b76f&productId=65f5a789e37ac17bfb45926f
Accept: application/json
Authorization: Bearer {{access_token}}



### find all
POST http://localhost:8089/api/v1/admin/products/find-all?storeId=65f023632bc46470c104b76f
Content-Type: application/json
Authorization: Bearer {{access_token}}

{

}

### find all in  category
POST http://localhost:8089/api/v1/admin/products/find-all?storeId=65f023632bc46470c104b76f
Content-Type: application/json
Authorization: Bearer {{access_token}}

{
  "category": {
    "id": {
      "id": "65f5afd81807e746f740e320"
    }
  }
}





### create group product
POST http://localhost:8089/api/v1/admin/products/create?storeId=65f023632bc46470c104b76f
Content-Type: application/json
Authorization: Bearer {{access_token}}

{
  "dto": {
    "name": "string",
    "description": "string",
    "price": {
      "price": 20,
      "currency": "USD"
    },
    "imageLink": {
      "imageLink": "https://google.com"
    },
    "amount": {
      "amount": 15
    },
    "productType": "GROUP",
    "imageLinks": {
      "imagesLinks": [
        {
          "imageLink": "https://google.com"
        }
      ]
    },
    "category": {
      "id": {
        "id": "65f5b471c919a450ab3f8649"
      }
    }
  },
  "productDetails": {
    "detail": {
      "name": "any",
      "descriptions": [
        "d1",
        "d2"
      ],
      "ltr": false,
      "shortDescription": "sd",
      "spec": {
        "key": "value"
      }
    },
    "extraImages": {
      "imagesLinks": [
        {
          "imageLink": "https://google.com"
        }
      ]
    }
  },
  "subProducts": [
    {
      "id": {
        "id": {
          "id": "65f5b494c919a450ab3f864b"
        }
      }
    },
    {
      "id": {
        "id": {
          "id": "65f5b484c919a450ab3f864a"
        }
      }
    }
  ]
}

