spring:
  application:
    name: domain-certificate-manager
  docker:
    compose:
      file: ${spring.application.name}/compose.yml
  sql:
    init:
      mode: always
  datasource:
    url: jdbc:postgresql://localhost:5432/certificatemanagerdb
    username: postgres
    password: password
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:9999/realms/cvhome/protocol/openid-connect/certs
  cloud:
    discovery:
      client:
        simple:
          instances:
            domain-ownership:
              - uri: "http://localhost:8081"
                metadata:
                  service-name: domain-ownership
                  instance: domain-ownership-1
            domain-certificate-manager:
              - uri: "http://localhost:8082"
                metadata:
                  service-name: domain-certificate-manager
                  instance: domain-certificate-manager-1
            auth:
              - uri: "http://localhost:9999"
                metadata:
                  service-name: auth
                  instance: auth-1
            ui:
              - uri: "http://localhost:4200"
                metadata:
                  service-name: ui
                  instance: ui-1
            gateway:
              - uri: "http://localhost:8080"
                metadata:
                  service-name: gateway
                  instance: gateway-1
server:
  forward-headers-strategy: FRAMEWORK
  port: 8082
info:
  app:
    name: ${spring.application.name}
management:
  info:
    env:
      enabled: true
    os:
      enabled: true
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: [ '*' ]
  metrics:
    tags:
      application: ${spring.application.name}
logging:
  level:
    org.springframework.jdbc.core.JdbcTemplate: debug
    org.springframework.boot: debug
    org.springframework.web: debug
    org.springframework.security: debug
    reactor.netty.http: debug
org:
  jobrunr:
    background-job-server:
      enabled: true
com:
  asrevo:
    auto-order-domains:
      domains:
        - domain: "gateway.com"
        - domain: "*.gateway.com"