spring:
  application:
    name: domain-certificate-manager
  docker:
    compose:
      file: ${spring.application.name}/compose.yml
  sql:
    init:
      mode: always
server:
  forward-headers-strategy: FRAMEWORK
  port: 8082
info:
  app:
    name: ${spring.application.name}
management:
  info:
    env:
      enabled: true
    os:
      enabled: true
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: [ '*' ]
  metrics:
    tags:
      application: ${spring.application.name}
logging:
  level:
    org.springframework.jdbc.core.JdbcTemplate: debug
    org.springframework.boot: debug
    org.springframework.web: debug
    org.springframework.security: debug
    reactor.netty.http: debug
org:
  jobrunr:
    background-job-server:
      enabled: true
com:
  asrevo:
    auto-order-domains:
      domains:
        - domain: "cvhome.click"
      default-domain: "cvhome.click"
    dcm:
      challenge-config:
        dns-config:
          providers:
            - route53
          route53-config:
            zone-id: "s"
        http-config:
          provider: s3
          s3-config:
            bucket: "cvhome-cert-storage"
        tls-alpn01-config:
          provider: s3
          s3-config:
            bucket: "cvhome-cert-storage"
