// GENERATED by scripts/theme-routes.mjs — do not edit. The route logic lives in src/shell/routes.
import theme from '@store-front/theme-furniture';
import {policyPage} from '@/shell/routes/policy';

export {generateMetadata} from '@/shell/routes/policy';
export default policyPage(theme);
