echo '127.0.0.1	gateway.com' | sudo tee -a /etc/hosts > /dev/null
echo '127.0.0.1	www.gateway.com' | sudo tee -a /etc/hosts > /dev/null
echo '127.0.0.1	admin.gateway.com' | sudo tee -a /etc/hosts > /dev/null
echo '127.0.0.1	auth.gateway.com' | sudo tee -a /etc/hosts > /dev/null
echo '127.0.0.1	store-pod-1.gateway.com' | sudo tee -a /etc/hosts > /dev/null
echo '127.0.0.1	store-ui.gateway.com' | sudo tee -a /etc/hosts > /dev/null
echo '127.0.0.1	ashraf.gateway.com' | sudo tee -a /etc/hosts > /dev/null
echo '127.0.0.1	ashraf.com' | sudo tee -a /etc/hosts > /dev/null
echo '127.0.0.1	dcm' | sudo tee -a /etc/hosts > /dev/null
echo '127.0.0.1	domain-ownership' | sudo tee -a /etc/hosts > /dev/null