plugins {
    id 'java'
}
group = 'com.asrevo.cvhome'

java {
    sourceCompatibility = '17'
}

repositories {
    mavenCentral()
}

tasks.named('test') {
    useJUnitPlatform()
}

dependencies {
    compileOnly 'org.projectlombok:lombok:1.18.28'
    annotationProcessor 'org.projectlombok:lombok:1.18.28'
}

