'use client'
// GENERATED by scripts/theme-client-barrier.mjs — the client barrier of the cosmetics theme.
//
// Server components import client components from HERE, never from their files: a direct import makes the
// component part of the route's shared chunk group (every store downloads it), while a next/dynamic issued from
// this client module makes ./client-bundle its own async chunk, fetched only by stores rendering this theme.
// The `import()` literal is what the next/dynamic transform records, so SSR preloads the chunk and its CSS.
// No `loading` option on purpose: it would wrap each component in a Suspense boundary, and the Frame's boundary
// above the page would flush the shell before a page's notFound()/error — every 404 would stream as a 200.
import dynamic from 'next/dynamic';

export const ThemeFrame = dynamic(() => import('./client-bundle').then(m => ({default: m.ThemeFrame})));
export const CartLineItem = dynamic(() => import('./client-bundle').then(m => ({default: m.CartLineItem})));
export const ProductCard = dynamic(() => import('./client-bundle').then(m => ({default: m.ProductCard})));
export const Announcement = dynamic(() => import('./client-bundle').then(m => ({default: m.Announcement})));
export const CartDrawer = dynamic(() => import('./client-bundle').then(m => ({default: m.CartDrawer})));
export const HeaderActions = dynamic(() => import('./client-bundle').then(m => ({default: m.HeaderActions})));
export const MobileNav = dynamic(() => import('./client-bundle').then(m => ({default: m.MobileNav})));
export const Nav = dynamic(() => import('./client-bundle').then(m => ({default: m.Nav})));
export const CheckoutResult = dynamic(() => import('./client-bundle').then(m => ({default: m.CheckoutResult})));
export const BuyBox = dynamic(() => import('./client-bundle').then(m => ({default: m.BuyBox})));
export const CheckoutForm = dynamic(() => import('./client-bundle').then(m => ({default: m.CheckoutForm})));
export const CustomerTabs = dynamic(() => import('./client-bundle').then(m => ({default: m.CustomerTabs})));
export const Gallery = dynamic(() => import('./client-bundle').then(m => ({default: m.Gallery})));
export const Hero = dynamic(() => import('./client-bundle').then(m => ({default: m.Hero})));
export const Listing = dynamic(() => import('./client-bundle').then(m => ({default: m.Listing})));
export const OrderDetails = dynamic(() => import('./client-bundle').then(m => ({default: m.OrderDetails})));
export const OrderSummary = dynamic(() => import('./client-bundle').then(m => ({default: m.OrderSummary})));
export const ProductRail = dynamic(() => import('./client-bundle').then(m => ({default: m.ProductRail})));
export const SearchBox = dynamic(() => import('./client-bundle').then(m => ({default: m.SearchBox})));
export const EmptyState = dynamic(() => import('./client-bundle').then(m => ({default: m.EmptyState})));
export const ErrorState = dynamic(() => import('./client-bundle').then(m => ({default: m.ErrorState})));
export const Redirecting = dynamic(() => import('./client-bundle').then(m => ({default: m.Redirecting})));
