// GENERATED by libs/types/scripts/build-color-schemas.mjs (THEME_DEFAULTS.cosmetics) — edit the seed there, then
// `npm run gen:colors` in libs/types. Same rules as the merchant presets (see that file's header).
import type {ColorSchema} from '@store-front/types';

/**
 * TODO Cosmetics: replace with the palette of the chosen visual world (copied from starter). (light)
 *
 * The theme's own palette — what renders when the merchant's colour theme is `DEFAULT` or unset. Wired as
 * `tokens.defaultColors` in `./index.ts`; any fixed preset the merchant picks replaces it whole.
 */
export const DEFAULT_COLORS: ColorSchema = {
    primary: "#1E1A16",
    secondary: "#DCD7CF",
    accent: "#B2001B",
    background: "#FDFCF9",
    foreground: "#1A1512",
    error: "#B7191C",
    warning: "#EE9E10",
    success: "#007533",
    info: "#0065A1",
    neutral: "#B0A9A5",
    border: "#DFDACF",
    ring: "#1E1A16",
    outline: "#1D1A18",
    hoverPrimary: "#0E0A07",
    focusPrimary: "#040201",
    hoverSecondary: "#C5C0B8",
    focusSecondary: "#B2ADA6",
    hoverAccent: "#8F0013",
    focusAccent: "#73000D",
    hoverError: "#99000D",
    focusError: "#7D0008",
    hoverWarning: "#D38A00",
    focusWarning: "#BA7900",
    hoverSuccess: "#005E28",
    focusSuccess: "#004B1E",
    hoverInfo: "#005182",
    focusInfo: "#004069",
    hoverNeutral: "#9A948F",
    focusNeutral: "#88827D",
};
