// GENERATED by libs/types/scripts/build-color-schemas.mjs (THEME_DEFAULTS.grocery) — edit the seed there, then
// `npm run gen:colors` in libs/types. Same rules as the merchant presets (see that file's header).
import type {ColorSchema} from '@store-front/types';

/**
 * Cash & Carry: concrete floor, near-black ink, safety-yellow price boards with dark text; crate-blue wash; signal-red statement. (light)
 *
 * The theme's own palette — what renders when the merchant's colour theme is `DEFAULT` or unset. Wired as
 * `tokens.defaultColors` in `./index.ts`; any fixed preset the merchant picks replaces it whole.
 */
export const DEFAULT_COLORS: ColorSchema = {
    primary: "#EDB417",
    secondary: "#B4D6F3",
    accent: "#B7010B",
    background: "#EFF2F5",
    foreground: "#14181F",
    error: "#B7191C",
    warning: "#EE9E10",
    success: "#007533",
    info: "#0065A1",
    neutral: "#A5ABB5",
    border: "#C9D2DC",
    ring: "#B08400",
    outline: "#A78742",
    hoverPrimary: "#D29F00",
    focusPrimary: "#BC8D00",
    hoverSecondary: "#9EBFDC",
    focusSecondary: "#8BACC9",
    hoverAccent: "#950007",
    focusAccent: "#780004",
    hoverError: "#99000D",
    focusError: "#7D0008",
    hoverWarning: "#D38A00",
    focusWarning: "#BA7900",
    hoverSuccess: "#005E28",
    focusSuccess: "#004B1E",
    hoverInfo: "#005182",
    focusInfo: "#004069",
    hoverNeutral: "#90969F",
    focusNeutral: "#7E848C",
};
