// GENERATED by scripts/theme-routes.mjs — do not edit. The route logic lives in src/shell/routes.
import theme from '@store-front/theme-fashion';
import {helpPage} from '@/shell/routes/help';

export {generateMetadata} from '@/shell/routes/help';
export default helpPage(async () => theme);
