export const CART_DATA_KEY: string = "store-ui-cart-data";
export const HOME_PAGE_PATH = "pages/page";
export const PRODUCT_PAGE_PATH = "pages/product/[url]/page";
export const CONTENT_PAGE_PATH = "pages/content/[url]/page";
export const CONTACT_PAGE_PATH = "pages/contact/page";
export const CHECKOUT_PAGE_PATH = "pages/checkout/page";
export const CATEGORY_PAGE_PATH = "pages/category/[url]/page";
export const CART_PAGE_PATH = "pages/category/[url]/page";
export const HEADER_PATH = `layout/header/page`;
export const FOOTER_PATH = `layout/footer/page`;
export const errorClass = "border-error";
export const defaultClass = "border-neutral";
export const focusErrorClass = "focus:ring-error";
export const focusDefaultClass = "focus:ring-primary";
export const locales = ['en', 'fr', 'ar', 'es', 'ru'];
export const FALLBACK_LOCALE = 'en';
export const STORE_DEFAULT_LOCALE_COOKIE_NAME = 'STORE-DEFAULT-LOCALE';
export const DEFAULT_STORE_POD_GATEWAY = "http://store-pod-1.gateway.com:8100"
export const FALLBACK_STORE_ID = "65f023632bc26470c104b75f";
