com:
  asrevo:
    cvhome:
      fargate:
        namespace: "cvhome.lcl"
spring:
  security:
    oauth2:
      client:
        registration:
          microservice:
            provider: keycloak
            client-id: microservice-app
            client-secret: r1nuVn4HefusLGwHIeRxbdOzdTZLEMvQ
            authorization-grant-type: password
          keycloak:
            client-id: web-app
            client-authentication-method: client_secret_basic
            authorization-grant-type: authorization_code
            scope: openid, profile, email
            redirect-uri: "{baseUrl}/login/oauth2/code/keycloak"
            provider: keycloak
            client-secret: hLwOF59NEOdMzYYrfxUbQEGVK1uTczj7
        provider:
          keycloak:
            jwk-set-uri: http://auth.cvhome.lcl:9999/realms/cvhome/protocol/openid-connect/certs
            authorization-uri: https://auth.${com.asrevo.cvhome.ssl.default-domain}:${server.port}/realms/cvhome/protocol/openid-connect/auth
            token-uri: http://auth.cvhome.lcl:9999/realms/cvhome/protocol/openid-connect/token
  cloud:
    loadbalancer:
      eager-load:
        clients:
          - "gateway"
          - "domain-certificate-manager"
          - "auth"
          - "welcome-ui"
          - "admin-ui"
          - "store-ui"
    ecs:
      discovery:
        namespace: "cvhome.lcl"
        namespace-id: "ns-je7qri6wn7fbsrpn"
    gateway:
      discovery:
        locator:
          enabled: true
      default-filters:
        - TokenRelay
        - PreserveHostHeader
        - AddResponseHeader=X-Frame-Options, SAMEORIGIN
      routes:
        - id: domain-certificate-manager
          uri: lb://domain-certificate-manager:8082
          predicates:
            - Path=/domain-certificate-manager/**
          filters:
            - StripPrefix=1
        - id: store
          uri: lb://store:8083
          predicates:
            - Path=/store/**
          filters:
            - StripPrefix=1
        - id: auth
          uri: lb://auth:9999
          predicates:
            - FHost=auth.${com.asrevo.cvhome.ssl.default-domain}
        - id: realms
          uri: lb://auth:9999
          predicates:
            - Path=/realms/**
          filters:
            - SetRequestHostHeader=auth.${com.asrevo.cvhome.ssl.default-domain}:${server.port}
        - id: resources
          uri: lb://auth:9999
          predicates:
            - Path=/resources/**
        - id: js
          uri: lb://auth:9999
          predicates:
            - Path=/js/**
        - id: welcome-ui
          uri: lb://welcome-ui:4400
          predicates:
            - FHost=www.${com.asrevo.cvhome.ssl.default-domain},${com.asrevo.cvhome.ssl.default-domain}
        - id: admin-ui
          uri: lb://admin-ui:4200
          predicates:
            - FHost=admin.${com.asrevo.cvhome.ssl.default-domain}
        - id: store-ui
          uri: lb://store-ui:4300
          predicates:
            - FHost={domain}.{x},{sub}.{domain}.{x}
          filters:
            - MapHostAsRequestParam=userId