// GENERATED by scripts/theme-routes.mjs — do not edit. The route logic lives in src/shell/routes.
import theme from '@store-front/theme-hunger';
import {loadingScreen} from '@/shell/routes/loading';

export default loadingScreen(theme, 'checkout');
