// GENERATED by scripts/theme-routes.mjs — do not edit. The route logic lives in src/shell/routes.
import theme from '@store-front/theme-jewellery';
import {helpPage} from '@/shell/routes/help';

export {generateMetadata} from '@/shell/routes/help';
export default helpPage(theme);
