spring:
  application:
    name: landing-ui
server:
  forward-headers-strategy: FRAMEWORK
  port: ${com.asrevo.cvhome.services.landing-ui.port}
info:
  app:
    name: ${spring.application.name}
management:
  observations:
    key-values:
      application: ${spring.application.name}
