spring:
  application:
    name: uaa
  config:
    import: "classpath:common-config.yml"
  security:
    oauth2:
      client:
        registration:
          s2s:
            provider: uaa
            client-id: store-core@service.store-core.internal
            client-secret: hLwOF59NEOdMzYYrfxUbQEGVK1uTczj7
            authorization-grant-type: client_credentials
            scope: store_core
  sql:
    init:
      schema-locations: classpath:init-sql/schema.sql
      data-locations: classpath:init-sql/data-common.sql

com:
  asrevo:
    cvhome:
      uaa:
        admin:
          password: admin
        oauth2:
          clients:
            admin-sdk:
              secret: hLwOF59NEOdMzYYrfxUbQEGVK1uTczj7
            store-pod-507f1f77@service.store-pod.internal:
              secret: hLwOF59NEOdMzYYrfxUbQEGVK1uTczj7
            store-core@service.store-core.internal:
              secret: hLwOF59NEOdMzYYrfxUbQEGVK1uTczj7
            web-app:
              secret: hLwOF59NEOdMzYYrfxUbQEGVK1uTczj7
              redirect-uri-paths:
                - "/login/oauth2/code/uaa"
              post-logout-redirect-uri-paths:
                - ""
