plugins {
    alias(libs.plugins.java.library.conventions)
}

dependencies {
    testImplementation libs.jakarta.persistence.api
    testImplementation libs.spring.data.jpa
    api project(':store-pod:commons:store-commons')
    api project(':store-pod:merchant:merchant-commons')
    compileOnly libs.spring.data.jpa
    compileOnly libs.jakarta.validation.api
    compileOnly libs.jackson.annotations
    compileOnly libs.lombok
    compileOnly libs.hibernate.core
    annotationProcessor libs.lombok
}
