spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/cvhome
    username: postgres
    password: password
  cloud:
    local:
      discovery:
        enabled: true
        services:
          dcm:
            - url: "http://localhost:8001"
              metadata:
                service-name: dcm
                instance: dcm-1
          router:
            - url: "http://localhost:8002"
              metadata:
                service-name: router
                instance: router-1
          auth:
            - url: "http://localhost:9999"
              metadata:
                service-name: auth
                instance: auth-1
          welcome-ui:
            - url: "http://localhost:4400"
              metadata:
                service-name: welcome-ui
                instance: welcome-ui-1
          manager:
            - url: "http://localhost:7001"
              metadata:
                service-name: manager
                instance: manager-1
          wallet:
            - url: "http://localhost:7002"
              metadata:
                service-name: wallet
                instance: wallet-1
          store-ui:
            - url: "http://localhost:4200"
              metadata:
                service-name: store-ui
                instance: store-ui-1
          store:
            - url: "http://localhost:7101"
              metadata:
                service-name: store
                instance: store-1
          landing-ui:
            - url: "http://localhost:7102"
              metadata:
                service-name: landing-ui
                instance: landing-ui-1