spring:
  cloud:
    loadbalancer:
      eager-load:
        clients:
          - "core-gateway"
          - "domain-certificate-manager"
          - "router"
          - "auth"
          - "welcome-ui"
    ecs:
      discovery:
        namespace: "core.cvhome.lcl"
        namespace-id: "ns-je7qri6wn7fbsrpn"
        enabled: true
        default-port: 8080
        service-ports:
          "domain-certificate-manager": 8001
          "router": 8002
          "auth": 9999
          "welcome-ui": 4400
    gateway:
      discovery:
        locator:
          enabled: true
      default-filters:
        - TokenRelay
        - PreserveHostHeader
        - AddResponseHeader=X-Frame-Options, SAMEORIGIN
      routes:
        - id: welcome-ui
          uri: lb://welcome-ui
          predicates:
            - FHost=www.${com.asrevo.cvhome.services.core-gateway.domain},${com.asrevo.cvhome.services.core-gateway.domain}