spring:
  security:
    oauth2:
      client:
        registration:
          microservice:
            provider: keycloak
            client-id: microservice-app
            client-secret: r1nuVn4HefusLGwHIeRxbdOzdTZLEMvQ
            authorization-grant-type: password
          keycloak:
            client-id: web-app
            client-authentication-method: client_secret_basic
            authorization-grant-type: authorization_code
            scope: openid, profile, email
            redirect-uri: "{baseUrl}/login/oauth2/code/keycloak"
            provider: keycloak
            client-secret: hLwOF59NEOdMzYYrfxUbQEGVK1uTczj7
        provider:
          keycloak:
            jwk-set-uri: http://localhost:9999/realms/cvhome/protocol/openid-connect/certs
            authorization-uri: http://auth.${com.asrevo.cvhome.ssl.default-domain}:${server.port}/realms/cvhome/protocol/openid-connect/auth
            token-uri: http://localhost:9999/realms/cvhome/protocol/openid-connect/token
  cloud:
    discovery:
      client:
        simple:
          instances:
            domain-certificate-manager:
              - uri: "http://localhost:8082"
                metadata:
                  service-name: domain-certificate-manager
                  instance: domain-certificate-manager-1
            auth:
              - uri: "http://localhost:9999"
                metadata:
                  service-name: auth
                  instance: auth-1
            admin-ui:
              - uri: "http://localhost:4200"
                metadata:
                  service-name: admin-ui
                  instance: admin-ui-1
            welcome-ui:
              - uri: "http://localhost:4400"
                metadata:
                  service-name: welcome-ui
                  instance: welcome-ui-1
    gateway:
      discovery:
        locator:
          enabled: true
      default-filters:
        - TokenRelay
        - PreserveHostHeader
        - AddResponseHeader=X-Frame-Options, SAMEORIGIN
      routes:
        - id: domain-certificate-manager
          uri: lb://domain-certificate-manager
          predicates:
            - Path=/domain-certificate-manager/**
          filters:
            - StripPrefix=1
        - id: auth
          uri: lb://auth
          predicates:
            - FHost=auth.${com.asrevo.cvhome.ssl.default-domain}
        - id: realms
          uri: lb://auth
          predicates:
            - Path=/realms/**
          filters:
            - SetRequestHostHeader=auth.${com.asrevo.cvhome.ssl.default-domain}:${server.port}
        - id: resources
          uri: lb://auth
          predicates:
            - Path=/resources/**
        - id: js
          uri: lb://auth
          predicates:
            - Path=/js/**
        - id: welcome-ui
          uri: lb://welcome-ui
          predicates:
            - FHost=www.${com.asrevo.cvhome.ssl.default-domain},${com.asrevo.cvhome.ssl.default-domain}
        - id: admin-ui
          uri: lb://admin-ui
          predicates:
            - FHost=admin.${com.asrevo.cvhome.ssl.default-domain}
