spring:
  cloud:
    local:
      discovery:
        enabled: true
        services:
          domain-certificate-manager:
            - url: "http://localhost:8001"
              metadata:
                service-name: domain-certificate-manager
                instance: domain-certificate-manager-1
          router:
            - url: "http://localhost:8002"
              metadata:
                service-name: router
                instance: router-1
          auth:
            - url: "http://localhost:9999"
              metadata:
                service-name: auth
                instance: auth-1
          welcome-ui:
            - url: "http://localhost:4400"
              metadata:
                service-name: welcome-ui
                instance: welcome-ui-1
    gateway:
      discovery:
        locator:
          enabled: true
      default-filters:
        - TokenRelay
        - PreserveHostHeader
        - AddResponseHeader=X-Frame-Options, SAMEORIGIN
      routes:
        - id: welcome-ui
          order: -1
          uri: lb://welcome-ui
          predicates:
            - FHost=www.${com.asrevo.cvhome.services.core-gateway.domain},${com.asrevo.cvhome.services.core-gateway.domain}