// GENERATED by scripts/theme-routes.mjs — do not edit. The route logic lives in src/shell/routes.
import theme from '@store-front/theme-jewellery';
import {productPage} from '@/shell/routes/product';

export {generateMetadata} from '@/shell/routes/product';
export default productPage(theme);
