spring:
  application:
    name: control-plane
  config:
    import: "classpath:common-config.yml"
  security:
    oauth2:
      client:
        registration:
          s2s:
            provider: uaa
            client-id: control-plane@service.store-core.internal
            client-secret: hLwOF59NEOdMzYYrfxUbQEGVK1uTczj7
            authorization-grant-type: client_credentials
com:
  asrevo:
    cvhome:
      kc:
        credentials:
          server-url: ${com.asrevo.cvhome.services.uaa.schema}://${com.asrevo.cvhome.services.uaa.domain}:${com.asrevo.cvhome.services.uaa.port}
          realm: cvhome
          client-id: internal-client
          client-secret: hLwOF59NEOdMzYYrfxUbQEGVK1uTczj7