-- Pages beyond the six the store shipped with.
--
-- Demo content for the test store 65f023632bc46470c104b76f (Riyadh Fashion Hub), in every language the store sells in.
-- Generated seed: ids are negative on purpose — content, media and menu ids all come from sequences that
-- only grow upward, so a seed row below zero can never collide with one the running service creates.

-- page: size-guide (PUBLISHED)
INSERT INTO content.content (content_id, date_created, date_modified, updt_id, code, content_type, sort_order, visible, store_merchant_id, status, publish_at, unpublish_at, version, created_by, updated_by, parent_id, noindex, canonical_url, og_media_id, show_in_footer, placement, starts_at, ends_at, policy_type, meta)
VALUES (-40001, now(), now(), 'seed', 'size-guide', 'PAGE', 10, true, '65f023632bc46470c104b76f', 'PUBLISHED', null, null, 1, 'seed', 'seed', null, false, null, null, true, null, null, null, null, null)
on conflict (content_id) do nothing;
INSERT INTO content.content_description (description_id, date_created, date_modified, updt_id, description, name, title, meta_description, meta_keywords, meta_title, sef_url, language_code, content_id, state, excerpt, alt_text, cta_label, subtitle)
VALUES (-400001, now(), now(), 'seed', '<h2>كيف تقيس</h2><p>قِس فوق ملابس داخلية خفيفة، والشريط ملاصق للجسم دون شدّ. المقاسات المذكورة هي مقاسات الجسم لا مقاسات القطعة.</p><h3>النساء</h3><table><tr><th>المقاس</th><th>الصدر</th><th>الخصر</th><th>الأرداف</th></tr><tr><td>S</td><td>84 سم</td><td>66 سم</td><td>92 سم</td></tr><tr><td>M</td><td>90 سم</td><td>72 سم</td><td>98 سم</td></tr><tr><td>L</td><td>96 سم</td><td>78 سم</td><td>104 سم</td></tr><tr><td>XL</td><td>104 سم</td><td>86 سم</td><td>112 سم</td></tr></table><h3>الرجال</h3><table><tr><th>المقاس</th><th>الصدر</th><th>الخصر</th></tr><tr><td>S</td><td>94 سم</td><td>80 سم</td></tr><tr><td>M</td><td>100 سم</td><td>86 سم</td></tr><tr><td>L</td><td>108 سم</td><td>94 سم</td></tr><tr><td>XL</td><td>116 سم</td><td>102 سم</td></tr></table><h3>بين مقاسين؟</h3><p>اختر الأكبر في القطع المنسوجة، والأصغر في القطع القطنية القابلة للتمدد. كل صفحة منتج تذكر إن كان القَصّ ضيقًا أو واسعًا.</p>', 'دليل المقاسات', 'دليل المقاسات', 'جداول مقاسات الرجال والنساء والأطفال بالسنتيمتر، مع طريقة القياس الصحيحة.', 'مقاسات, دليل المقاسات, قياس', 'دليل المقاسات | Riyadh Fashion Hub', 'size-guide-ar', 'ar', -40001, 'TRANSLATED', null, null, null, null)
on conflict (description_id) do nothing;
INSERT INTO content.content_description (description_id, date_created, date_modified, updt_id, description, name, title, meta_description, meta_keywords, meta_title, sef_url, language_code, content_id, state, excerpt, alt_text, cta_label, subtitle)
VALUES (-400002, now(), now(), 'seed', '<h2>How to measure</h2><p>Measure over light underwear, tape flat against the body and not pulled tight. The figures below are body measurements, not garment measurements.</p><h3>Women</h3><table><tr><th>Size</th><th>Bust</th><th>Waist</th><th>Hips</th></tr><tr><td>S</td><td>84 cm</td><td>66 cm</td><td>92 cm</td></tr><tr><td>M</td><td>90 cm</td><td>72 cm</td><td>98 cm</td></tr><tr><td>L</td><td>96 cm</td><td>78 cm</td><td>104 cm</td></tr><tr><td>XL</td><td>104 cm</td><td>86 cm</td><td>112 cm</td></tr></table><h3>Men</h3><table><tr><th>Size</th><th>Chest</th><th>Waist</th></tr><tr><td>S</td><td>94 cm</td><td>80 cm</td></tr><tr><td>M</td><td>100 cm</td><td>86 cm</td></tr><tr><td>L</td><td>108 cm</td><td>94 cm</td></tr><tr><td>XL</td><td>116 cm</td><td>102 cm</td></tr></table><h3>Between two sizes?</h3><p>Size up in woven pieces, down in stretch cotton. Every product page states whether the cut runs slim or relaxed.</p>', 'Size guide', 'Size guide', 'Women''s, men''s and kids'' size charts in centimetres, and how to measure properly.', 'sizing, size guide, measurements', 'Size guide | Riyadh Fashion Hub', 'size-guide', 'en', -40001, 'TRANSLATED', null, null, null, null)
on conflict (description_id) do nothing;

-- page: fabric-and-care (PUBLISHED)
INSERT INTO content.content (content_id, date_created, date_modified, updt_id, code, content_type, sort_order, visible, store_merchant_id, status, publish_at, unpublish_at, version, created_by, updated_by, parent_id, noindex, canonical_url, og_media_id, show_in_footer, placement, starts_at, ends_at, policy_type, meta)
VALUES (-40002, now(), now(), 'seed', 'fabric-and-care', 'PAGE', 11, true, '65f023632bc46470c104b76f', 'PUBLISHED', null, null, 1, 'seed', 'seed', null, false, null, null, false, null, null, null, null, null)
on conflict (content_id) do nothing;
INSERT INTO content.content_description (description_id, date_created, date_modified, updt_id, description, name, title, meta_description, meta_keywords, meta_title, sef_url, language_code, content_id, state, excerpt, alt_text, cta_label, subtitle)
VALUES (-400003, now(), now(), 'seed', '<h2>من أين تأتي أقمشتنا</h2><ul><li>القطن المُمشَّط من مصر وتركيا، بوزن 180 غرامًا للمتر فأعلى</li><li>الكتان من البرتغال، مغسول مسبقًا لتقليل الانكماش</li><li>الفيسكوز من لُبّ خشب معتمد من مجلس رعاية الغابات</li></ul><h2>العناية في مناخ الرياض</h2><p>الحرارة والغبار أقسى على النسيج من الغسيل نفسه.</p><ul><li>اغسل بماء بارد؛ الماء الساخن يثبّت العرق والغبار داخل الألياف</li><li>جفّف في الظل — الشمس المباشرة تُبهت الألوان الداكنة خلال أسابيع</li><li>اقلب القطع المطبوعة قبل الغسل والكي</li><li>الكتان يُكوى وهو رطب قليلًا، وإلا لن يستقيم</li></ul><h2>الوبر</h2><p>الوبر ليس عيبًا في القطن، بل ألياف قصيرة تتحرر مع الاستخدام. مشط النسيج يزيله دون إتلاف القطعة.</p>', 'الأقمشة والعناية', 'الأقمشة والعناية', 'من أين تأتي أقمشتنا، وكيف تعتني بها لتدوم مواسم لا موسمًا واحدًا.', 'أقمشة, عناية, غسيل', 'الأقمشة والعناية | Riyadh Fashion Hub', 'fabric-and-care-ar', 'ar', -40002, 'TRANSLATED', null, null, null, null)
on conflict (description_id) do nothing;
INSERT INTO content.content_description (description_id, date_created, date_modified, updt_id, description, name, title, meta_description, meta_keywords, meta_title, sef_url, language_code, content_id, state, excerpt, alt_text, cta_label, subtitle)
VALUES (-400004, now(), now(), 'seed', '<h2>Where our fabric comes from</h2><ul><li>Combed cotton from Egypt and Türkiye, 180 gsm and up</li><li>Linen from Portugal, pre-washed to limit shrinkage</li><li>Viscose from FSC-certified wood pulp</li></ul><h2>Care in the Riyadh climate</h2><p>Heat and dust are harder on cloth than washing is.</p><ul><li>Wash cold; hot water sets perspiration and dust into the fibre</li><li>Dry in shade — direct sun fades dark dyes within weeks</li><li>Turn printed pieces inside out to wash and to iron</li><li>Iron linen slightly damp, or it will not sit flat</li></ul><h2>Pilling</h2><p>Pilling is not a fault in cotton: it is short fibres working loose. A fabric comb removes it without damaging the garment.</p>', 'Fabric & care', 'Fabric & care', 'Where our fabrics come from, and how to look after them so they last seasons rather than one summer.', 'fabric, care, washing', 'Fabric & care | Riyadh Fashion Hub', 'fabric-and-care', 'en', -40002, 'TRANSLATED', null, null, null, null)
on conflict (description_id) do nothing;

-- page: careers (PUBLISHED)
INSERT INTO content.content (content_id, date_created, date_modified, updt_id, code, content_type, sort_order, visible, store_merchant_id, status, publish_at, unpublish_at, version, created_by, updated_by, parent_id, noindex, canonical_url, og_media_id, show_in_footer, placement, starts_at, ends_at, policy_type, meta)
VALUES (-40003, now(), now(), 'seed', 'careers', 'PAGE', 12, true, '65f023632bc46470c104b76f', 'PUBLISHED', null, null, 1, 'seed', 'seed', null, false, null, null, true, null, null, null, null, null)
on conflict (content_id) do nothing;
INSERT INTO content.content_description (description_id, date_created, date_modified, updt_id, description, name, title, meta_description, meta_keywords, meta_title, sef_url, language_code, content_id, state, excerpt, alt_text, cta_label, subtitle)
VALUES (-400005, now(), now(), 'seed', '<h2>العمل معنا</h2><p>نحن اثنان وأربعون شخصًا بين معرض العليا ومستودع الخرج وفريق تصميم صغير.</p><h3>الشواغر الحالية</h3><ul><li>مستشار مبيعات — دوام كامل، العليا</li><li>مصمم أنماط — دوام كامل، الرياض</li><li>أخصائي تجارة إلكترونية — دوام كامل، عن بُعد داخل المملكة</li></ul><p>أرسل سيرتك إلى <a href="mailto:careers@riyadhfashionhub.sa">careers@riyadhfashionhub.sa</a> مع سطرين عن سبب اهتمامك بهذا المجال تحديدًا.</p>', 'الوظائف', 'الوظائف', 'وظائف شاغرة في المعرض والمستودع وفريق التصميم في الرياض.', 'وظائف, توظيف, الرياض', 'الوظائف | Riyadh Fashion Hub', 'careers-ar', 'ar', -40003, 'TRANSLATED', null, null, null, null)
on conflict (description_id) do nothing;
INSERT INTO content.content_description (description_id, date_created, date_modified, updt_id, description, name, title, meta_description, meta_keywords, meta_title, sef_url, language_code, content_id, state, excerpt, alt_text, cta_label, subtitle)
VALUES (-400006, now(), now(), 'seed', '<h2>Working with us</h2><p>There are forty-two of us, across the Olaya store, the Al-Kharj warehouse and a small design team.</p><h3>Open roles</h3><ul><li>Sales advisor — full time, Olaya</li><li>Pattern designer — full time, Riyadh</li><li>E-commerce specialist — full time, remote within the Kingdom</li></ul><p>Send a CV to <a href="mailto:careers@riyadhfashionhub.sa">careers@riyadhfashionhub.sa</a> with two lines on why this particular field.</p>', 'Careers', 'Careers', 'Open roles across the Olaya store, the Al-Kharj warehouse and the design team.', 'jobs, hiring, riyadh', 'Careers | Riyadh Fashion Hub', 'careers', 'en', -40003, 'TRANSLATED', null, null, null, null)
on conflict (description_id) do nothing;

-- page: our-stores (PUBLISHED)
INSERT INTO content.content (content_id, date_created, date_modified, updt_id, code, content_type, sort_order, visible, store_merchant_id, status, publish_at, unpublish_at, version, created_by, updated_by, parent_id, noindex, canonical_url, og_media_id, show_in_footer, placement, starts_at, ends_at, policy_type, meta)
VALUES (-40004, now(), now(), 'seed', 'our-stores', 'PAGE', 13, true, '65f023632bc46470c104b76f', 'PUBLISHED', null, null, 1, 'seed', 'seed', (select content_id from content.content where store_merchant_id = '65f023632bc46470c104b76f' and code = 'location'), false, null, null, false, null, null, null, null, null)
on conflict (content_id) do nothing;
INSERT INTO content.content_description (description_id, date_created, date_modified, updt_id, description, name, title, meta_description, meta_keywords, meta_title, sef_url, language_code, content_id, state, excerpt, alt_text, cta_label, subtitle)
VALUES (-400007, now(), now(), 'seed', '<h2>معارضنا</h2><p>هذه الصفحة تابعة لصفحة « موقعنا »، وتستخدم للتحقق من مسار التنقل: الرئيسية › موقعنا › معارضنا.</p><ul><li><strong>العليا، الرياض</strong> — المعرض الرئيسي، خدمة التعديل مجانًا — يوميًا 10ص إلى 11م</li><li><strong>الرياض بارك</strong> — مجموعة مختارة — يوميًا 10ص إلى 12م</li><li><strong>جدة، حي الروضة</strong> — يوميًا 4م إلى 12م</li></ul><h3>خدمة التعديل</h3><p>تقصير البناطيل وتضييق الأكتاف مجانًا على أي قطعة تُشترى من المعرض، والتسليم خلال ثلاثة أيام.</p>', 'معارضنا', 'معارضنا', 'ثلاثة معارض في الرياض وجدة، بمواعيدها وخدماتها.', 'معارض, فروع, الرياض, جدة', 'معارضنا | Riyadh Fashion Hub', 'our-stores-ar', 'ar', -40004, 'TRANSLATED', null, null, null, null)
on conflict (description_id) do nothing;
INSERT INTO content.content_description (description_id, date_created, date_modified, updt_id, description, name, title, meta_description, meta_keywords, meta_title, sef_url, language_code, content_id, state, excerpt, alt_text, cta_label, subtitle)
VALUES (-400008, now(), now(), 'seed', '<h2>Our stores</h2><p>This page sits under “Location”, which makes it the breadcrumb check: it should read Home › Location › Our stores.</p><ul><li><strong>Olaya, Riyadh</strong> — flagship, free alterations — daily 10am–11pm</li><li><strong>Riyadh Park</strong> — selected range — daily 10am–midnight</li><li><strong>Al-Rawdah, Jeddah</strong> — daily 4pm–midnight</li></ul><h3>Alterations</h3><p>Hems and shoulder taper are free on anything bought in store, ready within three days.</p>', 'Our stores', 'Our stores', 'Three stores across Riyadh and Jeddah, with hours and in-store services.', 'stores, locations, riyadh, jeddah', 'Our stores | Riyadh Fashion Hub', 'our-stores', 'en', -40004, 'TRANSLATED', null, null, null, null)
on conflict (description_id) do nothing;

-- page: gift-cards (PUBLISHED)
INSERT INTO content.content (content_id, date_created, date_modified, updt_id, code, content_type, sort_order, visible, store_merchant_id, status, publish_at, unpublish_at, version, created_by, updated_by, parent_id, noindex, canonical_url, og_media_id, show_in_footer, placement, starts_at, ends_at, policy_type, meta)
VALUES (-40005, now(), now(), 'seed', 'gift-cards', 'PAGE', 14, true, '65f023632bc46470c104b76f', 'PUBLISHED', null, null, 1, 'seed', 'seed', null, false, 'https://org1-store1.asrevo.com/content/gift-cards', -490002, true, null, null, null, null, null)
on conflict (content_id) do nothing;
INSERT INTO content.content_description (description_id, date_created, date_modified, updt_id, description, name, title, meta_description, meta_keywords, meta_title, sef_url, language_code, content_id, state, excerpt, alt_text, cta_label, subtitle)
VALUES (-400009, now(), now(), 'seed', '<h2>هدية لا تحتاج مقاسًا</h2><p>بطاقاتنا من 100 إلى 5000 ريال، رقمية تصل خلال دقائق، أو مطبوعة داخل ظرف قماشي يُرسل مجانًا داخل المملكة.</p><p>صالحة لسنتين، تُستخدم أونلاين وفي المعارض، والرصيد المتبقي يبقى على البطاقة.</p><p>تحمل هذه الصفحة رابطًا قانونيًا وصورة Open Graph للتحقق من بيانات الـ SEO في المتجر.</p>', 'بطاقات الهدايا', 'بطاقات الهدايا', 'بطاقات هدايا من 100 إلى 5000 ريال، صالحة سنتين أونلاين وفي المعارض.', 'بطاقة هدية, قسيمة شراء', 'بطاقات الهدايا | Riyadh Fashion Hub', 'gift-cards-ar', 'ar', -40005, 'TRANSLATED', null, null, null, null)
on conflict (description_id) do nothing;
INSERT INTO content.content_description (description_id, date_created, date_modified, updt_id, description, name, title, meta_description, meta_keywords, meta_title, sef_url, language_code, content_id, state, excerpt, alt_text, cta_label, subtitle)
VALUES (-400010, now(), now(), 'seed', '<h2>A gift that needs no size</h2><p>Cards run from SAR 100 to SAR 5,000 — digital and delivered in minutes, or printed and posted free inside the Kingdom in a cloth envelope.</p><p>They are valid for two years, usable online and in store, and any remaining balance stays on the card.</p><p>This page carries a canonical URL and an Open Graph image, which makes it the check on the storefront''s SEO rendering.</p>', 'Gift cards', 'Gift cards', 'Gift cards from SAR 100 to SAR 5,000, valid two years online and in store.', 'gift card, voucher', 'Gift cards | Riyadh Fashion Hub', 'gift-cards', 'en', -40005, 'TRANSLATED', null, null, null, null)
on conflict (description_id) do nothing;

-- page: sustainability (PUBLISHED)
INSERT INTO content.content (content_id, date_created, date_modified, updt_id, code, content_type, sort_order, visible, store_merchant_id, status, publish_at, unpublish_at, version, created_by, updated_by, parent_id, noindex, canonical_url, og_media_id, show_in_footer, placement, starts_at, ends_at, policy_type, meta)
VALUES (-40006, now(), now(), 'seed', 'sustainability', 'PAGE', 15, true, '65f023632bc46470c104b76f', 'PUBLISHED', null, null, 1, 'seed', 'seed', null, true, null, null, false, null, null, null, null, null)
on conflict (content_id) do nothing;
INSERT INTO content.content_description (description_id, date_created, date_modified, updt_id, description, name, title, meta_description, meta_keywords, meta_title, sef_url, language_code, content_id, state, excerpt, alt_text, cta_label, subtitle)
VALUES (-400011, now(), now(), 'seed', '<h2>ما نقيسه</h2><p>هذه الصفحة مُعلَّمة بـ <code>noindex</code>: يجب أن تظهر في المتجر وتختفي من خريطة الموقع. هذا هو اختبار العلامة.</p><ul><li>التغليف ورقي بالكامل منذ 2025، بلا بلاستيك</li><li>94% من المرتجعات تعود للبيع بعد الفحص والكي</li><li>خدمة التعديل المجانية تطيل عمر القطعة، وهي أرخص إجراء بيئي متاح لنا</li></ul>', 'الاستدامة', 'الاستدامة', 'التغليف والمرتجعات وعمر القطعة — صفحة مستبعدة عمدًا من الفهرسة.', 'استدامة, تغليف, مرتجعات', 'الاستدامة | Riyadh Fashion Hub', 'sustainability-ar', 'ar', -40006, 'TRANSLATED', null, null, null, null)
on conflict (description_id) do nothing;
INSERT INTO content.content_description (description_id, date_created, date_modified, updt_id, description, name, title, meta_description, meta_keywords, meta_title, sef_url, language_code, content_id, state, excerpt, alt_text, cta_label, subtitle)
VALUES (-400012, now(), now(), 'seed', '<h2>What we measure</h2><p>This page is flagged <code>noindex</code>: it should render in the storefront but stay out of the sitemap. That is the check on the SEO flag.</p><ul><li>Packaging has been all-paper since 2025, with no plastic</li><li>94% of returns go back on sale after inspection and pressing</li><li>Free alterations extend garment life, which is the cheapest environmental measure available to us</li></ul>', 'Sustainability', 'Sustainability', 'Packaging, returns and garment lifespan — a page deliberately kept out of the index.', 'sustainability, packaging, returns', 'Sustainability | Riyadh Fashion Hub', 'sustainability', 'en', -40006, 'TRANSLATED', null, null, null, null)
on conflict (description_id) do nothing;

-- page: ramadan-collection (SCHEDULED)
INSERT INTO content.content (content_id, date_created, date_modified, updt_id, code, content_type, sort_order, visible, store_merchant_id, status, publish_at, unpublish_at, version, created_by, updated_by, parent_id, noindex, canonical_url, og_media_id, show_in_footer, placement, starts_at, ends_at, policy_type, meta)
VALUES (-40007, now(), now(), 'seed', 'ramadan-collection', 'PAGE', 16, true, '65f023632bc46470c104b76f', 'SCHEDULED', now() + interval '21 days', null, 1, 'seed', 'seed', null, false, null, null, false, null, null, null, null, null)
on conflict (content_id) do nothing;
INSERT INTO content.content_description (description_id, date_created, date_modified, updt_id, description, name, title, meta_description, meta_keywords, meta_title, sef_url, language_code, content_id, state, excerpt, alt_text, cta_label, subtitle)
VALUES (-400013, now(), now(), 'seed', '<h2>مجموعة رمضان</h2><p>هذه الصفحة بحالة <strong>SCHEDULED</strong> وتُنشر بعد ثلاثة أسابيع. يجب أن تظهر في لوحة التحكم وتعطي 404 في المتجر.</p>', 'مجموعة رمضان (مجدولة)', 'مجموعة رمضان (مجدولة)', 'صفحة مجدولة: يجب ألا تظهر في المتجر قبل موعد نشرها.', 'رمضان, مجموعة', 'مجموعة رمضان | Riyadh Fashion Hub', 'ramadan-collection-ar', 'ar', -40007, 'TRANSLATED', null, null, null, null)
on conflict (description_id) do nothing;
INSERT INTO content.content_description (description_id, date_created, date_modified, updt_id, description, name, title, meta_description, meta_keywords, meta_title, sef_url, language_code, content_id, state, excerpt, alt_text, cta_label, subtitle)
VALUES (-400014, now(), now(), 'seed', '<h2>Ramadan collection</h2><p>This page is <strong>SCHEDULED</strong> to publish in three weeks. It should be visible in the console and 404 in the storefront.</p>', 'Ramadan collection (scheduled)', 'Ramadan collection (scheduled)', 'A scheduled page: it must not appear in the storefront before its publish date.', 'ramadan, collection', 'Ramadan collection | Riyadh Fashion Hub', 'ramadan-collection', 'en', -40007, 'TRANSLATED', null, null, null, null)
on conflict (description_id) do nothing;

-- page: lookbook-2024 (ARCHIVED)
INSERT INTO content.content (content_id, date_created, date_modified, updt_id, code, content_type, sort_order, visible, store_merchant_id, status, publish_at, unpublish_at, version, created_by, updated_by, parent_id, noindex, canonical_url, og_media_id, show_in_footer, placement, starts_at, ends_at, policy_type, meta)
VALUES (-40008, now(), now(), 'seed', 'lookbook-2024', 'PAGE', 17, false, '65f023632bc46470c104b76f', 'ARCHIVED', null, null, 1, 'seed', 'seed', null, false, null, null, false, null, null, null, null, null)
on conflict (content_id) do nothing;
INSERT INTO content.content_description (description_id, date_created, date_modified, updt_id, description, name, title, meta_description, meta_keywords, meta_title, sef_url, language_code, content_id, state, excerpt, alt_text, cta_label, subtitle)
VALUES (-400015, now(), now(), 'seed', '<h2>كتالوج 2024</h2><p>مؤرشف واستُبدل بكتالوج 2026. يجب أن يبقى غير مرئي في المتجر.</p>', 'كتالوج 2024 (مؤرشف)', 'كتالوج 2024 (مؤرشف)', null, null, null, 'lookbook-2024-ar', 'ar', -40008, 'TRANSLATED', null, null, null, null)
on conflict (description_id) do nothing;
INSERT INTO content.content_description (description_id, date_created, date_modified, updt_id, description, name, title, meta_description, meta_keywords, meta_title, sef_url, language_code, content_id, state, excerpt, alt_text, cta_label, subtitle)
VALUES (-400016, now(), now(), 'seed', '<h2>Lookbook 2024</h2><p>Archived, replaced by the 2026 lookbook. Must stay invisible in the storefront.</p>', 'Lookbook 2024 (archived)', 'Lookbook 2024 (archived)', null, null, null, 'lookbook-2024', 'en', -40008, 'TRANSLATED', null, null, null, null)
on conflict (description_id) do nothing;

-- page: loyalty-programme (DRAFT)
INSERT INTO content.content (content_id, date_created, date_modified, updt_id, code, content_type, sort_order, visible, store_merchant_id, status, publish_at, unpublish_at, version, created_by, updated_by, parent_id, noindex, canonical_url, og_media_id, show_in_footer, placement, starts_at, ends_at, policy_type, meta)
VALUES (-40009, now(), now(), 'seed', 'loyalty-programme', 'PAGE', 18, true, '65f023632bc46470c104b76f', 'DRAFT', null, null, 1, 'seed', 'seed', null, false, null, null, false, null, null, null, null, null)
on conflict (content_id) do nothing;
INSERT INTO content.content_description (description_id, date_created, date_modified, updt_id, description, name, title, meta_description, meta_keywords, meta_title, sef_url, language_code, content_id, state, excerpt, alt_text, cta_label, subtitle)
VALUES (-400017, now(), now(), 'seed', '<h2>برنامج الولاء</h2><p>مسودة قيد الكتابة. غير مرئية في المتجر، وقابلة للتحرير في لوحة التحكم.</p>', 'برنامج الولاء (مسودة)', 'برنامج الولاء (مسودة)', null, null, null, 'loyalty-programme-ar', 'ar', -40009, 'DRAFT', null, null, null, null)
on conflict (description_id) do nothing;
INSERT INTO content.content_description (description_id, date_created, date_modified, updt_id, description, name, title, meta_description, meta_keywords, meta_title, sef_url, language_code, content_id, state, excerpt, alt_text, cta_label, subtitle)
VALUES (-400018, now(), now(), 'seed', '<h2>Loyalty programme</h2><p>A draft still being written. Invisible in the storefront, editable in the console.</p>', 'Loyalty programme (draft)', 'Loyalty programme (draft)', null, null, null, 'loyalty-programme', 'en', -40009, 'DRAFT', null, null, null, null)
on conflict (description_id) do nothing;

-- pages the store already had, promoted into the footer
UPDATE content.content SET show_in_footer = true
 WHERE store_merchant_id = '65f023632bc46470c104b76f' AND content_type = 'PAGE' AND code IN ('about-us', 'contact-us', 'location');
