-- Legal policies, each with a live version.
--
-- Demo content for the test store 65f023632bc46470c104b76f (Riyadh Fashion Hub), in every language the store sells in.
-- Generated seed: ids are negative on purpose — content, media and menu ids all come from sequences that
-- only grow upward, so a seed row below zero can never collide with one the running service creates.

-- policy: PRIVACY
INSERT INTO content.content (content_id, date_created, date_modified, updt_id, code, content_type, sort_order, visible, store_merchant_id, status, publish_at, unpublish_at, version, created_by, updated_by, parent_id, noindex, canonical_url, og_media_id, show_in_footer, placement, starts_at, ends_at, policy_type, meta)
VALUES (-40010, now(), now(), 'seed', 'privacy-policy', 'POLICY', 100, true, '65f023632bc46470c104b76f', 'PUBLISHED', null, null, 1, 'seed', 'seed', null, false, null, null, false, null, null, null, 'PRIVACY', '{"jurisdiction": null, "requiresAcceptance": false, "notifyCustomers": false, "displayAt": {"footer": true, "checkout": false, "signup": false}}')
on conflict (content_id) do nothing;
INSERT INTO content.content_description (description_id, date_created, date_modified, updt_id, description, name, title, meta_description, meta_keywords, meta_title, sef_url, language_code, content_id, state, excerpt, alt_text, cta_label, subtitle)
VALUES (-400019, now(), now(), 'seed', '<h2>سياسة الخصوصية</h2><p>Riyadh Fashion Hub، شارع العليا، الرياض، هي المسؤولة عن معالجة بياناتك وفق نظام حماية البيانات الشخصية السعودي.</p><h3>البيانات التي نجمعها</h3><ul><li>الاسم ورقم الجوال وعنوان التوصيل</li><li>سجل الطلبات والمرتجعات والمقاسات المحفوظة</li><li>بيانات التصفح إن وافقت على كوكيز القياس</li></ul><h3>مدة الاحتفاظ</h3><p>سجلات الطلبات عشر سنوات وفق الالتزامات الضريبية، وبيانات الحساب ثلاث سنوات من آخر نشاط.</p><h3>حقوقك</h3><p>لك حق الاطلاع والتصحيح والحذف والاعتراض عبر <a href="mailto:privacy@riyadhfashionhub.sa">privacy@riyadhfashionhub.sa</a>، ويمكنك التقدم بشكوى إلى الهيئة السعودية للبيانات والذكاء الاصطناعي.</p>', 'سياسة الخصوصية', 'سياسة الخصوصية', null, null, null, null, 'ar', -40010, 'TRANSLATED', null, null, null, null)
on conflict (description_id) do nothing;
INSERT INTO content.content_description (description_id, date_created, date_modified, updt_id, description, name, title, meta_description, meta_keywords, meta_title, sef_url, language_code, content_id, state, excerpt, alt_text, cta_label, subtitle)
VALUES (-400020, now(), now(), 'seed', '<h2>Privacy policy</h2><p>Riyadh Fashion Hub, Olaya Street, Riyadh, is the controller of your data under the Saudi Personal Data Protection Law.</p><h3>What we collect</h3><ul><li>Name, mobile number and delivery address</li><li>Order and return history, and saved sizes</li><li>Browsing data, if you accept measurement cookies</li></ul><h3>How long we keep it</h3><p>Order records are kept ten years under tax obligations; account data three years after your last activity.</p><h3>Your rights</h3><p>Access, rectification, erasure and objection can be exercised at <a href="mailto:privacy@riyadhfashionhub.sa">privacy@riyadhfashionhub.sa</a>. You may complain to SDAIA at any time.</p>', 'Privacy policy', 'Privacy policy', null, null, null, null, 'en', -40010, 'TRANSLATED', null, null, null, null)
on conflict (description_id) do nothing;
INSERT INTO content.policy_version (id, store_merchant_id, content_id, version, status, effective_from, note, translations, published_at, published_by)
VALUES (-4001, '65f023632bc46470c104b76f', -40010, 1, 'LIVE', now() - interval '30 days', null, '[{"language": "ar", "title": "سياسة الخصوصية", "body": "<h2>سياسة الخصوصية</h2><p>Riyadh Fashion Hub، شارع العليا، الرياض، هي المسؤولة عن معالجة بياناتك وفق نظام حماية البيانات الشخصية السعودي.</p><h3>البيانات التي نجمعها</h3><ul><li>الاسم ورقم الجوال وعنوان التوصيل</li><li>سجل الطلبات والمرتجعات والمقاسات المحفوظة</li><li>بيانات التصفح إن وافقت على كوكيز القياس</li></ul><h3>مدة الاحتفاظ</h3><p>سجلات الطلبات عشر سنوات وفق الالتزامات الضريبية، وبيانات الحساب ثلاث سنوات من آخر نشاط.</p><h3>حقوقك</h3><p>لك حق الاطلاع والتصحيح والحذف والاعتراض عبر <a href=\"mailto:privacy@riyadhfashionhub.sa\">privacy@riyadhfashionhub.sa</a>، ويمكنك التقدم بشكوى إلى الهيئة السعودية للبيانات والذكاء الاصطناعي.</p>", "state": "TRANSLATED"}, {"language": "en", "title": "Privacy policy", "body": "<h2>Privacy policy</h2><p>Riyadh Fashion Hub, Olaya Street, Riyadh, is the controller of your data under the Saudi Personal Data Protection Law.</p><h3>What we collect</h3><ul><li>Name, mobile number and delivery address</li><li>Order and return history, and saved sizes</li><li>Browsing data, if you accept measurement cookies</li></ul><h3>How long we keep it</h3><p>Order records are kept ten years under tax obligations; account data three years after your last activity.</p><h3>Your rights</h3><p>Access, rectification, erasure and objection can be exercised at <a href=\"mailto:privacy@riyadhfashionhub.sa\">privacy@riyadhfashionhub.sa</a>. You may complain to SDAIA at any time.</p>", "state": "TRANSLATED"}]', now(), 'seed')
on conflict (id) do nothing;

-- policy: RETURNS
INSERT INTO content.content (content_id, date_created, date_modified, updt_id, code, content_type, sort_order, visible, store_merchant_id, status, publish_at, unpublish_at, version, created_by, updated_by, parent_id, noindex, canonical_url, og_media_id, show_in_footer, placement, starts_at, ends_at, policy_type, meta)
VALUES (-40011, now(), now(), 'seed', 'return-policy', 'POLICY', 101, true, '65f023632bc46470c104b76f', 'PUBLISHED', null, null, 1, 'seed', 'seed', null, false, null, null, false, null, null, null, 'RETURNS', '{"jurisdiction": null, "requiresAcceptance": false, "notifyCustomers": false, "displayAt": {"footer": true, "checkout": false, "signup": false}}')
on conflict (content_id) do nothing;
INSERT INTO content.content_description (description_id, date_created, date_modified, updt_id, description, name, title, meta_description, meta_keywords, meta_title, sef_url, language_code, content_id, state, excerpt, alt_text, cta_label, subtitle)
VALUES (-400021, now(), now(), 'seed', '<h2>الاستبدال والاسترجاع</h2><p>ثلاثون يومًا من الاستلام، سواء اشتريت أونلاين أو من المعرض.</p><h3>الشروط</h3><ul><li>القطعة غير مستعملة وبطاقتها الأصلية مثبّتة</li><li>الملابس الداخلية والأقراط لا تُسترجع لأسباب صحية</li><li>الاسترجاع مجاني عبر شركة الشحن أو من أي معرض</li></ul><h3>الاسترداد</h3><p>خلال خمسة أيام عمل من وصول القطعة، بنفس وسيلة الدفع. القطع المعدَّلة على المقاس تُستبدل ولا تُسترد قيمتها.</p><p><em>النسخة الثانية — رفعنا المدة من أربعة عشر يومًا إلى ثلاثين، وأصبح الاسترجاع مجانيًا.</em></p>', 'سياسة الاستبدال والاسترجاع', 'سياسة الاستبدال والاسترجاع', null, null, null, null, 'ar', -40011, 'TRANSLATED', null, null, null, null)
on conflict (description_id) do nothing;
INSERT INTO content.content_description (description_id, date_created, date_modified, updt_id, description, name, title, meta_description, meta_keywords, meta_title, sef_url, language_code, content_id, state, excerpt, alt_text, cta_label, subtitle)
VALUES (-400022, now(), now(), 'seed', '<h2>Returns & exchanges</h2><p>Thirty days from delivery, whether you bought online or in store.</p><h3>Conditions</h3><ul><li>Unworn, with the original tag still attached</li><li>Underwear and pierced earrings cannot be returned, for hygiene reasons</li><li>Returns are free, by carrier pickup or at any store</li></ul><h3>Refunds</h3><p>Within five working days of the item arriving, to the original payment method. Altered garments can be exchanged but not refunded.</p><p><em>Version 2 — the window went from fourteen days to thirty, and returns are now free.</em></p>', 'Returns & exchanges', 'Returns & exchanges', null, null, null, null, 'en', -40011, 'TRANSLATED', null, null, null, null)
on conflict (description_id) do nothing;
INSERT INTO content.policy_version (id, store_merchant_id, content_id, version, status, effective_from, note, translations, published_at, published_by)
VALUES (-4002, '65f023632bc46470c104b76f', -40011, 1, 'ARCHIVED', now() - interval '400 days', 'Initial version', '[{"language": "ar", "title": "سياسة الاستبدال والاسترجاع", "body": "<h2>الاستبدال والاسترجاع</h2><p>أربعة عشر يومًا، ورسوم شحن الاسترجاع 25 ريالًا على العميل.</p><p><em>النسخة الأولى — مؤرشفة.</em></p>", "state": "TRANSLATED"}, {"language": "en", "title": "Returns & exchanges", "body": "<h2>Returns & exchanges</h2><p>Fourteen days, with a SAR 25 return shipping fee paid by the customer.</p><p><em>Version 1 — archived.</em></p>", "state": "TRANSLATED"}]', now(), 'seed')
on conflict (id) do nothing;
INSERT INTO content.policy_version (id, store_merchant_id, content_id, version, status, effective_from, note, translations, published_at, published_by)
VALUES (-4003, '65f023632bc46470c104b76f', -40011, 2, 'LIVE', now() - interval '30 days', 'Second version', '[{"language": "ar", "title": "سياسة الاستبدال والاسترجاع", "body": "<h2>الاستبدال والاسترجاع</h2><p>ثلاثون يومًا من الاستلام، سواء اشتريت أونلاين أو من المعرض.</p><h3>الشروط</h3><ul><li>القطعة غير مستعملة وبطاقتها الأصلية مثبّتة</li><li>الملابس الداخلية والأقراط لا تُسترجع لأسباب صحية</li><li>الاسترجاع مجاني عبر شركة الشحن أو من أي معرض</li></ul><h3>الاسترداد</h3><p>خلال خمسة أيام عمل من وصول القطعة، بنفس وسيلة الدفع. القطع المعدَّلة على المقاس تُستبدل ولا تُسترد قيمتها.</p><p><em>النسخة الثانية — رفعنا المدة من أربعة عشر يومًا إلى ثلاثين، وأصبح الاسترجاع مجانيًا.</em></p>", "state": "TRANSLATED"}, {"language": "en", "title": "Returns & exchanges", "body": "<h2>Returns & exchanges</h2><p>Thirty days from delivery, whether you bought online or in store.</p><h3>Conditions</h3><ul><li>Unworn, with the original tag still attached</li><li>Underwear and pierced earrings cannot be returned, for hygiene reasons</li><li>Returns are free, by carrier pickup or at any store</li></ul><h3>Refunds</h3><p>Within five working days of the item arriving, to the original payment method. Altered garments can be exchanged but not refunded.</p><p><em>Version 2 — the window went from fourteen days to thirty, and returns are now free.</em></p>", "state": "TRANSLATED"}]', now(), 'seed')
on conflict (id) do nothing;

-- policy: SHIPPING
INSERT INTO content.content (content_id, date_created, date_modified, updt_id, code, content_type, sort_order, visible, store_merchant_id, status, publish_at, unpublish_at, version, created_by, updated_by, parent_id, noindex, canonical_url, og_media_id, show_in_footer, placement, starts_at, ends_at, policy_type, meta)
VALUES (-40012, now(), now(), 'seed', 'shipping-policy', 'POLICY', 102, true, '65f023632bc46470c104b76f', 'PUBLISHED', null, null, 1, 'seed', 'seed', null, false, null, null, false, null, null, null, 'SHIPPING', '{"jurisdiction": null, "requiresAcceptance": false, "notifyCustomers": false, "displayAt": {"footer": true, "checkout": false, "signup": false}}')
on conflict (content_id) do nothing;
INSERT INTO content.content_description (description_id, date_created, date_modified, updt_id, description, name, title, meta_description, meta_keywords, meta_title, sef_url, language_code, content_id, state, excerpt, alt_text, cta_label, subtitle)
VALUES (-400023, now(), now(), 'seed', '<h2>الشحن</h2><p>الطلبات المؤكدة قبل الساعة الثالثة عصرًا تُشحن في نفس اليوم من مستودع الخرج.</p><table><tr><th>الوجهة</th><th>المدة</th><th>التكلفة</th></tr><tr><td>الرياض</td><td>يوم واحد</td><td>مجانًا فوق 200 ريال</td></tr><tr><td>جدة والدمام ومكة</td><td>يومان إلى ثلاثة</td><td>25 ريالًا</td></tr><tr><td>باقي مناطق المملكة</td><td>ثلاثة إلى خمسة أيام</td><td>30 ريالًا</td></tr><tr><td>دول الخليج</td><td>خمسة إلى ثمانية أيام</td><td>75 ريالًا</td></tr></table><p>التوصيل داخل الرياض متاح في نفس اليوم للطلبات قبل الظهر مقابل 35 ريالًا.</p>', 'سياسة الشحن', 'سياسة الشحن', null, null, null, null, 'ar', -40012, 'TRANSLATED', null, null, null, null)
on conflict (description_id) do nothing;
INSERT INTO content.content_description (description_id, date_created, date_modified, updt_id, description, name, title, meta_description, meta_keywords, meta_title, sef_url, language_code, content_id, state, excerpt, alt_text, cta_label, subtitle)
VALUES (-400024, now(), now(), 'seed', '<h2>Shipping</h2><p>Orders confirmed before 3pm ship the same day from the Al-Kharj warehouse.</p><table><tr><th>Destination</th><th>Time</th><th>Cost</th></tr><tr><td>Riyadh</td><td>1 day</td><td>Free over SAR 200</td></tr><tr><td>Jeddah, Dammam, Makkah</td><td>2–3 days</td><td>SAR 25</td></tr><tr><td>Rest of the Kingdom</td><td>3–5 days</td><td>SAR 30</td></tr><tr><td>GCC states</td><td>5–8 days</td><td>SAR 75</td></tr></table><p>Same-day delivery inside Riyadh is available for orders placed before noon, at SAR 35.</p>', 'Shipping policy', 'Shipping policy', null, null, null, null, 'en', -40012, 'TRANSLATED', null, null, null, null)
on conflict (description_id) do nothing;
INSERT INTO content.policy_version (id, store_merchant_id, content_id, version, status, effective_from, note, translations, published_at, published_by)
VALUES (-4004, '65f023632bc46470c104b76f', -40012, 1, 'LIVE', now() - interval '30 days', null, '[{"language": "ar", "title": "سياسة الشحن", "body": "<h2>الشحن</h2><p>الطلبات المؤكدة قبل الساعة الثالثة عصرًا تُشحن في نفس اليوم من مستودع الخرج.</p><table><tr><th>الوجهة</th><th>المدة</th><th>التكلفة</th></tr><tr><td>الرياض</td><td>يوم واحد</td><td>مجانًا فوق 200 ريال</td></tr><tr><td>جدة والدمام ومكة</td><td>يومان إلى ثلاثة</td><td>25 ريالًا</td></tr><tr><td>باقي مناطق المملكة</td><td>ثلاثة إلى خمسة أيام</td><td>30 ريالًا</td></tr><tr><td>دول الخليج</td><td>خمسة إلى ثمانية أيام</td><td>75 ريالًا</td></tr></table><p>التوصيل داخل الرياض متاح في نفس اليوم للطلبات قبل الظهر مقابل 35 ريالًا.</p>", "state": "TRANSLATED"}, {"language": "en", "title": "Shipping policy", "body": "<h2>Shipping</h2><p>Orders confirmed before 3pm ship the same day from the Al-Kharj warehouse.</p><table><tr><th>Destination</th><th>Time</th><th>Cost</th></tr><tr><td>Riyadh</td><td>1 day</td><td>Free over SAR 200</td></tr><tr><td>Jeddah, Dammam, Makkah</td><td>2–3 days</td><td>SAR 25</td></tr><tr><td>Rest of the Kingdom</td><td>3–5 days</td><td>SAR 30</td></tr><tr><td>GCC states</td><td>5–8 days</td><td>SAR 75</td></tr></table><p>Same-day delivery inside Riyadh is available for orders placed before noon, at SAR 35.</p>", "state": "TRANSLATED"}]', now(), 'seed')
on conflict (id) do nothing;

-- policy: COOKIES
INSERT INTO content.content (content_id, date_created, date_modified, updt_id, code, content_type, sort_order, visible, store_merchant_id, status, publish_at, unpublish_at, version, created_by, updated_by, parent_id, noindex, canonical_url, og_media_id, show_in_footer, placement, starts_at, ends_at, policy_type, meta)
VALUES (-40013, now(), now(), 'seed', 'cookie-policy', 'POLICY', 103, true, '65f023632bc46470c104b76f', 'PUBLISHED', null, null, 1, 'seed', 'seed', null, false, null, null, false, null, null, null, 'COOKIES', '{"jurisdiction": null, "requiresAcceptance": false, "notifyCustomers": false, "displayAt": {"footer": true, "checkout": false, "signup": false}}')
on conflict (content_id) do nothing;
INSERT INTO content.content_description (description_id, date_created, date_modified, updt_id, description, name, title, meta_description, meta_keywords, meta_title, sef_url, language_code, content_id, state, excerpt, alt_text, cta_label, subtitle)
VALUES (-400025, now(), now(), 'seed', '<h2>ملفات تعريف الارتباط</h2><p>نستخدم ثلاث فئات، واحدة منها لا يمكن إيقافها لأن السلة تعتمد عليها.</p><ul><li><strong>أساسية</strong> — السلة والجلسة والأمان. تعمل دائمًا.</li><li><strong>قياس</strong> — إحصاءات مجمّعة، ثلاثة عشر شهرًا.</li><li><strong>تخصيص</strong> — اقتراح مقاسات وأنماط، ستة أشهر.</li></ul><p>يُحفظ اختيارك ستة أشهر ويمكن تعديله من رابط « تفضيلات الكوكيز » أسفل الصفحة.</p>', 'سياسة ملفات تعريف الارتباط', 'سياسة ملفات تعريف الارتباط', null, null, null, null, 'ar', -40013, 'TRANSLATED', null, null, null, null)
on conflict (description_id) do nothing;
INSERT INTO content.content_description (description_id, date_created, date_modified, updt_id, description, name, title, meta_description, meta_keywords, meta_title, sef_url, language_code, content_id, state, excerpt, alt_text, cta_label, subtitle)
VALUES (-400026, now(), now(), 'seed', '<h2>Cookies</h2><p>Three families of cookies, one of which cannot be switched off because the cart depends on it.</p><ul><li><strong>Essential</strong> — cart, session, security. Always on.</li><li><strong>Measurement</strong> — aggregate statistics, 13 months.</li><li><strong>Personalisation</strong> — size and style suggestions, 6 months.</li></ul><p>Your choice is stored for six months and can be changed from the “Cookie preferences” link in the footer.</p>', 'Cookie policy', 'Cookie policy', null, null, null, null, 'en', -40013, 'TRANSLATED', null, null, null, null)
on conflict (description_id) do nothing;
INSERT INTO content.policy_version (id, store_merchant_id, content_id, version, status, effective_from, note, translations, published_at, published_by)
VALUES (-4005, '65f023632bc46470c104b76f', -40013, 1, 'LIVE', now() - interval '30 days', null, '[{"language": "ar", "title": "سياسة ملفات تعريف الارتباط", "body": "<h2>ملفات تعريف الارتباط</h2><p>نستخدم ثلاث فئات، واحدة منها لا يمكن إيقافها لأن السلة تعتمد عليها.</p><ul><li><strong>أساسية</strong> — السلة والجلسة والأمان. تعمل دائمًا.</li><li><strong>قياس</strong> — إحصاءات مجمّعة، ثلاثة عشر شهرًا.</li><li><strong>تخصيص</strong> — اقتراح مقاسات وأنماط، ستة أشهر.</li></ul><p>يُحفظ اختيارك ستة أشهر ويمكن تعديله من رابط « تفضيلات الكوكيز » أسفل الصفحة.</p>", "state": "TRANSLATED"}, {"language": "en", "title": "Cookie policy", "body": "<h2>Cookies</h2><p>Three families of cookies, one of which cannot be switched off because the cart depends on it.</p><ul><li><strong>Essential</strong> — cart, session, security. Always on.</li><li><strong>Measurement</strong> — aggregate statistics, 13 months.</li><li><strong>Personalisation</strong> — size and style suggestions, 6 months.</li></ul><p>Your choice is stored for six months and can be changed from the “Cookie preferences” link in the footer.</p>", "state": "TRANSLATED"}]', now(), 'seed')
on conflict (id) do nothing;

