-- Blog categories and posts.
--
-- Demo content for the test store 65f023632bc46470c104b76f (Riyadh Fashion Hub), in every language the store sells in.
-- Generated seed: ids are negative on purpose — content, media and menu ids all come from sequences that
-- only grow upward, so a seed row below zero can never collide with one the running service creates.

INSERT INTO content.post_category (id, store_merchant_id, slug, position, names)
VALUES (-451, '65f023632bc46470c104b76f', 'style-guides', 0, '{"ar": "دليل الإطلالة", "en": "Style guides"}')
on conflict (store_merchant_id, slug) do nothing;
INSERT INTO content.post_category (id, store_merchant_id, slug, position, names)
VALUES (-452, '65f023632bc46470c104b76f', 'fabric', 1, '{"ar": "الأقمشة", "en": "Fabric"}')
on conflict (store_merchant_id, slug) do nothing;
INSERT INTO content.post_category (id, store_merchant_id, slug, position, names)
VALUES (-453, '65f023632bc46470c104b76f', 'behind-the-seams', 2, '{"ar": "خلف الخياطة", "en": "Behind the seams"}')
on conflict (store_merchant_id, slug) do nothing;

-- post: dressing-for-riyadh-summer (PUBLISHED)
INSERT INTO content.content (content_id, date_created, date_modified, updt_id, code, content_type, sort_order, visible, store_merchant_id, status, publish_at, unpublish_at, version, created_by, updated_by, parent_id, noindex, canonical_url, og_media_id, show_in_footer, placement, starts_at, ends_at, policy_type, meta)
VALUES (-40026, now(), now(), 'seed', 'dressing-for-riyadh-summer', 'POST', 0, true, '65f023632bc46470c104b76f', 'PUBLISHED', now() - interval '3 days', null, 1, 'seed', 'seed', null, false, null, null, false, null, null, null, null, '{"heroMediaId": -490003, "categoryIds": [-451, -452], "tags": ["صيف", "كتان", "summer"], "authorName": "نورة القحطاني", "featured": true}')
on conflict (content_id) do nothing;
INSERT INTO content.content_description (description_id, date_created, date_modified, updt_id, description, name, title, meta_description, meta_keywords, meta_title, sef_url, language_code, content_id, state, excerpt, alt_text, cta_label, subtitle)
VALUES (-400051, now(), now(), 'seed', '<p>الجميع ينصح باللون الفاتح، وقليلون ينتبهون إلى أن نسيجًا داكنًا فضفاضًا من الكتان أبرد من قميص أبيض ضيق من البوليستر.</p><h2>النسيج أولًا</h2><p>في المناخ الجاف يبرّد العرق الجسم بالتبخر، وهو ما يحتاج نسيجًا ينفذ منه الهواء. الكتان والقطن المُمشَّط يفعلان ذلك؛ البوليستر يحبس البخار على الجلد.</p><h2>القَصّة ثانيًا</h2><p>المساحة بين القماش والجلد هي ما يسمح للهواء بالحركة. قميص واسع قليلًا أبرد فعليًا من آخر ملتصق، مهما تشابه اللون.</p><h2>الطبقات في الأماكن المكيَّفة</h2><p>الفارق بين الخارج والداخل في الرياض يتجاوز عشرين درجة. طبقة قطنية خفيفة تُخلع عند الدخول أذكى من مواجهة الفارق بقطعة واحدة.</p><h2>ثلاث قطع تكفي الموسم</h2><ul><li>قميص كتان بأكمام طويلة — يحمي من الشمس ويسمح بالهواء</li><li>بنطال قطني واسع من الأسفل</li><li>ثوب أو فستان بقَصّة مستقيمة لا تلتصق بالجسم</li></ul>', 'الملابس في صيف الرياض: النسيج قبل القَصّة', 'الملابس في صيف الرياض: النسيج قبل القَصّة', 'لماذا يتفوق الكتان والقطن المُمشَّط على البوليستر في المناخ الجاف، وكيف تختار القَصّة.', 'صيف, كتان, summer', 'الملابس في صيف الرياض | المجلة', 'dressing-for-riyadh-summer-ar', 'ar', -40026, 'TRANSLATED', 'خمسون درجة وجفاف شديد. اللون الفاتح ليس الحل، بل النسيج الذي يسمح بمرور الهواء.', null, null, null)
on conflict (description_id) do nothing;
INSERT INTO content.content_description (description_id, date_created, date_modified, updt_id, description, name, title, meta_description, meta_keywords, meta_title, sef_url, language_code, content_id, state, excerpt, alt_text, cta_label, subtitle)
VALUES (-400052, now(), now(), 'seed', '<p>Everyone recommends pale colours, and few notice that a loose dark linen shirt is cooler than a tight white polyester one.</p><h2>Fabric first</h2><p>In dry heat, sweat cools you by evaporating, which needs a weave air can pass through. Linen and combed cotton do that; polyester traps vapour against the skin.</p><h2>Cut second</h2><p>The gap between cloth and skin is what lets air move. A slightly loose shirt is genuinely cooler than a fitted one, whatever the colour.</p><h2>Layers, because of air conditioning</h2><p>The gap between outdoors and indoors in Riyadh runs past twenty degrees. A light cotton layer you take off on the way in beats meeting both with one garment.</p><h2>Three pieces that carry a season</h2><ul><li>A long-sleeved linen shirt — sun cover and airflow at once</li><li>Cotton trousers cut wide at the hem</li><li>A thobe or dress with a straight line that does not cling</li></ul>', 'Dressing for a Riyadh summer: fabric before cut', 'Dressing for a Riyadh summer: fabric before cut', 'Why linen and combed cotton beat polyester in dry heat, and how to choose a cut that helps.', 'صيف, كتان, summer', 'Dressing for a Riyadh summer | The Magazine', 'dressing-for-riyadh-summer', 'en', -40026, 'TRANSLATED', 'Fifty degrees and very dry air. Pale colour is not the answer — weave that lets air through is.', null, null, null)
on conflict (description_id) do nothing;
INSERT INTO content.media_usage (id, asset_id, owner_kind, owner_ref, owner_title, content_id, content_type, field)
VALUES (-4001, -490003, 'CONTENT', '-40026', 'الملابس في صيف الرياض: النسيج قبل القَصّة', -40026, 'POST', 'hero')
on conflict (id) do nothing;

-- post: reading-a-fabric-label (PUBLISHED)
INSERT INTO content.content (content_id, date_created, date_modified, updt_id, code, content_type, sort_order, visible, store_merchant_id, status, publish_at, unpublish_at, version, created_by, updated_by, parent_id, noindex, canonical_url, og_media_id, show_in_footer, placement, starts_at, ends_at, policy_type, meta)
VALUES (-40027, now(), now(), 'seed', 'reading-a-fabric-label', 'POST', 1, true, '65f023632bc46470c104b76f', 'PUBLISHED', now() - interval '10 days', null, 1, 'seed', 'seed', null, false, null, null, false, null, null, null, null, '{"heroMediaId": -490004, "categoryIds": [-452], "tags": ["أقمشة", "قطن", "fabric"], "authorName": "سارة الدوسري", "featured": false}')
on conflict (content_id) do nothing;
INSERT INTO content.content_description (description_id, date_created, date_modified, updt_id, description, name, title, meta_description, meta_keywords, meta_title, sef_url, language_code, content_id, state, excerpt, alt_text, cta_label, subtitle)
VALUES (-400053, now(), now(), 'seed', '<h2>الوزن بالغرام للمتر</h2><p>قميص قطني بوزن 120 غرامًا شفاف ويفقد شكله بعد عشر غسلات. عند 180 غرامًا يبقى معتدلًا. عند 220 يصلح لفصل أبرد.</p><h2>الممشَّط مقابل العادي</h2><p>التمشيط يزيل الألياف القصيرة قبل الغزل، فيقل الوبر ويزيد النعومة. الفارق في السعر بسيط والفارق في العمر كبير.</p><h2>المزج ليس عيبًا دائمًا</h2><ul><li>2 إلى 5% إيلاستين في القطن يحافظ على شكل الركبة والمرفق</li><li>أكثر من 15% بوليستر في قميص صيفي يعني حرارة محتبسة</li><li>الفيسكوز يسقط بجمال لكنه يضعف وهو مبلول — لا تعصره</li></ul><h2>ما لا تذكره البطاقة</h2><p>كثافة الحياكة وثبات اللون لا يظهران في أي رقم. الاختبار الوحيد هو الغسل الخامس.</p>', 'كيف تقرأ بطاقة القماش', 'كيف تقرأ بطاقة القماش', 'الوزن بالغرام، الغزل المُمشَّط، ونسب المزج: ما تعنيه أرقام بطاقة القماش فعلًا.', 'أقمشة, قطن, fabric', 'كيف تقرأ بطاقة القماش | المجلة', 'reading-a-fabric-label-ar', 'ar', -40027, 'TRANSLATED', '« 100% قطن » لا تكفي. الوزن ونوع الغزل يفرّقان بين قميص يدوم موسمًا وآخر يدوم خمسة.', null, null, null)
on conflict (description_id) do nothing;
INSERT INTO content.content_description (description_id, date_created, date_modified, updt_id, description, name, title, meta_description, meta_keywords, meta_title, sef_url, language_code, content_id, state, excerpt, alt_text, cta_label, subtitle)
VALUES (-400054, now(), now(), 'seed', '<h2>Grams per square metre</h2><p>A 120 gsm cotton shirt is see-through and loses its shape after ten washes. At 180 gsm it holds. At 220 it belongs to a cooler season.</p><h2>Combed versus carded</h2><p>Combing strips out short fibres before spinning, which means less pilling and a smoother hand. The price difference is small; the lifespan difference is not.</p><h2>Blends are not automatically a compromise</h2><ul><li>2–5% elastane in cotton keeps knees and elbows from bagging</li><li>More than 15% polyester in a summer shirt means trapped heat</li><li>Viscose drapes beautifully but is weak when wet — never wring it</li></ul><h2>What the label leaves out</h2><p>Knit density and colourfastness appear in no number. The only test is the fifth wash.</p>', 'How to read a fabric label', 'How to read a fabric label', 'Grams per square metre, combed yarn and blend ratios: what the numbers on a label actually mean.', 'أقمشة, قطن, fabric', 'How to read a fabric label | The Magazine', 'reading-a-fabric-label', 'en', -40027, 'TRANSLATED', '“100% cotton” tells you almost nothing. Weight and yarn type separate a shirt that lasts a season from one that lasts five.', null, null, null)
on conflict (description_id) do nothing;
INSERT INTO content.media_usage (id, asset_id, owner_kind, owner_ref, owner_title, content_id, content_type, field)
VALUES (-4002, -490004, 'CONTENT', '-40027', 'كيف تقرأ بطاقة القماش', -40027, 'POST', 'hero')
on conflict (id) do nothing;

-- post: inside-the-alterations-room (PUBLISHED)
INSERT INTO content.content (content_id, date_created, date_modified, updt_id, code, content_type, sort_order, visible, store_merchant_id, status, publish_at, unpublish_at, version, created_by, updated_by, parent_id, noindex, canonical_url, og_media_id, show_in_footer, placement, starts_at, ends_at, policy_type, meta)
VALUES (-40028, now(), now(), 'seed', 'inside-the-alterations-room', 'POST', 2, true, '65f023632bc46470c104b76f', 'PUBLISHED', now() - interval '19 days', null, 1, 'seed', 'seed', null, false, null, null, false, null, null, null, null, '{"heroMediaId": -490005, "categoryIds": [-453], "tags": ["تعديل", "خياطة", "atelier"], "authorName": "نورة القحطاني", "featured": false}')
on conflict (content_id) do nothing;
INSERT INTO content.content_description (description_id, date_created, date_modified, updt_id, description, name, title, meta_description, meta_keywords, meta_title, sef_url, language_code, content_id, state, excerpt, alt_text, cta_label, subtitle)
VALUES (-400055, now(), now(), 'seed', '<p>خلف المعرض في العليا غرفة بثلاث ماكينات، يعمل فيها خياطان يعدّلان نحو أربعين قطعة كل أسبوع.</p><h2>التعديل الأكثر طلبًا</h2><p>ليس تقصير البنطال، بل تضييق الكتف. معظم القمصان تُقاس على كتف أعرض من المتوسط هنا، والفارق سنتيمتر ونصف يغيّر شكل القطعة كلها.</p><h2>لماذا مجانًا</h2><p>لأن القطعة المعدَّلة لا تُسترجع، ولأن من يرتدي قطعة تناسبه فعلًا يعود. الحساب بسيط.</p><h2>ما لا يمكن تعديله</h2><ul><li>توسيع كتف ضيق — القماش غير موجود</li><li>تغيير مكان الجيوب دون أثر ظاهر</li><li>الجاكيتات المبطنة، إلا بتكلفة تتجاوز قيمتها</li></ul><h2>ثلاثة أيام</h2><p>المدة القياسية ثلاثة أيام. القطع المستعجلة قبل مناسبة تُنجز في يوم واحد إن أمكن، دون رسوم إضافية.</p>', 'داخل غرفة التعديل', 'داخل غرفة التعديل', 'جولة في غرفة التعديل بمعرض العليا، وأكثر التعديلات طلبًا ولماذا.', 'تعديل, خياطة, atelier', 'داخل غرفة التعديل | المجلة', 'inside-the-alterations-room-ar', 'ar', -40028, 'TRANSLATED', 'ثلاث ماكينات، خياطان، وأربعون قطعة أسبوعيًا. أكثر تعديل مطلوب ليس ما تتوقعه.', null, null, null)
on conflict (description_id) do nothing;
INSERT INTO content.content_description (description_id, date_created, date_modified, updt_id, description, name, title, meta_description, meta_keywords, meta_title, sef_url, language_code, content_id, state, excerpt, alt_text, cta_label, subtitle)
VALUES (-400056, now(), now(), 'seed', '<p>Behind the Olaya store is a room with three machines, where two tailors alter about forty garments a week.</p><h2>The most requested change</h2><p>Not shortening trousers — taking in the shoulder. Most shirts are cut for a broader shoulder than average here, and a centimetre and a half changes the whole line of the piece.</p><h2>Why it is free</h2><p>Because an altered garment does not come back as a return, and because someone wearing something that actually fits comes back to buy again. The arithmetic is simple.</p><h2>What cannot be altered</h2><ul><li>Letting out a narrow shoulder — the cloth is not there</li><li>Moving pockets without leaving a visible mark</li><li>Lined jackets, except at a cost beyond the garment''s worth</li></ul><h2>Three days</h2><p>Three days is standard. A piece needed for an occasion can usually be done in one, at no extra charge.</p>', 'Inside the alterations room', 'Inside the alterations room', 'A visit to the alterations room behind the Olaya store, and the changes people ask for most.', 'تعديل, خياطة, atelier', 'Inside the alterations room | The Magazine', 'inside-the-alterations-room', 'en', -40028, 'TRANSLATED', 'Three machines, two tailors, forty garments a week. The most requested alteration is not the one you would guess.', null, null, null)
on conflict (description_id) do nothing;
INSERT INTO content.media_usage (id, asset_id, owner_kind, owner_ref, owner_title, content_id, content_type, field)
VALUES (-4003, -490005, 'CONTENT', '-40028', 'داخل غرفة التعديل', -40028, 'POST', 'hero')
on conflict (id) do nothing;

-- post: building-a-capsule-wardrobe (PUBLISHED)
INSERT INTO content.content (content_id, date_created, date_modified, updt_id, code, content_type, sort_order, visible, store_merchant_id, status, publish_at, unpublish_at, version, created_by, updated_by, parent_id, noindex, canonical_url, og_media_id, show_in_footer, placement, starts_at, ends_at, policy_type, meta)
VALUES (-40029, now(), now(), 'seed', 'building-a-capsule-wardrobe', 'POST', 3, true, '65f023632bc46470c104b76f', 'PUBLISHED', now() - interval '28 days', null, 1, 'seed', 'seed', null, false, null, null, false, null, null, null, null, '{"heroMediaId": -490006, "categoryIds": [-451], "tags": ["خزانة", "أساسيات", "capsule"], "authorName": "سارة الدوسري", "featured": false}')
on conflict (content_id) do nothing;
INSERT INTO content.content_description (description_id, date_created, date_modified, updt_id, description, name, title, meta_description, meta_keywords, meta_title, sef_url, language_code, content_id, state, excerpt, alt_text, cta_label, subtitle)
VALUES (-400057, now(), now(), 'seed', '<h2>القاعدة الوحيدة</h2><p>كل قطعة يجب أن تتناسب مع ثلاث قطع أخرى على الأقل. القطعة التي لا تتناسب إلا مع واحدة تعيش في الخزانة ولا تخرج منها.</p><h2>القائمة</h2><ul><li>قميصان كتان محايدان</li><li>قميص أبيض قطني مُمشَّط</li><li>بنطالان: أحدهما فضفاض والآخر مستقيم</li><li>ثوب أو فستان بقَصّة بسيطة</li><li>طبقة خفيفة للأماكن المكيَّفة</li><li>حذاءان: يومي ورسمي</li><li>حزام، وحقيبة، ومنديل رقبة</li></ul><h2>لماذا تنجح</h2><p>لأن اللون المحايد يتناسب مع نفسه. أضف اللون في قطعة أو اثنتين لا في الاثنتي عشرة.</p><h2>ما تشتريه لاحقًا</h2><p>بعد شهر ستعرف أي قطعة تلبسها ثلاث مرات أسبوعيًا. اشترِ ثانية منها، لا شيئًا مختلفًا.</p>', 'خزانة من اثنتي عشرة قطعة', 'خزانة من اثنتي عشرة قطعة', 'كيف تبني خزانة مصغّرة تعمل في مناخ الرياض بين الخارج الحار والداخل المكيَّف.', 'خزانة, أساسيات, capsule', 'خزانة من اثنتي عشرة قطعة | المجلة', 'building-a-capsule-wardrobe-ar', 'ar', -40029, 'TRANSLATED', 'ليست تقشفًا، بل تقليل القرارات. اثنتا عشرة قطعة تعطي أكثر من ثلاثين إطلالة.', null, null, null)
on conflict (description_id) do nothing;
INSERT INTO content.content_description (description_id, date_created, date_modified, updt_id, description, name, title, meta_description, meta_keywords, meta_title, sef_url, language_code, content_id, state, excerpt, alt_text, cta_label, subtitle)
VALUES (-400058, now(), now(), 'seed', '<h2>The only rule</h2><p>Every piece must work with at least three others. A piece that works with one lives in the wardrobe and never leaves it.</p><h2>The list</h2><ul><li>Two neutral linen shirts</li><li>One white combed-cotton shirt</li><li>Two pairs of trousers: one wide, one straight</li><li>A thobe or dress with a simple line</li><li>A light layer for air-conditioned rooms</li><li>Two pairs of shoes: everyday and formal</li><li>A belt, a bag, a scarf</li></ul><h2>Why it works</h2><p>Because neutrals go with themselves. Put the colour in one or two pieces, not in all twelve.</p><h2>What to buy next</h2><p>After a month you will know which piece you wear three times a week. Buy a second one of that, not something different.</p>', 'A twelve-piece wardrobe', 'A twelve-piece wardrobe', 'How to build a capsule wardrobe that works in Riyadh, between the heat outside and the air conditioning inside.', 'خزانة, أساسيات, capsule', 'A twelve-piece wardrobe | The Magazine', 'building-a-capsule-wardrobe', 'en', -40029, 'TRANSLATED', 'Not austerity — fewer decisions. Twelve pieces yield more than thirty outfits.', null, null, null)
on conflict (description_id) do nothing;
INSERT INTO content.media_usage (id, asset_id, owner_kind, owner_ref, owner_title, content_id, content_type, field)
VALUES (-4004, -490006, 'CONTENT', '-40029', 'خزانة من اثنتي عشرة قطعة', -40029, 'POST', 'hero')
on conflict (id) do nothing;

-- post: what-happens-to-returns (PUBLISHED)
INSERT INTO content.content (content_id, date_created, date_modified, updt_id, code, content_type, sort_order, visible, store_merchant_id, status, publish_at, unpublish_at, version, created_by, updated_by, parent_id, noindex, canonical_url, og_media_id, show_in_footer, placement, starts_at, ends_at, policy_type, meta)
VALUES (-40030, now(), now(), 'seed', 'what-happens-to-returns', 'POST', 4, true, '65f023632bc46470c104b76f', 'PUBLISHED', now() - interval '44 days', null, 1, 'seed', 'seed', null, false, null, null, false, null, null, null, null, '{"heroMediaId": -490007, "categoryIds": [-453], "tags": ["مرتجعات", "استدامة", "returns"], "authorName": "خالد العتيبي", "featured": false}')
on conflict (content_id) do nothing;
INSERT INTO content.content_description (description_id, date_created, date_modified, updt_id, description, name, title, meta_description, meta_keywords, meta_title, sef_url, language_code, content_id, state, excerpt, alt_text, cta_label, subtitle)
VALUES (-400059, now(), now(), 'seed', '<p>الاسترجاع المجاني يعني عددًا أكبر من المرتجعات. السؤال الذي يهم: أين تذهب؟</p><h2>الفحص</h2><p>كل قطعة تُفحص عند الوصول: البطاقة، الروائح، آثار الاستخدام، اكتمال الأزرار. الفحص يستغرق دقيقتين.</p><h2>الكي وإعادة التغليف</h2><p>94% تُكوى وتُعاد إلى الرف خلال 48 ساعة. هذه ليست نسبة تسويقية بل رقم المستودع لعام كامل.</p><h2>الباقي</h2><ul><li>القطع ذات عيب بسيط تُباع بخصم في ركن « الفرصة الثانية » بمعرض العليا</li><li>ما لا يصلح للبيع يُتبرَّع به لجمعية إكساء</li><li>لا نُتلف قطعًا صالحة للارتداء — لا في المستودع ولا خارجه</li></ul>', 'ماذا يحدث للقطع المرتجعة؟', 'ماذا يحدث للقطع المرتجعة؟', 'مسار القطعة المرتجعة من المستودع إلى الرف مجددًا، ولماذا لا نتلف شيئًا.', 'مرتجعات, استدامة, returns', 'ماذا يحدث للقطع المرتجعة؟ | المجلة', 'what-happens-to-returns-ar', 'ar', -40030, 'TRANSLATED', '94% تعود للبيع. الباقي لا يُتلَف، وهذا ما يجري له فعلًا.', null, null, null)
on conflict (description_id) do nothing;
INSERT INTO content.content_description (description_id, date_created, date_modified, updt_id, description, name, title, meta_description, meta_keywords, meta_title, sef_url, language_code, content_id, state, excerpt, alt_text, cta_label, subtitle)
VALUES (-400060, now(), now(), 'seed', '<p>Free returns mean more returns. The question that matters is where they go.</p><h2>Inspection</h2><p>Every piece is checked on arrival: tag, odour, signs of wear, buttons intact. It takes two minutes.</p><h2>Pressing and repacking</h2><p>94% are pressed and back on the rail within 48 hours. That is not a marketing figure; it is the warehouse number across a full year.</p><h2>The rest</h2><ul><li>Pieces with a minor flaw are sold at a discount in the “Second chance” corner of the Olaya store</li><li>Anything unsellable is donated to the Eksaa charity</li><li>We destroy nothing that can still be worn — not in the warehouse, not anywhere</li></ul>', 'What happens to returned pieces', 'What happens to returned pieces', 'The path a returned garment takes from the warehouse back to the rail, and why we destroy nothing.', 'مرتجعات, استدامة, returns', 'What happens to returned pieces | The Magazine', 'what-happens-to-returns', 'en', -40030, 'TRANSLATED', '94% go back on sale. Nothing is destroyed, and here is what actually happens to the rest.', null, null, null)
on conflict (description_id) do nothing;
INSERT INTO content.media_usage (id, asset_id, owner_kind, owner_ref, owner_title, content_id, content_type, field)
VALUES (-4005, -490007, 'CONTENT', '-40030', 'ماذا يحدث للقطع المرتجعة؟', -40030, 'POST', 'hero')
on conflict (id) do nothing;

-- post: caring-for-linen (PUBLISHED)
INSERT INTO content.content (content_id, date_created, date_modified, updt_id, code, content_type, sort_order, visible, store_merchant_id, status, publish_at, unpublish_at, version, created_by, updated_by, parent_id, noindex, canonical_url, og_media_id, show_in_footer, placement, starts_at, ends_at, policy_type, meta)
VALUES (-40031, now(), now(), 'seed', 'caring-for-linen', 'POST', 5, true, '65f023632bc46470c104b76f', 'PUBLISHED', now() - interval '62 days', null, 1, 'seed', 'seed', null, false, null, null, false, null, null, null, null, '{"heroMediaId": -490003, "categoryIds": [-452, -451], "tags": ["كتان", "عناية", "linen"], "authorName": "خالد العتيبي", "featured": false}')
on conflict (content_id) do nothing;
INSERT INTO content.content_description (description_id, date_created, date_modified, updt_id, description, name, title, meta_description, meta_keywords, meta_title, sef_url, language_code, content_id, state, excerpt, alt_text, cta_label, subtitle)
VALUES (-400061, now(), now(), 'seed', '<h2>لماذا يتحسن</h2><p>ألياف الكتان صلبة في البداية وتلين مع كل غسلة، ما دامت الغسلة لا تكسرها. الحرارة والعصر هما ما يكسرانها.</p><h2>الغسل</h2><ul><li>ماء بارد، دورة لطيفة، حمولة نصف ممتلئة فقط</li><li>منظف بلا مبيّضات بصرية</li><li>لا تعصر أبدًا — الكتان أضعف وهو مبلول</li></ul><h2>التجفيف والكي</h2><p>علّقه مبلولًا قليلًا فيستقيم من ثقله. الكي وهو رطب من الجهة الخلفية، وحرارة متوسطة لا عالية.</p><h2>التخزين</h2><p>مطويًا لا معلّقًا؛ التعليق الطويل يترك أثرًا على الكتف لا يزول بالكي.</p><h2>التجاعيد</h2><p>التجاعيد ليست عيبًا في الكتان. القطعة التي لا تتجعد أبدًا ليست كتانًا خالصًا.</p>', 'الكتان: العناية التي تجعله يتحسن', 'الكتان: العناية التي تجعله يتحسن', 'كيف تغسل الكتان وتكويه وتخزّنه ليصبح أنعم كل عام بدل أن يهترئ.', 'كتان, عناية, linen', 'العناية بالكتان | المجلة', 'caring-for-linen-ar', 'ar', -40031, 'TRANSLATED', 'الكتان القماش الوحيد الذي يتحسن بالاستعمال — إن غسلته بطريقة لا تكسر أليافه.', null, null, null)
on conflict (description_id) do nothing;
INSERT INTO content.content_description (description_id, date_created, date_modified, updt_id, description, name, title, meta_description, meta_keywords, meta_title, sef_url, language_code, content_id, state, excerpt, alt_text, cta_label, subtitle)
VALUES (-400062, now(), now(), 'seed', '<h2>Why it improves</h2><p>Linen fibre starts stiff and softens with every wash, as long as the wash does not break it. Heat and wringing are what break it.</p><h2>Washing</h2><ul><li>Cold water, gentle cycle, drum no more than half full</li><li>Detergent without optical brighteners</li><li>Never wring — linen is at its weakest wet</li></ul><h2>Drying and pressing</h2><p>Hang it slightly wet and its own weight will pull it straight. Press it damp, from the reverse, at medium heat rather than high.</p><h2>Storage</h2><p>Folded, not hung; long hanging leaves a shoulder mark that pressing will not lift.</p><h2>Creases</h2><p>Creasing is not a fault in linen. A piece that never creases is not pure linen.</p>', 'Linen: the care that makes it improve', 'Linen: the care that makes it improve', 'How to wash, press and store linen so it softens every year instead of wearing out.', 'كتان, عناية, linen', 'Caring for linen | The Magazine', 'caring-for-linen', 'en', -40031, 'TRANSLATED', 'Linen is the one cloth that gets better with use — if you wash it in a way that does not break the fibre.', null, null, null)
on conflict (description_id) do nothing;
INSERT INTO content.media_usage (id, asset_id, owner_kind, owner_ref, owner_title, content_id, content_type, field)
VALUES (-4006, -490003, 'CONTENT', '-40031', 'الكتان: العناية التي تجعله يتحسن', -40031, 'POST', 'hero')
on conflict (id) do nothing;

-- post: autumn-lookbook-2026 (DRAFT)
INSERT INTO content.content (content_id, date_created, date_modified, updt_id, code, content_type, sort_order, visible, store_merchant_id, status, publish_at, unpublish_at, version, created_by, updated_by, parent_id, noindex, canonical_url, og_media_id, show_in_footer, placement, starts_at, ends_at, policy_type, meta)
VALUES (-40032, now(), now(), 'seed', 'autumn-lookbook-2026', 'POST', 6, true, '65f023632bc46470c104b76f', 'DRAFT', null, null, 1, 'seed', 'seed', null, false, null, null, false, null, null, null, null, '{"heroMediaId": -490004, "categoryIds": [-451], "tags": ["lookbook"], "authorName": "نورة القحطاني", "featured": false}')
on conflict (content_id) do nothing;
INSERT INTO content.content_description (description_id, date_created, date_modified, updt_id, description, name, title, meta_description, meta_keywords, meta_title, sef_url, language_code, content_id, state, excerpt, alt_text, cta_label, subtitle)
VALUES (-400063, now(), now(), 'seed', '<p>مسودة. يتحقق هذا المقال من أن منشور POST غير منشور يبقى خارج المدونة وقابلًا للتحرير في لوحة التحكم.</p>', 'كتالوج خريف 2026 (مسودة)', 'كتالوج خريف 2026 (مسودة)', null, 'lookbook', null, 'autumn-lookbook-2026-ar', 'ar', -40032, 'DRAFT', 'مقال قيد الكتابة — يجب ألا يظهر في المجلة.', null, null, null)
on conflict (description_id) do nothing;
INSERT INTO content.content_description (description_id, date_created, date_modified, updt_id, description, name, title, meta_description, meta_keywords, meta_title, sef_url, language_code, content_id, state, excerpt, alt_text, cta_label, subtitle)
VALUES (-400064, now(), now(), 'seed', '<p>Draft. This post is the check that an unpublished POST stays off the blog while remaining editable in the console.</p>', 'Autumn lookbook 2026 (draft)', 'Autumn lookbook 2026 (draft)', null, 'lookbook', null, 'autumn-lookbook-2026', 'en', -40032, 'DRAFT', 'Still being written — must not appear in the magazine.', null, null, null)
on conflict (description_id) do nothing;

