plugins {
    alias(libs.plugins.java.library.conventions)
}

dependencies {
    api project(':store-pod:commons:store-commons')
    implementation project(':store-pod:commons:reference:reference-commons')
    compileOnly libs.spring.data.jpa
    compileOnly libs.jakarta.validation.api
    compileOnly libs.jackson.databind
    compileOnly libs.lombok
    compileOnly libs.hibernate.core
    annotationProcessor libs.lombok
}
