spring:
  application:
    name: order
  config:
    import: "classpath:common-config.yml"
  security:
    oauth2:
      client:
        registration:
          s2s:
            provider: keycloak
            client-id: store@service.store-pod.internal
            client-secret: TqOdIVML83UNpley1BvQ9nHy6kaB5ZX5
            authorization-grant-type: client_credentials
  sql:
    init:
      schema-locations: classpath:init-sql/schema.sql
      data-locations: classpath:init-sql/data-common.sql
  jpa:
    properties:
      hibernate:
        default_schema: orders