// GENERATED by scripts/theme-routes.mjs — do not edit. The route logic lives in src/shell/routes.
import theme from '@store-front/theme-pink';
import {categoryPage} from '@/shell/routes/category';

export {generateMetadata} from '@/shell/routes/category';
export default categoryPage(theme);
