
spring:
  cloud:
    loadbalancer:
      eager-load:
        clients:
          - "store-core-gateway"
          - "auth"
          - "manager"
          - "store-ui"
    ecs:
      discovery:
        namespace: "store-core.cvhome.lcl"
        namespace-id: "ns-aacm3spcnftheq3b"
        enabled: true
        default-port: 8080
        service-ports:
          "store-core-gateway": 7000
          "auth": 9999
          "manager": 7001
          "store-ui": 4200
    gateway:
      forwarded:
        enabled: false
      x-forwarded:
        for-append: false
        host-append: false
        proto-append: false
        port-append: false
        prefix-append: false
      discovery:
        locator:
          enabled: true
      default-filters:
        - TokenRelay
        - PreserveHostHeader
        - AddResponseHeader=X-Frame-Options, SAMEORIGIN
      routes:
        - id: store
          order: -3
          uri: ${com.asrevo.cvhome.services.store-pod-gateway.schema}://${com.asrevo.cvhome.services.store-pod-gateway.domain}:${com.asrevo.cvhome.services.store-pod-gateway.port}
          predicates:
            - Path=/store/**
        - id: manager
          order: -2
          uri: lb://manager
          predicates:
            - Path=/manager/**
          filters:
            - StripPrefix=1
        - id: store-ui
          order: -1
          uri: lb://store-ui
          predicates:
            - FNotService=store,manager,auth
            - FHost=store-ui.${com.asrevo.cvhome.services.store-core-gateway.domain}