spring:
  cloud:
    local:
      discovery:
        enabled: true
        services:
          manager:
            - url: "http://localhost:7001"
              metadata:
                service-name: manager
                instance: manager-1
          wallet:
            - url: "http://localhost:7002"
              metadata:
                service-name: wallet
                instance: wallet-1
          store-ui:
            - url: "http://localhost:4300"
              metadata:
                service-name: store-ui
                instance: store-ui-1
    gateway:
      discovery:
        locator:
          enabled: true
      default-filters:
        - TokenRelay
        - PreserveHostHeader
        - AddResponseHeader=X-Frame-Options, SAMEORIGIN
      routes:
        - id: store-ui
          order: -1
          uri: lb://store-ui
          predicates:
            - FHost=store-ui.${com.asrevo.cvhome.services.core-gateway.domain}