spring:
  cloud:
    local:
      discovery:
        enabled: true
        services:
          dcm:
            - url: "http://localhost:8001"
              metadata:
                service-name: dcm
                instance: dcm-1
          router:
            - url: "http://localhost:8002"
              metadata:
                service-name: router
                instance: router-1
          auth:
            - url: "http://localhost:9999"
              metadata:
                service-name: auth
                instance: auth-1
          welcome-ui:
            - url: "http://localhost:4400"
              metadata:
                service-name: welcome-ui
                instance: welcome-ui-1
          manager:
            - url: "http://localhost:7001"
              metadata:
                service-name: manager
                instance: manager-1
          wallet:
            - url: "http://localhost:7002"
              metadata:
                service-name: wallet
                instance: wallet-1
          store-ui:
            - url: "http://localhost:4200"
              metadata:
                service-name: store-ui
                instance: store-ui-1
          store:
            - url: "http://localhost:6001"
              metadata:
                service-name: store
                instance: store-1
          landing-ui:
            - url: "http://localhost:6002"
              metadata:
                service-name: landing-ui
                instance: landing-ui-1
    gateway:
      discovery:
        locator:
          enabled: true
      default-filters:
        - TokenRelay
        - PreserveHostHeader
        - AddResponseHeader=X-Frame-Options, SAMEORIGIN
      routes:
        - id: store
          order: -3
          uri: ${com.asrevo.cvhome.services.store-pod-gateway.schema}://${com.asrevo.cvhome.services.store-pod-gateway.domain}:${com.asrevo.cvhome.services.store-pod-gateway.port}
          predicates:
            - Path=/store/**
        - id: manager
          order: -2
          uri: lb://manager
          predicates:
            - Path=/manager/**
          filters:
            - StripPrefix=1
        - id: store-ui
          order: -1
          uri: lb://store-ui
          predicates:
            - FNotService=store,manager,wallet,dcm,router,wallet,auth
            - FHost=store-ui.${com.asrevo.cvhome.services.core-gateway.domain}
com:
  asrevo:
    cvhome:
      calls:
        store: DIRECT