spring:
  application:
    name: store-core-gateway
  config:
    import: "classpath:common-config.yml"
  security:
    oauth2:
      client:
        registration:
          s2s:
            provider: uaa
            client-id: store-core@service.store-core.internal
            client-secret: hLwOF59NEOdMzYYrfxUbQEGVK1uTczj7
            authorization-grant-type: client_credentials
            scope: internal,store