#http://localhost:8080/oauth2/authorize?response_type=code&client_id=webapp&redirect_uri=https://app.example.com/callback&scope=openid%20profile%20api.read&code_challenge=YOUR_CODE_CHALLENGE&code_challenge_method=S256

#http://localhost:8080/oauth2/authorize?response_type=code&client_id=web-app&scope=openid&state=U1E9ME0qfLpLfvMPhdBdTee1G6aXeDn7tcP0YEomNeM%3D&redirect_uri=http://localhost:8000/login/oauth2/code/keycloak&nonce=urKkucl0JiiHH8clPXD5W0PTBX4iUIQwhcbw2YIjOmU&code_challenge=jNEXKgeT6hJMpWQYEMBbSdrhQHr5AOmdpoASkAsR8wQ&code_challenge_method=S256


### create a client
POST localhost:8080/api/v1/admin/clients
Content-Type: application/json

{
  "id": "66666666-6666-6666-6666-666666666666",
  "clientId": "webapp",
  "clientIdIssuedAt": "2025-12-04T18:46:01.222677Z",
  "clientSecretExpiresAt": "2025-12-04T18:46:01.222677Z",
  "clientName": "Web App",
  "clientAuthenticationMethods": [
    "client_secret_basic",
    "client_secret_post"
  ],
  "authorizationGrantTypes": [
    "authorization_code",
    "refresh_token"
  ],
  "redirectUris": [
    "https://app.example.com/callback"
  ],
  "postLogoutRedirectUris": [
    "naitaing"
  ],
  "scopes": [
    "openid",
    "profile",
    "api.read"
  ],
  "clientSettings": {
    "requireProofKey": true,
    "requireAuthorizationConsent": true,
    "jwkSetUrl": "gogole.com",
    "tokenEndpointAuthenticationSigningAlgorithm": "RS256",
    "x509CertificateSubjectDN": "domain.example"
  },
  "tokenSettings": {
    "accessTokenTimeToLive": "PT24H",
    "refreshTokenTimeToLive": "PT20H",
    "reuseRefreshTokens": true,
    "idTokenSignatureAlgorithm": "RS256",
    "authorizationCodeTimeToLive": "PT24H",
    "deviceCodeTimeToLive": "PT5M",
    "x509CertificateBoundAccessTokens": true,
    "accessTokenFormat": "self-contained"
  }
}

### client credentails
POST http://localhost:8001/oauth2/token
Content-Type: application/x-www-form-urlencoded
Authorization: Basic store-pod-507f1f77@service.store-pod.internal hLwOF59NEOdMzYYrfxUbQEGVK1uTczj7

grant_type = client_credentials &
scope = internal

# http://uaa.gateway.com:8001/oauth2/authorize?response_type=code&client_id=web-app&scope=openid&state=BGcm6UNZm2XPFiFDIhlWHqN9B300ii24efrfBEy6o4Y%3D&redirect_uri=http://gateway.com:8000/login/oauth2/code/uaa&nonce=9AY2XFqDO8_fVhSrfuWvnA-mj_VgT5h6nxTE008A22M&code_challenge=E9Melhoa2OwvFrEMTJguCHaoeK1t8URWbuGJSstw-cM&code_challenge_method=S256

# when this is secret hLwOF59NEOdMzYYrfxUbQEGVK1uTczj7 add curl to get token

http://gateway.com:8000/login/oauth2/code/uaa?code=Yt69JI_0FnIXpSS31aIGLkBs3bcFWuYW8G7jJ3K7FLNwuEs_2ajVYxLX7W2j2VYiCme5FDtTiJzMu5uSDhmrDEeyenW7XGkCWBWuHvDpXGzGKRY5n50LKeHvGtsasIYk &
state = BGcm6UNZm2XPFiFDIhlWHqN9B300ii24efrfBEy6o4Y%3D





###
# curl -X POST "http://uaa.gateway.com:8001/oauth2/token"
#  -H "Content-Type: application/x-www-form-urlencoded"
#  -u "web-app:hLwOF59NEOdMzYYrfxUbQEGVK1uTczj7"
#  -d "grant_type=authorization_code"
#  -d "code=YOUR_CODE"
#  -d "redirect_uri=http://gateway.com:8000/login/oauth2/code/uaa"
POST http://uaa.gateway.com:8001/oauth2/token
Content-Type: application/x-www-form-urlencoded
Authorization: Basic web-app hLwOF59NEOdMzYYrfxUbQEGVK1uTczj7

client_id = web-app &
grant_type = authorization_code &
code = Yt69JI_0FnIXpSS31aIGLkBs3bcFWuYW8G7jJ3K7FLNwuEs_2ajVYxLX7W2j2VYiCme5FDtTiJzMu5uSDhmrDEeyenW7XGkCWBWuHvDpXGzGKRY5n50LKeHvGtsasIYk &
code_verifier = dBjftJeZ4CVP-mB92K27uhbUJU1p1r_wW1gFWFOEjXk &
redirect_uri = http://gateway.com:8000/login/oauth2/code/uaa


###