create schema if not exists payment;
create table if not exists payment.sm_sequencer
(
    seq_name  varchar(255) not null primary key,
    seq_count bigint
);

create table if not exists payment.payment_configuration
(
    payment_configuration_id bigint generated by default as identity,
    api_key                  varchar(255),
    enabled                  boolean,
    payment_type             varchar(255),
    secret_key               varchar(255),
    store_merchant_id        varchar(50),
    webhook_secret           varchar(255),
    primary key (payment_configuration_id),
    constraint payment_configuration_payment_type_check
        check ((payment_type)::text = ANY
               ((ARRAY ['COD'::character varying, 'MANUAL_TRANSFER'::character varying, 'PAYPAL'::character varying, 'STRIPE'::character varying])::text[]))
);

create table if not exists payment.transaction
(
    transaction_id    bigint     not null,
    amount            numeric(38, 2),
    date_created      timestamp(6) with time zone,
    date_modified     timestamp(6) with time zone,
    updt_id           varchar(60),
    details           text,
    order_id          bigint,
    payment_type      varchar(255),
    transaction_date  timestamp(6) with time zone,
    transaction_type  varchar(255),
    cancel_url        varchar(1000),
    currency_code     varchar(6) not null,
    expire_at         timestamp(6) with time zone,
    external_id       varchar(255),
    redirect_url      varchar(1000),
    ref               varchar(255),
    status            varchar(255) check ((status in ('PENDING', 'PAID', 'PAY_LATER', 'FAILED'))),
    store_merchant_id varchar(50),
    success_url       varchar(1000),

    primary key (transaction_id),
    constraint uc_transaction_ref_store unique (ref, store_merchant_id),
    constraint transaction_payment_type_check
        check ((payment_type)::text = ANY
               ((ARRAY ['COD'::character varying, 'MANUAL_TRANSFER'::character varying, 'PAYPAL'::character varying, 'STRIPE'::character varying])::text[])),
    constraint transaction_transaction_type_check
        check ((transaction_type)::text = ANY
               ((ARRAY ['INIT'::character varying, 'AUTHORIZE'::character varying, 'CAPTURE'::character varying, 'AUTHORIZECAPTURE'::character varying, 'REFUND'::character varying, 'OK'::character varying])::text[]))
);
