receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:
  batch/traces:
    send_batch_size: 40
    send_batch_max_size: 60
    timeout: 1s

  batch/metrics:
    send_batch_size: 40
    send_batch_max_size: 60
    timeout: 1s

  batch/logs:
    send_batch_size: 40
    send_batch_max_size: 60
    timeout: 1s

  filter/drop_metrics:
    error_mode: ignore
    metrics:
      metric:
#        - IsMatch(name, "^http.*")
#        - IsMatch(name, "^application.*")
#        - IsMatch(name, "^jvm.*")
        - IsMatch(name, "^spring.*")
        - IsMatch(name, "^processedLogs.*")
        - IsMatch(name, "^disk.*")
        - IsMatch(name, "^jdbc.*")
        - IsMatch(name, "^system.*")
        - IsMatch(name, "^process.*")
        - IsMatch(name, "^tomcat.*")
        - IsMatch(name, "^nodejs.*")
        - IsMatch(name, "^logback.*")
        - IsMatch(name, "^hikaricp.*")
        - IsMatch(name, "^executor.*")
        - IsMatch(name, "^tasks.*")
        - IsMatch(name, "^v8js.*")

  memory_limiter:
    check_interval: 5s
    limit_mib: 4000
    spike_limit_mib: 500

exporters:
  debug:
    verbosity: normal
  otlp/tempo:
    endpoint: tempo:4317
    tls:
      insecure: true
  otlphttp/loki:
    endpoint: http://loki:3100/otlp
    tls:
      insecure: true
    compression: gzip

  prometheus:
    endpoint: 0.0.0.0:8889
    resource_to_telemetry_conversion:
      enabled: true
extensions:
  health_check:
    endpoint: 0.0.0.0:13133

service:
  extensions: [health_check]
  pipelines:
    traces:
      receivers: [ otlp ]
      processors: [ memory_limiter, batch/traces ]
      exporters: [ otlp/tempo ]

    metrics:
      receivers: [ otlp ]
      processors: [ memory_limiter, filter/drop_metrics, batch/metrics ]
      exporters: [ prometheus ]

    logs:
      receivers: [ otlp ]
      processors: [memory_limiter, batch/logs ]
      exporters: [ otlphttp/loki ]