package com.asrevo.cvhome.commons.domain;

public enum SubscriptionPlanFeatureCode {
    FREE_STORES,
    FREE_ORDERS,
    FREE_PRODUCTS,
    FREE_VISITORS,
    FREE_ACCOUNTS,
    LIMITED_STORES,
    LIMITED_ORDERS,
    LIMITED_PRODUCTS,
    LIMITED_VISITORS,
    LIMITED_ACCOUNTS,
    BASIC_STORES,
    BASIC_ORDERS,
    BASIC_PRODUCTS,
    BASIC_VISITORS,
    BASIC_ACCOUNTS,
    PERFORMANCE_STORES,
    PERFORMANCE_ORDERS,
    PERFORMANCE_PRODUCTS,
    PERFORMANCE_VISITORS,
    PERFORMANCE_ACCOUNTS
}
