plugins {
    id 'com.asrevo.java-library-conventions'
}

dependencies {
    api 'org.mongodb:bson:4.10.2'
    compileOnly 'com.fasterxml.jackson.core:jackson-databind:2.17.1'
    compileOnly 'com.fasterxml.jackson.core:jackson-annotations:2.17.1'
    compileOnly 'org.springframework.data:spring-data-commons:3.3.1'
    compileOnly 'org.springframework.cloud:spring-cloud-stream:4.1.2'
    compileOnly 'org.projectlombok:lombok:1.18.32'
    annotationProcessor 'org.projectlombok:lombok:1.18.32'
}
