plugins {
	alias(libs.plugins.java.library.conventions)
	alias(libs.plugins.spring.javaformat)
}

dependencies {
	api project(':store-pod:commons:store-commons')
	api project(':store-pod:content:content-commons')
	implementation project(':store-pod:store-modules:store-cms-commons')
	compileOnly libs.spring.data.jpa
	compileOnly libs.jakarta.validation.api
	compileOnly libs.lombok
	compileOnly libs.hibernate.core
	annotationProcessor libs.lombok
}
