spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/certificatemanagerdb
    username: postgres
    password: password
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${com.asrevo.cvhome.services.auth.schema}://${com.asrevo.cvhome.services.auth.domain}:${com.asrevo.cvhome.services.auth.port}/realms/cvhome/protocol/openid-connect/certs
  cloud:
    local:
      discovery:
        enabled: true
        services:
          domain-certificate-manager:
            - url: "http://localhost:8082"
              metadata:
                service-name: domain-certificate-manager
                instance: domain-certificate-manager-1
          auth:
            - url: "http://localhost:9999"
              metadata:
                service-name: auth
                instance: auth-1
          admin-ui:
            - url: "http://localhost:4200"
              metadata:
                service-name: admin-ui
                instance: admin-ui-1
          welcome-ui:
            - url: "http://localhost:4400"
              metadata:
                service-name: welcome-ui
                instance: welcome-ui-1
