// GENERATED by libs/types/scripts/build-color-schemas.mjs (THEME_DEFAULTS.pink) — edit the seed there, then
// `npm run gen:colors` in libs/types. Same rules as the merchant presets (see that file's header).
import type {ColorSchema} from '@store-front/types';

/**
 * Tokyo Girls Issue: paper-white stock, plum-black ink, hot-pink cover flood with dark text; petal wash support; cover-line yellow statement. (light)
 *
 * The theme's own palette — what renders when the merchant's colour theme is `DEFAULT` or unset. Wired as
 * `tokens.defaultColors` in `./index.ts`; any fixed preset the merchant picks replaces it whole.
 */
export const DEFAULT_COLORS: ColorSchema = {
    primary: "#E52995",
    secondary: "#FCD0E3",
    accent: "#FCD521",
    background: "#FEF8FB",
    foreground: "#1F111A",
    error: "#B7191C",
    warning: "#EE9E10",
    success: "#007533",
    info: "#0065A1",
    neutral: "#B4A6AF",
    border: "#E3D5DB",
    ring: "#E52995",
    outline: "#C45E8F",
    hoverPrimary: "#FF47AA",
    focusPrimary: "#FF79BA",
    hoverSecondary: "#E4B9CC",
    focusSecondary: "#D0A6B9",
    hoverAccent: "#E3BE00",
    focusAccent: "#CDAC00",
    hoverError: "#99000D",
    focusError: "#7D0008",
    hoverWarning: "#D38A00",
    focusWarning: "#BA7900",
    hoverSuccess: "#005E28",
    focusSuccess: "#004B1E",
    hoverInfo: "#005182",
    focusInfo: "#004069",
    hoverNeutral: "#9E9199",
    focusNeutral: "#8C7F87",
};
