// GENERATED by scripts/theme-routes.mjs — do not edit. The route logic lives in src/shell/routes.
import theme from '@store-front/theme-sports';
import {customerPage} from '@/shell/routes/customer';

export {generateMetadata} from '@/shell/routes/customer';
export default customerPage(theme);
