spring:
  config:
    import: "classpath:common-config.yml"
---
spring:
  application:
    name: merchant
  security:
    oauth2:
      client:
        registration:
          s2s:
            provider: keycloak
            client-id: store@service.store-pod.internal
            client-secret: TqOdIVML83UNpley1BvQ9nHy6kaB5ZX5
            authorization-grant-type: client_credentials
  sql:
    init:
      mode: always
      schema-locations: classpath:init-sql/schema.sql
      data-locations: classpath:init-sql/data-common.sql
  datasource:
    driver-class-name: org.postgresql.Driver
    hikari:
      schema: ${spring.application.name}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
server:
  forward-headers-strategy: NATIVE
  port: ${com.asrevo.cvhome.services.merchant.port}
info:
  app:
    name: ${spring.application.name}
management:
  observations:
    key-values:
      application: ${spring.application.name}