spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/cvhome
    username: postgres
    password: password
  sql:
    init:
      data-locations: classpath:init-sql/data-common.sql, classpath:init-sql/data-test-stores.sql, classpath:init-sql/stores/*/*.sql
  cloud:
    local:
      discovery:
        enabled: true
        services:
          auth:
            - url: "http://localhost:9999"
              metadata:
                service-name: auth
                instance: auth-1
          'store-core-gateway':
            - url: "http://localhost:8000"
              metadata:
                service-name: store-core-gateway
                instance: store-core-gateway-1
          'store-core-gateway.store-core.cvhome.lcl':
            - url: "http://localhost:8000"
              metadata:
                service-name: store-core-gateway
                instance: store-core-gateway-1
          store-ui:
            - url: "http://localhost:8010"
              metadata:
                service-name: store-ui
                instance: store-ui-1
          merchant:
            - url: "http://localhost:8120"
              metadata:
                service-name: merchant
                instance: merchant-1
          content:
            - url: "http://localhost:8121"
              metadata:
                service-name: content
                instance: content-1
          catalog:
            - url: "http://localhost:8122"
              metadata:
                service-name: catalog
                instance: catalog-1
          order:
            - url: "http://localhost:8123"
              metadata:
                service-name: order
                instance: order-1
          landing-ui:
            - url: "http://localhost:8110"
              metadata:
                service-name: landing-ui
                instance: landing-ui-1
          merchant-ui:
            - url: "http://localhost:8111"
              metadata:
                service-name: merchant-ui
                instance: merchant-ui-1
com:
  asrevo:
    cvhome:
      cdn:
        storage:
          provider: MINIO
          bucket: "d0dd4299-963a-4458-b31f-8efe31c35e8e"
          s3-url: "http://localhost:9000"
          s3-access-key: "minioadmin"
          s3-secret-key: "minioadmin"
          region: "eu-central-1"
        base-path: "http://localhost:9000/d0dd4299-963a-4458-b31f-8efe31c35e8e"