plugins {
    alias(libs.plugins.java.library.conventions)
}

dependencies {
    compileOnly libs.spring.web
    api project(':store-pod:commons:store-commons')
    api project(':store-pod:merchant:merchant-commons')
    api project(':store-pod:checkout:checkout-commons')
    compileOnly libs.lombok
    annotationProcessor libs.lombok
}
