plugins {
    alias(libs.plugins.java.library.conventions)
}

dependencies {
    api project(':store-commons:commons')
    api project(':store-core:billing:billing-commons')
    compileOnly libs.jackson.databind
    compileOnly libs.jakarta.validation.api
    compileOnly libs.spring.data.relational
    compileOnly libs.lombok
    annotationProcessor libs.lombok
}
