# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# GitHub recommends pinning actions to a commit SHA.
# To get a newer version, you will need to update the SHA.
# You can also reference a tag or branch, but the action may change without warning.
name: Trigger Deploying Store Pod To ECS

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'dev'
      imageTag:
        description: 'Docker images tag'
        required: true
        default: '0.0.0'
      index:
        description: 'Cluster Index'
        required: true
        default: '1'
jobs:
  deploy-services:
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS credentials For private region
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ secrets.AWS_REGION }}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - name: build state bucket
        id: build-state-bucket
        run: |
          aai=$(aws sts get-caller-identity --query Account --output text)
          bucket="${aai}-${GITHUB_REPOSITORY_OWNER_ID}-${AWS_REGION}"
          project=$(cksum <<< $bucket | cut -f 1 -d ' ')
          echo "project=${project}">> $GITHUB_OUTPUT
        env:
          AWS_REGION: ${{ secrets.AWS_REGION }}
      - name: get caller identity
        id: get-aws-account-id
        run: echo "aws-account-id=$(aws sts get-caller-identity --query Account --output text)">> $GITHUB_OUTPUT
      # store-pod-store-pod-gateway
      - name: Download store-pod-store-pod-gateway task definition
        run: |
          aws ecs describe-task-definition --task-definition "$PROJECT_ID-store-pod-gateway-$ENVIRONMENT" --query taskDefinition > store-pod-store-pod-gateway-definition.json
        env:
          PROJECT_ID: ${{ steps.build-state-bucket.outputs.project }}
          ENVIRONMENT: ${{ inputs.environment }}
      - name: Fill in new image ID in task definition
        id: store-pod-store-pod-gateway-task-def
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: store-pod-store-pod-gateway-definition.json
          container-name: store-pod-gateway
          image: "${{ steps.get-aws-account-id.outputs.aws-account-id }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ steps.build-state-bucket.outputs.project }}/store-pod/store-pod-gateway:${{ inputs.imageTag }}"
      - name: Deploy Amazon ECS task definition
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          task-definition: ${{ steps.store-pod-store-pod-gateway-task-def.outputs.task-definition }}
          service: store-pod-gateway
          cluster: store-pod-${{ inputs.index }}-${{ steps.build-state-bucket.outputs.project }}-${{ inputs.environment }}
      # store-pod-store-saas-gateway
      - name: Download store-pod-store-pod-saas-gateway task definition
        run: |
          aws ecs describe-task-definition --task-definition "$PROJECT_ID-store-pod-saas-gateway-$ENVIRONMENT" --query taskDefinition > store-pod-store-pod-saas-gateway-definition.json
        env:
          PROJECT_ID: ${{ steps.build-state-bucket.outputs.project }}
          ENVIRONMENT: ${{ inputs.environment }}
      - name: Fill in new image ID in task definition
        id: store-pod-store-pod-saas-gateway-task-def
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: store-pod-store-pod-saas-gateway-definition.json
          container-name: store-pod-saas-gateway
          image: "${{ steps.get-aws-account-id.outputs.aws-account-id }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ steps.build-state-bucket.outputs.project }}/store-pod/store-pod-saas-gateway:${{ inputs.imageTag }}"
      - name: Deploy Amazon ECS task definition
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          task-definition: ${{ steps.store-pod-store-pod-saas-gateway-task-def.outputs.task-definition }}
          service: store-pod-saas-gateway
          cluster: store-pod-${{ inputs.index }}-${{ steps.build-state-bucket.outputs.project }}-${{ inputs.environment }}
      # store-pod-store
      - name: Download store-pod-store task definition
        run: |
          aws ecs describe-task-definition --task-definition "$PROJECT_ID-store-$ENVIRONMENT" --query taskDefinition > store-pod-store-definition.json
        env:
          PROJECT_ID: ${{ steps.build-state-bucket.outputs.project }}
          ENVIRONMENT: ${{ inputs.environment }}
      - name: Fill in new image ID in task definition
        id: store-pod-store-task-def
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: store-pod-store-definition.json
          container-name: store
          image: "${{ steps.get-aws-account-id.outputs.aws-account-id }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ steps.build-state-bucket.outputs.project }}/store-pod/store:${{ inputs.imageTag }}"
      - name: Deploy Amazon ECS task definition
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          task-definition: ${{ steps.store-pod-store-task-def.outputs.task-definition }}
          service: store
          cluster: store-pod-${{ inputs.index }}-${{ steps.build-state-bucket.outputs.project }}-${{ inputs.environment }}
      # store-pod-landing-ui
      - name: Download store-pod-landing-ui task definition
        run: |
          aws ecs describe-task-definition --task-definition "$PROJECT_ID-landing-ui-$ENVIRONMENT" --query taskDefinition > store-pod-landing-ui-definition.json
        env:
          PROJECT_ID: ${{ steps.build-state-bucket.outputs.project }}
          ENVIRONMENT: ${{ inputs.environment }}
      - name: Fill in new image ID in task definition
        id: store-pod-landing-ui-task-def
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: store-pod-landing-ui-definition.json
          container-name: landing-ui
          image: "${{ steps.get-aws-account-id.outputs.aws-account-id }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ steps.build-state-bucket.outputs.project }}/store-pod/landing-ui:${{ inputs.imageTag }}"
      - name: Deploy Amazon ECS task definition
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          task-definition: ${{ steps.store-pod-landing-ui-task-def.outputs.task-definition }}
          service: landing-ui
          cluster: store-pod-${{ inputs.index }}-${{ steps.build-state-bucket.outputs.project }}-${{ inputs.environment }}