name: Trigger Publishing To Public ECR

on:
  workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'corretto'

      - name: Validate Gradle wrapper
        uses: gradle/actions/wrapper-validation@v3
      - name: Configure AWS credentials For US-EAST-1
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: us-east-1
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - name: build state bucket
        id: build-state-bucket
        run: |
          aai=$(aws sts get-caller-identity --query Account --output text)
          bucket="${aai}-${GITHUB_REPOSITORY_OWNER_ID}-${AWS_REGION}"
          project=$(cksum <<< $bucket | cut -f 1 -d ' ')
          echo "project=${project}">> $GITHUB_OUTPUT
        env:
          AWS_REGION: ${{ secrets.AWS_REGION }}
      - name: get caller identity
        id: get-aws-account-id
        run: echo "aws-account-id=$(aws sts get-caller-identity --query Account --output text)">> $GITHUB_OUTPUT
      - name: get public registry
        id: get-ecr-public-registry
        run: |
          aws ecr-public describe-registries --max-items 1 --output json --region us-east-1  >>f.json
          echo "ecr-public-registry=$(jq .registries[0].registryUri f.json | tr -d '"')">> $GITHUB_OUTPUT
      - name: Login to Amazon public ECR
        id: login-public-ecr
        uses: aws-actions/amazon-ecr-login@v2
        with:
          registry-type: public
          mask-password: 'false'
      - name: List docker images
        run: docker images
      - name: Suggest Build Version
        id: suggest-build-version
        run: echo "build-version=$(source extra/scripts/suggested-version.sh ${{ github.run_id }})">> $GITHUB_OUTPUT
      - name: Print Build Version
        run:  echo ${{ steps.suggest-build-version.outputs.build-version }}
      - name: Package And Publish Docker with Gradle
        run: ./gradlew bootBuildImage --publishImage -Dorg.gradle.project.version="${{ steps.suggest-build-version.outputs.build-version }}" -x test -x check
        env: # Or as an environment variable
          REGISTRY: "${{ steps.get-ecr-public-registry.outputs.ecr-public-registry }}/${{ steps.build-state-bucket.outputs.project }}"
          ECR_TOKEN: ${{ steps.login-public-ecr.outputs.docker_password_public_ecr_aws }}
        