name: Trigger Deploying Store Core To ECS

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'dev'
      imageTag:
        description: 'Docker images tag'
        required: true
        default: '0.0.0'
jobs:
  deploy-services:
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS credentials For private region
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ secrets.AWS_REGION }}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - name: build state bucket
        id: build-state-bucket
        run: |
          aai=$(aws sts get-caller-identity --query Account --output text)
          bucket="${aai}-${GITHUB_REPOSITORY_OWNER_ID}-${AWS_REGION}"
          project=$(cksum <<< $bucket | cut -f 1 -d ' ')
          echo "project=${project}">> $GITHUB_OUTPUT
        env:
          AWS_REGION: ${{ secrets.AWS_REGION }}
      - name: get caller identity
        id: get-aws-account-id
        run: echo "aws-account-id=$(aws sts get-caller-identity --query Account --output text)">> $GITHUB_OUTPUT
      # store-core-auth
      - name: Download store-core-auth task definition
        run: |
          aws ecs describe-task-definition --task-definition "$PROJECT_ID-auth-$ENVIRONMENT" --query taskDefinition > store-core-auth-definition.json
        env:
          PROJECT_ID: ${{ steps.build-state-bucket.outputs.project }}
          ENVIRONMENT: ${{ inputs.environment }}
      - name: Fill in new image ID in task definition
        id: store-core-auth-task-def
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: store-core-auth-definition.json
          container-name: auth
          image: "${{ steps.get-aws-account-id.outputs.aws-account-id }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ steps.build-state-bucket.outputs.project }}/store-core/auth:${{ inputs.imageTag }}"
      - name: Deploy Amazon ECS task definition
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          task-definition: ${{ steps.store-core-auth-task-def.outputs.task-definition }}
          service: auth
          cluster: store-core-${{ steps.build-state-bucket.outputs.project }}-${{ inputs.environment }}
      # store-core-manager
      - name: Download store-core-manager task definition
        run: |
          aws ecs describe-task-definition --task-definition "$PROJECT_ID-manager-$ENVIRONMENT" --query taskDefinition > store-core-manager-definition.json
        env:
          PROJECT_ID: ${{ steps.build-state-bucket.outputs.project }}
          ENVIRONMENT: ${{ inputs.environment }}
      - name: Fill in new image ID in task definition
        id: store-core-manager-task-def
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: store-core-manager-definition.json
          container-name: manager
          image: "${{ steps.get-aws-account-id.outputs.aws-account-id }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ steps.build-state-bucket.outputs.project }}/store-core/manager:${{ inputs.imageTag }}"
      - name: Deploy Amazon ECS task definition
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          task-definition: ${{ steps.store-core-manager-task-def.outputs.task-definition }}
          service: manager
          cluster: store-core-${{ steps.build-state-bucket.outputs.project }}-${{ inputs.environment }}
      # store-core-subscription
      - name: Download store-core-subscription task definition
        run: |
          aws ecs describe-task-definition --task-definition "$PROJECT_ID-subscription-$ENVIRONMENT" --query taskDefinition > store-core-subscription-definition.json
        env:
          PROJECT_ID: ${{ steps.build-state-bucket.outputs.project }}
          ENVIRONMENT: ${{ inputs.environment }}
      - name: Fill in new image ID in task definition
        id: store-core-subscription-task-def
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: store-core-subscription-definition.json
          container-name: subscription
          image: "${{ steps.get-aws-account-id.outputs.aws-account-id }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ steps.build-state-bucket.outputs.project }}/store-core/subscription:${{ inputs.imageTag }}"
      - name: Deploy Amazon ECS task definition
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          task-definition: ${{ steps.store-core-subscription-task-def.outputs.task-definition }}
          service: subscription
          cluster: store-core-${{ steps.build-state-bucket.outputs.project }}-${{ inputs.environment }}
      # store-core-store-core-gateway
      - name: Download store-core-store-core-gateway task definition
        run: |
          aws ecs describe-task-definition --task-definition "$PROJECT_ID-store-core-gateway-$ENVIRONMENT" --query taskDefinition > store-core-store-core-gateway-definition.json
        env:
          PROJECT_ID: ${{ steps.build-state-bucket.outputs.project }}
          ENVIRONMENT: ${{ inputs.environment }}
      - name: Fill in new image ID in task definition
        id: store-core-store-core-gateway-task-def
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: store-core-store-core-gateway-definition.json
          container-name: store-core-gateway
          image: "${{ steps.get-aws-account-id.outputs.aws-account-id }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ steps.build-state-bucket.outputs.project }}/store-core/store-core-gateway:${{ inputs.imageTag }}"
      - name: Deploy Amazon ECS task definition
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          task-definition: ${{ steps.store-core-store-core-gateway-task-def.outputs.task-definition }}
          service: store-core-gateway
          cluster: store-core-${{ steps.build-state-bucket.outputs.project }}-${{ inputs.environment }}
      # store-core-store-ui
      - name: Download store-core-store-ui task definition
        run: |
          aws ecs describe-task-definition --task-definition "$PROJECT_ID-store-ui-$ENVIRONMENT" --query taskDefinition > store-core-store-ui-definition.json
        env:
          PROJECT_ID: ${{ steps.build-state-bucket.outputs.project }}
          ENVIRONMENT: ${{ inputs.environment }}
      - name: Fill in new image ID in task definition
        id: store-core-store-ui-task-def
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: store-core-store-ui-definition.json
          container-name: store-ui
          image: "${{ steps.get-aws-account-id.outputs.aws-account-id }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ steps.build-state-bucket.outputs.project }}/store-core/store-ui:${{ inputs.imageTag }}"
      - name: Deploy Amazon ECS task definition
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          task-definition: ${{ steps.store-core-store-ui-task-def.outputs.task-definition }}
          service: store-ui
          cluster: store-core-${{ steps.build-state-bucket.outputs.project }}-${{ inputs.environment }}
      # store-core-welcome-ui
      - name: Download store-core-welcome-ui task definition
        run: |
          aws ecs describe-task-definition --task-definition "$PROJECT_ID-welcome-ui-$ENVIRONMENT" --query taskDefinition > store-core-welcome-ui-definition.json
        env:
          PROJECT_ID: ${{ steps.build-state-bucket.outputs.project }}
          ENVIRONMENT: ${{ inputs.environment }}
      - name: Fill in new image ID in task definition
        id: store-core-welcome-ui-task-def
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: store-core-welcome-ui-definition.json
          container-name: welcome-ui
          image: "${{ steps.get-aws-account-id.outputs.aws-account-id }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ steps.build-state-bucket.outputs.project }}/store-core/welcome-ui:${{ inputs.imageTag }}"
      - name: Deploy Amazon ECS task definition
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          task-definition: ${{ steps.store-core-welcome-ui-task-def.outputs.task-definition }}
          service: welcome-ui
          cluster: store-core-${{ steps.build-state-bucket.outputs.project }}-${{ inputs.environment }}