spring:
  application:
    name: store
  datasource:
    driver-class-name: org.postgresql.Driver
    hikari:
      schema: store
server:
  forward-headers-strategy: FRAMEWORK
  port: ${com.asrevo.cvhome.services.store.port}
info:
  app:
    name: ${spring.application.name}
management:
  observations:
    key-values:
      application: ${spring.application.name}